import type { LandingBlueprint } from "../components/landing/TrustedLandingRenderer";
export const landingGoals=["LEAD_GENERATION","APPOINTMENT_BOOKING","PRODUCT_OFFER","SERVICE_OFFER","SALES_PAGE"] as const;
export const channelStrategies=["SEARCH_PAID","SOCIAL_PAID","SOCIAL_ORGANIC","MESSAGING","MARKETPLACE","CLASSIFIED","REFERRAL","DIRECT"] as const;
export const componentOptions=["HERO","PROBLEM","SOLUTION","BENEFITS","FEATURES","TRUST","TESTIMONIALS","OFFER","FAQ","FORM_OR_ACTION","CTA","FOOTER"] as const;
export const goalLabels:Record<string,string>={LEAD_GENERATION:"جذب سرنخ",APPOINTMENT_BOOKING:"رزرو نوبت",PRODUCT_OFFER:"پیشنهاد محصول",SERVICE_OFFER:"پیشنهاد خدمت",SALES_PAGE:"صفحه فروش"};
export const strategyLabels:Record<string,string>={SEARCH_PAID:"جست‌وجوی پولی",SOCIAL_PAID:"شبکه اجتماعی پولی",SOCIAL_ORGANIC:"شبکه اجتماعی ارگانیک",MESSAGING:"پیام‌رسان / SMS",MARKETPLACE:"مارکت‌پلیس",CLASSIFIED:"آگهی طبقه‌بندی‌شده",REFERRAL:"معرفی",DIRECT:"ورود مستقیم"};
const sequences:Record<string,string[]>={LEAD_GENERATION:["HERO","BENEFITS","TRUST","CTA","FORM_OR_ACTION"],APPOINTMENT_BOOKING:["HERO","PROBLEM","BENEFITS","TRUST","FAQ","CTA"],PRODUCT_OFFER:["HERO","OFFER","BENEFITS","TRUST","FAQ","CTA"],SERVICE_OFFER:["HERO","PROBLEM","SOLUTION","BENEFITS","TRUST","FAQ","CTA"],SALES_PAGE:["HERO","OFFER","BENEFITS","TESTIMONIALS","FAQ","CTA"]};
const strategy:Record<string,{audienceState:string;messageMatchPriority:string;proofPriority:string;frictionLevel:string}>={SEARCH_PAID:{audienceState:"HIGH_INTENT",messageMatchPriority:"HIGH",proofPriority:"HIGH",frictionLevel:"LOW"},SOCIAL_PAID:{audienceState:"DISCOVERY",messageMatchPriority:"HIGH",proofPriority:"HIGH",frictionLevel:"STANDARD"},SOCIAL_ORGANIC:{audienceState:"WARM",messageMatchPriority:"MEDIUM",proofPriority:"HIGH",frictionLevel:"STANDARD"},MESSAGING:{audienceState:"WARM",messageMatchPriority:"HIGH",proofPriority:"MEDIUM",frictionLevel:"MINIMAL"},MARKETPLACE:{audienceState:"HIGH_INTENT",messageMatchPriority:"HIGH",proofPriority:"HIGH",frictionLevel:"LOW"},CLASSIFIED:{audienceState:"HIGH_INTENT",messageMatchPriority:"HIGH",proofPriority:"HIGH",frictionLevel:"MINIMAL"},REFERRAL:{audienceState:"WARM",messageMatchPriority:"MEDIUM",proofPriority:"HIGH",frictionLevel:"LOW"},DIRECT:{audienceState:"UNKNOWN",messageMatchPriority:"MEDIUM",proofPriority:"MEDIUM",frictionLevel:"STANDARD"}};
const actions:Record<string,string>={LEAD_GENERATION:"CONTACT",APPOINTMENT_BOOKING:"BOOKING",PRODUCT_OFFER:"PURCHASE",SERVICE_OFFER:"CONTACT",SALES_PAGE:"PURCHASE"};
const variants:Record<string,string>={HERO:"CENTERED",PROBLEM:"CARDS",SOLUTION:"STEPS",BENEFITS:"GRID",FEATURES:"GRID",TRUST:"FACTS",TESTIMONIALS:"CARDS",OFFER:"CARD",FAQ:"ACCORDION",FORM_OR_ACTION:"ACTION",CTA:"CENTERED",FOOTER:"MINIMAL"};
export function sectionFor(componentId:string,index=0){const proof=["TRUST","TESTIMONIALS"].includes(componentId),offer=componentId==="OFFER",cta=["HERO","OFFER","CTA","FORM_OR_ACTION"].includes(componentId);return{id:`${componentId.toLowerCase()}-${index}-${crypto.randomUUID().slice(0,8)}`,componentId,version:1,variant:variants[componentId],props:{heading:proof?"اعتماد با شواهد واقعی":offer?"پیشنهاد روشن شما":componentId==="FAQ"?"پرسش‌های پرتکرار":"عنوان این بخش",...(componentId==="HERO"?{headline:"یک وعده روشن و هماهنگ با مسیر ورود مشتری"}:{body:"متن این بخش را کوتاه، واقعی و قابل فهم نگه دارید."}),...(["BENEFITS","FEATURES","PROBLEM","SOLUTION","TRUST","TESTIMONIALS","FAQ"].includes(componentId)?{items:["مورد اول","مورد دوم"]}:{}),...(cta?{primaryCta:{label:"دریافت مشاوره",type:"WHATSAPP",target:"https://wa.me/989120000000"}}:{})},contentBindings:[],assetBindings:[],trackingBindings:cta?[{action:"CTA_CLICK"}]:[]};}
export function applyPreset(base:LandingBlueprint,goal:string,channelStrategy:string):LandingBlueprint{const s=strategy[channelStrategy],sequence=sequences[goal];return{...base,goal:goalLabels[goal],sections:sequence.map(sectionFor),conversionStrategy:{presetId:goal,presetVersion:1,goal,channelStrategy,strategyVersion:1,...s,conversionAction:actions[goal],recommendedSectionSequence:sequence},primaryCta:goal==="APPOINTMENT_BOOKING"?{label:"رزرو نوبت",type:"BOOKING",target:"https://example.com/booking"}:{label:"دریافت مشاوره",type:"WHATSAPP",target:"https://wa.me/989120000000"}};}
export function messageMatch(blueprint:LandingBlueprint){const s=blueprint.conversionStrategy,w:string[]=[],components=blueprint.sections.map(x=>x.componentId),ctas=[blueprint.primaryCta,...blueprint.sections.map(x=>x.props.primaryCta as LandingBlueprint["primaryCta"])].filter(Boolean);if(!s)return["یک هدف و مسیر ورودی انتخاب کنید."];if(s.goal==="APPOINTMENT_BOOKING"&&!ctas.some(x=>["BOOKING","PHONE","WHATSAPP"].includes(x!.type)))w.push("دعوت به اقدام با هدف رزرو هماهنگ نیست.");if(s.channelStrategy==="MARKETPLACE"&&!components.includes("OFFER"))w.push("برای ورودی مارکت‌پلیس، بخش پیشنهاد/ارزش لازم است.");if(s.channelStrategy==="MESSAGING"&&blueprint.sections.length>5)w.push("مسیر پیام‌رسان بهتر است کوتاه‌تر باشد.");if(s.proofPriority==="HIGH"&&!components.some(x=>["TRUST","TESTIMONIALS"].includes(x)))w.push("برای این مسیر، بخش اعتماد یا گواهی مشتری پیشنهاد می‌شود.");return w;}
