import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowClockwise, ArrowLeft, CheckCircle, ClockCounterClockwise, Info, Lightbulb, ShieldCheck, Siren, WarningCircle } from "@phosphor-icons/react";
import { apiFetch } from "../../lib/api";

type Fact={label:string;value:unknown;sourceRef:{type:string;id:string}};
type Belief={recommendationId:string;code:string;state:string;confidence:number|null;confidenceReason:string};
type Item={signalId:string;band:string;facts:Fact[];beliefs:Belief[];unknown:string[];action:{label:string;requiredApproval:string;executable:false;deepLink:string};explainability:Record<string,unknown>;whyThisIsHere:string};
type MissionControl={contractVersion:number;generatedAt:string;items:Item[];banners:Array<{code:string;staleReasons?:string[]}>;signalStatus:Array<{signalId:string;status:"ok"|"failed"}>;bounds:{maxItems:number;truncated:boolean}};

const signalLabels:Record<string,string>={EXPERIMENT_WINDOW_CLOSED_NO_DECISION:"پنجره سنجش آزمایش بسته شده است",CONVERTED_LEAD_WITHOUT_TREATMENT_LINKAGE:"تبدیل CRM به شواهد رشد متصل نیست",UNDECIDED_RECOMMENDATION:"یک پیشنهاد منتظر تصمیم انسانی است",CONTENT_CANDIDATE_STUCK:"نامزد محتوا نیازمند بررسی است"};
const actionLabels:Record<string,string>={REVIEW_EXPERIMENT_OUTCOME:"بررسی نتیجه آزمایش",REVIEW_EVIDENCE_LINKAGE:"بررسی اتصال شواهد",REVIEW_RECOMMENDATION:"بررسی پیشنهاد",REVIEW_CONTENT_CANDIDATE:"بررسی نامزد محتوا"};
const factLabels:Record<string,string>={EXPERIMENT_STATUS:"وضعیت آزمایش",MEASUREMENT_WINDOW_ENDED_AT:"پایان پنجره سنجش",DECISION_STATE:"وضعیت تصمیم",CRM_EVENT_TYPE:"رویداد CRM",OCCURRED_AT:"زمان وقوع",EVIDENCE_AUTHORITY:"مرجع شواهد",RECOMMENDATION_TYPE:"نوع پیشنهاد",CALCULATED_AT:"زمان محاسبه",CANDIDATE_STATE:"وضعیت نامزد",CREATED_AT:"زمان ایجاد"};
const values:Record<string,string>={NO_DECISION:"بدون تصمیم",DEFERRED:"به تعویق افتاده",AMBIGUOUS:"مبهم؛ نیازمند بررسی",CANONICAL_RECORD:"رکورد معتبر دامنه",RECONCILIATION_REQUIRED:"نیازمند تطبیق",PENDING:"در انتظار"};
const reasons:Record<string,string>={MEASUREMENT_WINDOW_ENDED_WITHOUT_GOVERNED_DECISION:"پنجره سنجش تمام شده اما تصمیم نهایی و قابل اتکا ثبت نشده است.",CANONICAL_CRM_CONVERSION_HAS_NO_GROWTH_EVIDENCE_LINK:"یک تبدیل معتبر CRM هنوز به درمان یا آزمایش رشد متصل نشده است؛ این به معنی از دست رفتن درآمد یا انتساب نیست.",GOVERNED_RECOMMENDATION_HAS_NO_DECISION:"پیشنهاد ثبت شده است، اما تصمیم انسانی درباره آن وجود ندارد.",PROVIDER_OUTCOME_REQUIRES_RECONCILIATION:"نتیجه ارائه‌دهنده قطعی نیست و باید پیش از هر اقدام تطبیق داده شود.",CANDIDATE_PENDING_BEYOND_AGE_FLOOR:"نامزد محتوا بیش از آستانه سیاست در انتظار مانده است."};
const unknownLabels:Record<string,string>={BUSINESS_IMPACT_VALUE:"اثر کسب‌وکاری نامشخص",CAUSALITY:"رابطه علّی نامشخص",ATTRIBUTION:"انتساب نامشخص",EXPERIMENT_EFFECTIVENESS:"اثربخشی نامشخص",TREATMENT_LINKAGE:"اتصال درمان نامشخص",PROVIDER_OUTCOME:"نتیجه ارائه‌دهنده نامشخص"};
const staleLabels:Record<string,string>={BUSINESS_PROFILE_CHANGED:"پروفایل کسب‌وکار تغییر کرده است",BUSINESS_DNA_CHANGED:"DNA کسب‌وکار تغییر کرده است",BRAND_BOOK_CHANGED:"برندبوک تغییر کرده است"};
const allowedLinks=[/^\/dashboard\/growth-loop\/[^/?#]+$/, /^\/dashboard\/content$/, /^\/dashboard\/crm$/, /^\/intelligence$/];

function text(value:unknown){const raw=String(value??"UNKNOWN");if(values[raw])return values[raw];if(/^\d{4}-\d{2}-\d{2}T/.test(raw)){const date=new Date(raw);if(!Number.isNaN(date.getTime()))return new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short"}).format(date);}return raw.replaceAll("_"," ");}
function safeLink(link:string){return allowedLinks.some(pattern=>pattern.test(link))?link:null;}

function MissionCard({item}:{item:Item}){
  const link=safeLink(item.action.deepLink),authority=item.facts.find(x=>x.label==="EVIDENCE_AUTHORITY")?.value,decision=item.facts.find(x=>x.label==="DECISION_STATE")?.value;
  const urgent=item.signalId==="CONTENT_CANDIDATE_STUCK"&&item.facts.some(x=>x.value==="RECONCILIATION_REQUIRED");
  return <article className={`rounded-[24px] border p-5 ${urgent?"border-rose-300/30 bg-rose-500/[0.07]":"border-white/[0.08] bg-black/25"}`}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><span aria-hidden="true" className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${urgent?"bg-rose-400/15 text-rose-200":"bg-violet-400/10 text-violet-200"}`}>{urgent?<Siren size={22}/>:<WarningCircle size={22}/>}</span><div><span className="text-[11px] font-bold text-white/40">{item.band}</span><h3 className="mt-1 text-base font-bold leading-7">{signalLabels[item.signalId]||item.signalId}</h3></div></div>{authority!=null&&<span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-300/20 bg-emerald-400/[0.08] px-3 py-1.5 text-xs text-emerald-200"><ShieldCheck size={15}/>{text(authority)}</span>}</div>
    {decision!=null&&<div className="mt-4 inline-flex items-center gap-2 rounded-xl border border-amber-300/15 bg-amber-300/[0.07] px-3 py-2 text-xs text-amber-100"><ClockCounterClockwise size={16}/>{text(decision)}</div>}
    <div className="mt-4 grid gap-2 sm:grid-cols-2">{item.facts.filter(x=>x.label!=="EVIDENCE_AUTHORITY"&&x.label!=="DECISION_STATE").map(x=><div key={`${x.label}:${x.sourceRef.id}`} className="rounded-xl border border-white/[0.06] bg-white/[0.025] px-3 py-2.5"><div className="flex items-center gap-1.5 text-[11px] text-cyan-200/75"><ShieldCheck size={13}/>واقعیت · {factLabels[x.label]||x.label}</div><div className="mt-1 truncate text-sm text-white/75" title={text(x.value)}>{text(x.value)}</div></div>)}</div>
    {item.beliefs.length>0&&<div className="mt-3 rounded-xl border border-violet-300/15 bg-violet-400/[0.06] p-3 text-xs leading-6 text-violet-100/75"><div className="mb-1 flex items-center gap-1.5 font-bold text-violet-100"><Lightbulb size={15}/>برداشت پیشنهادی، نه واقعیت</div>{item.beliefs.map(x=><div key={x.recommendationId}>{text(x.code)} · اطمینان: {x.confidence==null?"نامشخص":x.confidence}</div>)}</div>}
    {item.unknown.length>0&&<div className="mt-3 flex flex-wrap gap-2" aria-label="موارد نامشخص">{item.unknown.map(x=><span key={x} className="rounded-full border border-white/[0.08] bg-white/[0.03] px-2.5 py-1 text-[11px] text-white/45">UNKNOWN · {unknownLabels[x]||x}</span>)}</div>}
    <details className="mt-4 text-xs text-white/45"><summary className="min-h-11 cursor-pointer py-3">چرا اینجا نمایش داده شده؟</summary><p className="pb-2 leading-6">{reasons[item.whyThisIsHere]||item.whyThisIsHere}</p></details>
    {link&&<Link to={link} className="mt-2 inline-flex min-h-11 items-center gap-2 rounded-xl border border-violet-300/20 bg-violet-500/10 px-4 py-2 text-sm font-bold text-violet-100">{actionLabels[item.action.label]||item.action.label}<ArrowLeft size={16}/></Link>}
  </article>;
}

export default function MissionControlDashboard({userName}:{userName?:string|null}){
  const[data,setData]=useState<MissionControl|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await apiFetch("/api/mission-control"),body=await response.json().catch(()=>null);if(!response.ok||!body?.success||!body?.missionControl)throw new Error("MISSION_CONTROL_READ_FAILED");setData(body.missionControl);}catch{setError("مرکز مأموریت فعلاً در دسترس نیست. دوباره تلاش کنید.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const failed=useMemo(()=>data?.signalStatus.filter(x=>x.status==="failed")??[],[data]),allFailed=Boolean(data?.signalStatus.length&&failed.length===data.signalStatus.length),primary=data?.items.slice(0,4)??[],more=data?.items.slice(4,7)??[],firstName=userName?.trim().split(/\s+/)[0];
  return <section aria-labelledby="mission-control-title" className="rounded-[30px] border border-violet-300/15 bg-gradient-to-br from-violet-500/[0.10] via-white/[0.035] to-cyan-500/[0.06] p-5 sm:p-7">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-xs font-bold text-cyan-200/70">مرکز مأموریت رشد</div><h2 id="mission-control-title" className="mt-2 text-2xl font-black sm:text-3xl">{firstName?`${firstName}، چه چیزی الان به توجهت نیاز دارد؟`:"چه چیزی الان به توجه شما نیاز دارد؟"}</h2><p className="mt-2 text-sm leading-7 text-white/50">{data?`${new Intl.NumberFormat("fa-IR").format(data.items.length)} مورد بر پایه شواهد فعلی`:"نمایش اولویت‌های قابل بررسی بر پایه داده‌های معتبر"}</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex min-h-11 items-center justify-center gap-2 self-start rounded-xl border border-white/10 bg-white/[0.04] px-4 text-sm text-white/65 disabled:opacity-50"><ArrowClockwise className={loading?"animate-spin":""}/>به‌روزرسانی</button></div>
    {loading&&!data&&<div aria-live="polite" className="mt-6 grid gap-3 sm:grid-cols-2"><span className="h-48 animate-pulse rounded-3xl bg-white/[0.04]"/><span className="h-48 animate-pulse rounded-3xl bg-white/[0.04]"/></div>}
    {error&&!data&&<div role="alert" className="mt-6 rounded-2xl border border-rose-300/20 bg-rose-400/[0.08] p-5"><div className="flex items-center gap-2 font-bold text-rose-100"><WarningCircle/>خطا در دریافت اولویت‌ها</div><p className="mt-2 text-sm text-rose-100/65">{error}</p><button type="button" onClick={()=>void load()} className="mt-4 min-h-11 rounded-xl bg-white px-4 text-sm font-bold text-slate-950">تلاش دوباره</button></div>}
    {data?.banners.some(x=>x.code==="STALE_BUSINESS_CONTEXT")&&<div className="mt-6 rounded-2xl border border-amber-300/20 bg-amber-300/[0.08] p-4"><div className="flex items-center gap-2 font-bold text-amber-100"><WarningCircle/>Business Context نیازمند بازبینی است</div><ul className="mt-2 space-y-1 text-sm text-amber-100/65">{data.banners.flatMap(x=>x.staleReasons||[]).map(x=><li key={x}>• {staleLabels[x]||x}</li>)}</ul><Link to="/dashboard/business-brain" className="mt-3 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-amber-100">بازبینی زمینه کسب‌وکار<ArrowLeft/></Link></div>}
    {data&&failed.length>0&&!allFailed&&<div role="status" className="mt-5 flex items-start gap-2 rounded-xl border border-amber-200/15 bg-amber-200/[0.05] p-3 text-sm text-amber-100/70"><Info className="mt-0.5 shrink-0"/>بخشی از سیگنال‌ها در دسترس نیست ({failed.map(x=>x.signalId).join("، ")})؛ موارد موجود حذف یا حدس زده نشده‌اند.</div>}
    {data&&allFailed&&<div role="alert" className="mt-6 rounded-2xl border border-rose-300/20 bg-rose-400/[0.08] p-5"><div className="font-bold text-rose-100">هیچ سیگنالی قابل دریافت نیست</div><p className="mt-2 text-sm text-rose-100/65">برای بازیابی دوباره تلاش کنید؛ هیچ وضعیت مثبتی از نبود داده استنباط نشده است.</p><button type="button" onClick={()=>void load()} className="mt-4 min-h-11 rounded-xl bg-white px-4 text-sm font-bold text-slate-950">تلاش دوباره</button></div>}
    {data&&!allFailed&&data.items.length===0&&<div className="mt-6 rounded-2xl border border-emerald-300/15 bg-emerald-300/[0.06] p-6 text-center"><CheckCircle size={32} className="mx-auto text-emerald-300"/><h3 className="mt-3 font-bold">در حال حاضر مورد نیازمند توجهی دیده نمی‌شود</h3><p className="mt-2 text-sm text-white/45">این نتیجه فقط بر پایه سیگنال‌های موفق فعلی است.</p></div>}
    {primary.length>0&&<div className="mt-6 grid gap-4 lg:grid-cols-2">{primary.map((x,i)=><MissionCard key={`${x.signalId}:${i}`} item={x}/>)}</div>}
    {more.length>0&&<details className="mt-5 rounded-2xl border border-white/[0.08] bg-black/20 p-3"><summary className="flex min-h-11 cursor-pointer items-center px-2 text-sm font-bold text-white/65">نمایش {new Intl.NumberFormat("fa-IR").format(more.length)} مورد دیگر</summary><div className="mt-3 grid gap-4 lg:grid-cols-2">{more.map((x,i)=><MissionCard key={`${x.signalId}:more:${i}`} item={x}/>)}</div></details>}
    {data&&<div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-2 text-[11px] text-white/35"><span>آخرین تولید: {new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(data.generatedAt))}</span><span>حداکثر نمایش: {new Intl.NumberFormat("fa-IR").format(data.bounds.maxItems)} مورد</span>{data.bounds.truncated&&<span>نتایج بیشتر به‌صورت bounded نگه داشته شده‌اند</span>}</div>}
  </section>;
}
