import{evaluateSpc}from"../improvement/pdca-math.mjs";
export const constraintTypes=Object.freeze(["FLOW_CONSTRAINT","CONVERSION_CONSTRAINT","QUALITY_CONSTRAINT","ECONOMIC_CONSTRAINT","RELIABILITY_CONSTRAINT","DATA_INSUFFICIENCY"]);
export const rankingPolicy=Object.freeze({version:1,weights:Object.freeze({objectiveRelevance:.25,throughputImpact:.25,relativeLoss:.2,persistence:.1,sampleQuality:.1,downstreamDependency:.1})});
const mean=a=>a.reduce((s,n)=>s+n,0)/a.length,clamp=n=>Math.max(0,Math.min(1,n));
export function dataQuality(series){if(!series.length||series.some(x=>!Array.isArray(x.values)||x.values.length<3||x.values.some(v=>!Number.isFinite(v))))return"INSUFFICIENT";const n=Math.min(...series.map(x=>x.values.length));if(n>=30)return"GOOD";if(n>=10)return"LIMITED";return"POOR";}
export function persistencePosture(values){if(values.length<3)return"UNKNOWN";const changes=values.slice(1).map((v,i)=>v<values[i]);const losses=changes.filter(Boolean).length;return losses===changes.length&&losses>=4?"PERSISTENT":losses>=2?"REPEATED":losses===1?"TRANSIENT":"UNKNOWN";}
export function analyzeConstraintCore({flow,objectiveKey,series}){const quality=dataQuality(series);if(quality==="INSUFFICIENT")return Object.freeze({flowId:flow.flowId,objectiveKey,dataQuality:quality,candidates:Object.freeze([{kind:"CONSTRAINT_CANDIDATE",domain:flow.stages[0].domain,stage:flow.stages[0].id,metric:flow.stages[0].metricKey,type:"DATA_INSUFFICIENCY",reasonCodes:["CANONICAL_DATA_INSUFFICIENT"],objectiveRelevance:1,relativeDrop:null,throughputImpact:null,persistencePosture:"UNKNOWN",variationPosture:"INSUFFICIENT_DATA",dataQuality:quality,confidencePosture:"LOW",rankingFactors:{objectiveRelevance:1,throughputImpact:0,relativeLoss:0,persistence:0,sampleQuality:0,downstreamDependency:0},score:0}]),warnings:Object.freeze([])});
 const latest=series.map(x=>mean(x.values.slice(-Math.min(5,x.values.length)))),candidates=[];for(let i=1;i<series.length;i++){const upstream=latest[i-1],current=latest[i],drop=upstream<=0?0:clamp((upstream-current)/upstream),impact=Math.max(0,upstream-current),spc=evaluateSpc(series[i].values),persist=persistencePosture(series[i].values),objectiveRelevance=flow.stages.slice(i).some(s=>s.metricKey===objectiveKey)?1:.75,downstreamDependency=(series.length-i)/series.length,sampleQuality=quality==="GOOD"?1:quality==="LIMITED"?.7:.4,persistence=persist==="PERSISTENT"?1:persist==="REPEATED"?.7:persist==="TRANSIENT"?.3:0,throughputImpact=clamp(impact/Math.max(1,upstream)),f={objectiveRelevance,throughputImpact,relativeLoss:drop,persistence,sampleQuality,downstreamDependency},score=Object.entries(rankingPolicy.weights).reduce((s,[k,w])=>s+f[k]*w,0);candidates.push({kind:"CONSTRAINT_CANDIDATE",domain:flow.stages[i].domain,stage:flow.stages[i].id,metric:flow.stages[i].metricKey,type:drop>.05?"CONVERSION_CONSTRAINT":"FLOW_CONSTRAINT",reasonCodes:[drop>.05?"RELATIVE_STAGE_LOSS":"THROUGHPUT_LIMIT",spc.result==="COMMON_CAUSE"?"SYSTEM_VARIATION":"INVESTIGATE_VARIATION"],objectiveRelevance,relativeDrop:drop,throughputImpact:impact,persistencePosture:persist,variationPosture:spc.result,dataQuality:quality,confidencePosture:quality==="GOOD"&&persist==="PERSISTENT"?"HIGH":quality==="INSUFFICIENT"?"LOW":"MEDIUM",rankingFactors:f,score:Number(score.toFixed(6))});}
 candidates.sort((a,b)=>b.score-a.score||a.stage.localeCompare(b.stage));const warnings=[];for(let i=1;i<latest.length;i++)if(latest[i-1]>series[i-1].values[0]&&latest[i]<series[i].values[0])warnings.push("LOCAL_OPTIMIZATION_WARNING");return Object.freeze({flowId:flow.flowId,objectiveKey,dataQuality:quality,candidates:Object.freeze(candidates.slice(0,10)),warnings:Object.freeze([...new Set(warnings)])});}
