import { normalizeListeningRecord } from "../listening/listening-record-normalizer.mjs";
import { requireWorkspaceId } from "../tenant-context.mjs";
import { decodeCursor, CursorPaginationError } from "../query/cursor-pagination.mjs";
import { createOperationMetrics } from "../observability/operation-metrics.mjs";

export class ListeningError extends Error { constructor(message,status=400,code="LISTENING_ERROR"){super(message);this.status=status;this.code=code;} }
const TYPES=new Set(["BRAND","COMPETITOR","PRODUCT","KEYWORD","INDUSTRY","REPUTATION","CUSTOM"]);
const SOURCES=new Set(["WEB","SOCIAL"]);
const RETENTION=new Set(["EPHEMERAL_RAW","NORMALIZED_ONLY","COMPLIANCE_ARCHIVE","EXTERNAL_REFERENCE_ONLY"]);
const list=(v,name,max=100)=>{if(v==null)return[];if(!Array.isArray(v)||v.length>max||v.some(x=>typeof x!=="string"||!x.trim()||x.length>300))throw new ListeningError(`${name} is invalid.`);return [...new Set(v.map(x=>x.trim()))];};
const text=(v,name,max,required=false)=>{if(v==null||v===""){if(required)throw new ListeningError(`${name} is required.`);return null;}if(typeof v!=="string"||!v.trim()||v.length>max)throw new ListeningError(`${name} is invalid.`);return v.trim();};
const number=(v,name,min,max,fallback)=>{const n=v==null?fallback:Number(v);if(!Number.isInteger(n)||n<min||n>max)throw new ListeningError(`${name} must be between ${min} and ${max}.`);return n;};
function config(input={}){if(Object.hasOwn(input,"workspaceId")||Object.hasOwn(input,"workspace_id"))throw new ListeningError("Workspace ownership is server-resolved.");const sourceCategories=list(input.sourceCategories,"sourceCategories",2);if(!sourceCategories.length||sourceCategories.some(x=>!SOURCES.has(x)))throw new ListeningError("At least one valid source category is required.");const retentionClass=input.retentionClass||"NORMALIZED_ONLY";if(!RETENTION.has(retentionClass))throw new ListeningError("retentionClass is invalid.");return{keywords:list(input.keywords,"keywords"),exactPhrases:list(input.exactPhrases,"exactPhrases"),excludedPhrases:list(input.excludedPhrases,"excludedPhrases"),brandNames:list(input.brandNames,"brandNames"),competitorNames:list(input.competitorNames,"competitorNames"),productNames:list(input.productNames,"productNames"),domains:list(input.domains,"domains"),sourceCategories,providerFilters:list(input.providerFilters,"providerFilters"),languages:list(input.languages,"languages",30),regions:list(input.regions,"regions",30),authorFilters:list(input.authorFilters,"authorFilters"),collectionFrequency:text(input.collectionFrequency||"manual","collectionFrequency",50,true),retentionClass,retentionDays:input.retentionDays==null?null:number(input.retentionDays,"retentionDays",1,3650),maxRecordsPerRun:number(input.maxRecordsPerRun,"maxRecordsPerRun",1,1000,100),maxNormalizedTextLength:number(input.maxNormalizedTextLength,"maxNormalizedTextLength",100,20000,4000)};}
const boundedLimit=q=>{const n=Number(q.limit||50);if(!Number.isInteger(n)||n<1||n>100)throw new ListeningError("limit must be between 1 and 100.");return n;};
const time=(v,n)=>{if(!v)return null;if(!Number.isFinite(Date.parse(v)))throw new ListeningError(`${n} is invalid.`);return new Date(v).toISOString();};
const recordFilters=q=>{try{return{monitorVersionId:q.monitorVersionId?text(q.monitorVersionId,"monitorVersionId",100):null,provider:q.provider?text(q.provider,"provider",100):null,canonicalType:q.canonicalType?text(q.canonicalType,"canonicalType",50):null,language:q.language?text(q.language,"language",20):null,sourceCategory:q.sourceCategory?text(q.sourceCategory,"sourceCategory",20):null,publishedFrom:time(q.publishedFrom,"publishedFrom"),publishedTo:time(q.publishedTo,"publishedTo"),collectedFrom:time(q.collectedFrom,"collectedFrom"),collectedTo:time(q.collectedTo,"collectedTo"),cursor:decodeCursor(q.cursor,"listening_records",["collectedAt","id"]),limit:boundedLimit(q)}}catch(error){if(error instanceof CursorPaginationError)throw new ListeningError("cursor is invalid.",400,"INVALID_CURSOR");throw error;}};

export function createListeningService({sourceRegistry,repository,auditRepository=null,now=()=>new Date(),operationMetrics=createOperationMetrics()}){const audit=(userId,action,type,id,metadata)=>auditRepository?.createAuditLog({workspaceId:requireWorkspaceId(),userId,action,resourceType:type,resourceId:id,metadata,createdAt:now().toISOString()});return Object.freeze({
  sourceDefinitions(region){if(region&&!['GLOBAL','IRAN','MENA'].includes(region))throw new ListeningError("region is invalid.");return sourceRegistry.list({region});},
  createMonitor(payload,userId){const name=text(payload.name,"name",200,true),monitorType=text(payload.monitorType,"monitorType",30,true);if(!TYPES.has(monitorType))throw new ListeningError("monitorType is invalid.");const result=repository.createMonitor({name,monitorType,config:config(payload),userId,at:now().toISOString()});audit(userId,"listening.monitor_created","listening_monitor",result.monitor.id,{monitorType,versionId:result.version.id,versionNumber:1});return result;},
  createVersion(id,payload,userId){const result=repository.createVersion(text(id,"monitorId",100,true),config(payload),userId,now().toISOString());if(!result)throw new ListeningError("Listening monitor not found.",404,"MONITOR_NOT_FOUND");audit(userId,"listening.monitor_version_created","listening_monitor",id,{versionId:result.id,versionNumber:result.versionNumber});return result;},
  monitors:()=>repository.listMonitors(),
  versions(id){if(!repository.getMonitor(id))throw new ListeningError("Listening monitor not found.",404,"MONITOR_NOT_FOUND");return repository.listVersions(id);},
  collect(payload,userId){if(Object.hasOwn(payload,"workspaceId")||Object.hasOwn(payload,"workspace_id"))throw new ListeningError("Workspace ownership is server-resolved.");if(payload.providerState!==undefined&&payload.providerState!=="RATE_LIMITED")throw new ListeningError("providerState is invalid.");const version=repository.getVersion(text(payload.monitorVersionId,"monitorVersionId",100,true));if(!version)throw new ListeningError("Listening monitor version not found.",404,"MONITOR_VERSION_NOT_FOUND");const source=sourceRegistry.get(text(payload.sourceId,"sourceId",100,true),payload.sourceVersion||1);if(!source)throw new ListeningError("Listening source definition not found.",404,"SOURCE_NOT_FOUND");if(!source.runtimeAvailable)throw new ListeningError("Listening source adapter is not available in this deployment.",422,"SOURCE_RUNTIME_UNAVAILABLE");if(!version.sourceCategories.includes(source.category))throw new ListeningError("Source category is not enabled by this monitor.",422,"SOURCE_NOT_ALLOWED");if(version.providerFilters.length&&!version.providerFilters.includes(source.sourceId))throw new ListeningError("Provider is not enabled by this monitor.",422,"SOURCE_NOT_ALLOWED");if(!Array.isArray(payload.items))throw new ListeningError("items must be an array.");if(payload.items.length>version.maxRecordsPerRun)throw new ListeningError("Collection exceeds the monitor record limit.",413,"COLLECTION_LIMIT_EXCEEDED");const at=now().toISOString();try{const result=repository.collect({monitorVersionId:version.id,source,items:payload.items,providerState:payload.providerState,retryAfterSeconds:payload.retryAfterSeconds==null?null:number(payload.retryAfterSeconds,"retryAfterSeconds",1,86400),cursorBefore:payload.cursorBefore&&typeof payload.cursorBefore==='object'?payload.cursorBefore:{},cursorAfter:payload.cursorAfter&&typeof payload.cursorAfter==='object'?payload.cursorAfter:{},at,normalize:item=>normalizeListeningRecord(item,{provider:source.sourceId,sourceCategory:source.category,collectedAt:at,maxTextLength:version.maxNormalizedTextLength,retentionClass:version.retentionClass,retentionDays:version.retentionDays})});audit(userId,"listening.collection_completed","listening_collection_run",result.run.id,{monitorVersionId:version.id,sourceId:source.sourceId,status:result.run.status,accepted:result.run.itemsAccepted,deduplicated:result.run.itemsDeduplicated,rejected:result.run.itemsRejected});return result;}catch(e){if(e instanceof ListeningError)throw e;throw new ListeningError(e.message,400,"COLLECTION_REJECTED");}},
  runs(q={}){return repository.listRuns({monitorVersionId:q.monitorVersionId?text(q.monitorVersionId,"monitorVersionId",100):null,limit:boundedLimit(q)});},
  run(id){const value=repository.getRun(id);if(!value)throw new ListeningError("Collection run not found.",404,"RUN_NOT_FOUND");return value;},
  records(q={}){return repository.listRecords(recordFilters(q));},
  recordPage(q={}){const started=performance.now();try{const page=repository.listRecordPage(recordFilters(q));operationMetrics.record({operation:"listening_records.list",workspaceId:requireWorkspaceId(),durationMs:performance.now()-started,rowsRead:page.items.length+(page.nextCursor?1:0),rowsWritten:0,resultCount:page.items.length,reusedResult:false});return page;}catch(error){operationMetrics.record({operation:"listening_records.list",workspaceId:requireWorkspaceId(),durationMs:performance.now()-started,rowsRead:0,rowsWritten:0,resultCount:0,reusedResult:false,errorCode:error.code||"UNEXPECTED_ERROR"});throw error;}},
  operationMeasurements:operationMetrics.recent,
  record(id){const value=repository.getRecord(id);if(!value)throw new ListeningError("Listening record not found.",404,"RECORD_NOT_FOUND");return value;},
  aggregates:()=>repository.aggregates(),
});}
