import type { Dispatch, SetStateAction } from "react";
import type { LandingBlueprint } from "./TrustedLandingRenderer";
import { channelStrategies, goalLabels, landingGoals, strategyLabels } from "../../lib/landingConversion";

type Props={blueprint:LandingBlueprint;setBlueprint:Dispatch<SetStateAction<LandingBlueprint>>;selected:number;warnings:string[];onPreset:(goal:string,channel:string)=>void;onDuplicate:()=>void};
const variants:Record<string,string[]>={HERO:["CENTERED","SPLIT"],PROBLEM:["CARDS","NARRATIVE"],SOLUTION:["STEPS","SPLIT"],BENEFITS:["GRID","LIST"],FEATURES:["GRID","LIST"],TESTIMONIALS:["CARDS","QUOTE"],TRUST:["LOGOS","FACTS"],FAQ:["ACCORDION","LIST"],OFFER:["CARD","BANNER"],FORM_OR_ACTION:["ACTION"],CTA:["CENTERED","BANNER"],FOOTER:["MINIMAL","LINKS"]};
export default function LandingConversionInspector({blueprint,setBlueprint,selected,warnings,onPreset,onDuplicate}:Props){const s=blueprint.sections[selected],strategy=blueprint.conversionStrategy,cta=s?.props.primaryCta as LandingBlueprint["primaryCta"]|undefined,patch=(value:Record<string,unknown>)=>setBlueprint(b=>({...b,sections:b.sections.map((x,i)=>i===selected?{...x,props:{...x.props,...value}}:x)})),apply=()=>onPreset(strategy?.goal||"LEAD_GENERATION",strategy?.channelStrategy||"DIRECT");return <div className="space-y-4">
 <fieldset className="space-y-3 rounded-2xl border border-violet-400/20 bg-violet-400/5 p-4"><legend className="px-2 text-sm font-semibold text-violet-200">راهبرد تبدیل</legend>
  <label className="block text-xs text-white/65">هدف<select value={strategy?.goal||"LEAD_GENERATION"} onChange={e=>onPreset(e.target.value,strategy?.channelStrategy||"DIRECT")} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-[#0a0d1a] p-3">{landingGoals.map(x=><option key={x} value={x}>{goalLabels[x]}</option>)}</select></label>
  <label className="block text-xs text-white/65">مسیر ورودی<select value={strategy?.channelStrategy||"DIRECT"} onChange={e=>onPreset(strategy?.goal||"LEAD_GENERATION",e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-[#0a0d1a] p-3">{channelStrategies.map(x=><option key={x} value={x}>{strategyLabels[x]}</option>)}</select></label>
  {!strategy&&<button type="button" onClick={apply} className="min-h-11 w-full rounded-xl bg-violet-600 px-4 text-sm">ساخت صفحه از الگو</button>}
  {strategy&&<p className="text-xs leading-6 text-white/55">ترافیک: {strategyLabels[strategy.channelStrategy]} · هدف: {goalLabels[strategy.goal]} · اولویت تطابق پیام: {strategy.messageMatchPriority}</p>}
 </fieldset>
 <div role="status" className={`rounded-2xl border p-4 text-xs leading-6 ${warnings.length?"border-amber-400/30 bg-amber-400/5 text-amber-200":"border-emerald-400/30 bg-emerald-400/5 text-emerald-200"}`}><strong>{warnings.length?"نیازمند بازبینی پیام":"تطابق پیام مناسب است"}</strong>{warnings.map(x=><p key={x}>{x}</p>)}</div>
 {s&&<fieldset className="space-y-3 rounded-2xl border border-white/10 p-4"><legend className="px-2 text-sm font-semibold">تنظیمات بخش انتخاب‌شده</legend>
  <label className="block text-xs text-white/65">چیدمان<select value={s.variant} onChange={e=>setBlueprint(b=>({...b,sections:b.sections.map((x,i)=>i===selected?{...x,variant:e.target.value}:x)}))} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-[#0a0d1a] p-3">{(variants[s.componentId]||[s.variant]).map(x=><option key={x}>{x}</option>)}</select></label>
  {cta&&<><label className="block text-xs text-white/65">متن اقدام<input value={cta.label} maxLength={100} onChange={e=>patch({primaryCta:{...cta,label:e.target.value}})} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/20 p-3"/></label><label className="block text-xs text-white/65">نوع اقدام<select value={cta.type} onChange={e=>patch({primaryCta:{...cta,type:e.target.value}})} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-[#0a0d1a] p-3"><option value="EXTERNAL_URL">لینک امن</option><option value="BOOKING">رزرو خارجی</option><option value="PHONE">تماس</option><option value="WHATSAPP">واتس‌اپ</option></select></label><label className="block text-xs text-white/65">مقصد<input dir="ltr" value={cta.target} onChange={e=>patch({primaryCta:{...cta,target:e.target.value}})} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-left"/></label></>}
  <button type="button" onClick={onDuplicate} className="min-h-11 w-full rounded-xl border border-white/10 px-4 text-sm">تکثیر این بخش</button>
 </fieldset>}
 <fieldset className="grid grid-cols-2 gap-3 rounded-2xl border border-white/10 p-4"><legend className="px-2 text-sm font-semibold">ظاهر محدودشده</legend><label className="text-xs text-white/65">فاصله<select value={blueprint.designTokens.spacingDensity} onChange={e=>setBlueprint(b=>({...b,designTokens:{...b.designTokens,spacingDensity:e.target.value}}))} className="mt-2 min-h-11 w-full rounded-xl bg-[#0a0d1a] p-2"><option value="compact">فشرده</option><option value="comfortable">متعادل</option><option value="spacious">باز</option></select></label><label className="text-xs text-white/65">گوشه<select value={blueprint.designTokens.radius} onChange={e=>setBlueprint(b=>({...b,designTokens:{...b.designTokens,radius:e.target.value}}))} className="mt-2 min-h-11 w-full rounded-xl bg-[#0a0d1a] p-2"><option value="sm">کم</option><option value="md">متوسط</option><option value="lg">زیاد</option><option value="pill">کپسولی</option></select></label></fieldset>
 <p className="rounded-xl bg-white/5 p-3 text-xs leading-6 text-white/55">فرم داخلی و ذخیره اطلاعات حساس هنوز فعال نیست. برای تبدیل از واتس‌اپ، تماس یا لینک امن رزرو/فرم خارجی استفاده کنید.</p>
 </div>}
