import type { SectionConfig } from "../types";
import type { WebsiteTemplate } from "./types";

const item = (id: string, title: string, subtitle: string) => ({ id, title, subtitle, body: "", imageUrl: "", meta: "" });
const section = (id: string, type: SectionConfig["type"], title: string, subtitle: string, extra: Partial<SectionConfig> = {}): SectionConfig => ({ id, type, enabled: true, title, subtitle, backgroundColor: "#fff", textColor: "#0f172a", spacingTop: 32, spacingBottom: 32, ...extra });
const contact = (label: string) => section("contact-main", "contact", label, "فرم را کامل کنید تا با شما تماس بگیریم.", { showInNav: true, navLabel: "تماس", contact: { formEnabled: true, submitLabel: "ارسال درخواست", successMessage: "پیام شما ثبت شد.", phone: "", email: "", address: "", mapUrl: "" } });
const cards = (id: string, type: "services" | "team" | "portfolio", title: string, navLabel: string, values: [string, string][]) => section(id, type, title, "برای شروع آماده و قابل ویرایش است.", { showInNav: true, navLabel, columns: 3, items: values.map(([name, detail], index) => item(`${id}-${index}`, name, detail)) });

const medical: WebsiteTemplate = { id: "medical-practice-v1", label: "کلینیک و پزشک", description: "معرفی پزشک، خدمات درمانی و درخواست نوبت.", siteKind: "BUSINESS", design: { primaryColor: "#0f766e", secondaryColor: "#ccfbf1" }, header: { storeName: "کلینیک شما" }, hero: { layout: "background", eyebrow: "مراقبت حرفه‌ای", title: "سلامت شما، اولویت ماست", subtitle: "با آرامش، خدمات مناسب را انتخاب کنید.", ctaLabel: "درخواست نوبت", ctaHref: "#contact-main", backgroundColor: "#134e4a", overlayOpacity: 52 }, sections: [cards("doctor-main", "team", "پزشک شما", "پزشک", [["دکتر نام شما", "متخصص و مشاور درمان"]]), cards("services-main", "services", "خدمات کلینیک", "خدمات", [["ویزیت تخصصی", "بررسی و برنامه درمان"], ["درمان‌های کلینیک", "خدمت حرفه‌ای و ایمن"], ["پیگیری درمان", "همراهی پس از مراجعه"]]), section("testimonials-main", "text", "تجربه مراجعان", "نظر و رضایت مراجعان را اینجا اضافه کنید."), contact("درخواست نوبت")] };
const legal: WebsiteTemplate = { id: "legal-firm-v1", label: "موسسه حقوقی", description: "معرفی وکلا، تخصص‌ها، تجربه‌ها و درخواست مشاوره.", siteKind: "BUSINESS", design: { primaryColor: "#a16207", secondaryColor: "#fef3c7" }, header: { storeName: "موسسه حقوقی شما" }, hero: { layout: "background", eyebrow: "مشاوره حقوقی قابل اعتماد", title: "کنار شما برای تصمیم‌های مهم", subtitle: "مشاوره روشن و پیگیری دقیق پرونده.", ctaLabel: "درخواست مشاوره", ctaHref: "#contact-main", backgroundColor: "#292524", overlayOpacity: 58 }, sections: [cards("attorneys-main", "team", "وکلای ما", "وکلا", [["وکیل نام شما", "وکیل پایه یک دادگستری"], ["وکیل همکار", "مشاور حقوقی"]]), cards("practice-main", "services", "حوزه‌های فعالیت", "تخصص‌ها", [["حقوق خانواده", "مشاوره و پیگیری"], ["حقوق شرکت‌ها", "قرارداد و امور تجاری"], ["دعاوی ملکی", "بررسی و دفاع حقوقی"]]), cards("cases-main", "portfolio", "پرونده‌ها و تجربه‌ها", "تجربه‌ها", [["پرونده نمونه", "حقوق تجاری"], ["پرونده نمونه", "دعاوی ملکی"]]), contact("درخواست مشاوره حقوقی")] };
const education: WebsiteTemplate = { id: "education-center-v1", label: "مرکز آموزشی", description: "دوره‌ها، مدرسان، تجربه دانش‌پذیران و ثبت‌نام.", siteKind: "BUSINESS", design: { primaryColor: "#4338ca", secondaryColor: "#e0e7ff" }, header: { storeName: "آموزشگاه شما" }, hero: { layout: "centered", eyebrow: "یادگیری برای آینده", title: "مهارتی که آینده شما را می‌سازد", subtitle: "دوره‌های عملی با مسیر یادگیری روشن.", ctaLabel: "ثبت‌نام در دوره", ctaHref: "#contact-main", backgroundColor: "#312e81" }, sections: [cards("courses-main", "services", "دوره‌های آموزشی", "دوره‌ها", [["دوره پایه", "شروع اصولی و کاربردی"], ["دوره پیشرفته", "پروژه‌محور و تخصصی"], ["کارگاه عملی", "تمرین با مربی"]]), cards("teachers-main", "team", "مدرسان", "مدرسان", [["مدرس شما", "مدرس ارشد"], ["مدرس همکار", "مربی عملی"]]), section("testimonials-main", "text", "تجربه دانش‌پذیران", "داستان‌های موفقیت را اینجا با مخاطبانتان به اشتراک بگذارید."), contact("ثبت‌نام و مشاوره")] };
const corporate: WebsiteTemplate = { id: "corporate-company-v1", label: "شرکت حرفه‌ای", description: "درباره شرکت، خدمات، نمونه‌کارها، مشتریان و تماس.", siteKind: "BUSINESS", design: { primaryColor: "#0369a1", secondaryColor: "#e0f2fe" }, header: { storeName: "شرکت شما" }, hero: { layout: "split", eyebrow: "راهکارهای حرفه‌ای", title: "همراه مطمئن رشد کسب‌وکار شما", subtitle: "خدمات روشن و نتیجه‌محور برای سازمان شما.", ctaLabel: "درخواست مشاوره", ctaHref: "#contact-main" }, sections: [section("about-main", "about", "درباره شرکت", "داستان و مزیت رقابتی شما", { showInNav: true, navLabel: "درباره ما", body: "این بخش را با داستان، تخصص و دستاوردهای شرکت خود کامل کنید." }), cards("services-main", "services", "خدمات ما", "خدمات", [["مشاوره", "تحلیل و نقشه راه"], ["اجرا", "پیاده‌سازی راهکار"], ["پشتیبانی", "بهبود مستمر"]]), cards("portfolio-main", "portfolio", "نمونه‌کارها", "نمونه‌کارها", [["پروژه نمونه", "صنعت شما"], ["پروژه نمونه", "صنعت شما"]]), section("clients-main", "text", "مورد اعتماد مشتریان", "لوگوها یا نام مشتریان را اینجا اضافه کنید."), contact("شروع گفت‌وگو")] };

export const businessLaunchTemplates: readonly WebsiteTemplate[] = [medical, legal, education, corporate];
