export const migration029Phase4bGuards={version:29,name:"phase4b_immutability_tenant_guards",up(db){db.exec(`
CREATE TRIGGER IF NOT EXISTS trg_parsed_document_source BEFORE INSERT ON parsed_documents WHEN NOT EXISTS(SELECT 1 FROM knowledge_artifact_versions v WHERE v.id=NEW.artifact_version_id AND v.workspace_id=NEW.workspace_id) BEGIN SELECT RAISE(ABORT,'invalid parsed document source');END;
CREATE TRIGGER IF NOT EXISTS trg_extraction_source BEFORE INSERT ON extraction_runs WHEN NOT EXISTS(SELECT 1 FROM knowledge_artifact_versions v WHERE v.id=NEW.artifact_version_id AND v.workspace_id=NEW.workspace_id) OR (NEW.parsed_document_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM parsed_documents p WHERE p.id=NEW.parsed_document_id AND p.workspace_id=NEW.workspace_id AND p.artifact_version_id=NEW.artifact_version_id)) BEGIN SELECT RAISE(ABORT,'invalid extraction source');END;
CREATE TRIGGER IF NOT EXISTS trg_candidate_source BEFORE INSERT ON knowledge_field_candidates WHEN NOT EXISTS(SELECT 1 FROM extraction_runs r WHERE r.id=NEW.extraction_run_id AND r.workspace_id=NEW.workspace_id AND r.artifact_version_id=NEW.artifact_version_id) BEGIN SELECT RAISE(ABORT,'invalid candidate source');END;
CREATE TRIGGER IF NOT EXISTS trg_conflict_source BEFORE INSERT ON candidate_conflicts WHEN NOT EXISTS(SELECT 1 FROM knowledge_field_candidates c WHERE c.id=NEW.candidate_id AND c.workspace_id=NEW.workspace_id) OR (NEW.other_candidate_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM knowledge_field_candidates c WHERE c.id=NEW.other_candidate_id AND c.workspace_id=NEW.workspace_id)) BEGIN SELECT RAISE(ABORT,'invalid conflict source');END;
CREATE TRIGGER IF NOT EXISTS trg_review_source BEFORE INSERT ON candidate_reviews WHEN NOT EXISTS(SELECT 1 FROM knowledge_field_candidates c WHERE c.id=NEW.candidate_id AND c.workspace_id=NEW.workspace_id) BEGIN SELECT RAISE(ABORT,'invalid review source');END;
CREATE TRIGGER IF NOT EXISTS trg_proposal_link_source BEFORE INSERT ON proposal_candidate_links WHEN NOT EXISTS(SELECT 1 FROM canonical_proposals p WHERE p.id=NEW.proposal_id AND p.workspace_id=NEW.workspace_id) OR NOT EXISTS(SELECT 1 FROM knowledge_field_candidates c WHERE c.id=NEW.candidate_id AND c.workspace_id=NEW.workspace_id) BEGIN SELECT RAISE(ABORT,'invalid proposal attribution');END;
CREATE TRIGGER IF NOT EXISTS trg_fact_event_source BEFORE INSERT ON imported_fact_event_links WHEN NOT EXISTS(SELECT 1 FROM canonical_import_records f WHERE f.id=NEW.imported_fact_id AND f.workspace_id=NEW.workspace_id) OR NOT EXISTS(SELECT 1 FROM business_events e WHERE e.id=NEW.business_event_id AND e.workspace_id=NEW.workspace_id) BEGIN SELECT RAISE(ABORT,'invalid fact event mapping');END;
CREATE TRIGGER IF NOT EXISTS trg_parsed_immutable_u BEFORE UPDATE ON parsed_documents BEGIN SELECT RAISE(ABORT,'Parsed Documents are immutable');END;CREATE TRIGGER IF NOT EXISTS trg_parsed_immutable_d BEFORE DELETE ON parsed_documents BEGIN SELECT RAISE(ABORT,'Parsed Documents cannot be deleted');END;
CREATE TRIGGER IF NOT EXISTS trg_run_immutable_u BEFORE UPDATE ON extraction_runs BEGIN SELECT RAISE(ABORT,'Extraction Runs are immutable');END;CREATE TRIGGER IF NOT EXISTS trg_run_immutable_d BEFORE DELETE ON extraction_runs BEGIN SELECT RAISE(ABORT,'Extraction Runs cannot be deleted');END;
CREATE TRIGGER IF NOT EXISTS trg_field_candidate_u BEFORE UPDATE ON knowledge_field_candidates BEGIN SELECT RAISE(ABORT,'Candidates are immutable');END;CREATE TRIGGER IF NOT EXISTS trg_field_candidate_d BEFORE DELETE ON knowledge_field_candidates BEGIN SELECT RAISE(ABORT,'Candidates cannot be deleted');END;
CREATE TRIGGER IF NOT EXISTS trg_review_u BEFORE UPDATE ON candidate_reviews BEGIN SELECT RAISE(ABORT,'Reviews are immutable');END;CREATE TRIGGER IF NOT EXISTS trg_review_d BEFORE DELETE ON candidate_reviews BEGIN SELECT RAISE(ABORT,'Reviews cannot be deleted');END;
CREATE TRIGGER IF NOT EXISTS trg_conflict_u BEFORE UPDATE ON candidate_conflicts BEGIN SELECT RAISE(ABORT,'Conflicts are immutable');END;CREATE TRIGGER IF NOT EXISTS trg_conflict_d BEFORE DELETE ON candidate_conflicts BEGIN SELECT RAISE(ABORT,'Conflicts cannot be deleted');END;
CREATE TRIGGER IF NOT EXISTS trg_proposal_u BEFORE UPDATE ON canonical_proposals BEGIN SELECT RAISE(ABORT,'Canonical proposals are immutable drafts');END;CREATE TRIGGER IF NOT EXISTS trg_proposal_d BEFORE DELETE ON canonical_proposals BEGIN SELECT RAISE(ABORT,'Canonical proposals cannot be deleted');END;
CREATE TRIGGER IF NOT EXISTS trg_fact_link_u BEFORE UPDATE ON imported_fact_event_links BEGIN SELECT RAISE(ABORT,'Mapping links are immutable');END;CREATE TRIGGER IF NOT EXISTS trg_fact_link_d BEFORE DELETE ON imported_fact_event_links BEGIN SELECT RAISE(ABORT,'Mapping links cannot be deleted');END;`);}};
