export const migration034ListeningIntelligence={version:34,name:"listening_intelligence",up(db){db.exec(`
CREATE TABLE IF NOT EXISTS listening_topic_matches(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,listening_record_id TEXT NOT NULL,monitor_version_id TEXT NOT NULL,topic_type TEXT NOT NULL,topic_key TEXT NOT NULL,configured_text TEXT NOT NULL,matched_text TEXT NOT NULL,normalized_match TEXT NOT NULL,language TEXT,match_method TEXT NOT NULL,rule_version INTEGER NOT NULL,producer_key TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(workspace_id,producer_key),FOREIGN KEY(workspace_id) REFERENCES workspaces(id),FOREIGN KEY(listening_record_id) REFERENCES canonical_listening_records(id),FOREIGN KEY(monitor_version_id) REFERENCES listening_monitor_versions(id));
CREATE INDEX IF NOT EXISTS idx_listening_topics_query ON listening_topic_matches(workspace_id,topic_type,topic_key,created_at DESC);
CREATE TABLE IF NOT EXISTS listening_aggregates(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,metric_type TEXT NOT NULL,metric_version INTEGER NOT NULL,entity_type TEXT,entity_key TEXT,topic_key TEXT,source_type TEXT,channel TEXT,language TEXT,window_policy TEXT NOT NULL,window_start TEXT NOT NULL,window_end TEXT NOT NULL,point_in_time_cutoff TEXT NOT NULL,calculated_at TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('available','unavailable','insufficient_data')),numeric_value REAL,json_value TEXT,numerator REAL,denominator REAL,source_record_count INTEGER NOT NULL,source_manifest_json TEXT NOT NULL,context_version_id TEXT,producer TEXT NOT NULL,producer_version TEXT NOT NULL,producer_key TEXT NOT NULL,provenance_json TEXT NOT NULL,UNIQUE(workspace_id,producer_key),FOREIGN KEY(workspace_id) REFERENCES workspaces(id),FOREIGN KEY(context_version_id) REFERENCES business_context_versions(id),CHECK(json_value IS NULL OR json_valid(json_value)),CHECK(json_valid(source_manifest_json)),CHECK(json_valid(provenance_json)));
CREATE INDEX IF NOT EXISTS idx_listening_aggregates_query ON listening_aggregates(workspace_id,metric_type,window_end DESC,calculated_at DESC); CREATE INDEX IF NOT EXISTS idx_listening_aggregates_entity ON listening_aggregates(workspace_id,entity_type,entity_key,window_end DESC); CREATE INDEX IF NOT EXISTS idx_listening_aggregates_topic ON listening_aggregates(workspace_id,topic_key,window_end DESC);
CREATE TABLE IF NOT EXISTS listening_trend_signals(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,signal_type TEXT NOT NULL,signal_version INTEGER NOT NULL,current_aggregate_id TEXT NOT NULL,baseline_aggregate_id TEXT,state TEXT NOT NULL,severity TEXT NOT NULL,current_value REAL,baseline_value REAL,absolute_delta REAL,relative_delta REAL,confidence REAL,confidence_reason TEXT NOT NULL,window_start TEXT NOT NULL,window_end TEXT NOT NULL,calculated_at TEXT NOT NULL,context_version_id TEXT,producer TEXT NOT NULL,producer_version TEXT NOT NULL,producer_key TEXT NOT NULL,provenance_json TEXT NOT NULL,UNIQUE(workspace_id,producer_key),FOREIGN KEY(workspace_id) REFERENCES workspaces(id),FOREIGN KEY(current_aggregate_id) REFERENCES listening_aggregates(id),FOREIGN KEY(baseline_aggregate_id) REFERENCES listening_aggregates(id),FOREIGN KEY(context_version_id) REFERENCES business_context_versions(id),CHECK(json_valid(provenance_json)));
CREATE INDEX IF NOT EXISTS idx_listening_trends_query ON listening_trend_signals(workspace_id,signal_type,window_end DESC,calculated_at DESC);
CREATE TABLE IF NOT EXISTS listening_anomaly_results(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,metric_type TEXT NOT NULL,aggregate_id TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('insufficient_data','normal','elevated','anomalous')),score REAL,baseline_center REAL,dispersion REAL,current_value REAL,sample_count INTEGER NOT NULL,method TEXT NOT NULL,method_version INTEGER NOT NULL,baseline_window_start TEXT,baseline_window_end TEXT,calculated_at TEXT NOT NULL,explanation TEXT NOT NULL,producer_key TEXT NOT NULL,provenance_json TEXT NOT NULL,UNIQUE(workspace_id,producer_key),FOREIGN KEY(workspace_id) REFERENCES workspaces(id),FOREIGN KEY(aggregate_id) REFERENCES listening_aggregates(id),CHECK(json_valid(provenance_json)));
CREATE INDEX IF NOT EXISTS idx_listening_anomalies_query ON listening_anomaly_results(workspace_id,metric_type,calculated_at DESC);
CREATE TRIGGER IF NOT EXISTS trg_li_aggregate_guard BEFORE INSERT ON listening_aggregates BEGIN SELECT CASE WHEN NEW.context_version_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM business_context_versions c WHERE c.id=NEW.context_version_id AND c.workspace_id=NEW.workspace_id) THEN RAISE(ABORT,'cross-workspace listening context') END; SELECT CASE WHEN EXISTS(SELECT 1 FROM json_each(NEW.source_manifest_json,'$.recordIds') s WHERE NOT EXISTS(SELECT 1 FROM canonical_listening_records r WHERE r.id=s.value AND r.workspace_id=NEW.workspace_id)) THEN RAISE(ABORT,'cross-workspace listening source') END; END;
CREATE TRIGGER IF NOT EXISTS trg_li_topic_guard BEFORE INSERT ON listening_topic_matches BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM canonical_listening_records r WHERE r.id=NEW.listening_record_id AND r.workspace_id=NEW.workspace_id AND r.monitor_version_id=NEW.monitor_version_id) THEN RAISE(ABORT,'cross-workspace listening topic') END; END;
CREATE TRIGGER IF NOT EXISTS trg_li_trend_guard BEFORE INSERT ON listening_trend_signals BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM listening_aggregates a WHERE a.id=NEW.current_aggregate_id AND a.workspace_id=NEW.workspace_id) OR(NEW.baseline_aggregate_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM listening_aggregates b WHERE b.id=NEW.baseline_aggregate_id AND b.workspace_id=NEW.workspace_id))THEN RAISE(ABORT,'cross-workspace listening trend') END; END;
CREATE TRIGGER IF NOT EXISTS trg_li_anomaly_guard BEFORE INSERT ON listening_anomaly_results BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM listening_aggregates a WHERE a.id=NEW.aggregate_id AND a.workspace_id=NEW.workspace_id)THEN RAISE(ABORT,'cross-workspace listening anomaly') END; END;
CREATE TRIGGER IF NOT EXISTS trg_li_aggregate_update BEFORE UPDATE ON listening_aggregates BEGIN SELECT RAISE(ABORT,'listening aggregates are immutable'); END; CREATE TRIGGER IF NOT EXISTS trg_li_aggregate_delete BEFORE DELETE ON listening_aggregates BEGIN SELECT RAISE(ABORT,'listening aggregates are immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_li_topic_update BEFORE UPDATE ON listening_topic_matches BEGIN SELECT RAISE(ABORT,'listening topics are immutable'); END; CREATE TRIGGER IF NOT EXISTS trg_li_topic_delete BEFORE DELETE ON listening_topic_matches BEGIN SELECT RAISE(ABORT,'listening topics are immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_li_trend_update BEFORE UPDATE ON listening_trend_signals BEGIN SELECT RAISE(ABORT,'listening trends are immutable'); END; CREATE TRIGGER IF NOT EXISTS trg_li_trend_delete BEFORE DELETE ON listening_trend_signals BEGIN SELECT RAISE(ABORT,'listening trends are immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_li_anomaly_update BEFORE UPDATE ON listening_anomaly_results BEGIN SELECT RAISE(ABORT,'listening anomalies are immutable'); END; CREATE TRIGGER IF NOT EXISTS trg_li_anomaly_delete BEFORE DELETE ON listening_anomaly_results BEGIN SELECT RAISE(ABORT,'listening anomalies are immutable'); END;
`);}};
