export const migration056PerformanceObservations={version:56,name:"performance_observations",up(db){db.exec(`
 CREATE TABLE IF NOT EXISTS performance_observations(
  id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 100),workspace_id TEXT NOT NULL REFERENCES workspaces(id),distribution_context_id TEXT NOT NULL REFERENCES distribution_contexts(id),attribution_touch_id TEXT REFERENCES attribution_touches(id),observation_contract_id TEXT NOT NULL CHECK(length(observation_contract_id) BETWEEN 1 AND 100),observation_contract_version INTEGER NOT NULL CHECK(observation_contract_version>0),observation_type TEXT NOT NULL CHECK(length(observation_type) BETWEEN 1 AND 80),value_number REAL,value_text TEXT CHECK(value_text IS NULL OR length(value_text)<=2000),value_json TEXT CHECK(value_json IS NULL OR(json_valid(value_json) AND length(value_json)<=8192)),unit TEXT CHECK(unit IS NULL OR length(unit)<=40),sensor_type TEXT NOT NULL CHECK(length(sensor_type) BETWEEN 1 AND 80 AND sensor_type NOT GLOB '*[^a-z0-9._-]*'),sensor_version INTEGER NOT NULL CHECK(sensor_version>0),external_reference TEXT CHECK(external_reference IS NULL OR length(external_reference) BETWEEN 1 AND 500),occurred_at TEXT NOT NULL CHECK(length(occurred_at) BETWEEN 20 AND 40),ingested_at TEXT NOT NULL CHECK(length(ingested_at) BETWEEN 20 AND 40),payload_fingerprint TEXT CHECK(payload_fingerprint IS NULL OR(length(payload_fingerprint)=64 AND payload_fingerprint NOT GLOB '*[^0-9a-f]*')),idempotency_key TEXT NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 200),request_hash TEXT NOT NULL CHECK(length(request_hash)=64 AND request_hash NOT GLOB '*[^0-9a-f]*'),created_at TEXT NOT NULL CHECK(length(created_at) BETWEEN 20 AND 40),CHECK((value_number IS NOT NULL)+(value_text IS NOT NULL)+(value_json IS NOT NULL)=1)
 );
 CREATE UNIQUE INDEX IF NOT EXISTS uq_performance_observations_ingestion ON performance_observations(workspace_id,sensor_type,sensor_version,COALESCE(external_reference,''),idempotency_key);
 CREATE INDEX IF NOT EXISTS idx_performance_observations_context_history ON performance_observations(workspace_id,distribution_context_id,occurred_at DESC,ingested_at DESC,id DESC);
 CREATE INDEX IF NOT EXISTS idx_performance_observations_touch_history ON performance_observations(workspace_id,attribution_touch_id,occurred_at DESC,id DESC) WHERE attribution_touch_id IS NOT NULL;
 CREATE TRIGGER IF NOT EXISTS trg_performance_observations_insert_guard BEFORE INSERT ON performance_observations BEGIN
  SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM workspaces WHERE id=NEW.workspace_id AND status='active') THEN RAISE(ABORT,'performance observation workspace must be active') END;
  SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM distribution_contexts WHERE id=NEW.distribution_context_id AND workspace_id=NEW.workspace_id) THEN RAISE(ABORT,'performance observation context mismatch') END;
  SELECT CASE WHEN NEW.attribution_touch_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM attribution_touches WHERE id=NEW.attribution_touch_id AND workspace_id=NEW.workspace_id AND distribution_context_id=NEW.distribution_context_id) THEN RAISE(ABORT,'performance observation touch mismatch') END;
 END;
 CREATE TRIGGER IF NOT EXISTS trg_performance_observations_update_reject BEFORE UPDATE ON performance_observations BEGIN SELECT RAISE(ABORT,'performance observations are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS trg_performance_observations_delete_reject BEFORE DELETE ON performance_observations BEGIN SELECT RAISE(ABORT,'performance observations are immutable'); END;
`);}};
