export const migration058WebsiteBuilderFoundation={version:58,name:"website_builder_foundation",up(db){db.exec(`
CREATE TABLE IF NOT EXISTS website_projects(
 id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 100),workspace_id TEXT NOT NULL REFERENCES workspaces(id),created_by_user_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 200),slug TEXT NOT NULL CHECK(length(slug) BETWEEN 1 AND 80 AND slug NOT GLOB '*[^a-z0-9-]*'),website_type TEXT NOT NULL CHECK(website_type IN('CORPORATE','PROFESSIONAL_SERVICE','MEDICAL','LEGAL','SERVICE','CATALOG')),preset_id TEXT NOT NULL CHECK(length(preset_id) BETWEEN 1 AND 80),preset_version INTEGER NOT NULL CHECK(preset_version>0),business_context_version_id TEXT NOT NULL REFERENCES business_context_versions(id),locale TEXT NOT NULL CHECK(locale IN('fa-IR','en-US')),direction TEXT NOT NULL CHECK(direction IN('rtl','ltr')),theme_json TEXT NOT NULL CHECK(json_valid(theme_json) AND length(theme_json)<=8192),status TEXT NOT NULL CHECK(status IN('DRAFT','PUBLISHED','ARCHIVED')),current_publication_id TEXT REFERENCES website_publications(id),idempotency_key TEXT NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 200),request_hash TEXT NOT NULL CHECK(length(request_hash)=64),created_at TEXT NOT NULL,updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_website_project_slug ON website_projects(workspace_id,slug);
CREATE UNIQUE INDEX IF NOT EXISTS uq_website_project_create ON website_projects(workspace_id,created_by_user_id,idempotency_key);
CREATE INDEX IF NOT EXISTS idx_website_project_history ON website_projects(workspace_id,updated_at DESC,id DESC);
CREATE TRIGGER IF NOT EXISTS trg_website_project_insert_guard BEFORE INSERT ON website_projects BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM workspace_memberships WHERE workspace_id=NEW.workspace_id AND user_id=NEW.created_by_user_id AND status='active') THEN RAISE(ABORT,'website membership inactive') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM business_context_versions WHERE id=NEW.business_context_version_id AND workspace_id=NEW.workspace_id) THEN RAISE(ABORT,'website context mismatch') END;
 SELECT CASE WHEN NEW.locale='fa-IR' AND NEW.direction<>'rtl' THEN RAISE(ABORT,'website direction mismatch') END;
END;
CREATE TRIGGER IF NOT EXISTS trg_website_project_identity_guard BEFORE UPDATE ON website_projects WHEN NEW.id IS NOT OLD.id OR NEW.workspace_id IS NOT OLD.workspace_id OR NEW.created_by_user_id IS NOT OLD.created_by_user_id OR NEW.slug IS NOT OLD.slug OR NEW.website_type IS NOT OLD.website_type OR NEW.preset_id IS NOT OLD.preset_id OR NEW.preset_version IS NOT OLD.preset_version OR NEW.business_context_version_id IS NOT OLD.business_context_version_id OR NEW.theme_json IS NOT OLD.theme_json OR NEW.created_at IS NOT OLD.created_at BEGIN SELECT RAISE(ABORT,'website identity immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_website_project_delete_reject BEFORE DELETE ON website_projects BEGIN SELECT RAISE(ABORT,'website projects cannot be deleted'); END;

CREATE TABLE IF NOT EXISTS website_pages(
 id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 100),workspace_id TEXT NOT NULL REFERENCES workspaces(id),website_project_id TEXT NOT NULL REFERENCES website_projects(id),created_by_user_id TEXT NOT NULL REFERENCES users(id),page_type TEXT NOT NULL CHECK(page_type IN('HOME','ABOUT','SERVICES','SERVICE_DETAIL','CONTACT','FAQ','BLOG_INDEX','CUSTOM_PAGE')),name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 160),path TEXT NOT NULL CHECK(length(path) BETWEEN 1 AND 160 AND substr(path,1,1)='/'),navigation_visible INTEGER NOT NULL CHECK(navigation_visible IN(0,1)),navigation_order INTEGER NOT NULL CHECK(navigation_order BETWEEN 0 AND 1000),status TEXT NOT NULL CHECK(status IN('DRAFT','PUBLISHED','ARCHIVED')),current_draft_blueprint_id TEXT REFERENCES website_page_blueprint_versions(id),current_published_blueprint_id TEXT REFERENCES website_page_blueprint_versions(id),idempotency_key TEXT NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 200),request_hash TEXT NOT NULL CHECK(length(request_hash)=64),created_at TEXT NOT NULL,updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_website_page_path ON website_pages(workspace_id,website_project_id,path);
CREATE UNIQUE INDEX IF NOT EXISTS uq_website_page_create ON website_pages(workspace_id,website_project_id,created_by_user_id,idempotency_key);
CREATE INDEX IF NOT EXISTS idx_website_page_navigation ON website_pages(workspace_id,website_project_id,navigation_visible DESC,navigation_order,id);
CREATE TRIGGER IF NOT EXISTS trg_website_page_insert_guard BEFORE INSERT ON website_pages BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM website_projects WHERE id=NEW.website_project_id AND workspace_id=NEW.workspace_id) THEN RAISE(ABORT,'website page project mismatch') END; END;
CREATE TRIGGER IF NOT EXISTS trg_website_page_identity_guard BEFORE UPDATE ON website_pages WHEN NEW.id IS NOT OLD.id OR NEW.workspace_id IS NOT OLD.workspace_id OR NEW.website_project_id IS NOT OLD.website_project_id OR NEW.created_by_user_id IS NOT OLD.created_by_user_id OR NEW.page_type IS NOT OLD.page_type OR NEW.path IS NOT OLD.path OR NEW.created_at IS NOT OLD.created_at BEGIN SELECT RAISE(ABORT,'website page identity immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_website_page_delete_reject BEFORE DELETE ON website_pages BEGIN SELECT RAISE(ABORT,'website pages cannot be deleted'); END;

CREATE TABLE IF NOT EXISTS website_page_blueprint_versions(
 id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 100),workspace_id TEXT NOT NULL REFERENCES workspaces(id),website_project_id TEXT NOT NULL REFERENCES website_projects(id),website_page_id TEXT NOT NULL REFERENCES website_pages(id),created_by_user_id TEXT NOT NULL REFERENCES users(id),version INTEGER NOT NULL CHECK(version>0),schema_version INTEGER NOT NULL CHECK(schema_version>0),component_registry_version INTEGER NOT NULL CHECK(component_registry_version>0),design_token_version INTEGER NOT NULL CHECK(design_token_version>0),tracking_contract_version INTEGER NOT NULL CHECK(tracking_contract_version>0),renderer_version INTEGER NOT NULL CHECK(renderer_version>0),locale TEXT NOT NULL CHECK(length(locale) BETWEEN 2 AND 20),direction TEXT NOT NULL CHECK(direction IN('rtl','ltr')),blueprint_json TEXT NOT NULL CHECK(json_valid(blueprint_json) AND length(blueprint_json)<=131072),content_hash TEXT NOT NULL CHECK(length(content_hash)=64),supersedes_blueprint_id TEXT REFERENCES website_page_blueprint_versions(id),idempotency_key TEXT NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 200),request_hash TEXT NOT NULL CHECK(length(request_hash)=64),created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_website_page_blueprint_version ON website_page_blueprint_versions(workspace_id,website_page_id,version);
CREATE UNIQUE INDEX IF NOT EXISTS uq_website_page_blueprint_create ON website_page_blueprint_versions(workspace_id,website_page_id,created_by_user_id,idempotency_key);
CREATE INDEX IF NOT EXISTS idx_website_page_blueprint_history ON website_page_blueprint_versions(workspace_id,website_page_id,version DESC,id DESC);
CREATE TRIGGER IF NOT EXISTS trg_website_page_blueprint_insert_guard BEFORE INSERT ON website_page_blueprint_versions BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM website_pages WHERE id=NEW.website_page_id AND website_project_id=NEW.website_project_id AND workspace_id=NEW.workspace_id) THEN RAISE(ABORT,'website blueprint page mismatch') END; SELECT CASE WHEN NEW.version<>COALESCE((SELECT MAX(version)+1 FROM website_page_blueprint_versions WHERE website_page_id=NEW.website_page_id AND workspace_id=NEW.workspace_id),1) THEN RAISE(ABORT,'website blueprint version invalid') END; END;
CREATE TRIGGER IF NOT EXISTS trg_website_page_blueprint_update_reject BEFORE UPDATE ON website_page_blueprint_versions BEGIN SELECT RAISE(ABORT,'website page blueprints are immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_website_page_blueprint_delete_reject BEFORE DELETE ON website_page_blueprint_versions BEGIN SELECT RAISE(ABORT,'website page blueprints are immutable'); END;

CREATE TABLE IF NOT EXISTS website_publications(
 id TEXT PRIMARY KEY CHECK(length(id) BETWEEN 1 AND 100),workspace_id TEXT NOT NULL REFERENCES workspaces(id),website_project_id TEXT NOT NULL REFERENCES website_projects(id),published_by_user_id TEXT NOT NULL REFERENCES users(id),publication_version INTEGER NOT NULL CHECK(publication_version>0),manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json) AND length(manifest_json)<=131072),manifest_hash TEXT NOT NULL CHECK(length(manifest_hash)=64),host TEXT CHECK(host IS NULL OR length(host)<=255),base_path TEXT CHECK(base_path IS NULL OR length(base_path)<=500),status TEXT NOT NULL CHECK(status IN('PUBLISHED','FAILED','SUPERSEDED')),failure_code TEXT CHECK(failure_code IS NULL OR length(failure_code)<=100),idempotency_key TEXT NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 200),request_hash TEXT NOT NULL CHECK(length(request_hash)=64),created_at TEXT NOT NULL,published_at TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_website_publication_version ON website_publications(workspace_id,website_project_id,publication_version);
CREATE UNIQUE INDEX IF NOT EXISTS uq_website_publication_create ON website_publications(workspace_id,website_project_id,published_by_user_id,idempotency_key);
CREATE INDEX IF NOT EXISTS idx_website_publication_history ON website_publications(workspace_id,website_project_id,publication_version DESC,id DESC);
CREATE TRIGGER IF NOT EXISTS trg_website_publication_insert_guard BEFORE INSERT ON website_publications BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM website_projects WHERE id=NEW.website_project_id AND workspace_id=NEW.workspace_id) THEN RAISE(ABORT,'website publication project mismatch') END; SELECT CASE WHEN NEW.publication_version<>COALESCE((SELECT MAX(publication_version)+1 FROM website_publications WHERE website_project_id=NEW.website_project_id AND workspace_id=NEW.workspace_id),1) THEN RAISE(ABORT,'website publication version invalid') END; END;
CREATE TRIGGER IF NOT EXISTS trg_website_publication_update_reject BEFORE UPDATE ON website_publications BEGIN SELECT RAISE(ABORT,'website publications are immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_website_publication_delete_reject BEFORE DELETE ON website_publications BEGIN SELECT RAISE(ABORT,'website publications are immutable'); END;
`);}};
