export const migration062InventoryFulfillmentFoundation={version:62,name:"inventory_fulfillment_foundation",up(db){db.exec(`
CREATE TABLE IF NOT EXISTS commerce_inventory_items(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),catalog_id TEXT NOT NULL REFERENCES commerce_catalogs(id),product_id TEXT NOT NULL REFERENCES commerce_products(id),variant_id TEXT REFERENCES commerce_product_variants(id),tracking_mode TEXT NOT NULL CHECK(tracking_mode IN('TRACKED','UNTRACKED')),stock_on_hand INTEGER NOT NULL CHECK(stock_on_hand>=0),stock_reserved INTEGER NOT NULL DEFAULT 0 CHECK(stock_reserved>=0 AND stock_reserved<=stock_on_hand),low_stock_threshold INTEGER CHECK(low_stock_threshold IS NULL OR low_stock_threshold>=0),revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0),created_by_user_id TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_product ON commerce_inventory_items(workspace_id,product_id) WHERE variant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_variant ON commerce_inventory_items(workspace_id,product_id,variant_id) WHERE variant_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_catalog ON commerce_inventory_items(workspace_id,catalog_id,product_id,variant_id);
CREATE TRIGGER IF NOT EXISTS trg_inventory_identity_update BEFORE UPDATE ON commerce_inventory_items WHEN NEW.id<>OLD.id OR NEW.workspace_id<>OLD.workspace_id OR NEW.catalog_id<>OLD.catalog_id OR NEW.product_id<>OLD.product_id OR NEW.variant_id IS NOT OLD.variant_id OR NEW.created_by_user_id<>OLD.created_by_user_id BEGIN SELECT RAISE(ABORT,'inventory identity immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_inventory_tenant_guard BEFORE INSERT ON commerce_inventory_items WHEN NOT EXISTS(SELECT 1 FROM commerce_products p WHERE p.id=NEW.product_id AND p.workspace_id=NEW.workspace_id AND p.catalog_id=NEW.catalog_id) OR (NEW.variant_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM commerce_product_variants v WHERE v.id=NEW.variant_id AND v.product_id=NEW.product_id AND v.workspace_id=NEW.workspace_id)) BEGIN SELECT RAISE(ABORT,'inventory tenant mismatch'); END;

CREATE TABLE IF NOT EXISTS commerce_inventory_reservations(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),inventory_item_id TEXT NOT NULL REFERENCES commerce_inventory_items(id),pending_order_id TEXT NOT NULL REFERENCES commerce_pending_orders(id),confirmed_order_id TEXT REFERENCES commerce_orders(id),quantity INTEGER NOT NULL CHECK(quantity>0),status TEXT NOT NULL CHECK(status IN('ACTIVE','COMMITTED','RELEASED','EXPIRED')),idempotency_key TEXT NOT NULL,request_hash TEXT NOT NULL CHECK(length(request_hash)=64),expires_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,committed_at TEXT,released_at TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_reservation_order_item ON commerce_inventory_reservations(workspace_id,pending_order_id,inventory_item_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_reservation_idempotency ON commerce_inventory_reservations(workspace_id,pending_order_id,idempotency_key);
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_expiry ON commerce_inventory_reservations(workspace_id,status,expires_at,id);
CREATE INDEX IF NOT EXISTS idx_inventory_reservation_order ON commerce_inventory_reservations(workspace_id,pending_order_id,status,id);
CREATE TRIGGER IF NOT EXISTS trg_reservation_identity_update BEFORE UPDATE ON commerce_inventory_reservations WHEN NEW.id<>OLD.id OR NEW.workspace_id<>OLD.workspace_id OR NEW.inventory_item_id<>OLD.inventory_item_id OR NEW.pending_order_id<>OLD.pending_order_id OR NEW.quantity<>OLD.quantity OR NEW.idempotency_key<>OLD.idempotency_key OR NEW.request_hash<>OLD.request_hash BEGIN SELECT RAISE(ABORT,'reservation identity immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_reservation_delete BEFORE DELETE ON commerce_inventory_reservations BEGIN SELECT RAISE(ABORT,'reservation immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_reservation_tenant_guard BEFORE INSERT ON commerce_inventory_reservations WHEN NOT EXISTS(SELECT 1 FROM commerce_inventory_items i,commerce_pending_orders o WHERE i.id=NEW.inventory_item_id AND o.id=NEW.pending_order_id AND i.workspace_id=NEW.workspace_id AND o.workspace_id=NEW.workspace_id) BEGIN SELECT RAISE(ABORT,'reservation tenant mismatch'); END;
CREATE TRIGGER IF NOT EXISTS trg_reservation_transition BEFORE UPDATE ON commerce_inventory_reservations WHEN NEW.status<>OLD.status AND NOT(OLD.status='ACTIVE' AND NEW.status IN('COMMITTED','RELEASED','EXPIRED')) BEGIN SELECT RAISE(ABORT,'reservation transition invalid'); END;

CREATE TABLE IF NOT EXISTS commerce_fulfillments(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),confirmed_order_id TEXT NOT NULL REFERENCES commerce_orders(id),status TEXT NOT NULL CHECK(status IN('PENDING','READY_TO_SHIP','READY_FOR_PICKUP','SHIPPED','COMPLETED','BLOCKED','CANCELLED')),fulfillment_mode TEXT NOT NULL CHECK(fulfillment_mode IN('PHYSICAL_DELIVERY','PICKUP','SERVICE_OR_DIGITAL','CONTACT_TO_COMPLETE')),processing_status TEXT NOT NULL CHECK(processing_status IN('FULFILLMENT_PENDING','INVENTORY_COMMITTED','INVENTORY_EXCEPTION')),idempotency_key TEXT NOT NULL,request_hash TEXT NOT NULL CHECK(length(request_hash)=64),revision INTEGER NOT NULL DEFAULT 1,created_by_user_id TEXT REFERENCES users(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,ready_at TEXT,completed_at TEXT,cancelled_at TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS uq_fulfillment_order ON commerce_fulfillments(workspace_id,confirmed_order_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_fulfillment_create ON commerce_fulfillments(workspace_id,confirmed_order_id,idempotency_key);
CREATE INDEX IF NOT EXISTS idx_fulfillment_list ON commerce_fulfillments(workspace_id,status,updated_at DESC,id);
CREATE TRIGGER IF NOT EXISTS trg_fulfillment_identity_update BEFORE UPDATE ON commerce_fulfillments WHEN NEW.id<>OLD.id OR NEW.workspace_id<>OLD.workspace_id OR NEW.confirmed_order_id<>OLD.confirmed_order_id OR NEW.fulfillment_mode<>OLD.fulfillment_mode OR NEW.idempotency_key<>OLD.idempotency_key OR NEW.request_hash<>OLD.request_hash BEGIN SELECT RAISE(ABORT,'fulfillment identity immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_fulfillment_delete BEFORE DELETE ON commerce_fulfillments BEGIN SELECT RAISE(ABORT,'fulfillment history immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_fulfillment_tenant_guard BEFORE INSERT ON commerce_fulfillments WHEN NOT EXISTS(SELECT 1 FROM commerce_orders o WHERE o.id=NEW.confirmed_order_id AND o.workspace_id=NEW.workspace_id) BEGIN SELECT RAISE(ABORT,'fulfillment tenant mismatch'); END;

CREATE TABLE IF NOT EXISTS commerce_shipments(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),fulfillment_id TEXT NOT NULL REFERENCES commerce_fulfillments(id),confirmed_order_id TEXT NOT NULL REFERENCES commerce_orders(id),shipping_provider TEXT NOT NULL CHECK(shipping_provider IN('MANUAL','TEST','POST_IR','TIPAX','COURIER','OTHER')),provider_binding_version INTEGER NOT NULL CHECK(provider_binding_version>0),status TEXT NOT NULL CHECK(status IN('CREATED','READY','IN_TRANSIT','DELIVERED','FAILED','CANCELLED')),tracking_number TEXT CHECK(tracking_number IS NULL OR length(tracking_number) BETWEEN 1 AND 200),provider_shipment_reference TEXT CHECK(provider_shipment_reference IS NULL OR length(provider_shipment_reference)<=200),idempotency_key TEXT NOT NULL,request_hash TEXT NOT NULL CHECK(length(request_hash)=64),revision INTEGER NOT NULL DEFAULT 1,created_by_user_id TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,shipped_at TEXT,delivered_at TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS uq_shipment_fulfillment ON commerce_shipments(workspace_id,fulfillment_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_shipment_create ON commerce_shipments(workspace_id,fulfillment_id,idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_shipment_provider_reference ON commerce_shipments(shipping_provider,provider_shipment_reference) WHERE provider_shipment_reference IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_shipment_list ON commerce_shipments(workspace_id,status,updated_at DESC,id);
CREATE INDEX IF NOT EXISTS idx_shipment_order ON commerce_shipments(workspace_id,confirmed_order_id,id);
CREATE TRIGGER IF NOT EXISTS trg_shipment_identity_update BEFORE UPDATE ON commerce_shipments WHEN NEW.id<>OLD.id OR NEW.workspace_id<>OLD.workspace_id OR NEW.fulfillment_id<>OLD.fulfillment_id OR NEW.confirmed_order_id<>OLD.confirmed_order_id OR NEW.shipping_provider<>OLD.shipping_provider OR NEW.provider_binding_version<>OLD.provider_binding_version OR NEW.idempotency_key<>OLD.idempotency_key OR NEW.request_hash<>OLD.request_hash BEGIN SELECT RAISE(ABORT,'shipment identity immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_shipment_delete BEFORE DELETE ON commerce_shipments BEGIN SELECT RAISE(ABORT,'shipment history immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_shipment_tenant_guard BEFORE INSERT ON commerce_shipments WHEN NOT EXISTS(SELECT 1 FROM commerce_fulfillments f WHERE f.id=NEW.fulfillment_id AND f.confirmed_order_id=NEW.confirmed_order_id AND f.workspace_id=NEW.workspace_id) BEGIN SELECT RAISE(ABORT,'shipment tenant mismatch'); END;
CREATE TRIGGER IF NOT EXISTS trg_shipment_transition BEFORE UPDATE ON commerce_shipments WHEN NEW.status<>OLD.status AND NOT((OLD.status='CREATED' AND NEW.status IN('READY','IN_TRANSIT','FAILED','CANCELLED')) OR (OLD.status='READY' AND NEW.status IN('IN_TRANSIT','FAILED','CANCELLED')) OR (OLD.status='IN_TRANSIT' AND NEW.status IN('DELIVERED','FAILED'))) BEGIN SELECT RAISE(ABORT,'shipment transition invalid'); END;
`);}};
