export const migration067AiNativeGrowthWorkflow = { version: 67, name: "ai_native_growth_workflow", up(db) { db.exec(`
CREATE TABLE IF NOT EXISTS growth_strategies(
 id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id), version_number INTEGER NOT NULL CHECK(version_number>0), status TEXT NOT NULL CHECK(status IN('PROPOSED','APPROVED','REJECTED')),
 business_context_version_id TEXT NOT NULL REFERENCES business_context_versions(id), business_profile_id TEXT NOT NULL REFERENCES business_profiles(id), business_dna_version_id TEXT NOT NULL REFERENCES business_dna_versions(id), brand_book_version_id TEXT NOT NULL REFERENCES brand_book_versions(id),
 objective TEXT NOT NULL CHECK(length(objective) BETWEEN 1 AND 1000), strategy_json TEXT NOT NULL CHECK(length(strategy_json) BETWEEN 2 AND 60000), operation_id TEXT NOT NULL CHECK(operation_id='GROWTH_STRATEGY_GENERATION'), created_by_user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL, reviewed_by_user_id TEXT REFERENCES users(id), reviewed_at TEXT,
 UNIQUE(workspace_id,version_number)
);
CREATE TABLE IF NOT EXISTS growth_content_plans(
 id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id), growth_strategy_id TEXT NOT NULL REFERENCES growth_strategies(id), version_number INTEGER NOT NULL CHECK(version_number>0), status TEXT NOT NULL CHECK(status IN('PROPOSED','APPROVED','REJECTED')),
 plan_json TEXT NOT NULL CHECK(length(plan_json) BETWEEN 2 AND 60000), operation_id TEXT NOT NULL CHECK(operation_id='CONTENT_PLAN_GENERATION'), created_by_user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL, reviewed_by_user_id TEXT REFERENCES users(id), reviewed_at TEXT,
 UNIQUE(workspace_id,growth_strategy_id,version_number)
);
CREATE TABLE IF NOT EXISTS growth_landing_proposals(
 id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id), growth_strategy_id TEXT NOT NULL REFERENCES growth_strategies(id), content_plan_id TEXT REFERENCES growth_content_plans(id), version_number INTEGER NOT NULL CHECK(version_number>0), status TEXT NOT NULL CHECK(status IN('PROPOSED','APPROVED','REJECTED')),
 proposal_json TEXT NOT NULL CHECK(length(proposal_json) BETWEEN 2 AND 60000), operation_id TEXT NOT NULL CHECK(operation_id='LANDING_PROPOSAL_GENERATION'), created_by_user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL, reviewed_by_user_id TEXT REFERENCES users(id), reviewed_at TEXT, saved_draft_id TEXT,
 UNIQUE(workspace_id,growth_strategy_id,version_number)
);
CREATE TABLE IF NOT EXISTS growth_website_proposals(
 id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id), growth_strategy_id TEXT NOT NULL REFERENCES growth_strategies(id), content_plan_id TEXT REFERENCES growth_content_plans(id), version_number INTEGER NOT NULL CHECK(version_number>0), status TEXT NOT NULL CHECK(status IN('PROPOSED','APPROVED','REJECTED')),
 proposal_json TEXT NOT NULL CHECK(length(proposal_json) BETWEEN 2 AND 60000), operation_id TEXT NOT NULL CHECK(operation_id='WEBSITE_PROPOSAL_GENERATION'), created_by_user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL, reviewed_by_user_id TEXT REFERENCES users(id), reviewed_at TEXT, saved_draft_id TEXT,
 UNIQUE(workspace_id,growth_strategy_id,version_number)
);
CREATE INDEX IF NOT EXISTS idx_growth_strategies_workspace ON growth_strategies(workspace_id,created_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_growth_plans_workspace ON growth_content_plans(workspace_id,growth_strategy_id,created_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_growth_landing_workspace ON growth_landing_proposals(workspace_id,growth_strategy_id,created_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_growth_website_workspace ON growth_website_proposals(workspace_id,growth_strategy_id,created_at DESC,id DESC);
CREATE TRIGGER IF NOT EXISTS trg_growth_strategy_insert_guard BEFORE INSERT ON growth_strategies WHEN NOT EXISTS(SELECT 1 FROM business_context_versions c WHERE c.id=NEW.business_context_version_id AND c.workspace_id=NEW.workspace_id AND c.status='active' AND c.business_profile_id=NEW.business_profile_id AND c.business_dna_version_id=NEW.business_dna_version_id AND c.brand_book_version_id=NEW.brand_book_version_id) OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=NEW.workspace_id AND m.user_id=NEW.created_by_user_id AND m.status='active') BEGIN SELECT RAISE(ABORT,'growth source scope invalid'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_plan_insert_guard BEFORE INSERT ON growth_content_plans WHEN NOT EXISTS(SELECT 1 FROM growth_strategies s WHERE s.id=NEW.growth_strategy_id AND s.workspace_id=NEW.workspace_id AND s.status='APPROVED') OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=NEW.workspace_id AND m.user_id=NEW.created_by_user_id AND m.status='active') BEGIN SELECT RAISE(ABORT,'growth plan scope invalid'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_landing_insert_guard BEFORE INSERT ON growth_landing_proposals WHEN NOT EXISTS(SELECT 1 FROM growth_strategies s WHERE s.id=NEW.growth_strategy_id AND s.workspace_id=NEW.workspace_id AND s.status='APPROVED') OR (NEW.content_plan_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM growth_content_plans p WHERE p.id=NEW.content_plan_id AND p.workspace_id=NEW.workspace_id)) OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=NEW.workspace_id AND m.user_id=NEW.created_by_user_id AND m.status='active') BEGIN SELECT RAISE(ABORT,'landing proposal scope invalid'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_website_insert_guard BEFORE INSERT ON growth_website_proposals WHEN NOT EXISTS(SELECT 1 FROM growth_strategies s WHERE s.id=NEW.growth_strategy_id AND s.workspace_id=NEW.workspace_id AND s.status='APPROVED') OR (NEW.content_plan_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM growth_content_plans p WHERE p.id=NEW.content_plan_id AND p.workspace_id=NEW.workspace_id)) OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=NEW.workspace_id AND m.user_id=NEW.created_by_user_id AND m.status='active') BEGIN SELECT RAISE(ABORT,'website proposal scope invalid'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_strategy_update_guard BEFORE UPDATE ON growth_strategies WHEN NEW.id IS NOT OLD.id OR NEW.workspace_id IS NOT OLD.workspace_id OR NEW.version_number IS NOT OLD.version_number OR NEW.business_context_version_id IS NOT OLD.business_context_version_id OR NEW.business_profile_id IS NOT OLD.business_profile_id OR NEW.business_dna_version_id IS NOT OLD.business_dna_version_id OR NEW.brand_book_version_id IS NOT OLD.brand_book_version_id OR NEW.objective IS NOT OLD.objective OR NEW.strategy_json IS NOT OLD.strategy_json OR NEW.operation_id IS NOT OLD.operation_id OR NEW.created_by_user_id IS NOT OLD.created_by_user_id OR NEW.created_at IS NOT OLD.created_at OR OLD.status!='PROPOSED' OR NEW.status NOT IN('APPROVED','REJECTED') OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=OLD.workspace_id AND m.user_id=NEW.reviewed_by_user_id AND m.status='active' AND m.role IN('owner','admin')) BEGIN SELECT RAISE(ABORT,'growth strategy immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_plan_update_guard BEFORE UPDATE ON growth_content_plans WHEN NEW.id IS NOT OLD.id OR NEW.workspace_id IS NOT OLD.workspace_id OR NEW.growth_strategy_id IS NOT OLD.growth_strategy_id OR NEW.version_number IS NOT OLD.version_number OR NEW.plan_json IS NOT OLD.plan_json OR NEW.operation_id IS NOT OLD.operation_id OR NEW.created_by_user_id IS NOT OLD.created_by_user_id OR NEW.created_at IS NOT OLD.created_at OR OLD.status!='PROPOSED' OR NEW.status NOT IN('APPROVED','REJECTED') OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=OLD.workspace_id AND m.user_id=NEW.reviewed_by_user_id AND m.status='active' AND m.role IN('owner','admin')) BEGIN SELECT RAISE(ABORT,'growth plan immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_landing_update_guard BEFORE UPDATE ON growth_landing_proposals WHEN NEW.id IS NOT OLD.id OR NEW.workspace_id IS NOT OLD.workspace_id OR NEW.growth_strategy_id IS NOT OLD.growth_strategy_id OR NEW.content_plan_id IS NOT OLD.content_plan_id OR NEW.version_number IS NOT OLD.version_number OR NEW.proposal_json IS NOT OLD.proposal_json OR NEW.operation_id IS NOT OLD.operation_id OR NEW.created_by_user_id IS NOT OLD.created_by_user_id OR NEW.created_at IS NOT OLD.created_at OR (OLD.status!='PROPOSED' AND NOT(OLD.status='APPROVED' AND NEW.status='APPROVED' AND OLD.saved_draft_id IS NULL AND NEW.saved_draft_id IS NOT NULL)) OR (OLD.status='PROPOSED' AND (NEW.status NOT IN('APPROVED','REJECTED') OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=OLD.workspace_id AND m.user_id=NEW.reviewed_by_user_id AND m.status='active' AND m.role IN('owner','admin')))) BEGIN SELECT RAISE(ABORT,'landing proposal immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_website_update_guard BEFORE UPDATE ON growth_website_proposals WHEN NEW.id IS NOT OLD.id OR NEW.workspace_id IS NOT OLD.workspace_id OR NEW.growth_strategy_id IS NOT OLD.growth_strategy_id OR NEW.content_plan_id IS NOT OLD.content_plan_id OR NEW.version_number IS NOT OLD.version_number OR NEW.proposal_json IS NOT OLD.proposal_json OR NEW.operation_id IS NOT OLD.operation_id OR NEW.created_by_user_id IS NOT OLD.created_by_user_id OR NEW.created_at IS NOT OLD.created_at OR (OLD.status!='PROPOSED' AND NOT(OLD.status='APPROVED' AND NEW.status='APPROVED' AND OLD.saved_draft_id IS NULL AND NEW.saved_draft_id IS NOT NULL)) OR (OLD.status='PROPOSED' AND (NEW.status NOT IN('APPROVED','REJECTED') OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=OLD.workspace_id AND m.user_id=NEW.reviewed_by_user_id AND m.status='active' AND m.role IN('owner','admin')))) BEGIN SELECT RAISE(ABORT,'website proposal immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_strategy_delete BEFORE DELETE ON growth_strategies BEGIN SELECT RAISE(ABORT,'growth strategies immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_plan_delete BEFORE DELETE ON growth_content_plans BEGIN SELECT RAISE(ABORT,'growth plans immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_landing_delete BEFORE DELETE ON growth_landing_proposals BEGIN SELECT RAISE(ABORT,'growth proposals immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_growth_website_delete BEFORE DELETE ON growth_website_proposals BEGIN SELECT RAISE(ABORT,'growth proposals immutable'); END;
`); } };
