export const migration068ContinuousImprovementPdca={version:68,name:"continuous_improvement_pdca",up(db){db.exec(`
CREATE TABLE IF NOT EXISTS improvement_cycles(
 id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),objective TEXT NOT NULL CHECK(length(objective) BETWEEN 1 AND 1000),primary_kpi_definition_id TEXT NOT NULL REFERENCES kpi_definitions(id),guardrails_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(guardrails_json) AND length(guardrails_json)<=4000),
 baseline_window_start TEXT NOT NULL,baseline_window_end TEXT NOT NULL CHECK(baseline_window_end>baseline_window_start),baseline_value REAL NOT NULL,baseline_sample_count INTEGER NOT NULL CHECK(baseline_sample_count BETWEEN 3 AND 500),calculation_version INTEGER NOT NULL DEFAULT 1 CHECK(calculation_version=1),target_value REAL NOT NULL,hypothesis TEXT NOT NULL CHECK(length(hypothesis) BETWEEN 1 AND 1500),
 intervention_type TEXT NOT NULL CHECK(intervention_type IN('EXECUTION_REQUEST','ACTION_PROPOSAL','CONTENT_DRAFT','LANDING_DRAFT','WEBSITE_DRAFT','OTHER_GOVERNED')),intervention_reference_id TEXT NOT NULL CHECK(length(intervention_reference_id) BETWEEN 1 AND 200),execution_evidence_status TEXT NOT NULL DEFAULT 'UNVERIFIED' CHECK(execution_evidence_status IN('UNVERIFIED','VERIFIED')),
 measurement_window_start TEXT NOT NULL,measurement_window_end TEXT NOT NULL CHECK(measurement_window_end>measurement_window_start),experiment_type TEXT NOT NULL DEFAULT 'BEFORE_AFTER' CHECK(experiment_type IN('BEFORE_AFTER','CONTROLLED','AB_TEST','ROLLOUT','OBSERVATIONAL')),success_criteria TEXT NOT NULL CHECK(length(success_criteria)<=1000),failure_criteria TEXT NOT NULL CHECK(length(failure_criteria)<=1000),rollback_criteria TEXT CHECK(rollback_criteria IS NULL OR length(rollback_criteria)<=1000),
 source_strategy_id TEXT REFERENCES growth_strategies(id),source_recommendation_id TEXT REFERENCES intelligence_recommendations(id),parent_cycle_id TEXT REFERENCES improvement_cycles(id),status TEXT NOT NULL CHECK(status IN('DRAFT','PLANNED','APPROVED','IN_PROGRESS','MEASURING','EVALUATED','ACTED','CANCELLED')),act_decision TEXT CHECK(act_decision IS NULL OR act_decision IN('KEEP','IMPROVE','ROLLBACK','RETEST','STOP','INCONCLUSIVE')),knowledge_candidate_status TEXT CHECK(knowledge_candidate_status IS NULL OR knowledge_candidate_status='CANDIDATE'),
 created_by_user_id TEXT NOT NULL REFERENCES users(id),approved_by_user_id TEXT REFERENCES users(id),acted_by_user_id TEXT REFERENCES users(id),created_at TEXT NOT NULL,approved_at TEXT,acted_at TEXT
);
CREATE TABLE IF NOT EXISTS improvement_cycle_evaluations(
 id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),cycle_id TEXT NOT NULL UNIQUE REFERENCES improvement_cycles(id),measurement_value REAL NOT NULL,measurement_sample_count INTEGER NOT NULL CHECK(measurement_sample_count BETWEEN 3 AND 500),absolute_change REAL NOT NULL,percent_change REAL,target_reached INTEGER NOT NULL CHECK(target_reached IN(0,1)),outcome TEXT NOT NULL CHECK(outcome IN('IMPROVED','DEGRADED','NO_MEANINGFUL_CHANGE','TARGET_REACHED','TARGET_NOT_REACHED','INCONCLUSIVE','SPECIAL_CAUSE_DETECTED','INSUFFICIENT_DATA','TRADEOFF_DETECTED')),spc_method TEXT NOT NULL,spc_result TEXT NOT NULL CHECK(spc_result IN('COMMON_CAUSE','SPECIAL_CAUSE','TREND','SHIFT','INSUFFICIENT_DATA')),confidence_posture TEXT NOT NULL CHECK(confidence_posture IN('LOW','MEDIUM','HIGH')),causality_posture TEXT NOT NULL CHECK(causality_posture IN('ASSOCIATED_CHANGE','CAUSAL_EFFECT_CONFIRMED')),guardrail_results_json TEXT NOT NULL CHECK(json_valid(guardrail_results_json) AND length(guardrail_results_json)<=6000),calculation_version INTEGER NOT NULL DEFAULT 1 CHECK(calculation_version=1),evaluated_by_user_id TEXT NOT NULL REFERENCES users(id),evaluated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_improvement_cycles_status ON improvement_cycles(workspace_id,status,created_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_improvement_cycles_metric ON improvement_cycles(workspace_id,primary_kpi_definition_id,created_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS idx_improvement_cycles_strategy ON improvement_cycles(workspace_id,source_strategy_id,created_at DESC) WHERE source_strategy_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_improvement_cycles_parent ON improvement_cycles(workspace_id,parent_cycle_id,created_at DESC) WHERE parent_cycle_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_improvement_evaluations_cycle ON improvement_cycle_evaluations(workspace_id,cycle_id,evaluated_at DESC);
CREATE TRIGGER IF NOT EXISTS trg_improvement_cycle_insert_guard BEFORE INSERT ON improvement_cycles WHEN NOT EXISTS(SELECT 1 FROM kpi_definitions k WHERE k.id=NEW.primary_kpi_definition_id AND k.workspace_id=NEW.workspace_id AND k.status='active') OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=NEW.workspace_id AND m.user_id=NEW.created_by_user_id AND m.status='active') OR (NEW.parent_cycle_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM improvement_cycles p WHERE p.id=NEW.parent_cycle_id AND p.workspace_id=NEW.workspace_id AND p.status='ACTED')) OR (NEW.source_strategy_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM growth_strategies s WHERE s.id=NEW.source_strategy_id AND s.workspace_id=NEW.workspace_id)) OR (NEW.source_recommendation_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM intelligence_recommendations r WHERE r.id=NEW.source_recommendation_id AND r.workspace_id=NEW.workspace_id)) BEGIN SELECT RAISE(ABORT,'improvement cycle scope invalid');END;
CREATE TRIGGER IF NOT EXISTS trg_improvement_cycle_update_guard BEFORE UPDATE ON improvement_cycles WHEN NEW.id IS NOT OLD.id OR NEW.workspace_id IS NOT OLD.workspace_id OR NEW.objective IS NOT OLD.objective OR NEW.primary_kpi_definition_id IS NOT OLD.primary_kpi_definition_id OR NEW.guardrails_json IS NOT OLD.guardrails_json OR NEW.baseline_window_start IS NOT OLD.baseline_window_start OR NEW.baseline_window_end IS NOT OLD.baseline_window_end OR NEW.baseline_value IS NOT OLD.baseline_value OR NEW.baseline_sample_count IS NOT OLD.baseline_sample_count OR NEW.calculation_version IS NOT OLD.calculation_version OR NEW.target_value IS NOT OLD.target_value OR NEW.hypothesis IS NOT OLD.hypothesis OR NEW.intervention_type IS NOT OLD.intervention_type OR NEW.intervention_reference_id IS NOT OLD.intervention_reference_id OR NEW.measurement_window_start IS NOT OLD.measurement_window_start OR NEW.measurement_window_end IS NOT OLD.measurement_window_end OR NEW.experiment_type IS NOT OLD.experiment_type OR NEW.success_criteria IS NOT OLD.success_criteria OR NEW.failure_criteria IS NOT OLD.failure_criteria OR NEW.rollback_criteria IS NOT OLD.rollback_criteria OR NEW.source_strategy_id IS NOT OLD.source_strategy_id OR NEW.source_recommendation_id IS NOT OLD.source_recommendation_id OR NEW.parent_cycle_id IS NOT OLD.parent_cycle_id OR NEW.created_by_user_id IS NOT OLD.created_by_user_id OR NEW.created_at IS NOT OLD.created_at OR NOT((OLD.status='PLANNED' AND NEW.status='APPROVED') OR (OLD.status='APPROVED' AND NEW.status='MEASURING' AND NEW.execution_evidence_status='VERIFIED') OR (OLD.status='MEASURING' AND NEW.status='EVALUATED') OR (OLD.status='EVALUATED' AND NEW.status='ACTED' AND NEW.act_decision IS NOT NULL) OR (OLD.status IN('PLANNED','APPROVED') AND NEW.status='CANCELLED')) BEGIN SELECT RAISE(ABORT,'improvement cycle immutable or invalid transition');END;
CREATE TRIGGER IF NOT EXISTS trg_improvement_cycle_delete BEFORE DELETE ON improvement_cycles BEGIN SELECT RAISE(ABORT,'improvement cycles cannot be deleted');END;
CREATE TRIGGER IF NOT EXISTS trg_improvement_evaluation_insert_guard BEFORE INSERT ON improvement_cycle_evaluations WHEN NOT EXISTS(SELECT 1 FROM improvement_cycles c WHERE c.id=NEW.cycle_id AND c.workspace_id=NEW.workspace_id AND c.status='MEASURING' AND c.execution_evidence_status='VERIFIED') OR NOT EXISTS(SELECT 1 FROM workspace_memberships m WHERE m.workspace_id=NEW.workspace_id AND m.user_id=NEW.evaluated_by_user_id AND m.status='active') BEGIN SELECT RAISE(ABORT,'improvement evaluation scope invalid');END;
CREATE TRIGGER IF NOT EXISTS trg_improvement_evaluation_update BEFORE UPDATE ON improvement_cycle_evaluations BEGIN SELECT RAISE(ABORT,'improvement evaluations are immutable');END;
CREATE TRIGGER IF NOT EXISTS trg_improvement_evaluation_delete BEFORE DELETE ON improvement_cycle_evaluations BEGIN SELECT RAISE(ABORT,'improvement evaluations are immutable');END;
`);}};
