const ALLOWED_DENSITY=new Set(["compact","comfortable","spacious"]),ALLOWED_RADIUS=new Set(["small","medium","large"]),ALLOWED_SHELL=new Set(["loadder-business","minimal","dashboard"]);
const clean=(v,n)=>String(v||"").trim().slice(0,n);
export function applyLoadderEditorPatch(ui,patch={}){const next=structuredClone(ui);
 if(patch.theme){const{density,radius,shell}=patch.theme;if(density!==undefined&&!ALLOWED_DENSITY.has(density))throw new Error("Unsupported density");if(radius!==undefined&&!ALLOWED_RADIUS.has(radius))throw new Error("Unsupported radius");if(shell!==undefined&&!ALLOWED_SHELL.has(shell))throw new Error("Unsupported shell");next.theme={...next.theme,...(density?{density}:{}),...(radius?{radius}:{}),...(shell?{shell}:{})};}
 if(Array.isArray(patch.navigation)){const labels=new Map(patch.navigation.filter(x=>x&&typeof x.id==="string"&&typeof x.label==="string").map(x=>[x.id,clean(x.label,80)]));next.navigation=next.navigation.map(x=>labels.has(x.id)?{...x,label:labels.get(x.id)}:x);}
 if(Array.isArray(patch.views)){const titles=new Map(patch.views.filter(x=>x&&typeof x.id==="string"&&typeof x.title==="string").map(x=>[x.id,clean(x.title,100)]));next.views=next.views.map(x=>titles.has(x.id)?{...x,title:titles.get(x.id)}:x);}
 if(Array.isArray(patch.fields)){const vis=new Map(patch.fields.filter(x=>x&&typeof x.entityId==="string"&&typeof x.fieldId==="string"&&typeof x.visible==="boolean").map(x=>[`${x.entityId}:${x.fieldId}`,x.visible]));next.views=next.views.map(v=>{if(!v.resource)return v;const blocks=(v.blocks||[]).map(b=>{if(b.type==="data-table"&&Array.isArray(b.columns))return{...b,columns:b.columns.filter(c=>vis.get(`${v.resource}:${c.id}`)!==false)};if(b.type==="form"&&Array.isArray(b.fields))return{...b,fields:b.fields.filter(f=>vis.get(`${v.resource}:${f.id}`)!==false)};if(b.type==="record-summary"&&Array.isArray(b.fields))return{...b,fields:b.fields.filter(id=>vis.get(`${v.resource}:${id}`)!==false)};return b});return{...v,blocks}});}
 if(Array.isArray(patch.blocks)){for(const p of patch.blocks){if(!p||typeof p.viewId!=="string")continue;const idx=next.views.findIndex(v=>v.id===p.viewId);if(idx<0)throw new Error("Unknown view");const view=next.views[idx],blocks=[...(view.blocks||[])];if(Array.isArray(p.order)){const wanted=p.order.filter(x=>Number.isInteger(x)&&x>=0&&x<blocks.length);if(new Set(wanted).size!==blocks.length||wanted.length!==blocks.length)throw new Error("Block order must contain every block exactly once");next.views[idx]={...view,blocks:wanted.map(i=>blocks[i])};}if(Number.isInteger(p.index)&&typeof p.visible==="boolean"){if(p.index<0||p.index>=blocks.length)throw new Error("Unknown block");const changed=[...(next.views[idx].blocks||blocks)];changed[p.index]={...changed[p.index],hidden:!p.visible};next.views[idx]={...next.views[idx],blocks:changed};}}
 return Object.freeze(next)}
export const LOADDER_EDITOR_CAPABILITIES=Object.freeze({theme:["density","radius","shell"],navigation:["rename"],views:["rename"],fields:["hide"],blocks:["reorder","visibility"],future:["page-layout","component-props"]});
