import { loadderBusinessBuilderService } from "./business-builder-service.mjs";
import { exportLoadderApplication, importLoadderApplication } from "./portability.mjs";
import { applyLoadderEditorPatch } from "./editor-patch.mjs";
import { validateAppAccessPolicy } from "./app-access-policy.mjs";
import { createPreviewQualityGate } from "./preview-quality-gate.mjs";
export function createBusinessBuilderProjectService({ repository, builder = loadderBusinessBuilderService, previewAdapter }) {
  if (!repository) throw new TypeError("repository is required");
  const quality=createPreviewQualityGate({repository});
  function listProjects(){return repository.listProjects();}
  function getProject(id){const p=repository.getProject(id);return p?{...p,versions:repository.listVersions(id)}:null;}
  function createProject(input,actorId=null){const plan=builder.preview(input);const p=repository.createProject({name:plan.definition.name,intent:input.intent,locale:input.locale||"fa-IR"});const v=repository.createVersion(p.id,{definition:plan.definition,ui:plan.ui,bundle:plan.sourceBundle,buildPlan:plan,createdBy:actorId});return{project:repository.getProject(p.id),version:v};}
  function saveProject(id,input,actorId=null){const current=repository.getProject(id);if(!current)return null;const active=repository.getActiveVersion(id);const next={intent:input.intent??current.intent,name:input.name??current.name,locale:input.locale??current.locale};const plan=builder.preview(next);if(active?.definition?.accessPolicy){plan.definition={...plan.definition,accessPolicy:structuredClone(active.definition.accessPolicy)};plan.accessPolicy=structuredClone(active.definition.accessPolicy);}repository.updateProject(id,next);const v=repository.createVersion(id,{definition:plan.definition,ui:plan.ui,bundle:plan.sourceBundle,buildPlan:plan,createdBy:actorId});return{project:repository.getProject(id),version:v};}
  function applyEditorPatch(projectId,patch,actorId=null){const current=repository.getActiveVersion(projectId);if(!current)return null;const ui=applyLoadderEditorPatch(current.ui,patch);const buildPlan={...structuredClone(current.buildPlan),ui,editorPatch:structuredClone(patch),buildId:`${current.buildPlan?.buildId||current.id}-edit`};const v=repository.createVersion(projectId,{definition:current.definition,ui,bundle:current.bundle,buildPlan,createdBy:actorId});return{project:repository.getProject(projectId),version:v};}
  function applyAccessPolicy(projectId,input,actorId=null){const current=repository.getActiveVersion(projectId);if(!current)return null;const accessPolicy=validateAppAccessPolicy(input||{}),definition={...structuredClone(current.definition),accessPolicy};const buildPlan={...structuredClone(current.buildPlan),definition,accessPolicyUpdated:true,buildId:`${current.buildPlan?.buildId||current.id}-access`};const v=repository.createVersion(projectId,{definition,ui:current.ui,bundle:current.bundle,buildPlan,createdBy:actorId});return{project:repository.getProject(projectId),version:v};}
  function restoreVersion(projectId,versionId,actorId=null){const version=repository.getVersion(versionId);if(!version||version.projectId!==projectId)return null;const p=repository.getProject(projectId);if(!p)return null;const restored=repository.createVersion(projectId,{...version,createdBy:actorId});return{project:repository.getProject(projectId),version:restored,restoredFrom:versionId};}
  async function startPreview(projectId){const version=repository.getActiveVersion(projectId);if(!version)return null;const approval=repository.latestApproval(projectId,version.id,"preview");if(approval?.decision==="rejected"){const e=new Error("Preview rejected by approval gate.");e.code="PREVIEW_REJECTED";throw e;}const execution=previewAdapter?await previewAdapter.start({projectId,version}):{adapter:"loadder-contract-preview",url:`/dashboard/business-builder?project=${projectId}&version=${version.id}`};const session=repository.createPreviewSession({projectId,versionId:version.id,runtimeAdapter:execution.adapter,previewUrl:execution.url});return{session,version};}
  function qualityReport(projectId){return quality.report(projectId);}
  function recordQualityChecklist({projectId,versionId,checks,actorId=null}){return quality.recordHumanChecklist({projectId,versionId,checks,actorId});}
  function decide({projectId,versionId,stage,decision,actorId=null,note=null}){const active=repository.getActiveVersion(projectId);if(!active||active.id!==versionId){const e=new Error("Approval must target the active app version.");e.code="ACTIVE_VERSION_APPROVAL_REQUIRED";throw e;}if(stage==="preview"&&decision==="approved"){const report=quality.report(projectId);if(!report?.ready){const e=new Error("Preview quality gate must pass before preview approval.");e.code="PREVIEW_QUALITY_REQUIRED";e.report=report;throw e;}}if(stage==="production"&&decision==="approved"){const report=quality.report(projectId);if(!report?.ready){const e=new Error("Preview quality gate must pass before production approval.");e.code="PREVIEW_QUALITY_REQUIRED";e.report=report;throw e;}const preview=repository.latestApproval(projectId,versionId,"preview");if(preview?.decision!=="approved"){const e=new Error("Preview approval is required before production approval.");e.code="PREVIEW_APPROVAL_REQUIRED";throw e;}}return repository.recordApproval({projectId,versionId,stage,decision,decidedBy:actorId,note});}
  function canDeployProduction(projectId){const v=repository.getActiveVersion(projectId);if(!v)return false;const report=quality.report(projectId),preview=repository.latestApproval(projectId,v.id,"preview"),production=repository.latestApproval(projectId,v.id,"production");return report?.ready===true&&preview?.decision==="approved"&&production?.decision==="approved";}
  function exportProject(projectId){const p=repository.getProject(projectId),v=repository.getActiveVersion(projectId);return p&&v?exportLoadderApplication({project:p,version:v}):null;}
  function importProject(payload,actorId=null){const imported=importLoadderApplication(payload);const p=repository.createProject(imported.project);const buildPlan={contract:"loadder.imported-build-plan.v1",definition:imported.version.definition,ui:imported.version.ui,sourceBundle:imported.version.bundle,imported:true};const v=repository.createVersion(p.id,{definition:imported.version.definition,ui:imported.version.ui,bundle:imported.version.bundle,buildPlan,createdBy:actorId});return{project:repository.getProject(p.id),version:v};}
  return{listProjects,getProject,createProject,saveProject,applyEditorPatch,applyAccessPolicy,restoreVersion,startPreview,qualityReport,recordQualityChecklist,decide,canDeployProduction,exportProject,importProject};
}
