const labels: Record<string, string> = {
  AI_GENERATED: "Generated by Loadder",
  MANUAL_TEXT: "Created manually",
  CLIENT_UPLOADED: "Uploaded by you",
  EXTERNAL_IMPORTED: "Imported",
};

export default function ContentSourceBadge({ sourceType }: { sourceType: string }) {
  return <span className="rounded-full border border-cyan-300/15 bg-cyan-500/10 px-2.5 py-1 text-[11px] text-cyan-200">{labels[sourceType] || sourceType}</span>;
}
