const SHA=/^[a-f0-9]{64}$/,IDENTITY=/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,199}$/;
export const GATEWAY_RESULT_TYPES=Object.freeze(["SUCCEEDED","FAILED","UNKNOWN","REJECTED_BEFORE_EXECUTION"]);
export const EXECUTION_FAILURE_CODES=Object.freeze(["VALIDATION_REJECTED","AUTHORIZATION_INVALID","REQUEST_EXPIRED","CAPABILITY_UNAVAILABLE","CONNECTION_UNAVAILABLE","CREDENTIAL_UNAVAILABLE","ACCOUNT_IDENTITY_MISMATCH","RATE_LIMITED","PROVIDER_REJECTED","PROVIDER_TEMPORARY_FAILURE","NETWORK_AMBIGUOUS","PROVIDER_UNKNOWN"]);
const exact=(value,fields,name)=>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).some(k=>!fields.includes(k))||fields.some(k=>!Object.hasOwn(value,k)))throw new Error(`${name} contains unsupported fields.`);return value;};
const identity=(v,n)=>{if(typeof v!=="string"||!IDENTITY.test(v))throw new Error(`${n} is invalid.`);return v;};
export function normalizeGatewayResult(value){exact(value,["providerInvocationStarted","resultType","normalizedResultCode","providerReference","responseHash"],"Gateway result");if(typeof value.providerInvocationStarted!=="boolean"||!GATEWAY_RESULT_TYPES.includes(value.resultType))throw new Error("Gateway result is invalid.");identity(value.normalizedResultCode,"normalizedResultCode");if(value.providerReference!==null)identity(value.providerReference,"providerReference");if(!SHA.test(value.responseHash))throw new Error("responseHash is invalid.");return Object.freeze({...value});}
export function validateReconciliationIdentity(value){exact(value,["executionRequestId","requestFingerprint","capabilityId","capabilityVersion","providerAccountIdentityId","providerIdempotencyKey","providerReference"],"Reconciliation identity");for(const field of["executionRequestId","capabilityId","providerAccountIdentityId"])identity(value[field],field);for(const field of["requestFingerprint","providerIdempotencyKey"])if(!SHA.test(value[field]))throw new Error(`${field} is invalid.`);if(!Number.isInteger(value.capabilityVersion)||value.capabilityVersion<1)throw new Error("capabilityVersion is invalid.");if(value.providerReference!==null)identity(value.providerReference,"providerReference");return Object.freeze({...value});}
export function validateProviderAccountIdentity(value){exact(value,["id","workspaceId","connectionId","providerKind","externalAccountKeyHash","externalAccountType","identityVersion","verificationMethod","verifiedAt","createdAt"],"Provider account identity");for(const field of["id","workspaceId","connectionId","providerKind","externalAccountType","verificationMethod"])identity(value[field],field);if(!SHA.test(value.externalAccountKeyHash)||!Number.isInteger(value.identityVersion)||value.identityVersion<1||![value.verifiedAt,value.createdAt].every(v=>typeof v==="string"&&Number.isFinite(Date.parse(v))))throw new Error("Provider account identity is invalid.");return Object.freeze({...value});}
export function assertCapabilityGatewayInterface(value){exact(value,["invokeRegisteredCapability"],"Capability gateway interface");if(typeof value.invokeRegisteredCapability!=="function")throw new Error("Capability gateway interface is invalid.");return value;}
export function assertCapabilityAdapterInterface(value,{supportsReconciliation=false}={}){const fields=supportsReconciliation?["invokeCapability","reconcileCapability"]:["invokeCapability"];exact(value,fields,"Capability adapter interface");if(fields.some(k=>typeof value[k]!=="function"))throw new Error("Capability adapter interface is invalid.");return value;}
export function assertCredentialResolverInterface(value){exact(value,["resolveOpaqueCredentialHandle"],"Credential resolver interface");if(typeof value.resolveOpaqueCredentialHandle!=="function")throw new Error("Credential resolver interface is invalid.");return value;}
