import {evaluatePromotion} from "./promotion-engine.mjs";
const int=(v,f,{min=0}={})=>{const n=Number(v);if(!Number.isInteger(n)||n<min)throw new TypeError(`${f} must be integer >= ${min}`);return n};const txt=v=>String(v??"").trim();const clone=v=>structuredClone(v);
export function createCart(input={}){const id=txt(input.id),workspaceId=txt(input.workspaceId),storeId=txt(input.storeId),currency=txt(input.currency).toUpperCase();if(!id||!workspaceId||!storeId||!currency)throw new TypeError("cart identity fields are required");return Object.freeze({id,workspaceId,storeId,currency,status:"OPEN",lines:Object.freeze([]),promotion:null,metadata:Object.freeze(clone(input.metadata&&typeof input.metadata==="object"?input.metadata:{}))})}
function assertOpen(cart){if(cart.status!=="OPEN")throw new Error("CART_NOT_OPEN")}
function assertOwnership(cart,line){if(cart.workspaceId!==line.workspaceId||cart.storeId!==line.storeId)throw new Error("CROSS_TENANT_CART_LINE")}
export function addLine(cart,input={}){assertOpen(cart);const line={id:txt(input.id),workspaceId:txt(input.workspaceId),storeId:txt(input.storeId),productId:txt(input.productId),variantId:txt(input.variantId),sku:txt(input.sku),name:txt(input.name),category:input.category??null,brand:input.brand??null,quantity:int(input.quantity,"line.quantity",{min:1}),unitPriceMinor:int(input.unitPriceMinor,"line.unitPriceMinor"),currency:txt(input.currency).toUpperCase(),reservationId:txt(input.reservationId)||null};if(!line.id||!line.variantId)throw new TypeError("line.id and line.variantId are required");assertOwnership(cart,line);if(line.currency!==cart.currency)throw new Error("CART_CURRENCY_MISMATCH");const existing=cart.lines.find(x=>x.variantId===line.variantId&&x.unitPriceMinor===line.unitPriceMinor);const lines=existing?cart.lines.map(x=>x===existing?Object.freeze({...x,quantity:x.quantity+line.quantity}):x):[...cart.lines,Object.freeze(line)];return Object.freeze({...cart,lines:Object.freeze(lines)})}
export function setLineQuantity(cart,lineId,quantity){assertOpen(cart);const q=int(quantity,"quantity");const lines=q===0?cart.lines.filter(x=>x.id!==lineId):cart.lines.map(x=>x.id===lineId?Object.freeze({...x,quantity:q}):x);return Object.freeze({...cart,lines:Object.freeze(lines)})}
export function applyPromotion(cart,promotion,context={}){assertOpen(cart);const result=evaluatePromotion(cart,promotion,context);return Object.freeze({...cart,promotion:Object.freeze(clone(result))})}
export function cartTotals(cart){const subtotalMinor=cart.lines.reduce((s,l)=>s+l.quantity*l.unitPriceMinor,0);const discountMinor=Math.min(subtotalMinor,cart.promotion?.discountMinor||0);return Object.freeze({subtotalMinor,discountMinor,totalMinor:subtotalMinor-discountMinor,currency:cart.currency,itemCount:cart.lines.reduce((s,l)=>s+l.quantity,0)})}
export function closeCart(cart){assertOpen(cart);return Object.freeze({...cart,status:"CLOSED"})}
