import express from "express";
import rateLimit from "express-rate-limit";
import { AuthError, SESSION_COOKIE_NAME } from "../services/auth-service.mjs";
import { getSessionToken } from "../middleware/auth.mjs";
import { db } from "../../db/workspace-database.mjs";
import { createSiteProjectRepository } from "../repositories/site-project-repository.mjs";
import { renderPublishedSite } from "./public-sites.mjs";
import { createEcommerceService, isVariantPurchasable } from "../services/ecommerce-service.mjs";
import { projectPublicStorePresentation } from "../services/store-public-presentation.mjs";
import { createSiteLeadService } from "../services/site-lead-service.mjs";
import { publishedSiteHeaders } from "../services/public-site-headers.mjs";
import { runWithWorkspace } from "../tenant-context.mjs";
import { createPublicBusinessAppRouter } from "../business-builder/public-app-router.mjs";
import { CART_CAPABILITY_HEADER, ORDER_CAPABILITY_HEADER, createPublicCapability, matchesPublicCapability } from "../services/public-commerce-capability.mjs";

export function createAuthRouter({ authService, nodeEnv = "development", exposeDevelopmentOtp = false }) {
  const router = express.Router();
  const publicSiteRepository = createSiteProjectRepository(db);
  const ecommerceService = createEcommerceService({ db });
  const siteLeadService = createSiteLeadService({ db });
  const sendOtpLimiter = rateLimit({ windowMs: 60 * 1000, limit: 5, standardHeaders: "draft-8", legacyHeaders: false, message: { success:false, message:"تعداد درخواست‌ها زیاد است. کمی بعد دوباره تلاش کنید." } });
  const leadLimiter = rateLimit({ windowMs: 60 * 1000, limit: 5, standardHeaders: "draft-8", legacyHeaders: false, message:{ success:false,message:"تعداد درخواست‌ها زیاد است. کمی بعد دوباره تلاش کنید." } });
  const checkoutLimiter = rateLimit({ windowMs: 60 * 1000, limit: 20, standardHeaders: "draft-8", legacyHeaders: false, message:{ success:false,message:"درخواست‌های خرید زیاد است. کمی بعد دوباره تلاش کنید." } });

  function handleAuthError(error,res){ if(error instanceof AuthError)return res.status(error.status).json({success:false,message:error.message,code:error.code}); console.error("Authentication error:",error);return res.status(500).json({success:false,message:"خطای داخلی احراز هویت."}); }
  function publicStore(siteProjectId){const row=db.prepare("SELECT p.id,p.workspace_id AS workspaceId,p.name,p.site_type AS siteType,v.id AS publishedVersionId,v.version AS publishedVersion,v.published_at AS publishedAt,v.content_json AS publishedContentJson FROM site_projects p JOIN site_publish_versions v ON v.id=(SELECT latest.id FROM site_publish_versions latest WHERE latest.site_project_id=p.id AND latest.workspace_id=p.workspace_id ORDER BY latest.version DESC LIMIT 1) WHERE p.id=? AND p.site_type='STORE' AND p.status='PUBLISHED'").get(siteProjectId);if(!row)return null;let content={};try{content=JSON.parse(row.publishedContentJson||"{}")}catch{return null}return{...row,presentation:projectPublicStorePresentation(content)}}
  // A published site of a non-commerce type. Same publish/version truth as the
  // storefront resolver, so preview, publish, live and rollback stay identical.
  function publicSite(siteProjectId){const row=db.prepare("SELECT p.id,p.workspace_id AS workspaceId,p.name,p.site_type AS siteType,v.id AS publishedVersionId,v.version AS publishedVersion,v.published_at AS publishedAt,v.content_json AS publishedContentJson FROM site_projects p JOIN site_publish_versions v ON v.id=(SELECT latest.id FROM site_publish_versions latest WHERE latest.site_project_id=p.id AND latest.workspace_id=p.workspace_id ORDER BY latest.version DESC LIMIT 1) WHERE p.id=? AND p.site_type='BUSINESS' AND p.status='PUBLISHED'").get(siteProjectId);if(!row)return null;let content={};try{content=JSON.parse(row.publishedContentJson||"{}")}catch{return null}return{...row,canonicalDomain:publicSiteRepository.getActiveDomainForProject(siteProjectId),presentation:projectPublicStorePresentation(content,{preserveSectionIds:true,includeCommerce:false})}}
  function publicNotFound(res,code="PUBLIC_RESOURCE_NOT_FOUND"){return res.status(404).json({success:false,code,message:"Resource not found."})}
  function cartNotFound(res){return publicNotFound(res,"CART_NOT_FOUND")}
  function cartRow(req){const row=db.prepare("SELECT id,workspace_id AS workspaceId,site_project_id AS siteProjectId,public_capability_hash AS capabilityHash FROM ecommerce_carts WHERE id=?").get(req.params.cartId);if(!row||!matchesPublicCapability(req.get(CART_CAPABILITY_HEADER),row.capabilityHash)||!publicStore(row.siteProjectId))return null;return row}
  function orderRow(req){const row=db.prepare("SELECT id,workspace_id AS workspaceId,site_project_id AS siteProjectId,receipt_capability_hash AS capabilityHash FROM ecommerce_orders WHERE id=?").get(req.params.orderId);if(!row||!matchesPublicCapability(req.get(ORDER_CAPABILITY_HEADER),row.capabilityHash)||!publicStore(row.siteProjectId))return null;return row}
  function publicProduct(product){if(!product||product.status!=="ACTIVE")return null;const gallery=Array.isArray(product.metadata?.gallery)?product.metadata.gallery.filter(x=>typeof x==="string").slice(0,12):[];return{id:product.id,siteProjectId:product.siteProjectId,name:product.name,slug:product.slug,description:product.description||"",category:product.category||null,brand:product.brand||null,currency:product.currency,basePriceMinor:product.basePriceMinor,compareAtPriceMinor:product.compareAtPriceMinor??null,featured:Boolean(product.featured),seoTitle:product.seoTitle||null,seoDescription:product.seoDescription||null,metadata:{gallery},gallery,variants:(product.variants||[]).filter(v=>v.active).map(v=>({id:v.id,sku:v.sku,title:v.title,priceMinor:v.priceMinor,inventoryQuantity:v.inventoryQuantity,inventoryPolicy:v.inventoryPolicy,purchasable:isVariantPurchasable(v),options:v.options||{},imageUrl:v.imageUrl||null}))}}
  function storefrontError(error,res){console.error("Public storefront error:",error);const status=Number(error?.status)||500;return res.status(status>=400&&status<600?status:500).json({success:false,code:error?.code||"STOREFRONT_ERROR",message:status===500?"Unable to process storefront request.":error.message})}

  if(process.env.BUSINESS_BUILDER_PUBLIC_APPS_ENABLED==="true") router.use(createPublicBusinessAppRouter({db}));
  router.get("/status",(req,res)=>res.json({success:true,mode:"persistent-session",productionReady:false,otpDelivery:"not-connected",developmentOtpExposed:nodeEnv!=="production"&&exposeDevelopmentOtp,publicBusinessAppsEnabled:process.env.BUSINESS_BUILDER_PUBLIC_APPS_ENABLED==="true"}));
  const sendLegacySite=(req,res,slug)=>{try{const published=publicSiteRepository.getPublishedPublic(req.params.id);if(!published)return res.status(404).send("Site not found");const html=renderPublishedSite(published.project,published.version,published.assets,{slug,basePath:`/api/auth/sites/${req.params.id}`,canonicalDomain:publicSiteRepository.getActiveDomainForProject(req.params.id),noindex:true});if(html===null)return res.status(404).send("Page not found");res.set(publishedSiteHeaders({"X-Robots-Tag":"noindex, follow"}));return res.type("html").send(html)}catch(error){console.error("Published site error:",error);return res.status(500).send("Unable to render site")}};
  router.get("/sites/:id/:slug",(req,res)=>sendLegacySite(req,res,req.params.slug));
  router.get("/sites/:id",(req,res)=>sendLegacySite(req,res,""));

  router.get("/site/:siteProjectId",(req,res)=>{try{const site=publicSite(req.params.siteProjectId);if(!site)return publicNotFound(res,"SITE_NOT_FOUND");return res.json({success:true,site:{id:site.id,name:site.name,siteType:site.siteType},canonicalDomain:site.canonicalDomain,publishedVersion:{id:site.publishedVersionId,version:site.publishedVersion,publishedAt:site.publishedAt},presentation:site.presentation})}catch(e){return storefrontError(e,res)}});
  router.post("/site/:siteProjectId/leads",leadLimiter,(req,res)=>{try{const site=publicSite(req.params.siteProjectId);if(!site)return publicNotFound(res,"SITE_NOT_FOUND");runWithWorkspace(site.workspaceId,()=>siteLeadService.submit(site.id,req.body||{}));/* The acknowledgement is identical whether the lead was stored, suppressed as a duplicate, or dropped by the honeypot, so automation learns nothing. Internal CRM ids are never public. */return res.status(201).json({success:true,received:true})}catch(e){return storefrontError(e,res)}});
  router.get("/storefront/:siteProjectId",(req,res)=>{try{const store=publicStore(req.params.siteProjectId);if(!store)return res.status(404).json({success:false,message:"Store not found."});const products=runWithWorkspace(store.workspaceId,()=>ecommerceService.listProducts(store.id)).map(publicProduct).filter(Boolean);return res.json({success:true,store:{id:store.id,name:store.name},publishedVersion:{id:store.publishedVersionId,version:store.publishedVersion,publishedAt:store.publishedAt},presentation:store.presentation,categories:[...new Set(products.map(p=>p.category).filter(Boolean))],brands:[...new Set(products.map(p=>p.brand).filter(Boolean))],productCount:products.length})}catch(e){return storefrontError(e,res)}});
  router.get("/storefront/:siteProjectId/products",(req,res)=>{try{const store=publicStore(req.params.siteProjectId);if(!store)return res.status(404).json({success:false,message:"Store not found."});const q=String(req.query.q||"").trim().toLocaleLowerCase("fa"),category=String(req.query.category||"").trim(),brand=String(req.query.brand||"").trim(),onlyInStock=String(req.query.inStock||"")==="1",onlyFeatured=String(req.query.featured||"")==="1",sort=String(req.query.sort||"newest");let products=runWithWorkspace(store.workspaceId,()=>ecommerceService.listProducts(store.id)).map(publicProduct).filter(Boolean);if(q)products=products.filter(p=>[p.name,p.description,p.category,p.brand,...p.variants.map(v=>v.sku)].filter(Boolean).join(" ").toLocaleLowerCase("fa").includes(q));if(category)products=products.filter(p=>p.category===category);if(brand)products=products.filter(p=>p.brand===brand);if(onlyFeatured)products=products.filter(p=>p.featured);if(onlyInStock)products=products.filter(p=>p.variants.some(v=>v.inventoryPolicy!=="DENY"||v.inventoryQuantity>0));if(sort==="price-asc")products.sort((a,b)=>a.basePriceMinor-b.basePriceMinor);if(sort==="price-desc")products.sort((a,b)=>b.basePriceMinor-a.basePriceMinor);return res.json({success:true,products})}catch(e){return storefrontError(e,res)}});
  router.get("/storefront/:siteProjectId/products/:slug",(req,res)=>{try{const store=publicStore(req.params.siteProjectId);if(!store)return res.status(404).json({success:false,message:"Store not found."});const product=runWithWorkspace(store.workspaceId,()=>ecommerceService.listProducts(store.id)).map(publicProduct).find(x=>x?.slug===req.params.slug);if(!product)return res.status(404).json({success:false,message:"Product not found."});return res.json({success:true,store:{id:store.id,name:store.name},product})}catch(e){return storefrontError(e,res)}});

  router.post("/storefront/:siteProjectId/carts",(req,res)=>{try{const store=publicStore(req.params.siteProjectId);if(!store)return publicNotFound(res);const capability=createPublicCapability();const cart=runWithWorkspace(store.workspaceId,()=>ecommerceService.createCart(store.id,{email:req.body?.email||null,currency:req.body?.currency||"IRT",publicCapabilityHash:capability.hash}));return res.status(201).json({success:true,cart,cartCapability:capability.value})}catch(e){return storefrontError(e,res)}});
  router.get("/storefront/carts/:cartId",(req,res)=>{try{const row=cartRow(req);if(!row)return cartNotFound(res);const cart=runWithWorkspace(row.workspaceId,()=>ecommerceService.getCart(row.id));return res.json({success:true,cart})}catch(e){return storefrontError(e,res)}});
  router.post("/storefront/carts/:cartId/items",(req,res)=>{try{const row=cartRow(req);if(!row)return cartNotFound(res);const variant=db.prepare("SELECT v.id,p.status,p.site_project_id AS siteProjectId FROM ecommerce_variants v JOIN ecommerce_products p ON p.id=v.product_id WHERE v.id=? AND v.workspace_id=? AND p.workspace_id=?").get(req.body?.variantId,row.workspaceId,row.workspaceId);if(!variant||variant.status!=="ACTIVE"||variant.siteProjectId!==row.siteProjectId)return res.status(404).json({success:false,code:"VARIANT_NOT_AVAILABLE",message:"Product variant not available."});const cart=runWithWorkspace(row.workspaceId,()=>ecommerceService.addCartItem(row.id,{variantId:variant.id,quantity:req.body?.quantity||1}));return res.status(201).json({success:true,cart})}catch(e){return storefrontError(e,res)}});
  router.put("/storefront/carts/:cartId/items/:variantId",(req,res)=>{try{const row=cartRow(req);if(!row)return cartNotFound(res);const cart=runWithWorkspace(row.workspaceId,()=>ecommerceService.setCartItemQuantity(row.id,req.params.variantId,req.body?.quantity));return res.json({success:true,cart})}catch(e){return storefrontError(e,res)}});

  router.get("/storefront/:siteProjectId/checkout-options",(req,res)=>{try{const store=publicStore(req.params.siteProjectId);if(!store)return res.status(404).json({success:false,message:"Store not found."});const shipping=db.prepare("SELECT id,name,price_minor AS priceMinor,active FROM ecommerce_shipping_methods WHERE workspace_id=? AND site_project_id=? AND active=1 ORDER BY price_minor,name").all(store.workspaceId,store.id);return res.json({success:true,shippingMethods:shipping,paymentMethods:[{key:"manual",title:"پرداخت آزمایشی / هماهنگی با فروشگاه",enabled:true}]})}catch(e){return storefrontError(e,res)}});
  router.post("/storefront/carts/:cartId/coupon",checkoutLimiter,(req,res)=>{try{const row=cartRow(req);if(!row)return cartNotFound(res);const code=String(req.body?.code||"").trim().slice(0,64);const cart=runWithWorkspace(row.workspaceId,()=>ecommerceService.applyCoupon(row.id,code));return res.json({success:true,cart})}catch(e){return storefrontError(e,res)}});
  router.post("/storefront/carts/:cartId/shipping",checkoutLimiter,(req,res)=>{try{const row=cartRow(req);if(!row)return cartNotFound(res);const methodId=String(req.body?.shippingMethodId||"");const method=db.prepare("SELECT id FROM ecommerce_shipping_methods WHERE id=? AND workspace_id=? AND site_project_id=? AND active=1").get(methodId,row.workspaceId,row.siteProjectId);if(!method)return res.status(404).json({success:false,code:"SHIPPING_NOT_FOUND",message:"Shipping method not available."});const cart=runWithWorkspace(row.workspaceId,()=>ecommerceService.setCartShipping(row.id,method.id));return res.json({success:true,cart})}catch(e){return storefrontError(e,res)}});
  router.post("/storefront/carts/:cartId/checkout",checkoutLimiter,(req,res)=>{try{const row=cartRow(req);if(!row)return cartNotFound(res);const email=String(req.body?.email||"").trim().slice(0,180),phone=String(req.body?.phone||"").trim().slice(0,32),fullName=String(req.body?.fullName||"").trim().slice(0,120);if(!fullName||!phone)return res.status(400).json({success:false,message:"نام و شماره موبایل الزامی است."});const address=req.body?.shippingAddress||{};const shippingAddress={fullName,phone,province:String(address.province||"").slice(0,80),city:String(address.city||"").slice(0,80),address:String(address.address||"").slice(0,500),postalCode:String(address.postalCode||"").slice(0,32),notes:String(address.notes||"").slice(0,500)},receipt=createPublicCapability();const order=runWithWorkspace(row.workspaceId,()=>ecommerceService.checkout(row.id,{email:email||null,paymentProvider:"manual",shippingMethod:String(req.body?.shippingMethod||"").slice(0,120)||null,shippingAddress,receiptCapabilityHash:receipt.hash}));return res.status(201).json({success:true,receiptCapability:receipt.value,order:{id:order.id,siteProjectId:order.siteProjectId,currency:order.currency,status:order.status,paymentStatus:order.paymentStatus,fulfillmentStatus:order.fulfillmentStatus,subtotalMinor:order.subtotalMinor,discountMinor:order.discountMinor,shippingMinor:order.shippingMinor,totalMinor:order.totalMinor,items:order.items,createdAt:order.createdAt}})}catch(e){return storefrontError(e,res)}});
  router.get("/storefront/orders/:orderId",(req,res)=>{try{const row=orderRow(req);if(!row)return publicNotFound(res);const order=runWithWorkspace(row.workspaceId,()=>ecommerceService.getOrder(row.id));return res.json({success:true,order:{id:order.id,siteProjectId:order.siteProjectId,currency:order.currency,status:order.status,paymentStatus:order.paymentStatus,fulfillmentStatus:order.fulfillmentStatus,subtotalMinor:order.subtotalMinor,discountMinor:order.discountMinor,shippingMinor:order.shippingMinor,totalMinor:order.totalMinor,items:order.items,createdAt:order.createdAt}})}catch(e){return storefrontError(e,res)}});

  router.post("/send-otp",sendOtpLimiter,(req,res)=>{try{const result=authService.requestOtp(req.body||{}),response={success:true,message:"کد تأیید ایجاد شد.",expiresAt:result.challenge.expiresAt};if(nodeEnv!=="production"&&exposeDevelopmentOtp)response.developmentOtp=result.code;return res.json(response)}catch(e){return handleAuthError(e,res)}});
  router.post("/verify-otp",(req,res)=>{try{const result=authService.verifyOtp(req.body||{});res.cookie(SESSION_COOKIE_NAME,result.sessionToken,authService.sessionCookieOptions(nodeEnv));return res.json({success:true,user:result.user,memberships:result.memberships,activeWorkspace:result.activeWorkspace,authDisposition:result.authDisposition})}catch(e){return handleAuthError(e,res)}});
  router.get("/me",(req,res)=>{const identity=authService.resolveSession(getSessionToken(req));if(!identity)return res.status(401).json({success:false,message:"Authentication required."});return res.json({success:true,user:identity.user,memberships:identity.memberships,activeWorkspace:identity.activeWorkspace})});
  router.post("/logout",(req,res)=>{authService.revokeSession(getSessionToken(req));res.clearCookie(SESSION_COOKIE_NAME,{httpOnly:true,secure:nodeEnv==="production",sameSite:"lax",path:"/"});return res.json({success:true})});
  return router;
}
