import express from "express";
const text=(v,max=200)=>typeof v==="string"&&v.trim()&&v.trim().length<=max?v.trim():null;
export function createBookingRouter({repository}) { const r=express.Router(); const bad=(res,message="Invalid booking input.")=>res.status(400).json({success:false,message});
  r.get("/booking",(_q,res)=>res.json({success:true,services:repository.listServices(),providers:repository.listProviders(),availability:repository.listAvailability(),appointments:repository.listAppointments()}));
  r.post("/booking/services",(q,res)=>{const name=text(q.body?.name);const durationMinutes=Number(q.body?.durationMinutes);if(!name||!Number.isInteger(durationMinutes)||durationMinutes<5||durationMinutes>1440)return bad(res);return res.status(201).json({success:true,service:repository.createService({name,durationMinutes})});});
  r.post("/booking/providers",(q,res)=>{const name=text(q.body?.name);if(!name)return bad(res);return res.status(201).json({success:true,provider:repository.createProvider({name})});});
  r.post("/booking/providers/:providerId/services/:serviceId",(q,res)=>repository.associate(q.params.providerId,q.params.serviceId)?res.status(201).json({success:true}):res.status(404).json({success:false,message:"Booking record not found."}));
  r.post("/booking/availability",(q,res)=>{const {providerId,weekday,startsAt,endsAt}=q.body||{};if(!text(providerId)||!Number.isInteger(weekday)||weekday<0||weekday>6||!text(startsAt)||!text(endsAt)||startsAt>=endsAt)return bad(res);const availability=repository.addAvailability({providerId,weekday,startsAt,endsAt});return availability?res.status(201).json({success:true,availability}):res.status(404).json({success:false,message:"Provider not found."});});
  r.post("/booking/appointments",(q,res)=>{const {serviceId,providerId,customerName,startsAt}=q.body||{};if(!text(serviceId)||!text(providerId)||!text(customerName)||!text(startsAt))return bad(res);const appointment=repository.createAppointment({serviceId,providerId,customerName,startsAt});return appointment?res.status(201).json({success:true,appointment}):res.status(404).json({success:false,message:"Booking records not found."});}); return r; }
