import express from "express";
import { resolveCapabilities } from "../site-platform/capability-resolver.mjs";
import { BookingError } from "../repositories/booking-repository.mjs";

const text = (value, max = 200) => typeof value === "string" && value.trim() && value.trim().length <= max ? value.trim() : null;
const bookingEnabled = (siteProjectService) => siteProjectService.list().some((project) => resolveCapabilities(project).capabilities.includes("booking"));

export function createBookingRouter({ repository, siteProjectService }) {
  const router = express.Router();
  const bad = (res, message = "Invalid booking input.") => res.status(400).json({ success: false, message });
  const requireBookingCapability = (_req, res, next) => {
    if (!bookingEnabled(siteProjectService)) return res.status(403).json({ success: false, code: "BOOKING_CAPABILITY_REQUIRED", message: "Booking is not enabled for this workspace." });
    return next();
  };

  router.use("/booking", requireBookingCapability);
  router.get("/booking", (_req, res) => res.json({ success: true, services: repository.listServices(), providers: repository.listProviders(), associations: repository.listAssociations(), availability: repository.listAvailability(), appointments: repository.listAppointments() }));
  router.post("/booking/services", (req, res) => { const name = text(req.body?.name); const durationMinutes = Number(req.body?.durationMinutes), modalities = Array.isArray(req.body?.modalities) && req.body.modalities.every((entry) => text(entry, 40)) ? req.body.modalities.map((entry) => entry.trim()) : []; const priceAmount = req.body?.priceAmount == null ? null : Number(req.body.priceAmount), priceCurrency = req.body?.priceCurrency == null ? null : text(req.body.priceCurrency, 8); if (!name || !Number.isInteger(durationMinutes) || durationMinutes < 5 || durationMinutes > 1440 || (priceAmount != null && (!Number.isInteger(priceAmount) || priceAmount < 0)) || (priceAmount != null && !priceCurrency)) return bad(res); return res.status(201).json({ success: true, service: repository.createService({ name, durationMinutes, modalities, priceAmount, priceCurrency }) }); });
  router.post("/booking/providers", (req, res) => { const name = text(req.body?.name); if (!name) return bad(res); return res.status(201).json({ success: true, provider: repository.createProvider({ name }) }); });
  router.post("/booking/providers/:providerId/services/:serviceId", (req, res) => repository.associate(req.params.providerId, req.params.serviceId) ? res.status(201).json({ success: true }) : res.status(404).json({ success: false, message: "Booking record not found." }));
  router.post("/booking/availability", (req, res) => { const { providerId, weekday, startsAt, endsAt } = req.body || {}, capacity = req.body?.capacity == null ? 1 : Number(req.body.capacity), status = req.body?.status || "ACTIVE"; if (!text(providerId) || !Number.isInteger(weekday) || weekday < 0 || weekday > 6 || !text(startsAt) || !text(endsAt) || startsAt >= endsAt || !Number.isInteger(capacity) || capacity < 1 || !["ACTIVE", "CANCELLED"].includes(status)) return bad(res); const availability = repository.addAvailability({ providerId, weekday, startsAt, endsAt, capacity, status }); return availability ? res.status(201).json({ success: true, availability }) : res.status(404).json({ success: false, message: "Provider not found." }); });
  router.post("/booking/appointments", (req, res) => { const { serviceId, providerId, customerName, startsAt } = req.body || {}; if (!text(serviceId) || !text(providerId) || !text(customerName) || !text(startsAt)) return bad(res); const appointment = repository.createAppointment({ serviceId, providerId, customerName, startsAt }); return appointment ? res.status(201).json({ success: true, appointment }) : res.status(404).json({ success: false, message: "Booking records not found." }); });
  router.get("/booking/customer/services", (_req, res) => res.json({ success: true, services: repository.listCustomerServices() }));
  router.get("/booking/customer/services/:serviceId/providers", (req, res) => res.json({ success: true, providers: repository.listEligibleProviders(req.params.serviceId) }));
  router.get("/booking/customer/slots", (req, res) => { const { serviceId, providerId, date } = req.query; if (!text(serviceId) || !text(providerId) || !text(date, 10)) return bad(res); return res.json({ success: true, slots: repository.listCustomerSlots({ serviceId, providerId, date }) }); });
  router.post("/booking/customer/review", (req, res) => { const { serviceId, providerId, date, startsAt, modality } = req.body || {}; const quote = repository.quoteCustomerBooking({ serviceId, providerId, date, startsAt, modality: modality || null }); return quote ? res.json({ success: true, quote }) : res.status(404).json({ success: false, code: "BOOKING_SLOT_NOT_FOUND", message: "The selected booking details are unavailable." }); });
  router.post("/booking/customer/appointments", (req, res) => { const { serviceId, providerId, date, startsAt, customerName, customerContact, modality } = req.body || {}; if (!text(serviceId) || !text(providerId) || !text(date, 10) || !text(startsAt, 5) || !text(customerName) || (customerContact != null && !text(customerContact))) return bad(res); try { const created = repository.createCustomerAppointment({ serviceId, providerId, date, startsAt, customerName, customerContact: customerContact || null, modality: modality || null }); return res.status(201).json({ success: true, ...created }); } catch (error) { if (error instanceof BookingError) return res.status(error.status).json({ success: false, code: error.code, message: error.message }); throw error; } });
  router.get("/booking/customer/confirmations/:reference", (req, res) => { const confirmation = repository.getCustomerConfirmation(req.params.reference); return confirmation ? res.json({ success: true, confirmation }) : res.status(404).json({ success: false, code: "BOOKING_CONFIRMATION_NOT_FOUND", message: "Booking confirmation was not found." }); });
  return router;
}
