import express from "express";
import { db } from "../../db/workspace-database.mjs";
import { loadderBusinessBuilderService } from "../business-builder/business-builder-service.mjs";
import { createContractPreviewAdapter } from "../business-builder/contract-preview-adapter.mjs";
import { createBusinessBuilderProjectService } from "../business-builder/project-service.mjs";
import { createBusinessAppRuntimeRouter } from "../business-builder/runtime-router.mjs";
import { getCommercialBuilderCatalog } from "../business-builder/commercial-catalog.mjs";
import { LOADDER_EDITOR_CAPABILITIES } from "../business-builder/editor-patch.mjs";
import { navigateLoadder } from "../business-builder/navigator.mjs";
import { createBusinessBuilderRateLimiter } from "../business-builder/business-builder-rate-limit.mjs";
import { createOperationsDashboardService } from "../business-builder/operations-dashboard.mjs";
import { requireWorkspaceId } from "../tenant-context.mjs";
import { createBusinessBuilderRepository } from "../repositories/business-builder-repository.mjs";

export function createBusinessBuilderRouter({ service = loadderBusinessBuilderService, projects = null, previewAdapter = null, database = db } = {}) {
  const router = express.Router(),writeLimit=createBusinessBuilderRateLimiter("write"),ops=createOperationsDashboardService(database);
  const adminMembership=userId=>userId?database.prepare("SELECT role,status FROM workspace_memberships WHERE workspace_id=? AND user_id=?").get(requireWorkspaceId(),userId):null;
  const isAdmin=req=>{const m=adminMembership(req.user?.id);return m?.status==="active"&&(m.role==="owner"||m.role==="admin");};
  router.get("/business-builder/catalog",(req,res)=>res.json({success:true,...getCommercialBuilderCatalog(),editor:LOADDER_EDITOR_CAPABILITIES}));
  router.get("/business-builder/operations",(req,res)=>res.json({success:true,summary:ops.workspaceSummary()}));
  router.get("/business-builder/admin",(req,res)=>isAdmin(req)?res.json({success:true,...ops.adminSummary()}):res.status(403).json({success:false,code:"ADMIN_FORBIDDEN"}));
  router.get("/business-builder/projects/:id/operations",(req,res)=>{const data=ops.projectSummary(req.params.id);return data?res.json({success:true,...data}):res.status(404).json({success:false,code:"PROJECT_NOT_FOUND"});});
  router.post("/business-builder/navigator",(req,res)=>{const project=req.body?.projectId&&projects?projects.getProject(req.body.projectId):null;return res.json({success:true,guidance:navigateLoadder({goal:req.body?.goal||"",screen:req.body?.screen||"builder",project})});});
  router.post("/business-builder/preview",writeLimit,(req,res)=>{try{const intent=String(req.body?.intent||"").trim();if(!intent)return res.status(400).json({success:false,code:"BUSINESS_INTENT_REQUIRED"});return res.status(201).json({success:true,preview:service.preview({intent,name:req.body?.name,locale:req.body?.locale||"fa-IR"})});}catch(error){return res.status(400).json({success:false,code:error?.code||"BUSINESS_BUILDER_PREVIEW_FAILED",message:error?.message});}});
  if(!projects)return router;
  router.get("/business-builder/projects",(req,res)=>res.json({success:true,projects:projects.listProjects()}));
  router.get("/business-builder/projects/:id",(req,res)=>{const project=projects.getProject(req.params.id);return project?res.json({success:true,project}):res.status(404).json({success:false,code:"PROJECT_NOT_FOUND"});});
  router.get("/business-builder/projects/:id/export",(req,res)=>{const exported=projects.exportProject(req.params.id);if(!exported)return res.status(404).json({success:false,code:"PROJECT_NOT_FOUND"});res.setHeader("Content-Disposition",`attachment; filename="loadder-${req.params.id}.json"`);return res.json(exported);});
  router.post("/business-builder/import",writeLimit,(req,res)=>{try{return res.status(201).json({success:true,...projects.importProject(req.body,req.user?.id||null)});}catch(error){return res.status(400).json({success:false,code:error?.code||"IMPORT_FAILED",message:error?.message});}});
  router.post("/business-builder/projects",writeLimit,(req,res)=>{try{const intent=String(req.body?.intent||"").trim();if(!intent)return res.status(400).json({success:false,code:"BUSINESS_INTENT_REQUIRED"});return res.status(201).json({success:true,...projects.createProject({intent,name:req.body?.name,locale:req.body?.locale||"fa-IR"},req.user?.id||null)});}catch(error){return res.status(400).json({success:false,code:error?.code||"PROJECT_CREATE_FAILED",message:error?.message});}});
  router.put("/business-builder/projects/:id",writeLimit,(req,res)=>{try{const result=projects.saveProject(req.params.id,req.body||{},req.user?.id||null);return result?res.json({success:true,...result}):res.status(404).json({success:false,code:"PROJECT_NOT_FOUND"});}catch(error){return res.status(400).json({success:false,code:error?.code||"PROJECT_SAVE_FAILED",message:error?.message});}});
  router.post("/business-builder/projects/:id/editor-patch",writeLimit,(req,res)=>{try{const result=projects.applyEditorPatch(req.params.id,req.body||{},req.user?.id||null);return result?res.status(201).json({success:true,...result}):res.status(404).json({success:false,code:"ACTIVE_VERSION_NOT_FOUND"});}catch(error){return res.status(400).json({success:false,code:"EDITOR_PATCH_INVALID",message:error?.message});}});
  router.post("/business-builder/projects/:id/versions/:versionId/restore",writeLimit,(req,res)=>{const result=projects.restoreVersion(req.params.id,req.params.versionId,req.user?.id||null);return result?res.status(201).json({success:true,...result}):res.status(404).json({success:false,code:"VERSION_NOT_FOUND"});});
  router.post("/business-builder/projects/:id/preview-sessions",writeLimit,async(req,res)=>{try{const result=await projects.startPreview(req.params.id);return result?res.status(201).json({success:true,...result}):res.status(404).json({success:false,code:"ACTIVE_VERSION_NOT_FOUND"});}catch(error){return res.status(409).json({success:false,code:error?.code||"PREVIEW_START_FAILED",message:error?.message});}});
  router.get("/business-builder/projects/:id/preview/document",(req,res)=>{const project=projects.getProject(req.params.id);if(!project?.activeVersionId||!previewAdapter)return res.status(404).send("Preview not available");const version=project.versions.find(v=>v.id===project.activeVersionId);if(!version)return res.status(404).send("Preview version not found");res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'; img-src data:; form-action 'none'; frame-ancestors 'self'");return res.send(previewAdapter.render({version}));});
  router.post("/business-builder/projects/:id/approvals",writeLimit,(req,res)=>{const{stage,decision,versionId}=req.body||{};if(!["preview","production"].includes(stage)||!["approved","rejected"].includes(decision)||!versionId)return res.status(400).json({success:false,code:"INVALID_APPROVAL"});const approval=projects.decide({projectId:req.params.id,versionId,stage,decision,actorId:req.user?.id||null,note:req.body?.note||null});return res.status(201).json({success:true,approval,productionDeploymentAllowed:projects.canDeployProduction(req.params.id)});});
  router.use(createBusinessAppRuntimeRouter({db:database,projects}));
  return router;
}
const defaultPreviewAdapter=createContractPreviewAdapter();const defaultRepository=createBusinessBuilderRepository(db);const defaultProjectService=createBusinessBuilderProjectService({repository:defaultRepository,builder:loadderBusinessBuilderService,previewAdapter:defaultPreviewAdapter});export default createBusinessBuilderRouter({projects:defaultProjectService,previewAdapter:defaultPreviewAdapter,database:db});
