import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowRight, Copy, DownloadSimple, FloppyDisk } from "@phosphor-icons/react";
import { apiFetch } from "../lib/api";
import { contentItemMarkdown, contentItemText, downloadContent } from "../lib/contentItemFormatting";

type Item = { id: string; title: string; content: Record<string, unknown>; contractId: string; contractVersion: number; placementId: string; placementVersion: number; revision: number; updatedAt: string };
const labels: Record<string, string> = { hook: "هوک", body: "بدنه", cta: "دعوت به اقدام", hashtags: "هشتگ‌ها", headlines: "تیترها", descriptions: "توضیحات", ctaLabel: "برچسب CTA", subject: "موضوع", previewText: "متن پیش‌نمایش", greeting: "سلام", bodySections: "بخش‌های بدنه", signoff: "امضا", title: "عنوان مقاله", seoTitle: "عنوان سئو", metaDescription: "توضیح متا", primaryKeyword: "کلیدواژه اصلی", slug: "Slug", benefits: "مزایا", proofPoints: "شواهد", finalCta: "CTA پایانی" };

export default function ContentItemPage() {
  const { id = "" } = useParams(), navigate = useNavigate();
  const [item, setItem] = useState<Item | null>(null), [title, setTitle] = useState(""), [content, setContent] = useState<Record<string, unknown>>({}), [notice, setNotice] = useState(""), [error, setError] = useState("");
  useEffect(() => { void apiFetch(`/api/content/items/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(); setItem(data.item); setTitle(data.item.title); setContent(data.item.content); }).catch(() => setError("محتوا پیدا نشد.")); }, [id]);
  const dirty = useMemo(() => Boolean(item) && (title !== item!.title || JSON.stringify(content) !== JSON.stringify(item!.content)), [item, title, content]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const leave = (event: React.MouseEvent) => { if (dirty && !window.confirm("تغییرات ذخیره‌نشده باقی بماند؟")) event.preventDefault(); };
  async function save() { if (!item) return; setError(""); const response = await apiFetch(`/api/content/items/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, content, expectedRevision: item.revision }) }); const data = await response.json(); if (!response.ok) { setError(data.code === "CONTENT_ITEM_REVISION_CONFLICT" ? "نسخه دیگری ذخیره شده است؛ صفحه را تازه کن." : "ذخیره انجام نشد."); return; } setItem(data.item); setTitle(data.item.title); setContent(data.item.content); setNotice("تغییرات ذخیره شد."); }
  async function duplicate() { if (!item || (dirty && !window.confirm("تغییرات ذخیره‌نشده رها شود؟"))) return; const response = await apiFetch(`/api/content/items/${item.id}/duplicate`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: "{}" }); const data = await response.json(); if (response.ok) navigate(`/dashboard/library/${data.item.id}`); }
  if (!item) return <main dir="rtl" className="loadder-dashboard-bg min-h-screen p-10 text-white">{error || "در حال بارگذاری…"}</main>;
  const text = contentItemText(item.contractId, content);
  return <main dir="rtl" className="loadder-dashboard-bg min-h-screen text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-5xl items-center gap-4 px-6 py-5"><Link onClick={leave} to="/dashboard/library" className="rounded-full border border-white/10 p-3"><ArrowRight size={18}/></Link><div><h1 className="text-xl font-bold">ویرایش محتوا</h1><p className="text-xs text-white/40" dir="ltr">{item.contractId} · revision {item.revision}</p></div></div></header><section className="mx-auto max-w-5xl px-6 py-8"><label className="text-sm text-white/50">عنوان کتابخانه</label><input value={title} maxLength={200} onChange={(event) => setTitle(event.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"/><div className="mt-5 rounded-3xl border border-white/10 bg-[#080d1d]/75 p-6"><ContractEditor value={content} onChange={setContent}/></div>{error && <p className="mt-4 text-red-300">{error}</p>}{notice && <p className="mt-4 text-cyan-300">{notice}</p>}<div className="mt-6 flex flex-wrap gap-3"><button disabled={!dirty} onClick={save} className="flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 disabled:opacity-35"><FloppyDisk/>ذخیره</button><button onClick={duplicate} className="rounded-xl border border-white/10 px-5 py-3">ساخت کپی</button><button onClick={async () => { await navigator.clipboard.writeText(text); setNotice("کپی شد."); }} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3"><Copy/>کپی</button><button onClick={() => downloadContent(`${title}.txt`, text)} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3"><DownloadSimple/>TXT</button><button onClick={() => downloadContent(`${title}.md`, contentItemMarkdown(title, item.contractId, content), "text/markdown;charset=utf-8")} className="rounded-xl border border-white/10 px-4 py-3">Markdown</button></div><p className="mt-5 text-xs text-white/35">ذخیره فقط کتابخانه را به‌روزرسانی می‌کند؛ هیچ انتشار یا اجرایی انجام نمی‌شود.</p></section></main>;
}

function ContractEditor({ value, onChange }: { value: Record<string, unknown>; onChange: (value: Record<string, unknown>) => void }) {
  const set = (field: string, next: unknown) => onChange({ ...value, [field]: next });
  return <div className="grid gap-4">{Object.entries(value).map(([field, current]) => <div key={field}><label className="mb-2 block text-sm text-white/55">{labels[field] || field}</label><ValueEditor field={field} value={current} onChange={(next) => set(field, next)}/></div>)}</div>;
}

function ValueEditor({ field, value, onChange }: { field: string; value: unknown; onChange: (value: unknown) => void }) {
  if (typeof value === "string") return <textarea dir={field === "slug" ? "ltr" : "rtl"} value={value} onChange={(event) => onChange(event.target.value)} rows={field === "body" ? 6 : 3} className="w-full rounded-xl border border-white/10 bg-black/20 p-3"/>;
  if (Array.isArray(value) && value.every((entry) => typeof entry === "string")) return <textarea value={value.join("\n")} onChange={(event) => onChange(event.target.value.split("\n"))} rows={Math.max(3, value.length)} className="w-full rounded-xl border border-white/10 bg-black/20 p-3"/>;
  if (Array.isArray(value)) return <div className="space-y-3">{value.map((entry, index) => <div key={index} className="rounded-xl border border-white/10 p-3"><ValueEditor field={`${field}-${index}`} value={entry} onChange={(next) => onChange(value.map((item, itemIndex) => itemIndex === index ? next : item))}/></div>)}</div>;
  if (value && typeof value === "object") return <div className="grid gap-3">{Object.entries(value as Record<string, unknown>).map(([child, current]) => <div key={child}><label className="mb-1 block text-xs text-white/40">{labels[child] || child}</label><ValueEditor field={child} value={current} onChange={(next) => onChange({ ...(value as Record<string, unknown>), [child]: next })}/></div>)}</div>;
  return null;
}
