import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowRight, Copy, DownloadSimple, FloppyDisk } from "@phosphor-icons/react";
import { apiFetch } from "../lib/api";
import { contentItemMarkdown, contentItemText, downloadContent } from "../lib/contentItemFormatting";
import ContractContentEditor from "../components/content/ContractContentEditor";
import ContentSourceBadge from "../components/content/ContentSourceBadge";

type Item = { id: string; sourceType: string; mediaType: string; title: string; content: Record<string, unknown>; contractId: string | null; contractVersion: number | null; placementId: string | null; placementVersion: number | null; revision: number; updatedAt: string; primaryAsset: { id: string; mimeType: string; width: number; height: number; durationMs: number | null } | null };
type CreativePlacement = { id: string; placementKind: "WEBSITE" | "SOCIAL" | "ADVERTISEMENT" | "EMAIL" | "OTHER"; channel: string; status: "ACTIVE" | "PAUSED" | "REMOVED" };

export default function ContentItemPage() {
  const { id = "" } = useParams(), navigate = useNavigate();
  const [item, setItem] = useState<Item | null>(null), [title, setTitle] = useState(""), [content, setContent] = useState<Record<string, unknown>>({}), [notice, setNotice] = useState(""), [error, setError] = useState("");
  const [previewUrl, setPreviewUrl] = useState("");
  const [placements, setPlacements] = useState<CreativePlacement[]>([]);
  useEffect(() => { void apiFetch(`/api/content/items/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(); setItem(data.item); setTitle(data.item.title); setContent(data.item.content); }).catch(() => setError("محتوا پیدا نشد.")); }, [id]);
  useEffect(() => { void apiFetch(`/api/content/items/${id}/placements`).then(async (response) => { const data = await response.json(); if (response.ok) setPlacements(data.placements); }); }, [id]);
  const dirty = useMemo(() => Boolean(item) && (title !== item!.title || JSON.stringify(content) !== JSON.stringify(item!.content)), [item, title, content]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const leave = (event: React.MouseEvent) => { if (dirty && !window.confirm("تغییرات ذخیره‌نشده باقی بماند؟")) event.preventDefault(); };
  async function save() { if (!item) return; setError(""); const response = await apiFetch(`/api/content/items/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, content, expectedRevision: item.revision }) }); const data = await response.json(); if (!response.ok) { setError(data.code === "CONTENT_ITEM_REVISION_CONFLICT" ? "نسخه دیگری ذخیره شده است؛ صفحه را تازه کن." : "ذخیره انجام نشد."); return; } setItem(data.item); setTitle(data.item.title); setContent(data.item.content); setNotice("تغییرات ذخیره شد."); }
  async function duplicate() { if (!item || (dirty && !window.confirm("تغییرات ذخیره‌نشده رها شود؟"))) return; const response = await apiFetch(`/api/content/items/${item.id}/duplicate`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: "{}" }); const data = await response.json(); if (response.ok) navigate(`/dashboard/library/${data.item.id}`); }
  async function loadPreview() { if (!item?.primaryAsset) return; const response = await apiFetch(`/api/content/assets/${item.primaryAsset.id}/access`, { method: "POST" }); const data = await response.json(); if (response.ok) setPreviewUrl(data.access.url); else setError("نمایش فایل انجام نشد."); }
  if (!item) return <main dir="rtl" className="loadder-dashboard-bg min-h-screen p-10 text-white">{error || "در حال بارگذاری…"}</main>;
  const text = item.contractId ? contentItemText(item.contractId, content) : "";
  return <main dir="rtl" className="loadder-dashboard-bg min-h-screen text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-5xl items-center gap-4 px-6 py-5"><Link onClick={leave} to="/dashboard/library" className="rounded-full border border-white/10 p-3"><ArrowRight size={18}/></Link><div><div className="flex items-center gap-3"><h1 className="text-xl font-bold">ویرایش محتوا</h1><ContentSourceBadge sourceType={item.sourceType}/></div><p className="text-xs text-white/40" dir="ltr">{item.contractId} · revision {item.revision}</p></div></div></header><section className="mx-auto max-w-5xl px-6 py-8"><label className="text-sm text-white/50">عنوان کتابخانه</label><input value={title} maxLength={200} onChange={(event) => setTitle(event.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3"/>
<div className="mt-5 rounded-3xl border border-white/10 bg-[#080d1d]/75 p-6">{item.primaryAsset ? <div><p className="text-sm text-white/50">{item.mediaType} · {item.primaryAsset.width}×{item.primaryAsset.height}</p>{previewUrl ? (item.mediaType === "IMAGE" ? <img src={previewUrl} alt={item.title} className="mt-4 max-h-[70vh] rounded-2xl object-contain"/> : <video src={previewUrl} controls preload="metadata" className="mt-4 max-h-[70vh] rounded-2xl"/>) : <button onClick={() => void loadPreview()} className="mt-4 rounded-xl bg-cyan-500/15 px-4 py-2 text-cyan-200">نمایش فایل</button>}</div> : <ContractContentEditor value={content} onChange={setContent}/>}</div>
<section className="mt-5 rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="text-sm font-semibold">استفاده‌شده در</h2>{placements.length ? <ul className="mt-3 flex flex-wrap gap-2">{placements.map((placement) => <li key={placement.id} className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/60">{placement.placementKind} · {placement.channel}{placement.status !== "ACTIVE" ? ` · ${placement.status}` : ""}</li>)}</ul> : <p className="mt-2 text-xs text-white/35">هنوز محل استفاده‌ای ثبت نشده است.</p>}</section>
{error && <p className="mt-4 text-red-300">{error}</p>}{notice && <p className="mt-4 text-cyan-300">{notice}</p>}<div className="mt-6 flex flex-wrap gap-3"><button disabled={!dirty} onClick={save} className="flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 disabled:opacity-35"><FloppyDisk/>ذخیره</button><button onClick={duplicate} className="rounded-xl border border-white/10 px-5 py-3">ساخت کپی</button>{!item.primaryAsset && <><button onClick={async () => { await navigator.clipboard.writeText(text); setNotice("کپی شد."); }} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3"><Copy/>کپی</button><button onClick={() => downloadContent(`${title}.txt`, text)} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3"><DownloadSimple/>TXT</button><button onClick={() => downloadContent(`${title}.md`, contentItemMarkdown(title, item.contractId || "", content), "text/markdown;charset=utf-8")} className="rounded-xl border border-white/10 px-4 py-3">Markdown</button></>}</div><p className="mt-5 text-xs text-white/35">ذخیره فقط کتابخانه را به‌روزرسانی می‌کند؛ هیچ انتشار یا اجرایی انجام نمی‌شود.</p></section></main>;
}
