import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, FileText, Sparkle } from "@phosphor-icons/react";
import { apiFetch } from "../lib/api";
import ContentSourceBadge from "../components/content/ContentSourceBadge";

type Item = { id: string; sourceType: string; title: string; contractId: string; placementId: string; mediaType: string; updatedAt: string };
const filters = [{ id: "", label: "همه" }, { id: "social_post", label: "شبکه اجتماعی" }, { id: "ad_copy", label: "تبلیغات" }, { id: "marketing_email", label: "ایمیل" }, { id: "blog_outline", label: "بلاگ" }, { id: "landing_page_copy", label: "صفحه فرود" }];

export default function ContentLibraryPage() {
  const [items, setItems] = useState<Item[]>([]), [filter, setFilter] = useState(""), [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); const query = new URLSearchParams({ limit: "20" }); if (filter) query.set("contractId", filter); void apiFetch(`/api/content/items?${query}`, { signal: controller.signal }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(); setItems(data.items); }).catch((reason) => { if (reason?.name !== "AbortError") setError("بارگذاری کتابخانه انجام نشد."); }); return () => controller.abort(); }, [filter]);
  return <main dir="rtl" className="loadder-dashboard-bg min-h-screen text-white"><header className="border-b border-white/10 bg-[#030617]/80"><div className="mx-auto flex max-w-6xl items-center gap-4 px-6 py-5"><Link to="/dashboard" className="rounded-full border border-white/10 p-3"><ArrowRight size={18}/></Link><FileText size={28} className="text-cyan-300"/><div className="flex-1"><h1 className="text-2xl font-bold">کتابخانه محتوا</h1><p className="text-sm text-white/45">محتوای ذخیره‌شده و قابل ویرایش برند</p></div><Link to="/dashboard/library/new" className="rounded-xl bg-violet-600 px-4 py-2 text-sm">افزودن محتوا · ساخت متن دستی</Link></div></header><section className="mx-auto max-w-6xl px-6 py-8"><div className="flex flex-wrap gap-2">{filters.map((item) => <button key={item.id} onClick={() => setFilter(item.id)} className={`rounded-full px-4 py-2 text-sm ${filter === item.id ? "bg-violet-500" : "border border-white/10 bg-white/5"}`}>{item.label}</button>)}</div>{error && <p className="mt-6 text-red-300">{error}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="rounded-3xl border border-white/10 bg-[#080d1d]/75 p-5"><div className="flex items-center justify-between text-xs text-white/40"><span>{item.mediaType}</span><span dir="ltr">{item.placementId}</span></div><div className="mt-3"><ContentSourceBadge sourceType={item.sourceType}/></div><h2 className="mt-4 text-lg font-semibold">{item.title}</h2><p className="mt-2 text-xs text-white/40">آخرین تغییر: {new Date(item.updatedAt).toLocaleString("fa-IR")}</p><Link to={`/dashboard/library/${item.id}`} className="mt-5 inline-flex rounded-xl bg-violet-500/20 px-4 py-2 text-sm text-violet-200">باز کردن و ادامه ویرایش</Link></article>)}</div>{!items.length && !error && <div className="mt-8 rounded-3xl border border-dashed border-white/10 p-12 text-center"><Sparkle size={30} className="mx-auto text-white/30"/><p className="mt-4 text-white/50">هنوز محتوایی ذخیره نشده است.</p><Link to="/dashboard/library/new" className="mt-5 inline-block rounded-xl bg-violet-600 px-5 py-3">ساخت متن دستی</Link></div>}</section></main>;
}
