import { Link, useLocation } from "react-router-dom";
import type { ElementType } from "react";
import BusinessBrainMotion from "../components/BusinessBrainMotion";
import WorkspaceSelector from "../components/WorkspaceSelector";
import { House, FolderOpen, Sparkle, ChartLineUp, Gear, Plus, BookOpenText, FileText, Globe, Gauge, InstagramLogo, Megaphone, UsersThree, Lightning, Brain } from "@phosphor-icons/react";
import { useStagger } from "../lib/animations/useStagger";
import { demoBusiness } from "../data/demoBusiness";
import { withDemo } from "../lib/demoMode";
type Tool = { title: string; icon: ElementType; status: string; route: string };
const tools: Tool[] = [
  { title: "Business Brain", icon: Brain, status: "آماده", route: "/dashboard/business-brain" },
  { title: "برند بوک", icon: BookOpenText, status: "آماده", route: "/dashboard/brand-book" },
  { title: "بیزنس پروپوزال", icon: FileText, status: "آماده", route: "/dashboard/business-proposal" },
  { title: "سایت‌ساز هوشمند", icon: Globe, status: "آماده", route: "/dashboard/websites/new" },
  { title: "مدیریت سایت", icon: Globe, status: "آماده", route: "/dashboard/site-operations" },
  { title: "KPI", icon: Gauge, status: "آماده", route: "/dashboard/kpi" },
  { title: "تولید محتوا", icon: Sparkle, status: "آماده", route: "/dashboard/content" },
  { title: "مدیر سوشال", icon: InstagramLogo, status: "آماده", route: "/dashboard/social" },
  { title: "تبلیغات هوشمند", icon: Megaphone, status: "آماده", route: "/dashboard/ads" },
  { title: "CRM", icon: UsersThree, status: "آماده", route: "/dashboard/crm" },
  { title: "تحلیل و گزارش", icon: ChartLineUp, status: "آماده", route: "/dashboard/analytics" },
  { title: "اتوماسیون", icon: Lightning, status: "آماده", route: "/dashboard/automation" },
];
function ToolCard({ tool }: { tool: Tool }) { const Icon = tool.icon; return <Link data-stagger to={tool.route} className="group relative min-h-[190px] overflow-hidden rounded-[24px] border border-violet-300/20 bg-white/[0.035] p-5 text-right transition duration-300 hover:-translate-y-1 hover:border-violet-300/45 hover:bg-white/[0.06]"><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-violet-500/[0.08] via-transparent to-fuchsia-500/[0.05]" /><div className="relative z-10"><div className="flex items-start justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-[15px] border border-violet-300/20 bg-black/25 text-cyan-300"><Icon size={22} weight="duotone" /></div><span className="rounded-full bg-emerald-400/10 px-3 py-1.5 text-sm text-emerald-300">{tool.status}</span></div><h3 className="mt-6 text-base font-semibold text-white">{tool.title}</h3><p className="mt-2 text-sm leading-7 text-white/45">برای شروع کلیک کن</p><div className="mt-4 flex items-center gap-2 text-sm text-violet-300/65"><span className="h-1.5 w-1.5 rounded-full bg-violet-300" /> آماده شروع</div></div></Link>; }
export default function DashboardPage() {
  const location = useLocation(); const isDemo = new URLSearchParams(location.search).get("demo") === "1"; const business = isDemo ? demoBusiness : null; const dashboardRef = useStagger();
  return <main ref={dashboardRef} dir="rtl" className="min-h-screen bg-[#050507] text-white">
    <aside className="fixed right-0 top-0 z-40 flex h-screen w-[260px] flex-col border-l border-white/[0.08] bg-black/60 p-5 backdrop-blur-2xl"><div className="mb-10"><div dir="ltr" className="text-left text-xl font-semibold">Loadder AI</div><p className="mt-1 text-sm text-white/45">مرکز هوشمند کسب‌وکار</p></div><nav className="space-y-2"><div className="flex items-center gap-3 rounded-2xl border border-violet-400/20 bg-violet-500/10 px-4 py-3.5 text-sm"><House size={20} weight="duotone" /> صفحه اصلی</div><Link to="/dashboard/websites" className="flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-sm text-white/55 transition hover:bg-white/[0.04]"><FolderOpen size={20} /> پروژه‌های سایت</Link><Link to="/dashboard/business-brain" className="flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-sm text-white/55 transition hover:bg-white/[0.04]"><Sparkle size={20} /> متخصص‌های هوش مصنوعی</Link><Link to={withDemo("/dashboard/analytics")} className="flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-sm text-white/55 transition hover:bg-white/[0.04]"><ChartLineUp size={20} /> تحلیل و گزارش‌ها</Link><Link to="/dashboard/site-operations" className="flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-sm text-white/55 transition hover:bg-white/[0.04]"><Globe size={20} /> مدیریت سایت</Link><button type="button" className="flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-sm text-white/55 transition hover:bg-white/[0.04]"><Gear size={20} /> تنظیمات</button></nav><div className="mt-auto rounded-[22px] border border-white/[0.08] bg-white/[0.03] p-4"><div className="text-sm text-white/45">فضای کاری</div><div className="mt-2"><WorkspaceSelector /></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/[0.05]"><div className="h-full w-[35%] rounded-full bg-gradient-to-l from-violet-500 via-fuchsia-500 to-cyan-400" /></div><div className="mt-2 text-sm text-white/40">تکمیل پروفایل ۳۵٪</div></div></aside>
    <section className="mr-[260px] min-h-screen"><header className="sticky top-0 z-30 flex items-center justify-between border-b border-white/[0.06] bg-[#050507]/85 px-8 py-5 backdrop-blur-2xl"><div><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">داشبورد</h1>{isDemo && <span className="rounded-full border border-cyan-300/15 bg-cyan-500/[0.08] px-3 py-1 text-xs text-cyan-200">نسخه دمو</span>}</div><p className="mt-1 text-sm text-white/45">{isDemo ? `${business?.name} — نمای یکپارچه کسب‌وکار` : "همه ابزارهای هوش مصنوعی کسب‌وکارت در یک جا"}</p></div><Link to="/dashboard/websites/new" className="flex items-center gap-2 rounded-full border border-fuchsia-300/20 bg-gradient-to-l from-violet-500/20 to-fuchsia-500/15 px-5 py-3 text-sm"><Plus size={16} weight="bold" /> ساخت سایت جدید</Link></header><div className="p-8"><section className="relative overflow-hidden rounded-[30px] border border-white/[0.08] bg-white/[0.035] p-8"><div className="pointer-events-none absolute -left-20 -top-20 h-[300px] w-[300px] rounded-full bg-violet-500/10 blur-[100px]" /><div className="relative z-10"><h2 className="text-3xl font-semibold">کسب‌وکارت را هوشمندتر مدیریت کن.</h2><p className="mt-4 max-w-3xl text-base leading-8 text-white/55">از ساخت برند و محتوا تا سایت‌ساز هوشمند، CRM، Analytics و Automation؛ همه به Business Brain مشترک Loadder متصل می‌شوند.</p></div></section><section className="mt-8"><BusinessBrainMotion /></section><section className="mt-10"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-semibold">متخصص‌های هوش مصنوعی</h2><p className="mt-1 text-sm text-white/45">ابزار موردنظرت را انتخاب کن.</p></div><span className="text-sm text-violet-300/70">۱۲ متخصص فعال</span></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5">{tools.map((tool) => <ToolCard key={tool.title} tool={tool} />)}</div></section><section className="mt-10"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">پروژه‌های اخیر</h2><Link to="/dashboard/websites" className="text-sm text-violet-300">مشاهده سایت‌ها</Link></div><div data-stagger className="mt-5 rounded-[26px] border border-white/[0.07] bg-white/[0.025] p-10 text-center"><FolderOpen size={30} weight="duotone" className="mx-auto text-white/30" /><p className="mt-4 text-base text-white/50">هنوز پروژه سایتی ساخته نشده</p><Link to="/dashboard/websites/new" className="mt-5 inline-flex rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold">ساخت اولین سایت</Link></div></section></div></section>
  </main>;
}
