/* oxlint-disable react/set-state-in-effect -- authenticated API hydration is intentionally effect-driven */
import { useEffect, useState } from "react";
import { ArrowRight, Copy, Globe, Plus } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Domain={id:string;hostname:string;status:string;verificationRecordName:string;verificationToken:string;tlsStatus:string;verifiedAt:string|null};
type Readiness={publicPublishingConfigured:boolean;managedDomainConfigured:boolean;customDomainVerificationReady:boolean;tlsProvisioningConfigured:boolean;publicMediaConfigured:boolean};
const json=async(path:string,init?:RequestInit)=>{const response=await apiFetch(path,init),body=await response.json();if(!response.ok)throw new Error(body.code||"DOMAIN_OPERATION_FAILED");return body;};
const labels:Record<string,string>={PENDING_VERIFICATION:"در انتظار تایید DNS",VERIFIED:"تایید شده",ACTIVE:"فعال",FAILED:"خطا",DISABLED:"غیرفعال",UNKNOWN:"وضعیت HTTPS نامشخص",PENDING:"در انتظار HTTPS",READY:"آماده HTTPS"};

export default function DomainManagementPage(){
 const[domains,setDomains]=useState<Domain[]>([]),[readiness,setReadiness]=useState<Readiness|null>(null),[hostname,setHostname]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{const result=await json("/api/domains");setDomains(result.domains);setReadiness(result.readiness);};
 useEffect(()=>{void load().catch(error=>setMessage(error.message));},[]);
 const act=async(operation:()=>Promise<void>)=>{setBusy(true);setMessage("");try{await operation();await load();}catch(error){setMessage(error instanceof Error?error.message:"DOMAIN_OPERATION_FAILED");}finally{setBusy(false);}};
 const add=()=>act(async()=>{await json("/api/domains",{method:"POST",headers:{"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({hostname})});setHostname("");setMessage("دامنه ثبت شد. رکورد TXT را در DNS قرار دهید.");});
 const verify=(id:string)=>act(async()=>{const result=await json(`/api/domains/${id}/verify`,{method:"POST"});setMessage(result.verified?"مالکیت دامنه تایید شد.":"رکورد صحیح هنوز در DNS دیده نشد.");});
 return <main dir="rtl" className="min-h-screen bg-[#050507] p-5 text-white"><div className="mx-auto max-w-5xl space-y-5"><header className="flex items-center gap-3"><Link to="/dashboard" className="rounded-xl border border-white/10 p-3"><ArrowRight/></Link><Globe size={30}/><div><h1 className="text-2xl font-bold">دامنه و انتشار عمومی</h1><p className="text-sm text-white/50">اتصال امن دامنه، تایید DNS و آمادگی HTTPS</p></div></header>
 <section className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">افزودن دامنه</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input dir="ltr" value={hostname} onChange={event=>setHostname(event.target.value)} placeholder="example.com" className="min-h-11 flex-1 rounded-xl bg-black/30 px-4"/><button disabled={busy||!hostname} onClick={()=>void add()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 disabled:opacity-40"><Plus/>افزودن</button></div></section>
 <section className="grid gap-4">{domains.map(domain=><article key={domain.id} className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 dir="ltr" className="text-lg font-semibold">{domain.hostname}</h2><p className="mt-1 text-sm text-white/50">{labels[domain.status]||domain.status} · {labels[domain.tlsStatus]||domain.tlsStatus}</p></div><button disabled={busy||domain.status==="DISABLED"} onClick={()=>void verify(domain.id)} className="min-h-11 rounded-xl border border-white/10 px-4">بررسی DNS</button></div><div className="mt-4 grid gap-3 rounded-2xl bg-black/20 p-4 text-sm"><p><span className="text-white/45">نوع:</span> TXT</p><button dir="ltr" onClick={()=>void navigator.clipboard.writeText(domain.verificationRecordName)} className="flex items-center justify-between gap-2 text-left"><code>{domain.verificationRecordName}</code><Copy/></button><button dir="ltr" onClick={()=>void navigator.clipboard.writeText(domain.verificationToken)} className="flex items-center justify-between gap-2 overflow-hidden text-left"><code className="truncate">{domain.verificationToken}</code><Copy/></button></div></article>)}</section>
 {readiness&&<section className="rounded-3xl border border-white/10 bg-white/[.03] p-5 text-sm text-white/60"><p>انتشار عمومی: {readiness.publicPublishingConfigured?"آماده":"نیازمند پیکربندی"}</p><p>دامنه مدیریت‌شده: {readiness.managedDomainConfigured?"آماده":"نیازمند پیکربندی"}</p><p>صدور TLS: {readiness.tlsProvisioningConfigured?"آماده":"مسدود تا اتصال ارائه‌دهنده"}</p><p>رسانه عمومی: {readiness.publicMediaConfigured?"آماده":"نیازمند پیکربندی"}</p></section>}
 {message&&<p className="rounded-xl border border-amber-400/20 bg-amber-400/10 p-3 text-sm text-amber-200">{message}</p>}</div></main>;
}
