import { useRef, useState, type ReactNode } from "react";
import { ArrowRight, Desktop, DeviceMobile, DeviceTablet, Eye, FloppyDisk, Gear, Image, Layout, PaintBrush, Plus, Sparkle, SquaresFour, Trash } from "@phosphor-icons/react";
import { Link } from "react-router-dom";

type Viewport = "desktop" | "tablet" | "mobile";
type Align = "right" | "center" | "left";
type Kind = "hero" | "about" | "services" | "doctors" | "stats" | "faq" | "media" | "testimonials" | "footer";
type Section = { id:string; kind:Kind; title:string; subtitle:string; bg:string; fg:string; padding:number; radius:number; align:Align; imageUrl?:string; buttonText?:string; visible:boolean };

const seed:Section[] = [
  {id:"hero",kind:"hero",title:"لبخندی زیبا و ماندگار، با مراقبت تخصصی",subtitle:"رزرو آنلاین، مشاوره سریع و خدمات تخصصی دندانپزشکی در یک تجربه آرام و حرفه‌ای.",bg:"#eef3ff",fg:"#0f2557",padding:64,radius:0,align:"right",buttonText:"رزرو نوبت",visible:true},
  {id:"about",kind:"about",title:"متخصصان تو، برای لبخند تو",subtitle:"درمان دقیق، تجهیزات مدرن و برنامه درمانی شخصی‌سازی‌شده برای هر بیمار.",bg:"#ffffff",fg:"#102149",padding:64,radius:0,align:"right",visible:true},
  {id:"services",kind:"services",title:"خدمات تخصصی کلینیک",subtitle:"از معاینه و پیشگیری تا درمان‌های زیبایی و تخصصی.",bg:"#ffffff",fg:"#102149",padding:54,radius:0,align:"center",visible:true},
  {id:"doctors",kind:"doctors",title:"متعهد به لبخند شما",subtitle:"تیم پزشکان متخصص و باتجربه، در کنار شما از مشاوره تا درمان.",bg:"#eef3ff",fg:"#102149",padding:64,radius:0,align:"center",visible:true},
  {id:"stats",kind:"stats",title:"اعتماد در اعداد",subtitle:"تجربه، رضایت و کیفیتی که قابل اندازه‌گیری است.",bg:"#eef3ff",fg:"#102149",padding:40,radius:0,align:"center",visible:true},
  {id:"faq",kind:"faq",title:"سوالات متداول",subtitle:"پاسخ سریع به سوال‌هایی که پیش از مراجعه ممکن است داشته باشید.",bg:"#ffffff",fg:"#102149",padding:64,radius:0,align:"right",visible:true},
  {id:"media",kind:"media",title:"قبل از درمان، با مسیر آشنا شوید",subtitle:"ویدئوی معرفی کلینیک، محیط، تجهیزات و روند مراجعه.",bg:"#ffffff",fg:"#102149",padding:48,radius:22,align:"center",visible:true},
  {id:"testimonials",kind:"testimonials",title:"مشتریان از ما می‌گویند",subtitle:"تجربه بیماران، بهترین تصویر از کیفیت خدمات ماست.",bg:"#eef3ff",fg:"#102149",padding:64,radius:0,align:"center",visible:true},
  {id:"footer",kind:"footer",title:"کلینیک شما",subtitle:"رزرو نوبت، تماس، شبکه‌های اجتماعی و اطلاعات ضروری کلینیک.",bg:"#07162f",fg:"#ffffff",padding:48,radius:0,align:"right",visible:true},
];

const names:Record<Kind,string>={hero:"Hero و رزرو",about:"معرفی کلینیک",services:"خدمات",doctors:"پزشکان",stats:"آمار",faq:"FAQ",media:"ویدئو / رسانه",testimonials:"نظرات بیماران",footer:"Footer"};

export default function MedicalWebsiteStudioPage(){
  const [sections,setSections]=useState<Section[]>(seed);
  const [selected,setSelected]=useState("hero");
  const [viewport,setViewport]=useState<Viewport>("desktop");
  const [tab,setTab]=useState<"content"|"style"|"advanced">("content");
  const imageInput=useRef<HTMLInputElement>(null);
  const active=sections.find(s=>s.id===selected) || sections[0];
  const width=viewport==="desktop"?"1180px":viewport==="tablet"?"768px":"390px";
  const patch=(changes:Partial<Section>)=>setSections(items=>items.map(s=>s.id===active.id?{...s,...changes}:s));
  const add=(kind:Kind)=>{const id=`${kind}-${Date.now()}`;const next:Section={...seed.find(s=>s.kind===kind)!,id,title:names[kind]};setSections(x=>[...x,next]);setSelected(id)};
  const remove=()=>{if(sections.length<=1)return;const next=sections.filter(s=>s.id!==active.id);setSections(next);setSelected(next[0].id)};
  const upload=(file:File)=>{if(!file.type.startsWith("image/"))return;const reader=new FileReader();reader.onload=()=>patch({imageUrl:String(reader.result)});reader.readAsDataURL(file)};

  return <main dir="rtl" className="h-screen overflow-hidden bg-[#0b1019] text-white">
    <input ref={imageInput} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value=""}} />
    <header className="flex h-[62px] items-center justify-between border-b border-white/10 bg-[#0d131d] px-4">
      <div className="flex items-center gap-2"><Link to="/dashboard/websites" className="rounded-lg border border-white/10 p-2 text-white/60"><ArrowRight/></Link><button className="flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-sm font-bold"><FloppyDisk/> ذخیره Template</button><button className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm"><Eye/> پیش‌نمایش</button></div>
      <div className="flex items-center gap-1 rounded-xl bg-white/[.04] p-1"><View active={viewport==="desktop"} onClick={()=>setViewport("desktop")}><Desktop/></View><View active={viewport==="tablet"} onClick={()=>setViewport("tablet")}><DeviceTablet/></View><View active={viewport==="mobile"} onClick={()=>setViewport("mobile")}><DeviceMobile/></View></div>
      <div><div className="text-xs text-white/35">Template</div><b className="text-sm">کلینیک و پزشک · Medical 01</b></div>
    </header>
    <div className="grid h-[calc(100vh-62px)] grid-cols-[72px_250px_minmax(0,1fr)_310px]">
      <nav className="border-l border-white/10 bg-[#0b111a] p-2 text-[11px] text-white/55"><Tool icon={<Layout/>} label="بخش‌ها" active/><Tool icon={<SquaresFour/>} label="المان‌ها"/><Tool icon={<Image/>} label="رسانه"/><Tool icon={<PaintBrush/>} label="استایل‌ها"/><Tool icon={<Gear/>} label="تنظیمات"/></nav>
      <aside className="overflow-y-auto border-l border-white/10 bg-[#101722] p-4"><div className="mb-4 text-xs font-bold text-white/60">بلوک‌های پزشکی</div><div className="grid grid-cols-2 gap-3">{(Object.keys(names) as Kind[]).map(k=><button key={k} onClick={()=>add(k)} className="min-h-20 rounded-xl border border-white/10 bg-white/[.035] p-3 text-xs text-white/70 hover:border-violet-400/50"><Plus className="mx-auto mb-2 text-lg"/>{names[k]}</button>)}</div><div className="mt-6 text-xs font-bold text-white/60">لایه‌ها</div><div className="mt-3 space-y-2">{sections.map(s=><button key={s.id} onClick={()=>setSelected(s.id)} className={`w-full rounded-xl border p-3 text-right text-xs ${selected===s.id?"border-violet-400/50 bg-violet-500/10":"border-white/10 bg-white/[.02]"}`}><div className="font-bold">{s.title}</div><div className="mt-1 text-[10px] text-white/30">{names[s.kind]}</div></button>)}</div></aside>
      <section className="overflow-auto bg-[#202733] p-7"><div className="mx-auto transition-all" style={{width,maxWidth:"100%"}}><div className="overflow-hidden bg-white shadow-[0_25px_80px_rgba(0,0,0,.4)]"><MedicalHeader/>{sections.filter(s=>s.visible).map(s=><Canvas key={s.id} section={s} selected={s.id===selected} onClick={()=>setSelected(s.id)}/>)}</div></div></section>
      <aside className="overflow-y-auto border-r border-white/10 bg-[#101722] p-5"><div className="mb-4 flex items-center justify-between"><b className="text-sm">تنظیمات بخش</b><span className="text-white/25">×</span></div><div className="mb-5 flex border-b border-white/10 text-xs"><Tab active={tab==="content"} onClick={()=>setTab("content")}>محتوا</Tab><Tab active={tab==="style"} onClick={()=>setTab("style")}>استایل</Tab><Tab active={tab==="advanced"} onClick={()=>setTab("advanced")}>پیشرفته</Tab></div>{tab==="content"&&<div className="space-y-4"><Field label="عنوان"><input className="input" value={active.title} onChange={e=>patch({title:e.target.value})}/></Field><Field label="توضیح"><textarea className="input min-h-24" value={active.subtitle} onChange={e=>patch({subtitle:e.target.value})}/></Field>{active.kind==="hero"&&<Field label="متن CTA"><input className="input" value={active.buttonText||"رزرو نوبت"} onChange={e=>patch({buttonText:e.target.value})}/></Field>}<button onClick={()=>imageInput.current?.click()} className="flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.04] py-3 text-xs"><Image/> آپلود / تغییر تصویر</button><label className="flex items-center justify-between rounded-xl border border-white/10 p-3 text-xs"><span>نمایش این بخش در صفحه</span><input type="checkbox" checked={active.visible} onChange={e=>patch({visible:e.target.checked})}/></label></div>}{tab==="style"&&<div className="space-y-5"><Color label="پس‌زمینه" value={active.bg} onChange={v=>patch({bg:v})}/><Color label="رنگ متن" value={active.fg} onChange={v=>patch({fg:v})}/><Field label={`فاصله عمودی: ${active.padding}px`}><input className="w-full accent-violet-500" type="range" min="16" max="120" value={active.padding} onChange={e=>patch({padding:Number(e.target.value)})}/></Field><Field label={`گوشه‌ها: ${active.radius}px`}><input className="w-full accent-violet-500" type="range" min="0" max="48" value={active.radius} onChange={e=>patch({radius:Number(e.target.value)})}/></Field></div>}{tab==="advanced"&&<div className="space-y-4"><div className="rounded-xl border border-violet-400/20 bg-violet-500/10 p-4 text-xs"><div className="mb-2 flex items-center gap-2 font-bold"><Sparkle/> Design Copilot</div>در نسخه بعدی، تغییرات AI، Drag & Drop تصویر و تنظیم مستقیم هر Element روی Canvas از همین پنل کنترل می‌شود.</div><button onClick={remove} className="flex w-full items-center justify-center gap-2 rounded-xl border border-rose-400/20 bg-rose-500/10 p-3 text-sm text-rose-300"><Trash/> حذف بخش</button></div>}</aside>
    </div>
  </main>
}

function MedicalHeader(){return <div className="flex items-center justify-between border-b border-slate-100 bg-white px-7 py-4 text-slate-900"><div className="font-black text-[#173b80]">کلینیک شما ✦</div><div className="hidden gap-5 text-xs text-slate-500 md:flex"><span>خانه</span><span>خدمات</span><span>پزشکان</span><span>سوالات</span><span>تماس</span></div><button className="rounded-lg bg-[#3167d8] px-4 py-2 text-xs font-bold text-white">رزرو نوبت</button></div>}
function Canvas({section:s,selected,onClick}:{section:Section;selected:boolean;onClick:()=>void}){return <section onClick={onClick} className={`relative cursor-pointer transition ${selected?"ring-2 ring-inset ring-violet-500":"hover:ring-1 hover:ring-inset hover:ring-violet-300"}`} style={{background:s.bg,color:s.fg,padding:`${s.padding}px 6%`,borderRadius:s.radius,textAlign:s.align}}>{selected&&<span className="absolute right-3 top-3 rounded bg-violet-600 px-2 py-1 text-[9px] text-white">{names[s.kind]}</span>}<MedicalBlock s={s}/></section>}
function MedicalBlock({s}:{s:Section}){if(s.kind==="hero")return <div className="grid items-center gap-8 md:grid-cols-2"><div><div className="mb-3 text-xs font-bold text-blue-600">مراقبت تخصصی، تجربه انسانی</div><h1 className="text-4xl font-black leading-tight md:text-6xl">{s.title}</h1><p className="mt-5 max-w-xl text-sm opacity-60 md:text-base">{s.subtitle}</p><div className="mt-7 flex gap-3"><button className="rounded-xl bg-[#3167d8] px-6 py-3 text-sm font-bold text-white">{s.buttonText||"رزرو نوبت"}</button><button className="rounded-xl border border-current/15 px-5 py-3 text-sm">☎ مشاوره تلفنی</button></div><div className="mt-5 text-xs opacity-50">★★★★★ رضایت بیماران · پاسخ‌گویی سریع</div></div><div className="relative min-h-80 overflow-hidden rounded-[30px] bg-[#cbdcff]">{s.imageUrl?<img src={s.imageUrl} className="absolute inset-0 h-full w-full object-cover"/>:<div className="grid min-h-80 place-items-center text-8xl">🩺</div>}<div className="absolute bottom-5 right-5 rounded-2xl bg-[#142d68] px-5 py-4 text-sm font-bold text-white shadow-xl">☎ تماس فوری با کلینیک</div></div></div>;
if(s.kind==="about")return <div className="grid items-center gap-10 md:grid-cols-2"><div className="grid grid-cols-2 gap-3"><div className="min-h-56 rounded-3xl bg-blue-50"/>{s.imageUrl?<img src={s.imageUrl} className="h-full min-h-56 w-full rounded-3xl object-cover"/>:<div className="grid min-h-56 place-items-center rounded-3xl bg-slate-100 text-6xl">🦷</div>}</div><div><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-4 opacity-60">{s.subtitle}</p><div className="mt-6 grid gap-3 text-sm"><span>✓ تشخیص دقیق و برنامه درمان شخصی</span><span>✓ تجهیزات و متریال به‌روز</span><span>✓ تجربه آرام و شفاف برای بیمار</span></div></div></div>;
if(s.kind==="services")return <div><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-3 opacity-55">{s.subtitle}</p><div className="mt-10 grid gap-5 md:grid-cols-4">{["دندانپزشکی ترمیمی","زیبایی و طراحی لبخند","ارتودنسی","ایمپلنت و جراحی"].map((x,i)=><div key={x} className="rounded-2xl border border-slate-100 bg-white p-5 text-center shadow-sm"><div className="text-4xl">{["🦷","✨","😁","⚕️"][i]}</div><div className="mt-4 font-bold">{x}</div><p className="mt-2 text-xs opacity-50">مشاوره، تشخیص و مسیر درمان تخصصی.</p></div>)}</div></div>;
if(s.kind==="doctors")return <div><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-3 opacity-55">{s.subtitle}</p><div className="mt-8 grid gap-4 md:grid-cols-4">{["دکتر سارا احمدی","دکتر علی رضایی","دکتر مریم نادری","دکتر امیر حسینی"].map((x,i)=><div key={x} className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="grid aspect-[4/5] place-items-center bg-slate-100 text-7xl">{["👩🏻‍⚕️","👨🏻‍⚕️","👩🏽‍⚕️","👨🏽‍⚕️"][i]}</div><div className="p-4 text-center"><b>{x}</b><div className="mt-1 text-xs opacity-45">متخصص دندانپزشکی</div></div></div>)}</div></div>;
if(s.kind==="stats")return <div className="grid gap-6 md:grid-cols-4">{[["+15","سال تجربه"],["+800","درمان موفق"],["+2500","بیمار راضی"],["+10000","مشاوره و مراجعه"]].map(([n,l])=><div key={l}><div className="text-4xl font-black text-blue-600">{n}</div><div className="mt-2 text-xs opacity-55">{l}</div></div>)}</div>;
if(s.kind==="faq")return <div className="grid gap-8 md:grid-cols-[.8fr_1.2fr]"><div><h2 className="text-4xl font-black">{s.title}</h2><p className="mt-4 opacity-55">{s.subtitle}</p></div><div>{["برای اولین مراجعه چه مدارکی لازم است؟","آیا امکان رزرو آنلاین وجود دارد؟","مدت زمان درمان چطور مشخص می‌شود؟","شرایط پرداخت و پیگیری چگونه است؟"].map(q=><div key={q} className="border-b border-slate-200 py-4 text-sm font-semibold">{q}<span className="float-left">+</span></div>)}</div></div>;
if(s.kind==="media")return <div><div className="mx-auto max-w-2xl text-center"><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-3 opacity-55">{s.subtitle}</p></div><div className="relative mx-auto mt-8 aspect-video max-w-4xl overflow-hidden rounded-3xl bg-slate-200">{s.imageUrl?<img src={s.imageUrl} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-7xl">▶</div>}</div></div>;
if(s.kind==="testimonials")return <div><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-3 opacity-55">{s.subtitle}</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="rounded-2xl bg-white p-6 text-right shadow-sm"><div className="text-3xl text-blue-600">“</div><p className="mt-3 text-sm opacity-60">تجربه مراجعه بسیار منظم، شفاف و حرفه‌ای بود و تیم درمان با حوصله همه مراحل را توضیح داد.</p><div className="mt-5 text-xs font-bold">بیمار کلینیک</div></div>)}</div></div>;
return <div className="grid gap-8 md:grid-cols-4"><div><div className="text-xl font-black">{s.title}</div><p className="mt-3 text-xs opacity-55">{s.subtitle}</p></div><div><b>خدمات</b><div className="mt-3 space-y-2 text-xs opacity-55"><div>ترمیم و زیبایی</div><div>ایمپلنت</div><div>ارتودنسی</div></div></div><div><b>دسترسی سریع</b><div className="mt-3 space-y-2 text-xs opacity-55"><div>رزرو نوبت</div><div>پزشکان</div><div>FAQ</div></div></div><div><b>تماس</b><div className="mt-3 space-y-2 text-xs opacity-55"><div>۰۲۱-۰۰۰۰۰۰۰۰</div><div>info@clinic.ir</div><div>Instagram · WhatsApp</div></div></div></div>}
function Tool({icon,label,active=false}:{icon:ReactNode;label:string;active?:boolean}){return <button className={`mb-2 flex w-full flex-col items-center gap-1 rounded-xl py-3 ${active?"bg-violet-600 text-white":"hover:bg-white/5"}`}><span className="text-xl">{icon}</span>{label}</button>}
function View({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button onClick={onClick} className={`rounded-lg p-2 ${active?"bg-white/10":"text-white/35"}`}>{children}</button>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button onClick={onClick} className={`flex-1 border-b-2 py-3 ${active?"border-violet-500 text-violet-300":"border-transparent text-white/40"}`}>{children}</button>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-2 block text-[11px] text-white/45">{label}</span>{children}</label>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className="flex items-center justify-between"><span className="text-xs text-white/55">{label}</span><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-8 w-10 bg-transparent"/></div>}
