import { useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { apiFetch } from "../lib/api";
import { patientHeaders, readPatientSession } from "../lib/patientSession";
import { bookingExperienceFor } from "../lib/bookingExperience";
import { formatAppointmentWhen, formatBookingDay, formatPersianNumber, formatPrice, formatSlotTime, toPersianDigits } from "../lib/appointmentTime";

type Service={id:string;name:string;durationMinutes:number;modalities:string[];price?:{amount:number;currency:string}|null};
type Provider={id:string;name:string}; type Slot={startsAt:string;startsAtTime:string;state:"available"|"limited"|"full"|"cancelled";remainingCapacity:number;modalityOptions:string[]};
const read=async(r:Response)=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"دریافت اطلاعات ناموفق بود.");return d};
const today=()=>new Date().toISOString().slice(0,10);
const MODE_LABELS:Record<string,string>={ONLINE:"آنلاین",IN_PERSON:"حضوری",VIDEO:"ویدئویی",AUDIO:"صوتی",TEXT:"متنی"};const modalityLabel=(m:string)=>MODE_LABELS[m]||m;
const SLOT_STATE:Record<Slot["state"],string>={limited:"ظرفیت محدود",available:"موجود",full:"تکمیل",cancelled:"لغو"};
export default function PublicBookingPage(){
  const {siteProjectId}=useParams(); const [query]=useSearchParams(); const appProject=query.get("app")||""; const identityHeaders=():Record<string,string>=>{const patient=readPatientSession(siteProjectId||"");if(patient)return patientHeaders(patient);try{const token=sessionStorage.getItem(`loadder-public-app-token:${appProject}`);return appProject&&token?{"X-Loadder-App-Token":token,"X-Loadder-App-Project":appProject}:{}}catch{return {}}}; const base=`/api/auth/site/${siteProjectId}/booking`;
  const [siteType,setSiteType]=useState<string|null|undefined>(undefined),[siteName,setSiteName]=useState(""),[servicesLoaded,setServicesLoaded]=useState(false); const X=bookingExperienceFor(siteType),T=X.theme,labels=X.stepLabels,fa=X.localizeDigits;
  const clock=(t:string)=>fa?formatSlotTime(t):t, day=(d:string)=>fa?formatBookingDay(d):d, money=(p:Service["price"])=>(p?formatPrice(p):"");
  useEffect(()=>{void apiFetch(`/api/auth/site/${siteProjectId}`).then(read).then(d=>{setSiteType(d.site?.siteType??null);setSiteName(d.site?.name||"")}).catch(()=>setSiteType(null))},[siteProjectId]);
  const [services,setServices]=useState<Service[]>([]),[providers,setProviders]=useState<Provider[]>([]),[slots,setSlots]=useState<Slot[]>([]),[service,setService]=useState<Service|null>(null),[provider,setProvider]=useState<Provider|null>(null),[modality,setModality]=useState(""),[date,setDate]=useState(today()),[slot,setSlot]=useState<Slot|null>(null),[name,setName]=useState(""),[contact,setContact]=useState(""),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[confirmation,setConfirmation]=useState<any>(null);
  const [catalog,setCatalog]=useState<{id:string;providers:{id:string;modalities:string[]}[]}[]>([]);
  useEffect(()=>{void apiFetch(`${base}/catalog`).then(read).then(d=>setCatalog(d.services||[])).catch(()=>setCatalog([]))},[base]);
  // Only care modes the chosen doctor really offers for this service (the service defines the set; the doctor may restrict it).
  const modeOptions:string[]=(service&&provider?catalog.find(x=>x.id===service.id)?.providers.find(x=>x.id===provider.id)?.modalities:undefined)??service?.modalities??[];
  // The journey is fixed up front from the catalog: the mode step exists when any service offers care modes, so the stepper never changes length mid-flow.
  const needsModality=services.some(x=>(x.modalities||[]).length>0);
  useEffect(()=>{setModality(m=>modeOptions.includes(m)?m:(modeOptions[0]||""))},[modeOptions.join(",")]); const visibleSteps=useMemo(()=>needsModality?[...labels]:[...labels.slice(0,2),...labels.slice(3)],[needsModality,labels]);
  useEffect(()=>{void apiFetch(`${base}/services`).then(read).then(d=>setServices(d.services||[])).catch(e=>setMessage(e.message)).finally(()=>setServicesLoaded(true))},[base]);
  useEffect(()=>{if(!service)return;setProvider(null);setSlot(null);setModality(service.modalities?.[0]||"");void apiFetch(`${base}/services/${service.id}/providers`).then(read).then(d=>setProviders(d.providers||[])).catch(e=>setMessage(e.message))},[base,service]);
  useEffect(()=>{if(!service||!provider)return;setSlot(null);void apiFetch(`${base}/slots?serviceId=${encodeURIComponent(service.id)}&providerId=${encodeURIComponent(provider.id)}&date=${date}`).then(read).then(d=>setSlots(d.slots||[])).catch(e=>setMessage(e.message))},[base,service,provider,date]);
  // Known context from a service/doctor page deep-link: preselect it and skip the matching steps.
  const wantedService=query.get("service")||"",wantedProvider=query.get("provider")||"";
  const [catalogServiceIds,setCatalogServiceIds]=useState<string[]|null>(null),applied=useRef({service:false,provider:false});
  useEffect(()=>{if(!wantedProvider||wantedService)return;void apiFetch(`${base}/catalog`).then(read).then(d=>setCatalogServiceIds((d.services||[]).filter((x:{providers:{id:string}[]})=>x.providers.some(p=>p.id===wantedProvider)).map((x:{id:string})=>x.id))).catch(()=>setCatalogServiceIds(null))},[base,wantedProvider,wantedService]);
  const visibleServices=useMemo(()=>catalogServiceIds&&!wantedService?services.filter(x=>catalogServiceIds.includes(x.id)):services,[services,catalogServiceIds,wantedService]);
  useEffect(()=>{if(applied.current.service||!services.length)return;const wanted=wantedService||(visibleServices.length===1&&wantedProvider&&catalogServiceIds?visibleServices[0].id:"");const match=wanted?services.find(x=>x.id===wanted):undefined;if(match){applied.current.service=true;setService(match);setStep(x=>Math.max(x,1))}},[services,visibleServices,wantedService,wantedProvider,catalogServiceIds]);
  useEffect(()=>{if(applied.current.provider||!wantedProvider||!service||!providers.length)return;const match=providers.find(x=>x.id===wantedProvider);if(match){applied.current.provider=true;setProvider(match);setStep(x=>Math.max(x,2))}},[providers,service,wantedProvider]);
  const next=async()=>{setMessage("");if(step===0&&!service)return setMessage(X.pickService);if(step===1&&!provider)return setMessage(X.pickProvider);if(needsModality&&step===2&&modeOptions.length>0&&!modality)return setMessage(X.pickMode);const slotStep=needsModality?3:2;if(step===slotStep&&!slot)return setMessage(X.pickSlot);const detailsStep=slotStep+1;if(step===detailsStep&&(!name.trim()||!contact.trim()))return setMessage(X.detailsRequired);const reviewStep=detailsStep+1;if(step===reviewStep){setBusy(true);try{await read(await apiFetch(`${base}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceId:service?.id,providerId:provider?.id,date,startsAt:slot?.startsAtTime,modality:modality||null})}));}catch(e){setMessage(e instanceof Error?e.message:X.unavailableSlot);return}finally{setBusy(false)}}setStep(x=>x+1)};
  const claim=async()=>{setBusy(true);setMessage("");try{const d=await read(await apiFetch(`${base}/appointments`,{method:"POST",headers:{"Content-Type":"application/json",...identityHeaders()},body:JSON.stringify({serviceId:service?.id,providerId:provider?.id,date,startsAt:slot?.startsAtTime,modality:modality||null,customerName:name.trim(),customerContact:contact.trim()})}));const checked=await read(await apiFetch(`${base}/confirmations/${encodeURIComponent(d.confirmation.reference)}`));setConfirmation(checked.confirmation);setStep(visibleSteps.length-1)}catch(e){setMessage(e instanceof Error?e.message:X.submitFailed)}finally{setBusy(false)}};
  if(siteType===undefined)return <main dir="rtl" data-booking-loading className="min-h-screen bg-[#f7f3ea]" aria-busy="true"/>;
  const medical=X.kind==="MEDICAL",accentText=medical?"text-[#5f7560]":"text-[#8d6b35]",pageStyle={"--form-accent":T.focus} as CSSProperties;
  const backLink=<Link to={`/site/${siteProjectId}`} className={`inline-flex min-h-11 items-center text-sm font-bold ${accentText}`}>{X.backToSite}</Link>;
  const header=X.siteHeader?<header data-booking-header className="flex items-center justify-between gap-3 border-b border-[#2b2a27]/10 pb-4"><Link to={`/site/${siteProjectId}`} className="flex min-w-0 items-center gap-3"><span aria-hidden className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#5f7560] font-black text-white">{(siteName||"•").trim().slice(0,1)}</span><b data-booking-site-name className="truncate text-base">{siteName}</b></Link>{backLink}</header>:backLink;
  const footer=X.siteHeader?<p className="mx-auto mt-4 flex max-w-3xl items-center justify-center gap-1 text-center text-xs text-[#2b2a27]/60">{siteName&&<>{siteName} · </>}<Link to={`/site/${siteProjectId}`} className="inline-flex min-h-11 items-center font-bold underline underline-offset-4">{X.backToSite}</Link></p>:null;
  const btn="inline-flex min-h-11 items-center justify-center rounded-xl px-5 py-3 font-bold";
  if(confirmation)return <main dir="rtl" data-booking-experience={X.kind} data-light-form style={pageStyle} className={`min-h-screen ${T.page} p-4 text-[#f5f0e5] sm:p-8`}><section className={`mx-auto mt-4 max-w-xl rounded-3xl ${T.card} p-6 text-[#292721] sm:mt-12 sm:p-8`}>{medical&&header}<p className={`${medical?"mt-6":""} text-sm ${medical?"font-bold text-[#5f7560]":"text-[#a98242]"}`}>{X.confirmedEyebrow}</p><h1 className="mt-2 flex flex-wrap items-baseline gap-x-2 text-xl font-black sm:text-2xl">کد پیگیری: <bdi dir="ltr" className="inline-block break-all">{confirmation.reference}</bdi></h1><dl className="mt-5 grid gap-1 leading-8"><div><dt className="sr-only">{X.rows.service}</dt><dd>{confirmation.service.name} با {confirmation.provider.name}</dd></div>{confirmation.modality&&<div><dt className="sr-only">{X.rows.mode}</dt><dd>{modalityLabel(confirmation.modality)}</dd></div>}<div><dt className="sr-only">{X.rows.time}</dt><dd data-appointment-when>{formatAppointmentWhen(confirmation.startsAt)}</dd></div></dl><div className="mt-7 flex flex-wrap gap-3"><Link className={`${btn} ${T.primary} text-white`} to={`/site/${siteProjectId}`}>{X.backToSite}</Link>{readPatientSession(siteProjectId||"")&&<Link data-patient-portal-link to={`/site/${siteProjectId}/patient/portal`} className={`${btn} border border-[#292721] text-sm`}>مشاهدهٔ در نوبت‌های من</Link>}{appProject&&<Link data-booking-portal-link to={`/learn/${appProject}/${siteProjectId}`} className={`${btn} border border-[#292721] text-sm`}>بازگشت به پرتال آموزشی</Link>}</div></section>{footer}</main>;
  const empty=servicesLoaded&&!services.length&&!message;
  const card=(selected:boolean)=>`min-h-11 rounded-2xl border p-4 text-right ${selected?T.accentSoft:"border-stone-200 bg-white"}`;
  const slotStep=needsModality?3:2,detailsStep=slotStep+1,reviewStep=detailsStep+1;
  const row=(label:string,value:string)=>value?<div className="flex flex-wrap justify-between gap-x-4 border-b border-stone-100 py-2 last:border-0"><dt className="text-stone-500">{label}</dt><dd className="font-bold">{value}</dd></div>:null;
  const field="mt-1 w-full min-h-11 rounded-xl border border-stone-300 bg-white p-3";
  return <main dir="rtl" data-booking-experience={X.kind} data-light-form style={pageStyle} className={`min-h-screen ${T.page} p-3 text-[#292721] sm:p-8`}><section className={`mx-auto max-w-3xl rounded-[2rem] ${T.card} p-5 sm:p-10`}>{header}<h1 className="mt-4 text-3xl font-black">{X.title}</h1>{empty?<div data-booking-empty className="mt-9 rounded-2xl border border-dashed border-stone-300 bg-white p-6 leading-8"><h2 className="text-xl font-black">{X.emptyTitle}</h2><p className="mt-2 text-stone-600">{X.emptyBody}</p><Link to={`/site/${siteProjectId}`} className={`${btn} ${T.primary} mt-5 text-white`}>{X.backToSite}</Link></div>:<>
    {servicesLoaded&&<><div data-stepper="mobile" className="mt-6 sm:hidden"><p className="text-sm font-black" data-step-progress>{X.progress(formatPersianNumber(step+1),formatPersianNumber(visibleSteps.length))}</p><div role="progressbar" aria-valuemin={1} aria-valuemax={visibleSteps.length} aria-valuenow={step+1} className="mt-2 h-1.5 overflow-hidden rounded-full bg-stone-200"><div className={`h-full rounded-full ${medical?"bg-[#5f7560]":"bg-[#a98242]"}`} style={{width:`${((step+1)/visibleSteps.length)*100}%`}}/></div></div>
    <ol data-stepper="desktop" className="mt-7 hidden gap-2 text-center text-xs sm:grid" style={{gridTemplateColumns:`repeat(${visibleSteps.length},minmax(0,1fr))`}}>{visibleSteps.map((label,i)=><li key={label} aria-current={i===step?"step":undefined} className={i<=step?`font-black ${T.accent}`:T.muted}><span className="mx-auto mb-1 grid h-7 w-7 place-items-center rounded-full border border-current">{formatPersianNumber(i+1)}</span>{label}</li>)}</ol></>}
    <div className="mt-8 min-h-48 pb-8"><h2 className="text-xl font-black">{visibleSteps[step]}</h2>
    {step===0&&<div className="mt-5 grid gap-3 sm:grid-cols-2">{visibleServices.map(x=><button aria-pressed={service?.id===x.id} className={card(service?.id===x.id)} onClick={()=>setService(x)} key={x.id}><b>{x.name}</b><span className="mt-1 block text-sm text-stone-500">{fa?formatPersianNumber(x.durationMinutes):x.durationMinutes} دقیقه{fa&&x.price?` · ${money(x.price)}`:""}</span></button>)}</div>}
    {step===1&&<div className="mt-5 grid gap-3 sm:grid-cols-2">{!providers.length&&<p data-booking-no-providers className="col-span-full text-sm text-stone-600">{X.noProviders}</p>}{providers.map(x=><button aria-pressed={provider?.id===x.id} className={card(provider?.id===x.id)} onClick={()=>setProvider(x)} key={x.id}><b>{x.name}</b></button>)}</div>}
    {needsModality&&step===2&&<div className="mt-5 flex flex-wrap gap-3">{modeOptions.length===0&&<p className="text-sm text-stone-600">{X.noModeNote}</p>}{modeOptions.map(x=><button aria-pressed={modality===x} onClick={()=>setModality(x)} className={`min-h-11 rounded-xl border px-5 py-3 ${modality===x?T.accentSoft:"border-stone-200 bg-white"}`} key={x}>{modalityLabel(x)}</button>)}</div>}
    {step===slotStep&&<><label htmlFor="booking-date" className="mt-5 block text-sm font-bold">{X.dateLabel}</label><input id="booking-date" className="mt-1 min-h-11 rounded-xl border border-stone-300 bg-white p-3" type="date" value={date} onChange={e=>setDate(e.target.value)}/>{fa&&date&&<p data-booking-date-fa className="mt-2 text-sm text-stone-600">{day(date)}</p>}<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{slots.map(x=><button aria-pressed={slot?.startsAt===x.startsAt} disabled={x.state==="full"||x.state==="cancelled"} onClick={()=>setSlot(x)} className={`min-h-11 rounded-xl border p-3 ${slot?.startsAt===x.startsAt?T.accentSoft:"border-stone-200 bg-white"} disabled:opacity-40`} key={x.startsAt}>{clock(x.startsAtTime)}<span className="block text-xs">{SLOT_STATE[x.state]}</span></button>)}</div></>}
    {step===detailsStep&&<div className="mt-5 grid gap-4"><label className="block text-sm font-bold">{X.nameField}<input className={field} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label className="block text-sm font-bold">{X.contactField}<input className={field} value={contact} onChange={e=>setContact(e.target.value)} inputMode="tel" autoComplete="tel" dir="ltr" style={{textAlign:"right"}}/></label></div>}
    {step===reviewStep&&<dl data-booking-review className="mt-5 rounded-2xl bg-white p-5 leading-8">{row(X.rows.service,service?.name||"")}{row(X.rows.provider,provider?.name||"")}{row(X.rows.mode,modality?modalityLabel(modality):"")}{row(X.rows.date,day(date))}{row(X.rows.time,slot?clock(slot.startsAtTime):"")}{row(X.rows.person,name.trim())}{row(X.rows.contact,fa?toPersianDigits(contact.trim()):contact.trim())}{row(X.rows.price,money(service?.price))}</dl>}</div>
    {message&&<p role="alert" className="mb-4 text-sm text-red-700">{message}</p>}
    <div className="flex justify-between gap-3"><button disabled={!step||busy} onClick={()=>setStep(x=>x-1)} className="min-h-11 rounded-xl border border-stone-300 px-5 py-3 disabled:opacity-40">قبلی</button>{step===visibleSteps.length-2?<button disabled={busy} onClick={claim} className={`${btn} ${medical?"bg-[#5f7560]":"bg-[#a98242]"} text-white`}>{busy?"در حال ثبت…":"تأیید و ثبت"}</button>:<button disabled={busy} onClick={next} className={`${btn} ${T.primary} text-white`}>{busy?"در حال بررسی…":"ادامه"}</button>}</div></>}
  </section>{footer}</main>;
}
