import { useEffect, useMemo, useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import { apiUrl } from "../lib/api";
import PublicCustomerAccountPanel from "../components/PublicCustomerAccountPanel";

type Field={id:string;name?:string;type:string;required?:boolean};
type Entity={id:string;name:string;fields:Field[]};
type Store={id:string;name:string;slug:string};
type Bootstrap={project:{id:string;name:string;locale:string};definition:{id:string;name:string;entities:Entity[]};principal?:{email:string;role:string}|null;commerceStores?:Store[]};
const call=(path:string,init:RequestInit={})=>fetch(apiUrl(path),{...init,credentials:"omit"});

export default function PublicBusinessAppPage(){
  const {projectId=""}=useParams(),[params,setParams]=useSearchParams();
  const [boot,setBoot]=useState<Bootstrap|null>(null),[entityId,setEntityId]=useState(""),[records,setRecords]=useState<any[]>([]),[form,setForm]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[accountMode,setAccountMode]=useState(false);
  const tokenKey=`loadder-public-app-token:${projectId}`,token=()=>sessionStorage.getItem(tokenKey)||"",headers=():Record<string,string>=>{const value=token();return value?{"X-Loadder-App-Token":value}:{}};
  async function bootstrap(){const r=await call(`/api/auth/public/apps/${projectId}/bootstrap`,{headers:headers()}),b=await r.json();if(!r.ok)throw new Error(b.code==="APP_SESSION_REQUIRED"?"برای ورود به این اپ به دعوت معتبر نیاز دارید.":"اپ در دسترس نیست.");setBoot(b);setEntityId(x=>x||b.definition.entities?.[0]?.id||"");}
  async function load(id=entityId){if(!id)return;const r=await call(`/api/auth/public/apps/${projectId}/data/${id}?limit=50`,{headers:headers()}),b=await r.json();if(r.ok)setRecords(b.records||[]);else setMessage(b.code==="APP_ACCESS_FORBIDDEN"?"شما اجازه مشاهده این بخش را ندارید.":"دریافت اطلاعات ناموفق بود.");}
  useEffect(()=>{(async()=>{try{const invite=params.get("invite");if(invite){const r=await call(`/api/auth/public/apps/${projectId}/invite/exchange`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:invite})}),b=await r.json();if(!r.ok)throw new Error("دعوت معتبر نیست یا قبلاً استفاده شده است.");sessionStorage.setItem(tokenKey,b.session.token);params.delete("invite");setParams(params,{replace:true});}await bootstrap();}catch(e){setMessage(e instanceof Error?e.message:"خطا در ورود")}finally{setLoading(false)}})()},[projectId]);
  useEffect(()=>{if(entityId&&!accountMode)load(entityId).catch(()=>{})},[entityId,accountMode]);
  const entity=useMemo(()=>boot?.definition.entities.find(x=>x.id===entityId)||boot?.definition.entities[0],[boot,entityId]);
  async function save(){if(!entity)return;const r=await call(`/api/auth/public/apps/${projectId}/data/${entity.id}`,{method:"POST",headers:{"Content-Type":"application/json",...headers()},body:JSON.stringify(form)}),b=await r.json();if(!r.ok){setMessage(b.code==="APP_ACCESS_FORBIDDEN"?"نقش شما اجازه ثبت اطلاعات در این بخش را ندارد.":b.message||"ذخیره ناموفق بود.");return}setForm({});setMessage("ذخیره شد.");await load(entity.id);}
  function logout(){sessionStorage.removeItem(tokenKey);location.reload();}
  if(loading)return <main dir="rtl" className="min-h-screen bg-[#08090b] p-8 text-center text-white/50">در حال بارگذاری اپ...</main>;
  if(!boot)return <main dir="rtl" className="min-h-screen bg-[#08090b] p-8 text-white"><div className="mx-auto mt-20 max-w-lg rounded-3xl border border-white/10 p-8 text-center"><h1 className="text-2xl font-semibold">Loadder App</h1><p className="mt-4 text-white/55">{message||"این اپ در دسترس نیست."}</p></div></main>;
  const customer=boot.principal?.role==="customer"&&token()&&Boolean(boot.commerceStores?.length);
  return <main dir="rtl" className="min-h-screen bg-[#08090b] text-white"><div className="mx-auto max-w-7xl px-5 py-6">
    <header className="mb-6 flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-5"><div><p className="text-xs text-white/35">POWERED BY LOADDER</p><h1 className="mt-1 text-3xl font-semibold">{boot.project.name}</h1><p className="mt-1 text-xs text-white/40">{boot.principal?`${boot.principal.email} · ${boot.principal.role}`:"Public access"}</p></div><div className="flex gap-2">{customer&&<button onClick={()=>setAccountMode(x=>!x)} className={`rounded-xl border px-4 py-2 text-xs ${accountMode?"border-white bg-white text-black":"border-white/10 text-white/70"}`}>{accountMode?"بازگشت به اپ":"حساب من"}</button>}{token()&&<button onClick={logout} className="rounded-xl border border-white/10 px-4 py-2 text-xs text-white/60">خروج</button>}</div></header>
    {accountMode&&customer?<PublicCustomerAccountPanel projectId={projectId} token={token()} stores={boot.commerceStores||[]}/>:<div className="grid gap-4 lg:grid-cols-[220px_1fr_320px]"><aside className="rounded-2xl border border-white/10 p-3">{boot.definition.entities.map(e=><button key={e.id} onClick={()=>setEntityId(e.id)} className={`mb-1 w-full rounded-xl px-3 py-2 text-right ${entity?.id===e.id?"bg-white/10":"text-white/55"}`}>{e.name}</button>)}</aside><section className="rounded-2xl border border-white/10 p-4"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold">{entity?.name}</h2><button onClick={()=>load()} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">به‌روزرسانی</button></div><div className="overflow-auto"><table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b border-white/10 text-white/40">{entity?.fields.map(f=><th key={f.id} className="px-3 py-3 text-right font-normal">{f.name||f.id}</th>)}</tr></thead><tbody>{records.map(r=><tr key={r.id} className="border-b border-white/5">{entity?.fields.map(f=><td key={f.id} className="px-3 py-3 text-white/70">{String(r[f.id]??"—")}</td>)}</tr>)}</tbody></table>{records.length===0&&<p className="py-12 text-center text-sm text-white/30">هنوز داده‌ای ثبت نشده است.</p>}</div></section><aside className="rounded-2xl border border-white/10 p-4"><h3 className="mb-4 font-semibold">ثبت اطلاعات</h3>{entity?.fields.map(f=><label key={f.id} className="mb-3 block"><span className="mb-1 block text-xs text-white/40">{f.name||f.id}{f.required?" *":""}</span><input value={form[f.id]||""} onChange={e=>setForm(x=>({...x,[f.id]:e.target.value}))} className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 outline-none"/></label>)}<button onClick={save} className="w-full rounded-xl bg-white py-2.5 text-sm font-semibold text-black">ذخیره</button>{message&&<p className="mt-3 text-xs text-white/50">{message}</p>}</aside></div>}
  </div></main>;
}
