import { useEffect,useState } from "react";
import { ArrowLeft,ArrowRight,Check,CircleNotch,MagicWand,Storefront } from "@phosphor-icons/react";
import { Link,useNavigate } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string;content:Record<string,unknown>};
type Setup={industry:string;channels:string[];storeName:string;currency:string;country:string;brandColor:string;shipping:string;payment:string;completed:boolean};
const industries=["کالای دیجیتال","زیبایی و سلامت","کالای پزشکی","ابزارآلات","کتاب و لوازم تحریر","وسایل خانه و آشپزخانه","اسباب‌بازی، کودک و نوزاد","مد و پوشاک","محصولات بومی و محلی","سایر"];
const channels=["فروشگاه حضوری","وب‌سایت","اینستاگرام","کانال تلگرام","واتساپ","دیوار","دیجی‌کالا","باسلام","فروش تلفنی"];
const seed:Setup={industry:"",channels:[],storeName:"",currency:"IRT",country:"IR",brandColor:"#6d5dfc",shipping:"manual",payment:"manual",completed:false};
async function json(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"خطا در ارتباط با فروشگاه");return d}
export default function StoreSetupWizardPage(){
 const nav=useNavigate(),[project,setProject]=useState<Project|null>(null),[step,setStep]=useState(0),[setup,setSetup]=useState<Setup>(seed),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void boot()},[]);
 async function boot(){try{setBusy(true);const data=await json(await apiFetch("/api/site-projects"));const p=(data.projects||[]).find((x:Project)=>String(x.siteType).toUpperCase()==="STORE")||data.projects?.[0];if(!p)throw new Error("ابتدا یک پروژه فروشگاهی بساز.");const detail=await json(await apiFetch(`/api/site-projects/${p.id}`));setProject(detail.project);const saved=detail.project?.content?.storeSetupV10 as Setup|undefined;if(saved)setSetup({...seed,...saved});else setSetup(s=>({...s,storeName:p.name||"فروشگاه من"}))}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 function toggle(c:string){setSetup(s=>({...s,channels:s.channels.includes(c)?s.channels.filter(x=>x!==c):[...s.channels,c]}))}
 const valid=[!!setup.industry,setup.channels.length>0,!!setup.storeName.trim(),!!setup.currency&&!!setup.country,true][step];
 async function finish(){if(!project)return;try{setBusy(true);const value={...setup,completed:true};const r=await json(await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:{...project.content,storeSetupV10:value}})}));setProject(r.project);setSetup(value);nav("/dashboard/websites/admin")}catch(e){setMessage(e instanceof Error?e.message:"ذخیره انجام نشد")}finally{setBusy(false)}}
 const progress=((step+1)/5)*100;
 return <main dir="rtl" className="min-h-screen bg-[#f7f8fc] text-slate-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-4"><Link to="/dashboard/websites" className="rounded-xl border p-2"><ArrowRight/></Link><div className="text-center"><div className="text-xs text-slate-400">راه‌اندازی فروشگاه · مرحله {step+1} از ۵</div><b>Loadder Commerce Setup</b></div><Storefront size={26} className="text-violet-600"/></div></header><div className="mx-auto max-w-3xl px-5 py-10"><div className="mb-8 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-violet-600 transition-all" style={{width:`${progress}%`}}/></div>{busy&&<div className="mb-4 flex items-center gap-2 rounded-xl bg-white p-3 text-sm"><CircleNotch className="animate-spin"/> در حال آماده‌سازی...</div>}{message&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</div>}
 {step===0&&<Step title="زمینه کاری" sub="فروشگاه شما بیشتر در چه حوزه‌ای فعالیت می‌کند؟"><div className="grid gap-3 sm:grid-cols-2">{industries.map(x=><Choice key={x} active={setup.industry===x} onClick={()=>setSetup({...setup,industry:x})}>{x}</Choice>)}</div></Step>}
 {step===1&&<Step title="کانال‌های فروش" sub="در حال حاضر محصولاتتان را از چه مسیرهایی معرفی یا می‌فروشید؟"><div className="grid gap-3 sm:grid-cols-2">{channels.map(x=><Choice key={x} active={setup.channels.includes(x)} onClick={()=>toggle(x)} multi>{x}</Choice>)}</div></Step>}
 {step===2&&<Step title="هویت فروشگاه" sub="نام و رنگ پایه‌ای که فروشگاه اولیه با آن ساخته شود."><Field label="نام فروشگاه"><input value={setup.storeName} onChange={e=>setSetup({...setup,storeName:e.target.value})} className="input-light"/></Field><Field label="رنگ برند"><div className="flex gap-3"><input type="color" value={setup.brandColor} onChange={e=>setSetup({...setup,brandColor:e.target.value})} className="h-12 w-20 rounded-xl border bg-white p-1"/><input value={setup.brandColor} onChange={e=>setSetup({...setup,brandColor:e.target.value})} className="input-light flex-1" dir="ltr"/></div></Field></Step>}
 {step===3&&<Step title="بازار و ارز" sub="این اطلاعات بعداً برای پرداخت، مالیات، قیمت و نسخه بین‌المللی استفاده می‌شود."><div className="grid gap-4 sm:grid-cols-2"><Field label="کشور"><select value={setup.country} onChange={e=>setSetup({...setup,country:e.target.value})} className="input-light"><option value="IR">ایران</option><option value="AE">امارات</option><option value="TR">ترکیه</option><option value="DE">آلمان</option><option value="US">آمریکا</option></select></Field><Field label="ارز"><select value={setup.currency} onChange={e=>setSetup({...setup,currency:e.target.value})} className="input-light"><option value="IRT">تومان</option><option value="IRR">ریال</option><option value="AED">AED</option><option value="USD">USD</option><option value="EUR">EUR</option></select></Field></div></Step>}
 {step===4&&<Step title="فعال‌سازی فروش" sub="درگاه و ارسال را الان می‌توانی به‌صورت آزمایشی تعیین کنی؛ Provider واقعی بعداً قابل اتصال است."><div className="grid gap-4 sm:grid-cols-2"><Field label="روش ارسال"><select value={setup.shipping} onChange={e=>setSetup({...setup,shipping:e.target.value})} className="input-light"><option value="manual">ارسال دستی / تست</option><option value="pickup">تحویل حضوری</option><option value="provider">Provider حمل‌ونقل</option></select></Field><Field label="روش پرداخت"><select value={setup.payment} onChange={e=>setSetup({...setup,payment:e.target.value})} className="input-light"><option value="manual">پرداخت آزمایشی</option><option value="iran">درگاه ایرانی</option><option value="international">درگاه بین‌المللی</option></select></Field></div><div className="mt-6 rounded-2xl bg-violet-50 p-5 text-sm text-violet-900"><div className="flex items-center gap-2 font-black"><MagicWand/> بعد از تکمیل</div><p className="mt-2 leading-7">لودر وارد پنل فروشگاه می‌شود؛ از آنجا می‌توانی محصول، سفارش، موجودی، طراحی سایت، دامنه، ارسال، پرداخت و مراحل افزایش فروش را مدیریت کنی.</p></div></Step>}
 <div className="mt-8 flex items-center justify-between"><button disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="rounded-xl border bg-white px-5 py-3 text-sm font-bold disabled:opacity-30">مرحله قبل</button>{step<4?<button disabled={!valid} onClick={()=>setStep(s=>s+1)} className="flex items-center gap-2 rounded-xl bg-violet-600 px-6 py-3 text-sm font-black text-white disabled:opacity-30">مرحله بعد <ArrowLeft/></button>:<button disabled={busy} onClick={()=>void finish()} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-6 py-3 text-sm font-black text-white"><Check/> ساخت پنل فروشگاه</button>}</div></div></main>}
function Step({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><h1 className="text-2xl font-black">{title}</h1><p className="mt-2 mb-7 text-sm leading-7 text-slate-500">{sub}</p>{children}</section>}
function Choice({active,onClick,children,multi}:{active:boolean;onClick:()=>void;children:React.ReactNode;multi?:boolean}){return <button onClick={onClick} className={`flex min-h-16 items-center justify-between rounded-2xl border px-5 text-right transition ${active?"border-violet-500 bg-violet-50 text-violet-900":"border-slate-200 bg-slate-50 hover:border-slate-300"}`}><span className="font-bold">{children}</span><span className={`grid h-6 w-6 place-items-center border ${multi?"rounded-md":"rounded-full"} ${active?"border-violet-600 bg-violet-600 text-white":"border-slate-400"}`}>{active&&<Check size={14}/>}</span></button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mb-5 block text-sm font-bold text-slate-700">{label}<div className="mt-2">{children}</div></label>}
