import { useEffect,useState } from "react";
import { ArrowLeft,ArrowRight,Check,CircleNotch,MagicWand,Storefront } from "@phosphor-icons/react";
import { Link,useNavigate } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string;content:Record<string,unknown>};
type Setup={industry:string;channels:string[];productCount:string;salesGoal:string;learning:string;storeName:string;currency:string;country:string;brandColor:string;shipping:string;payment:string;completed:boolean};
const industries=["مد و پوشاک","آرایشی و بهداشتی","کالای دیجیتال","غذا و خوراکی","خانه و آشپزخانه","ابزار و خودرو","طلا و زیورآلات","هنر و صنایع‌دستی","مبل و دکوراسیون","کودک و نوزاد","پت‌شاپ","آموزش و محتوا","ورزش و سفر","سلامت و پزشکی","لوازم تحریر و اداری","کتاب و فرهنگ","خدمات تخصصی","سایر"];
const channels=["فروش ندارم","فروشگاه حضوری","سایت","اینستاگرام","کانال تلگرام","واتساپ","دیوار","دیجی‌کالا","ترب","باسلام","فروش تلفنی","سایر موارد"];
const productCounts=["کمتر از ۱۰۰ عدد","بین ۱۰۰ تا ۱٬۰۰۰ عدد","حداقل ۱٬۰۰۰ عدد","هنوز محصول آماده ندارم"];
const salesGoals=["کمتر از ۱۰۰ میلیون تومان","بین ۱۰۰ تا ۵۰۰ میلیون تومان","بین ۵۰۰ میلیون تا ۱ میلیارد تومان","حداقل ۱ میلیارد تومان"];
const learningOptions=["ویدئوهای آموزشی را می‌بینم","مشاوره تلفنی می‌خواهم","نیازی به آموزش ندارم"];
const seed:Setup={industry:"",channels:[],productCount:"",salesGoal:"",learning:"",storeName:"",currency:"IRT",country:"IR",brandColor:"#6d5dfc",shipping:"manual",payment:"manual",completed:false};
async function json(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"خطا در ارتباط با فروشگاه");return d}
export default function StoreSetupWizardPage(){
 const nav=useNavigate(),[project,setProject]=useState<Project|null>(null),[step,setStep]=useState(0),[setup,setSetup]=useState<Setup>(seed),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void boot()},[]);
 async function boot(){try{setBusy(true);const data=await json(await apiFetch("/api/site-projects"));const p=(data.projects||[]).find((x:Project)=>String(x.siteType).toUpperCase()==="STORE")||data.projects?.[0];if(!p)throw new Error("ابتدا یک پروژه فروشگاهی بساز.");const detail=await json(await apiFetch(`/api/site-projects/${p.id}`));setProject(detail.project);const saved=detail.project?.content?.storeSetupV10 as Setup|undefined;if(saved)setSetup({...seed,...saved});else setSetup(s=>({...s,storeName:p.name||"فروشگاه من"}))}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 function toggle(c:string){setSetup(s=>({...s,channels:s.channels.includes(c)?s.channels.filter(x=>x!==c):[...s.channels,c]}))}
 const valid=[!!setup.industry,setup.channels.length>0,!!setup.productCount,!!setup.salesGoal,!!setup.learning,!!setup.storeName.trim(),!!setup.currency&&!!setup.country,true][step];
 async function finish(){if(!project)return;try{setBusy(true);const value={...setup,completed:true};const r=await json(await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:{...project.content,storeSetupV10:value}})}));setProject(r.project);setSetup(value);nav("/dashboard/websites/admin",{state:{created:true}})}catch(e){setMessage(e instanceof Error?e.message:"ذخیره انجام نشد")}finally{setBusy(false)}}
 const progress=((step+1)/8)*100;
 return <main dir="rtl" className="min-h-screen bg-white text-slate-900"><header className="border-b"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-4"><Link to="/dashboard/websites" className="rounded-xl border p-2"><ArrowRight/></Link><div className="text-center"><div className="text-xs text-slate-400">ایجاد فروشگاه · مرحله {step+1} از ۸</div><b>Loadder Commerce</b></div><Storefront size={26} className="text-violet-600"/></div></header><div className="mx-auto max-w-3xl px-5 py-9"><div className="mb-8 h-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-violet-600 transition-all" style={{width:`${progress}%`}}/></div>{busy&&<div className="mb-4 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm"><CircleNotch className="animate-spin"/> در حال آماده‌سازی...</div>}{message&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</div>}
 {step===0&&<Step title="کدام گروه به کار شما مرتبط‌تر است؟" sub="لودر بر اساس حوزه شما ساختار اولیه فروشگاه، پیشنهاد سکشن‌ها و تنظیمات Commerce را آماده می‌کند."><Grid>{industries.map(x=><Choice key={x} active={setup.industry===x} onClick={()=>setSetup({...setup,industry:x})}>{x}</Choice>)}</Grid></Step>}
 {step===1&&<Step title="محصولات خود را چطور می‌فروشید؟" sub="هر تعداد مسیر که الان استفاده می‌کنید انتخاب کنید."><Grid>{channels.map(x=><Choice key={x} active={setup.channels.includes(x)} onClick={()=>toggle(x)} multi>{x}</Choice>)}</Grid></Step>}
 {step===2&&<Step title="چه تعداد محصول دارید؟" sub="برای آماده‌سازی Catalog، Import و نوع مدیریت محصول به این اطلاعات نیاز داریم."><Stack>{productCounts.map(x=><Choice key={x} active={setup.productCount===x} onClick={()=>setSetup({...setup,productCount:x})}>{x}</Choice>)}</Stack></Step>}
 {step===3&&<Step title="می‌خواهید به چقدر فروش ماهانه برسید؟" sub="این عدد فقط برای شخصی‌سازی برنامه رشد و داشبورد شما استفاده می‌شود."><Stack>{salesGoals.map(x=><Choice key={x} active={setup.salesGoal===x} onClick={()=>setSetup({...setup,salesGoal:x})}>{x}</Choice>)}</Stack></Step>}
 {step===4&&<Step title="کدام روش آموزشی را ترجیح می‌دهید؟" sub="بعداً می‌توانیم مسیر راه‌اندازی را با توجه به انتخاب شما کوتاه یا آموزشی کنیم."><Stack>{learningOptions.map(x=><Choice key={x} active={setup.learning===x} onClick={()=>setSetup({...setup,learning:x})}>{x}</Choice>)}</Stack></Step>}
 {step===5&&<Step title="هویت فروشگاه" sub="نام و رنگ اولیه را انتخاب کنید؛ همه‌چیز بعداً در Visual Studio قابل تغییر است."><Field label="نام فروشگاه"><input value={setup.storeName} onChange={e=>setSetup({...setup,storeName:e.target.value})} className="input-light"/></Field><Field label="رنگ برند"><div className="flex gap-3"><input type="color" value={setup.brandColor} onChange={e=>setSetup({...setup,brandColor:e.target.value})} className="h-12 w-20 rounded-xl border bg-white p-1"/><input value={setup.brandColor} onChange={e=>setSetup({...setup,brandColor:e.target.value})} className="input-light flex-1" dir="ltr"/></div></Field></Step>}
 {step===6&&<Step title="بازار و ارز" sub="کشور و ارز پایه؛ برای قیمت، پرداخت، ارسال و نسخه بین‌المللی استفاده می‌شود."><div className="grid gap-4 sm:grid-cols-2"><Field label="کشور"><select value={setup.country} onChange={e=>setSetup({...setup,country:e.target.value})} className="input-light"><option value="IR">ایران</option><option value="AE">امارات</option><option value="TR">ترکیه</option><option value="DE">آلمان</option><option value="US">آمریکا</option></select></Field><Field label="ارز"><select value={setup.currency} onChange={e=>setSetup({...setup,currency:e.target.value})} className="input-light"><option value="IRT">تومان</option><option value="IRR">ریال</option><option value="AED">AED</option><option value="USD">USD</option><option value="EUR">EUR</option></select></Field></div></Step>}
 {step===7&&<Step title="فعال‌سازی فروش" sub="تنظیم اولیه ارسال و پرداخت را مشخص کنید؛ Provider واقعی بعداً از پنل فروشگاه قابل اتصال است."><div className="grid gap-4 sm:grid-cols-2"><Field label="روش ارسال"><select value={setup.shipping} onChange={e=>setSetup({...setup,shipping:e.target.value})} className="input-light"><option value="manual">ارسال دستی / تست</option><option value="pickup">تحویل حضوری</option><option value="provider">Provider حمل‌ونقل</option></select></Field><Field label="روش پرداخت"><select value={setup.payment} onChange={e=>setSetup({...setup,payment:e.target.value})} className="input-light"><option value="manual">پرداخت آزمایشی</option><option value="iran">درگاه ایرانی</option><option value="international">درگاه بین‌المللی</option></select></Field></div><div className="mt-6 rounded-2xl bg-violet-50 p-5 text-sm text-violet-900"><div className="flex items-center gap-2 font-black"><MagicWand/> فروشگاه اولیه آماده می‌شود</div><p className="mt-2 leading-7">بعد از ساخت، مستقیم وارد مرکز کنترل می‌شوید؛ محصول، سفارش، طراحی، دامنه، ارسال، پرداخت و رشد فروش از همان‌جا مدیریت می‌شود.</p></div></Step>}
 <div className="mt-8 flex items-center justify-between"><button disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="rounded-xl border bg-white px-5 py-3 text-sm font-bold disabled:opacity-30">مرحله قبل</button>{step<7?<button disabled={!valid} onClick={()=>setStep(s=>s+1)} className="flex items-center gap-2 rounded-xl bg-violet-600 px-6 py-3 text-sm font-black text-white disabled:opacity-30">مرحله بعد <ArrowLeft/></button>:<button disabled={busy} onClick={()=>void finish()} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-6 py-3 text-sm font-black text-white"><Check/> ایجاد فروشگاه</button>}</div></div></main>}
function Step({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><h1 className="text-2xl font-black">{title}</h1><p className="mt-2 mb-7 text-sm leading-7 text-slate-500">{sub}</p>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-3 sm:grid-cols-2">{children}</div>}
function Stack({children}:{children:React.ReactNode}){return <div className="space-y-3">{children}</div>}
function Choice({active,onClick,children,multi}:{active:boolean;onClick:()=>void;children:React.ReactNode;multi?:boolean}){return <button onClick={onClick} className={`flex min-h-16 w-full items-center justify-between rounded-2xl border px-5 text-right transition ${active?"border-violet-500 bg-violet-50 text-violet-900":"border-slate-200 bg-white hover:border-slate-300"}`}><span className="font-bold">{children}</span><span className={`grid h-6 w-6 place-items-center border ${multi?"rounded-md":"rounded-full"} ${active?"border-violet-600 bg-violet-600 text-white":"border-slate-300"}`}>{active&&<Check size={14}/>}</span></button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mb-5 block text-sm font-bold text-slate-700">{label}<div className="mt-2">{children}</div></label>}
