import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Minus, Plus, ShoppingCart } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string};
type Variant={id:string;sku:string;inventoryQuantity:number};
type Product={id:string;name:string;currency:string;basePriceMinor:number;status:string;variants:Variant[]};
type CartItem={variantId:string;productName:string;sku:string;quantity:number;unitPriceMinor:number;lineTotalMinor:number};
type Cart={id:string;currency:string;subtotalMinor:number;discountMinor:number;shippingMinor:number;totalMinor:number;items:CartItem[];status:string};
type Order={id:string;status:string;paymentStatus:string;totalMinor:number;currency:string};

async function read(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"عملیات فروشگاه ناموفق بود");return d}
const fmt=(n:number,c:string)=>new Intl.NumberFormat("fa-IR",{style:"currency",currency:c||"USD",maximumFractionDigits:2}).format((n||0)/100);

export default function StorefrontTestPage(){
 const[project,setProject]=useState<Project|null>(null),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Cart|null>(null),[order,setOrder]=useState<Order|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{void boot()},[]);
 const itemCount=useMemo(()=>cart?.items.reduce((n,i)=>n+i.quantity,0)||0,[cart]);
 async function boot(){try{const p=await read(await apiFetch("/api/site-projects"));const store=(p.projects||[]).find((x:Project)=>String(x.siteType).toUpperCase()==="STORE");if(!store){setMessage("پروژه فروشگاهی پیدا نشد.");return}setProject(store);const catalog=await read(await apiFetch(`/api/stores/${store.id}/products`));setProducts((catalog.products||[]).filter((x:Product)=>x.status==="ACTIVE"))}catch(e){setMessage(e instanceof Error?e.message:"خطا")}}
 async function ensureCart(currency:string){if(cart&&cart.status==="ACTIVE")return cart; if(!project)throw new Error("فروشگاه آماده نیست");const d=await read(await apiFetch(`/api/stores/${project.id}/carts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currency,email:"smoke-test@loadder.local"})}));setCart(d.cart);return d.cart as Cart}
 async function add(product:Product){const v=product.variants.find(x=>x.inventoryQuantity>0);if(!v)return setMessage("این محصول موجودی ندارد.");setBusy(true);try{const c=await ensureCart(product.currency);if(c.currency!==product.currency)throw new Error("برای این تست، محصولات با ارز یکسان انتخاب کن.");const d=await read(await apiFetch(`/api/commerce/carts/${c.id}/items`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({variantId:v.id,quantity:1})}));setCart(d.cart);setMessage("به سبد اضافه شد.")}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 async function qty(item:CartItem,next:number){if(!cart)return;setBusy(true);try{const d=await read(await apiFetch(`/api/commerce/carts/${cart.id}/items/${item.variantId}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({quantity:Math.max(0,next)})}));setCart(d.cart)}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 async function checkout(){if(!cart||!cart.items.length)return;setBusy(true);try{const d=await read(await apiFetch(`/api/commerce/carts/${cart.id}/checkout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:"smoke-test@loadder.local",paymentProvider:"MANUAL_TEST",shippingAddress:{country:"TEST",city:"Loadder"}})}));setOrder(d.order);setCart(null);setMessage("Checkout واقعی انجام شد و Order ساخته شد؛ هیچ پرداخت خارجی اجرا نشد.");await boot()}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 return <main dir="rtl" className="min-h-screen bg-[#f5f6f8] text-slate-900"><header className="sticky top-0 z-20 flex items-center justify-between border-b bg-white px-5 py-4"><div className="flex items-center gap-3"><Link to="/dashboard/websites/commerce" className="rounded-xl border p-2"><ArrowRight/></Link><div><b>{project?.name||"فروشگاه آزمایشی"}</b><div className="text-xs text-slate-400">Storefront E2E Test</div></div></div><div className="flex items-center gap-2 rounded-xl bg-slate-100 px-4 py-2 text-sm"><ShoppingCart/> {itemCount} کالا</div></header>
 <div className="mx-auto grid max-w-7xl gap-6 p-5 lg:grid-cols-[1fr_360px]"><section><div className="mb-5 rounded-3xl bg-slate-900 p-8 text-white"><div className="text-sm text-violet-300">Loadder Commerce</div><h1 className="mt-2 text-3xl font-black">تست واقعی مسیر خرید</h1><p className="mt-3 text-sm text-white/60">محصول → سبد → Checkout → Order → کاهش موجودی</p></div>{message&&<div className="mb-4 rounded-xl border bg-white p-3 text-sm">{message}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map(p=>{const v=p.variants[0];return <article key={p.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="aspect-[4/3] rounded-xl bg-gradient-to-br from-slate-100 to-slate-200"/><h2 className="mt-4 font-bold">{p.name}</h2><div className="mt-1 text-xs text-slate-400">SKU: {v?.sku||"—"}</div><div className="mt-4 flex items-end justify-between"><div><b>{fmt(p.basePriceMinor,p.currency)}</b><div className={`mt-1 text-xs ${Number(v?.inventoryQuantity)>0?"text-emerald-600":"text-rose-500"}`}>{v?.inventoryQuantity||0} موجود</div></div><button disabled={busy||!v||v.inventoryQuantity<1} onClick={()=>void add(p)} className="rounded-xl bg-violet-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-30">افزودن</button></div></article>})}</div>{!products.length&&<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-slate-400">اول در Commerce Manager یک محصول ACTIVE ثبت کن.</div>}</section>
 <aside className="h-fit rounded-2xl border bg-white p-5 shadow-sm lg:sticky lg:top-24"><h2 className="flex items-center gap-2 font-black"><ShoppingCart/> سبد خرید واقعی</h2><div className="mt-4 space-y-3">{cart?.items.map(i=><div key={i.variantId} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-3"><div><b className="text-sm">{i.productName}</b><div className="text-xs text-slate-400">{i.sku}</div></div><b className="text-sm">{fmt(i.lineTotalMinor,cart.currency)}</b></div><div className="mt-3 flex items-center gap-2"><button disabled={busy} onClick={()=>void qty(i,i.quantity-1)} className="rounded-lg border bg-white p-1"><Minus/></button><span className="min-w-8 text-center">{i.quantity}</span><button disabled={busy} onClick={()=>void qty(i,i.quantity+1)} className="rounded-lg border bg-white p-1"><Plus/></button></div></div>)}{!cart?.items.length&&<p className="py-8 text-center text-sm text-slate-400">سبد خالی است.</p>}</div>{cart&&<div className="mt-4 border-t pt-4 text-sm"><div className="flex justify-between"><span>جمع</span><span>{fmt(cart.subtotalMinor,cart.currency)}</span></div><div className="mt-2 flex justify-between font-black"><span>قابل پرداخت</span><span>{fmt(cart.totalMinor,cart.currency)}</span></div><button disabled={busy||!cart.items.length} onClick={()=>void checkout()} className="mt-4 w-full rounded-xl bg-slate-900 p-3 font-bold text-white disabled:opacity-30">Checkout آزمایشی</button></div>}{order&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><b>Order ساخته شد</b><div dir="ltr" className="mt-1 text-xs">{order.id}</div><div className="mt-2">{fmt(order.totalMinor,order.currency)} · {order.status} · {order.paymentStatus}</div></div>}</aside></div></main>
}
