import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Desktop, DeviceMobile, DeviceTablet, FloppyDisk, Image, Package, ShoppingCart, Storefront, UploadSimple } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string;content:Record<string,unknown>};
type Variant={id:string;sku:string;priceMinor:number|null;inventoryQuantity:number;imageUrl?:string|null;active:boolean};
type Product={id:string;name:string;brand?:string|null;status:string;currency:string;basePriceMinor:number;variants:Variant[]};
type Cart={id:string;currency:string;totalMinor:number;items:{quantity:number}[]};
type Section="header"|"hero"|"banner"|"products"|"trust"|"footer";
type Theme={
 accent:string;surface:string;cardRadius:number;productColumns:number;
 header:{visible:boolean;storeName:string;logoUrl:string;showSearch:boolean;showAccount:boolean;showCart:boolean};
 hero:{visible:boolean;title:string;subtitle:string;buttonText:string;imageUrl:string;height:number;align:"right"|"center"|"left"};
 banner:{visible:boolean;title:string;subtitle:string;buttonText:string;imageUrl:string;height:number};
 products:{visible:boolean;title:string;showBrand:boolean;showSku:boolean;showStock:boolean};
 trust:{visible:boolean;title:string};
 footer:{visible:boolean;title:string;subtitle:string};
};
const seed:Theme={accent:"#6d5dfc",surface:"#f6f7fb",cardRadius:22,productColumns:4,header:{visible:true,storeName:"فروشگاه شما",logoUrl:"",showSearch:true,showAccount:true,showCart:true},hero:{visible:true,title:"فروشگاهی که برای فروش ساخته شده",subtitle:"محصولات واقعی، موجودی واقعی و تجربه خرید یکپارچه",buttonText:"مشاهده محصولات",imageUrl:"",height:430,align:"right"},banner:{visible:true,title:"پیشنهاد ویژه این هفته",subtitle:"برای این بنر کمپین، تخفیف یا محصول ویژه تعریف کن",buttonText:"مشاهده پیشنهاد",imageUrl:"",height:220},products:{visible:true,title:"محصولات فروشگاه",showBrand:true,showSku:true,showStock:true},trust:{visible:true,title:"خرید مطمئن و سریع"},footer:{visible:true,title:"فروشگاه شما",subtitle:"تمام حقوق محفوظ است."}};
async function readJson(r:Response){const t=await r.text();return t?JSON.parse(t):{}}
const money=(minor:number,currency:string)=>new Intl.NumberFormat("fa-IR",{style:"currency",currency:currency==="IRT"?"IRR":currency||"USD",maximumFractionDigits:0}).format(currency==="IRT"?minor*10:minor/100);

export default function StoreWebsiteStudioPageV4(){
 const[project,setProject]=useState<Project|null>(null),[products,setProducts]=useState<Product[]>([]),[theme,setTheme]=useState<Theme>(seed),[selected,setSelected]=useState<Section>("hero"),[viewport,setViewport]=useState<"desktop"|"tablet"|"mobile">("desktop"),[cart,setCart]=useState<Cart|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null),uploadTarget=useRef<"logo"|"hero"|"banner">("hero");
 useEffect(()=>{void load()},[]);
 async function load(){try{setBusy(true);const rp=await apiFetch("/api/site-projects");const pd=await readJson(rp);if(!rp.ok)throw new Error(pd.message||"پروژه‌ها بارگذاری نشدند");const p=(pd.projects||[]).find((x:Project)=>String(x.siteType).toUpperCase()==="STORE")||pd.projects?.[0];if(!p)throw new Error("پروژه فروشگاهی پیدا نشد");const rr=await apiFetch(`/api/site-projects/${p.id}`);const rd=await readJson(rr);if(!rr.ok)throw new Error(rd.message||"پروژه باز نشد");setProject(rd.project);const saved=rd.project?.content?.commerceStudioV4 as Theme|undefined;if(saved)setTheme({...seed,...saved,header:{...seed.header,...saved.header},hero:{...seed.hero,...saved.hero},banner:{...seed.banner,...saved.banner},products:{...seed.products,...saved.products},trust:{...seed.trust,...saved.trust},footer:{...seed.footer,...saved.footer}});const rc=await apiFetch(`/api/stores/${p.id}/products`);const cd=await readJson(rc);if(rc.ok)setProducts(cd.products||[])}catch(e){setMessage(e instanceof Error?e.message:"خطا در بارگذاری")}finally{setBusy(false)}}
 const width=viewport==="desktop"?"1180px":viewport==="tablet"?"780px":"390px";
 const activeProducts=useMemo(()=>products.filter(p=>p.status==="ACTIVE"),[products]);
 async function save(){if(!project)return;setBusy(true);try{const r=await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:{...project.content,commerceStudioV4:theme}})});const d=await readJson(r);if(!r.ok)throw new Error(d.message||"ذخیره نشد");setProject(d.project);setMessage("طراحی ذخیره شد")}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 async function upload(file:File){if(!project)return;if(!file.type.startsWith("image/"))return setMessage("فقط تصویر قابل قبول است");if(file.size>3*1024*1024)return setMessage("حداکثر حجم تصویر ۳ مگابایت است");setBusy(true);try{const dataUrl=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error("خواندن تصویر ناموفق بود"));r.readAsDataURL(file)});const kind=uploadTarget.current==="logo"?"logo":uploadTarget.current==="hero"?"hero":"banner";const r=await apiFetch(`/api/site-projects/${project.id}/assets`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,name:file.name,url:dataUrl,altText:file.name})});const d=await readJson(r);if(!r.ok)throw new Error(d.message||"آپلود ناموفق بود");const url=d.asset?.url||dataUrl;if(uploadTarget.current==="logo")setTheme(t=>({...t,header:{...t.header,logoUrl:url}}));if(uploadTarget.current==="hero")setTheme(t=>({...t,hero:{...t.hero,imageUrl:url}}));if(uploadTarget.current==="banner")setTheme(t=>({...t,banner:{...t.banner,imageUrl:url}}));setMessage("تصویر روی همان بخش اعمال شد")}catch(e){setMessage(e instanceof Error?e.message:"خطا در آپلود")}finally{setBusy(false)}}
 function pick(target:"logo"|"hero"|"banner"){uploadTarget.current=target;fileRef.current?.click()}
 async function ensureCart(){if(cart)return cart;if(!project)throw new Error("پروژه آماده نیست");const r=await apiFetch(`/api/stores/${project.id}/carts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currency:activeProducts[0]?.currency||"USD"})});const d=await readJson(r);if(!r.ok)throw new Error(d.message||"سبد ساخته نشد");setCart(d.cart);return d.cart as Cart}
 async function addToCart(p:Product){const v=p.variants?.find(x=>x.active);if(!v)return setMessage("Variant فعال ندارد");try{const c=await ensureCart();const r=await apiFetch(`/api/commerce/carts/${c.id}/items`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({variantId:v.id,quantity:1})});const d=await readJson(r);if(!r.ok)throw new Error(d.message||"به سبد اضافه نشد");setCart(d.cart)}catch(e){setMessage(e instanceof Error?e.message:"خطا")}}
 const sectionNames:Record<Section,string>={header:"هدر سایت",hero:"هیرو اصلی",banner:"بنر تبلیغاتی",products:"محصولات",trust:"اعتمادسازی",footer:"فوتر"};
 return <main dir="rtl" className="h-screen overflow-hidden bg-[#0a0f17] text-white"><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=""}}/>
  <header className="flex h-16 items-center justify-between border-b border-white/10 bg-[#0d131d] px-4"><div className="flex gap-2"><Link to="/dashboard" className="rounded-xl border border-white/10 p-2"><ArrowRight/></Link><button onClick={()=>void save()} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-bold"><FloppyDisk/>ذخیره</button><Link to="/dashboard/websites/commerce" className="rounded-xl border border-white/10 px-4 py-2 text-sm">مدیریت محصولات</Link></div><div className="flex rounded-xl bg-white/5 p-1"><button onClick={()=>setViewport("desktop")} className="p-2"><Desktop/></button><button onClick={()=>setViewport("tablet")} className="p-2"><DeviceTablet/></button><button onClick={()=>setViewport("mobile")} className="p-2"><DeviceMobile/></button></div><div><div className="text-[10px] text-white/40">Store Studio V4</div><b>{project?.name||"Store Builder"}</b></div></header>
  <div className="grid h-[calc(100vh-64px)] grid-cols-[250px_minmax(0,1fr)_330px]">
   <aside className="overflow-y-auto border-l border-white/10 bg-[#101722] p-4"><b className="text-sm">بخش‌های سایت</b><p className="mt-1 text-[11px] leading-5 text-white/40">هر بخش اسم و تنظیمات مستقل دارد؛ هدر، هیرو و بنر دیگر با هم قاطی نمی‌شوند.</p><div className="mt-4 space-y-2">{(["header","hero","banner","products","trust","footer"] as Section[]).map(s=><button key={s} onClick={()=>setSelected(s)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-xs ${selected===s?"border-violet-500 bg-violet-500/10":"border-white/10"}`}><span>{sectionNames[s]}</span><span className="text-white/30">ویرایش</span></button>)}</div><div className="mt-5 rounded-xl border border-white/10 p-3"><div className="flex items-center gap-2 text-xs"><Package/> Catalog واقعی</div><div className="mt-2 text-[11px] text-white/45">{activeProducts.length} محصول فعال</div></div>{message&&<div className="mt-4 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-6">{message}</div>}</aside>
   <section className="overflow-auto bg-[#252c38] p-7"><div className="mx-auto min-h-full overflow-hidden bg-white text-slate-900 shadow-2xl" style={{width,maxWidth:"100%"}}>
    {theme.header.visible&&<div onClick={()=>setSelected("header")} className={`relative flex items-center gap-5 border-b px-7 py-4 ${selected==="header"?"ring-2 ring-inset ring-violet-500":""}`}>{theme.header.logoUrl?<img src={theme.header.logoUrl} className="h-10 w-10 rounded-lg object-contain"/>:<button onClick={e=>{e.stopPropagation();pick("logo")}} className="grid h-10 w-10 place-items-center rounded-lg border border-dashed text-slate-400"><UploadSimple/></button>}<b className="text-xl">{theme.header.storeName}</b>{theme.header.showSearch&&<div className="flex-1 rounded-xl border px-4 py-3 text-xs text-slate-400">جستجو در محصولات…</div>}{theme.header.showAccount&&<button className="rounded-xl border px-4 py-2 text-xs">حساب کاربری</button>}{theme.header.showCart&&<button className="flex items-center gap-2 rounded-xl border px-4 py-2 text-xs"><ShoppingCart/>سبد {cart?.items?.reduce((s,i)=>s+i.quantity,0)||0}</button>}<CanvasTag label="هدر سایت" onUpload={()=>pick("logo")}/></div>}
    {theme.hero.visible&&<section onClick={()=>setSelected("hero")} className={`relative grid place-items-center overflow-hidden px-10 ${selected==="hero"?"ring-2 ring-inset ring-violet-500":""}`} style={{height:theme.hero.height,background:theme.hero.imageUrl?`linear-gradient(90deg,rgba(10,15,25,.72),rgba(10,15,25,.22)),url(${theme.hero.imageUrl}) center/cover`:`linear-gradient(135deg,${theme.accent}22,#fff)`}}><div className="w-full max-w-3xl text-white" style={{textAlign:theme.hero.align}}><h1 className="text-5xl font-black leading-tight">{theme.hero.title}</h1><p className="mt-5 text-lg opacity-85">{theme.hero.subtitle}</p><button className="mt-7 rounded-2xl px-7 py-3 font-black text-white" style={{background:theme.accent}}>{theme.hero.buttonText}</button></div><CanvasTag label="هیرو اصلی" onUpload={()=>pick("hero")}/></section>}
    {theme.trust.visible&&<section onClick={()=>setSelected("trust")} className={`grid grid-cols-4 gap-3 px-8 py-6 ${selected==="trust"?"ring-2 ring-inset ring-violet-500":""}`}>{["پرداخت امن","ارسال سریع","موجودی لحظه‌ای","ضمانت بازگشت"].map(x=><div key={x} className="rounded-2xl border p-5 text-center text-xs font-bold">✦<div className="mt-2">{x}</div></div>)}</section>}
    {theme.products.visible&&<section onClick={()=>setSelected("products")} className={`px-8 py-10 ${selected==="products"?"ring-2 ring-inset ring-violet-500":""}`} style={{background:theme.surface}}><h2 className="mb-6 text-3xl font-black">{theme.products.title}</h2><div className="grid gap-4" style={{gridTemplateColumns:`repeat(${Math.max(2,Math.min(5,theme.productColumns))},minmax(0,1fr))`}}>{activeProducts.map(p=>{const v=p.variants?.[0],stock=v?.inventoryQuantity||0,price=v?.priceMinor??p.basePriceMinor;return <article key={p.id} className="overflow-hidden bg-white shadow-sm ring-1 ring-black/5" style={{borderRadius:theme.cardRadius}}><div className="aspect-square bg-slate-100">{v?.imageUrl?<img src={v.imageUrl} className="h-full w-full object-contain p-3"/>:<div className="grid h-full place-items-center text-4xl">📦</div>}</div><div className="p-4">{theme.products.showBrand&&p.brand&&<div className="text-[10px] font-bold text-violet-500">{p.brand}</div>}<b className="mt-1 block text-sm">{p.name}</b>{theme.products.showSku&&v?.sku&&<div className="mt-1 text-[10px] text-slate-400">SKU {v.sku}</div>}<div className="mt-4 flex items-end justify-between"><div><div className="font-black">{money(price,p.currency)}</div>{theme.products.showStock&&<div className={`mt-1 text-[10px] ${stock>0?"text-emerald-600":"text-red-500"}`}>{stock>0?`${stock} موجود`:"ناموجود"}</div>}</div><button disabled={stock<=0} onClick={e=>{e.stopPropagation();void addToCart(p)}} className="rounded-xl px-3 py-2 text-xs font-bold text-white disabled:opacity-40" style={{background:theme.accent}}>افزودن</button></div></div></article>})}</div></section>}
    {theme.banner.visible&&<section onClick={()=>setSelected("banner")} className={`relative m-8 overflow-hidden rounded-3xl ${selected==="banner"?"ring-2 ring-violet-500":""}`} style={{height:theme.banner.height,background:theme.banner.imageUrl?`linear-gradient(90deg,rgba(10,15,25,.76),rgba(10,15,25,.25)),url(${theme.banner.imageUrl}) center/cover`:theme.accent}}><div className="flex h-full items-center p-10 text-white"><div><h2 className="text-3xl font-black">{theme.banner.title}</h2><p className="mt-3 opacity-85">{theme.banner.subtitle}</p><button className="mt-5 rounded-xl bg-white px-5 py-2 text-sm font-black text-slate-900">{theme.banner.buttonText}</button></div></div><CanvasTag label="بنر تبلیغاتی" onUpload={()=>pick("banner")}/></section>}
    {theme.footer.visible&&<footer onClick={()=>setSelected("footer")} className={`bg-slate-950 px-8 py-10 text-white ${selected==="footer"?"ring-2 ring-inset ring-violet-500":""}`}><b>{theme.footer.title}</b><p className="mt-2 text-xs text-white/50">{theme.footer.subtitle}</p></footer>}
   </div></section>
   <aside className="overflow-y-auto border-r border-white/10 bg-[#101722] p-5"><div className="text-[10px] text-white/40">در حال ویرایش</div><h3 className="mt-1 text-lg font-black">{sectionNames[selected]}</h3><Editor selected={selected} theme={theme} setTheme={setTheme} pick={pick}/></aside>
  </div></main>}

function CanvasTag({label,onUpload}:{label:string;onUpload:()=>void}){return <div className="absolute left-3 top-3 z-20 flex items-center gap-2 rounded-xl bg-slate-950/85 px-3 py-2 text-[11px] font-bold text-white shadow-lg"><span>{label}</span><button onClick={e=>{e.stopPropagation();onUpload()}} className="flex items-center gap-1 rounded-lg bg-white/10 px-2 py-1"><Image/>تصویر</button></div>}
function Editor({selected,theme,setTheme,pick}:{selected:Section;theme:Theme;setTheme:React.Dispatch<React.SetStateAction<Theme>>;pick:(t:"logo"|"hero"|"banner")=>void}){const input="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-white";const toggle=(checked:boolean,onChange:(v:boolean)=>void,label:string)=><label className="mt-3 flex items-center justify-between rounded-xl border border-white/10 p-3 text-xs"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>;
 if(selected==="header")return <div className="mt-5"><label className="text-xs text-white/50">نام فروشگاه<input className={input} value={theme.header.storeName} onChange={e=>setTheme(t=>({...t,header:{...t.header,storeName:e.target.value}}))}/></label><button onClick={()=>pick("logo")} className="mt-3 w-full rounded-xl border border-white/10 p-3 text-xs">آپلود / تغییر لوگو</button>{toggle(theme.header.showSearch,v=>setTheme(t=>({...t,header:{...t.header,showSearch:v}})),"نمایش جستجو")}{toggle(theme.header.showAccount,v=>setTheme(t=>({...t,header:{...t.header,showAccount:v}})),"نمایش حساب کاربری")}{toggle(theme.header.showCart,v=>setTheme(t=>({...t,header:{...t.header,showCart:v}})),"نمایش سبد خرید")}</div>;
 if(selected==="hero")return <div className="mt-5"><label className="text-xs text-white/50">عنوان Hero<input className={input} value={theme.hero.title} onChange={e=>setTheme(t=>({...t,hero:{...t.hero,title:e.target.value}}))}/></label><label className="mt-4 block text-xs text-white/50">توضیح<textarea className={input} value={theme.hero.subtitle} onChange={e=>setTheme(t=>({...t,hero:{...t.hero,subtitle:e.target.value}}))}/></label><label className="mt-4 block text-xs text-white/50">متن دکمه<input className={input} value={theme.hero.buttonText} onChange={e=>setTheme(t=>({...t,hero:{...t.hero,buttonText:e.target.value}}))}/></label><button onClick={()=>pick("hero")} className="mt-3 w-full rounded-xl border border-white/10 p-3 text-xs">آپلود / تغییر تصویر Hero</button><label className="mt-4 block text-xs text-white/50">ارتفاع: {theme.hero.height}px<input type="range" min="280" max="700" value={theme.hero.height} onChange={e=>setTheme(t=>({...t,hero:{...t.hero,height:Number(e.target.value)}}))} className="mt-2 w-full"/></label></div>;
 if(selected==="banner")return <div className="mt-5"><label className="text-xs text-white/50">عنوان بنر<input className={input} value={theme.banner.title} onChange={e=>setTheme(t=>({...t,banner:{...t.banner,title:e.target.value}}))}/></label><label className="mt-4 block text-xs text-white/50">توضیح<textarea className={input} value={theme.banner.subtitle} onChange={e=>setTheme(t=>({...t,banner:{...t.banner,subtitle:e.target.value}}))}/></label><label className="mt-4 block text-xs text-white/50">متن دکمه<input className={input} value={theme.banner.buttonText} onChange={e=>setTheme(t=>({...t,banner:{...t.banner,buttonText:e.target.value}}))}/></label><button onClick={()=>pick("banner")} className="mt-3 w-full rounded-xl border border-white/10 p-3 text-xs">آپلود / تغییر تصویر بنر</button><label className="mt-4 block text-xs text-white/50">ارتفاع: {theme.banner.height}px<input type="range" min="140" max="420" value={theme.banner.height} onChange={e=>setTheme(t=>({...t,banner:{...t.banner,height:Number(e.target.value)}}))} className="mt-2 w-full"/></label></div>;
 if(selected==="products")return <div className="mt-5"><label className="text-xs text-white/50">عنوان محصولات<input className={input} value={theme.products.title} onChange={e=>setTheme(t=>({...t,products:{...t.products,title:e.target.value}}))}/></label><label className="mt-4 block text-xs text-white/50">تعداد ستون: {theme.productColumns}<input type="range" min="2" max="5" value={theme.productColumns} onChange={e=>setTheme(t=>({...t,productColumns:Number(e.target.value)}))} className="mt-2 w-full"/></label><label className="mt-4 block text-xs text-white/50">گردی کارت: {theme.cardRadius}px<input type="range" min="0" max="40" value={theme.cardRadius} onChange={e=>setTheme(t=>({...t,cardRadius:Number(e.target.value)}))} className="mt-2 w-full"/></label>{toggle(theme.products.showBrand,v=>setTheme(t=>({...t,products:{...t.products,showBrand:v}})),"نمایش برند")}{toggle(theme.products.showSku,v=>setTheme(t=>({...t,products:{...t.products,showSku:v}})),"نمایش SKU")}{toggle(theme.products.showStock,v=>setTheme(t=>({...t,products:{...t.products,showStock:v}})),"نمایش موجودی")}</div>;
 if(selected==="trust")return <div className="mt-5"><label className="text-xs text-white/50">عنوان اعتمادسازی<input className={input} value={theme.trust.title} onChange={e=>setTheme(t=>({...t,trust:{...t.trust,title:e.target.value}}))}/></label></div>;
 return <div className="mt-5"><label className="text-xs text-white/50">عنوان فوتر<input className={input} value={theme.footer.title} onChange={e=>setTheme(t=>({...t,footer:{...t.footer,title:e.target.value}}))}/></label><label className="mt-4 block text-xs text-white/50">توضیح<input className={input} value={theme.footer.subtitle} onChange={e=>setTheme(t=>({...t,footer:{...t.footer,subtitle:e.target.value}}))}/></label></div>}
