import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Desktop, DeviceMobile, DeviceTablet, FloppyDisk, ShoppingCart, Storefront, Package, SlidersHorizontal, Eye, Sparkle, Plus, Minus } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string;content:Record<string,unknown>};
type Variant={id:string;sku:string;title:string;priceMinor:number|null;inventoryQuantity:number;imageUrl?:string|null;active:boolean};
type Product={id:string;name:string;description:string;category?:string|null;brand?:string|null;status:string;currency:string;basePriceMinor:number;compareAtPriceMinor?:number|null;featured:boolean;variants:Variant[]};
type CartItem={variantId:string;productName:string;quantity:number;lineTotalMinor:number};
type Cart={id:string;currency:string;subtotalMinor:number;discountMinor:number;shippingMinor:number;totalMinor:number;items:CartItem[]};
type SectionKey="hero"|"trust"|"products"|"promo"|"footer";
type Theme={accent:string;surface:string;heroTitle:string;heroSubtitle:string;heroButton:string;radius:number;productColumns:number;showStock:boolean;showSku:boolean;showBrand:boolean;showCartPreview:boolean;showCheckoutPreview:boolean;sections:Record<SectionKey,boolean>};
const seed:Theme={accent:"#6d5dfc",surface:"#f6f7fb",heroTitle:"فروشگاهی که برای فروش ساخته شده",heroSubtitle:"محصولات واقعی، موجودی واقعی، سبد خرید واقعی — همه داخل یک Builder زنده",heroButton:"مشاهده محصولات",radius:22,productColumns:4,showStock:true,showSku:true,showBrand:true,showCartPreview:true,showCheckoutPreview:false,sections:{hero:true,trust:true,products:true,promo:true,footer:true}};
const money=(minor:number,currency:string)=>new Intl.NumberFormat("fa-IR",{style:"currency",currency:currency==="IRT"?"IRR":currency||"USD",maximumFractionDigits:0}).format(currency==="IRT"?minor*10:minor/100);
async function json(r:Response){const t=await r.text();return t?JSON.parse(t):{}}

export default function StoreWebsiteStudioPageV3(){
 const[project,setProject]=useState<Project|null>(null),[products,setProducts]=useState<Product[]>([]),[theme,setTheme]=useState<Theme>(seed),[tab,setTab]=useState<"design"|"products"|"commerce">("design"),[viewport,setViewport]=useState<"desktop"|"tablet"|"mobile">("desktop"),[cart,setCart]=useState<Cart|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{void load()},[]);
 async function load(){try{setBusy(true);const rp=await apiFetch("/api/site-projects");const pd=await json(rp);if(!rp.ok)throw new Error(pd.message||"پروژه‌ها بارگذاری نشدند");const p=(pd.projects||[]).find((x:Project)=>String(x.siteType).toUpperCase()==="STORE")||pd.projects?.[0];if(!p)throw new Error("پروژه فروشگاهی پیدا نشد");const rr=await apiFetch(`/api/site-projects/${p.id}`);const rd=await json(rr);if(!rr.ok)throw new Error(rd.message||"پروژه باز نشد");setProject(rd.project);const saved=rd.project?.content?.commerceStudioV3 as Theme|undefined;if(saved)setTheme({...seed,...saved,sections:{...seed.sections,...saved.sections}});const rc=await apiFetch(`/api/stores/${p.id}/products`);const cd=await json(rc);if(!rc.ok)throw new Error(cd.message||"Catalog بارگذاری نشد");setProducts(cd.products||[])}catch(e){setMessage(e instanceof Error?e.message:"خطا در بارگذاری")}finally{setBusy(false)}}
 const width=viewport==="desktop"?"1180px":viewport==="tablet"?"780px":"390px";
 const activeProducts=useMemo(()=>products.filter(p=>p.status==="ACTIVE"),[products]);
 async function save(){if(!project)return;setBusy(true);try{const r=await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:{...project.content,commerceStudioV3:theme}})});const d=await json(r);if(!r.ok)throw new Error(d.message||"ذخیره نشد");setProject(d.project);setMessage("طراحی فروشگاه ذخیره شد")}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 async function ensureCart(){if(cart)return cart;if(!project)throw new Error("پروژه آماده نیست");const r=await apiFetch(`/api/stores/${project.id}/carts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currency:activeProducts[0]?.currency||"USD"})});const d=await json(r);if(!r.ok)throw new Error(d.message||"سبد ساخته نشد");setCart(d.cart);return d.cart as Cart}
 async function addToCart(p:Product){const v=p.variants?.find(x=>x.active);if(!v)return setMessage("این محصول Variant فعال ندارد");try{setBusy(true);const c=await ensureCart();const r=await apiFetch(`/api/commerce/carts/${c.id}/items`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({variantId:v.id,quantity:1})});const d=await json(r);if(!r.ok)throw new Error(d.message||"به سبد اضافه نشد");setCart(d.cart);setTheme(x=>({...x,showCartPreview:true}));setMessage(`${p.name} به سبد اضافه شد`)}catch(e){setMessage(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 async function adjustStock(v:Variant,delta:number){try{const r=await apiFetch(`/api/commerce/variants/${v.id}/inventory-adjustments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({delta})});const d=await json(r);if(!r.ok)throw new Error(d.message||"موجودی تغییر نکرد");setProducts(ps=>ps.map(p=>({...p,variants:p.variants.map(x=>x.id===v.id?d.variant:x)})));}catch(e){setMessage(e instanceof Error?e.message:"خطا")}}
 const cardProduct=(p:Product)=>{const v=p.variants?.[0],price=v?.priceMinor??p.basePriceMinor,stock=v?.inventoryQuantity??0;return <article key={p.id} className="group overflow-hidden bg-white shadow-sm ring-1 ring-black/5" style={{borderRadius:theme.radius}}><div className="aspect-square bg-gradient-to-br from-slate-50 to-slate-100 p-4">{v?.imageUrl?<img src={v.imageUrl} className="h-full w-full object-contain"/>:<div className="grid h-full place-items-center text-5xl">📦</div>}</div><div className="p-4">{theme.showBrand&&p.brand&&<div className="text-[10px] font-bold uppercase tracking-wider text-violet-500">{p.brand}</div>}<h3 className="mt-1 line-clamp-2 min-h-10 text-sm font-black">{p.name}</h3>{theme.showSku&&v?.sku&&<div className="mt-1 text-[10px] text-slate-400">SKU {v.sku}</div>}<div className="mt-4 flex items-end justify-between gap-2"><div><div className="text-sm font-black">{money(price,p.currency)}</div>{theme.showStock&&<div className={`mt-1 text-[10px] font-bold ${stock>0?"text-emerald-600":"text-red-500"}`}>{stock>0?`${stock} عدد موجود`:"ناموجود"}</div>}</div><button disabled={stock<=0||busy} onClick={e=>{e.stopPropagation();void addToCart(p)}} className="rounded-xl px-3 py-2 text-xs font-bold text-white disabled:opacity-40" style={{background:theme.accent}}>افزودن</button></div></div></article>};
 return <main dir="rtl" className="h-screen overflow-hidden bg-[#0a0f17] text-white">
  <header className="flex h-[64px] items-center justify-between border-b border-white/10 bg-[#0d131d] px-4"><div className="flex items-center gap-2"><Link to="/dashboard" className="rounded-xl border border-white/10 p-2"><ArrowRight/></Link><button onClick={()=>void save()} disabled={busy} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-bold"><FloppyDisk/>ذخیره</button><Link to="/dashboard/websites/storefront-test" className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm"><Eye/>تست خرید</Link></div><div className="flex rounded-xl bg-white/5 p-1"><button onClick={()=>setViewport("desktop")} className="p-2"><Desktop/></button><button onClick={()=>setViewport("tablet")} className="p-2"><DeviceTablet/></button><button onClick={()=>setViewport("mobile")} className="p-2"><DeviceMobile/></button></div><div className="text-left"><div className="text-[10px] text-white/40">Commerce Studio V3</div><b>{project?.name||"Store Builder"}</b></div></header>
  <div className="grid h-[calc(100vh-64px)] grid-cols-[285px_minmax(0,1fr)_320px]">
   <aside className="overflow-y-auto border-l border-white/10 bg-[#101722] p-4"><div className="grid grid-cols-3 gap-1 rounded-xl bg-black/20 p-1 text-[11px]"><button onClick={()=>setTab("design")} className={`rounded-lg py-2 ${tab==="design"?"bg-violet-600":""}`}><SlidersHorizontal className="mx-auto mb-1"/>طراحی</button><button onClick={()=>setTab("products")} className={`rounded-lg py-2 ${tab==="products"?"bg-violet-600":""}`}><Package className="mx-auto mb-1"/>محصولات</button><button onClick={()=>setTab("commerce")} className={`rounded-lg py-2 ${tab==="commerce"?"bg-violet-600":""}`}><Storefront className="mx-auto mb-1"/>فروشگاه</button></div>
    {tab==="design"&&<div className="mt-5 space-y-4"><b className="text-sm">سکشن‌های Canvas</b>{(Object.keys(theme.sections) as SectionKey[]).map(k=><label key={k} className="flex items-center justify-between rounded-xl border border-white/10 p-3 text-xs"><span>{({hero:"Hero",trust:"اعتمادسازی",products:"محصولات واقعی",promo:"بنر فروش",footer:"Footer"} as Record<SectionKey,string>)[k]}</span><input type="checkbox" checked={theme.sections[k]} onChange={e=>setTheme(t=>({...t,sections:{...t.sections,[k]:e.target.checked}}))}/></label>)}</div>}
    {tab==="products"&&<div className="mt-5"><div className="flex items-center justify-between"><b className="text-sm">Catalog واقعی</b><Link to="/dashboard/websites/commerce" className="text-[11px] text-violet-300">مدیریت کامل</Link></div><div className="mt-3 space-y-3">{products.map(p=>{const v=p.variants?.[0];return <div key={p.id} className="rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex items-start justify-between gap-2"><div><b className="text-xs">{p.name}</b><div className="mt-1 text-[10px] text-white/40">{v?.sku||"بدون SKU"} · {p.status}</div></div><span className="text-[10px]">{v?.inventoryQuantity??0}</span></div>{v&&<div className="mt-3 flex gap-2"><button onClick={()=>void adjustStock(v,-1)} className="rounded-lg border border-white/10 p-2"><Minus/></button><button onClick={()=>void adjustStock(v,1)} className="rounded-lg border border-white/10 p-2"><Plus/></button></div>}</div>})}{!products.length&&<div className="rounded-xl border border-dashed border-white/15 p-5 text-xs text-white/45">از «مدیریت کامل» اولین محصول واقعی را بساز.</div>}</div></div>}
    {tab==="commerce"&&<div className="mt-5 space-y-3"><b className="text-sm">تجربه خرید</b><label className="flex items-center justify-between rounded-xl border border-white/10 p-3 text-xs">Cart Drawer<input type="checkbox" checked={theme.showCartPreview} onChange={e=>setTheme(t=>({...t,showCartPreview:e.target.checked}))}/></label><label className="flex items-center justify-between rounded-xl border border-white/10 p-3 text-xs">Checkout Preview<input type="checkbox" checked={theme.showCheckoutPreview} onChange={e=>setTheme(t=>({...t,showCheckoutPreview:e.target.checked}))}/></label><Link to="/dashboard/websites/storefront-test" className="block rounded-xl bg-emerald-500/15 p-3 text-center text-xs font-bold text-emerald-300">اجرای خرید واقعی آزمایشی</Link></div>}
    {message&&<div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-6">{message}</div>}</aside>
   <section className="overflow-auto bg-[#252c38] p-7"><div className="relative mx-auto min-h-full overflow-hidden bg-white text-slate-900 shadow-2xl transition-all" style={{width,maxWidth:"100%"}}><div className="flex items-center gap-5 border-b px-7 py-4"><b className="text-xl">{project?.name||"فروشگاه شما"}</b><div className="flex-1 rounded-xl border px-4 py-3 text-xs text-slate-400">جستجو در محصولات واقعی…</div><button onClick={()=>setTheme(t=>({...t,showCartPreview:!t.showCartPreview}))} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-xs"><ShoppingCart/>سبد {cart?.items?.reduce((s,i)=>s+i.quantity,0)||0}</button></div>
    {theme.sections.hero&&<section className="grid min-h-[390px] place-items-center px-10 text-center" style={{background:`linear-gradient(135deg,${theme.accent}18,#ffffff)`}}><div className="max-w-3xl"><div className="mx-auto mb-5 grid h-14 w-14 place-items-center rounded-2xl text-2xl text-white" style={{background:theme.accent}}><Sparkle/></div><h1 className="text-5xl font-black leading-tight">{theme.heroTitle}</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-500">{theme.heroSubtitle}</p><button className="mt-7 rounded-2xl px-7 py-3 font-black text-white" style={{background:theme.accent}}>{theme.heroButton}</button></div></section>}
    {theme.sections.trust&&<section className="grid grid-cols-4 gap-3 px-8 py-6">{["پرداخت امن","ارسال سریع","موجودی لحظه‌ای","ضمانت بازگشت"].map(x=><div key={x} className="rounded-2xl border bg-white p-5 text-center text-xs font-bold">✦<div className="mt-2">{x}</div></div>)}</section>}
    {theme.sections.products&&<section className="px-8 py-10" style={{background:theme.surface}}><div className="mb-6 flex items-end justify-between"><div><div className="text-xs font-bold" style={{color:theme.accent}}>LIVE CATALOG</div><h2 className="mt-1 text-3xl font-black">محصولات فروشگاه</h2><p className="mt-1 text-sm text-slate-500">این کارت‌ها مستقیم از Commerce Core می‌آیند.</p></div><span className="rounded-full bg-white px-3 py-1 text-xs shadow-sm">{activeProducts.length} محصول فعال</span></div><div className="grid gap-4" style={{gridTemplateColumns:`repeat(${Math.max(2,theme.productColumns)},minmax(0,1fr))`}}>{activeProducts.length?activeProducts.map(cardProduct):<div className="col-span-full rounded-2xl border-2 border-dashed bg-white p-12 text-center text-slate-400">هنوز محصول ACTIVE نداری. از پنل محصولات اضافه کن.</div>}</div></section>}
    {theme.sections.promo&&<section className="m-8 flex items-center justify-between rounded-[28px] p-9 text-white" style={{background:theme.accent}}><div><div className="text-sm opacity-70">کمپین فروش</div><h2 className="mt-1 text-3xl font-black">بنر فروش کاملاً قابل طراحی</h2><p className="mt-2 text-sm opacity-80">بعداً Coupon و کمپین‌ها را مستقیم به این سکشن وصل می‌کنیم.</p></div><button className="rounded-xl bg-white px-5 py-3 text-sm font-black" style={{color:theme.accent}}>خرید کنید</button></section>}
    {theme.sections.footer&&<footer className="grid grid-cols-4 gap-8 bg-[#101722] px-8 py-10 text-white"><div><b>{project?.name||"Store"}</b><p className="mt-3 text-xs text-white/50">فروشگاه ساخته‌شده با Loadder</p></div><div className="text-xs text-white/60">محصولات<br/>دسته‌بندی‌ها<br/>برندها</div><div className="text-xs text-white/60">ارسال<br/>بازگشت<br/>قوانین</div><div className="text-xs text-white/60">تماس<br/>شبکه‌های اجتماعی<br/>خبرنامه</div></footer>}
    {theme.showCartPreview&&<div className="absolute left-5 top-20 z-20 w-[310px] rounded-3xl border bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><b>سبد خرید</b><span className="text-xs text-slate-400">LIVE</span></div>{cart?.items?.length?<div className="mt-4 space-y-3">{cart.items.map(i=><div key={i.variantId} className="flex items-center justify-between border-b pb-3 text-xs"><span>{i.productName} × {i.quantity}</span><b>{money(i.lineTotalMinor,cart.currency)}</b></div>)}<div className="flex justify-between pt-2 text-sm"><span>جمع</span><b>{money(cart.totalMinor,cart.currency)}</b></div><button onClick={()=>setTheme(t=>({...t,showCheckoutPreview:true}))} className="w-full rounded-xl py-3 text-sm font-black text-white" style={{background:theme.accent}}>ادامه پرداخت</button></div>:<div className="mt-5 rounded-2xl bg-slate-50 p-6 text-center text-xs text-slate-400">سبد خالی است؛ از کارت محصول «افزودن» را بزن.</div>}</div>}
    {theme.showCheckoutPreview&&<div className="absolute inset-0 z-30 grid place-items-center bg-black/45 p-8"><div className="w-full max-w-xl rounded-3xl bg-white p-7 shadow-2xl"><div className="flex items-center justify-between"><div><div className="text-xs font-bold" style={{color:theme.accent}}>CHECKOUT PREVIEW</div><h3 className="mt-1 text-2xl font-black">تکمیل سفارش</h3></div><button onClick={()=>setTheme(t=>({...t,showCheckoutPreview:false}))} className="rounded-xl border px-3 py-2 text-xs">بستن</button></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl border p-3 text-xs text-slate-400">نام و نام خانوادگی</div><div className="rounded-xl border p-3 text-xs text-slate-400">شماره تماس</div><div className="col-span-2 rounded-xl border p-3 text-xs text-slate-400">آدرس تحویل</div><div className="rounded-xl border p-3 text-xs text-slate-400">روش ارسال</div><div className="rounded-xl border p-3 text-xs text-slate-400">روش پرداخت</div></div><div className="mt-5 flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span className="text-sm">مبلغ سفارش</span><b>{cart?money(cart.totalMinor,cart.currency):"—"}</b></div><Link to="/dashboard/websites/storefront-test" className="mt-4 block rounded-xl py-3 text-center text-sm font-black text-white" style={{background:theme.accent}}>اجرای Checkout آزمایشی واقعی</Link></div></div>}
   </div></section>
   <aside className="overflow-y-auto border-r border-white/10 bg-[#101722] p-5"><b className="text-sm">ظاهر فروشگاه</b><label className="mt-5 block text-xs text-white/50">رنگ برند<input type="color" value={theme.accent} onChange={e=>setTheme(t=>({...t,accent:e.target.value}))} className="mt-2 h-10 w-full rounded bg-transparent"/></label><label className="mt-4 block text-xs text-white/50">عنوان Hero<input value={theme.heroTitle} onChange={e=>setTheme(t=>({...t,heroTitle:e.target.value}))} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white"/></label><label className="mt-4 block text-xs text-white/50">متن Hero<textarea value={theme.heroSubtitle} onChange={e=>setTheme(t=>({...t,heroSubtitle:e.target.value}))} className="mt-2 min-h-24 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-white"/></label><label className="mt-4 block text-xs text-white/50">تعداد ستون محصول: {theme.productColumns}<input type="range" min="2" max="5" value={theme.productColumns} onChange={e=>setTheme(t=>({...t,productColumns:Number(e.target.value)}))} className="mt-2 w-full"/></label><label className="mt-4 block text-xs text-white/50">گردی کارت: {theme.radius}px<input type="range" min="0" max="36" value={theme.radius} onChange={e=>setTheme(t=>({...t,radius:Number(e.target.value)}))} className="mt-2 w-full"/></label>{[["showStock","نمایش موجودی"],["showSku","نمایش SKU"],["showBrand","نمایش برند"]] .map(([k,l])=><label key={k} className="mt-3 flex items-center justify-between rounded-xl border border-white/10 p-3 text-xs"><span>{l}</span><input type="checkbox" checked={Boolean(theme[k as keyof Theme])} onChange={e=>setTheme(t=>({...t,[k]:e.target.checked}))}/></label>)}</aside>
  </div>
 </main>
}
