import { useEffect, useMemo, useRef, useState, type DragEvent } from "react";
import { ArrowRight, Desktop, DeviceMobile, DeviceTablet, FloppyDisk, Image, Package, ShoppingCart, UploadSimple } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string;content:Record<string,unknown>};
type Variant={id:string;sku:string;priceMinor:number|null;inventoryQuantity:number;imageUrl?:string|null;active:boolean};
type Product={id:string;name:string;brand?:string|null;status:string;currency:string;basePriceMinor:number;variants:Variant[]};
type Cart={id:string;items:{quantity:number}[]};
type Section="header"|"hero"|"banner"|"products"|"trust"|"footer";
type MediaTarget="logo"|"hero"|"banner";
type Theme={accent:string;surface:string;cardRadius:number;productColumns:number;header:{visible:boolean;storeName:string;logoUrl:string;showSearch:boolean;showAccount:boolean;showCart:boolean};hero:{visible:boolean;title:string;subtitle:string;buttonText:string;imageUrl:string;height:number};banner:{visible:boolean;title:string;subtitle:string;buttonText:string;imageUrl:string;height:number};products:{visible:boolean;title:string;showBrand:boolean;showSku:boolean;showStock:boolean};trust:{visible:boolean;title:string};footer:{visible:boolean;title:string;subtitle:string}};
const seed:Theme={accent:"#6d5dfc",surface:"#f6f7fb",cardRadius:22,productColumns:4,header:{visible:true,storeName:"فروشگاه شما",logoUrl:"",showSearch:true,showAccount:true,showCart:true},hero:{visible:true,title:"فروشگاهی که برای فروش ساخته شده",subtitle:"تصویر Hero را همین‌جا بکش و رها کن؛ نتیجه را همان لحظه ببین.",buttonText:"مشاهده محصولات",imageUrl:"",height:430},banner:{visible:true,title:"پیشنهاد ویژه این هفته",subtitle:"بنر کمپین را مستقیم روی همین بخش آپلود کن.",buttonText:"مشاهده پیشنهاد",imageUrl:"",height:220},products:{visible:true,title:"محصولات فروشگاه",showBrand:true,showSku:true,showStock:true},trust:{visible:true,title:"خرید مطمئن و سریع"},footer:{visible:true,title:"فروشگاه شما",subtitle:"تمام حقوق محفوظ است."}};
const sectionNames:Record<Section,string>={header:"هدر سایت",hero:"هیرو اصلی",banner:"بنر تبلیغاتی",products:"محصولات",trust:"اعتمادسازی",footer:"فوتر"};
async function readJson(r:Response){const t=await r.text();return t?JSON.parse(t):{}}
const money=(minor:number,currency:string)=>new Intl.NumberFormat("fa-IR",{style:"currency",currency:currency==="IRT"?"IRR":currency||"USD",maximumFractionDigits:0}).format(currency==="IRT"?minor*10:minor/100);

export default function StoreWebsiteStudioPageV5(){
 const[project,setProject]=useState<Project|null>(null),[products,setProducts]=useState<Product[]>([]),[theme,setTheme]=useState(seed),[selected,setSelected]=useState<Section>("hero"),[viewport,setViewport]=useState<"desktop"|"tablet"|"mobile">("desktop"),[cart,setCart]=useState<Cart|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[dragTarget,setDragTarget]=useState<MediaTarget|null>(null);
 const fileRef=useRef<HTMLInputElement>(null),pendingTarget=useRef<MediaTarget>("hero");
 useEffect(()=>{void load()},[]);
 async function load(){try{setBusy(true);const rp=await apiFetch("/api/site-projects");const pd=await readJson(rp);const p=(pd.projects||[]).find((x:Project)=>String(x.siteType).toUpperCase()==="STORE")||pd.projects?.[0];if(!p)throw new Error("پروژه فروشگاهی پیدا نشد");const rr=await apiFetch(`/api/site-projects/${p.id}`);const rd=await readJson(rr);if(!rr.ok)throw new Error(rd.message||"پروژه باز نشد");setProject(rd.project);const saved=rd.project?.content?.commerceStudioV5 as Theme|undefined;if(saved)setTheme({...seed,...saved,header:{...seed.header,...saved.header},hero:{...seed.hero,...saved.hero},banner:{...seed.banner,...saved.banner},products:{...seed.products,...saved.products},trust:{...seed.trust,...saved.trust},footer:{...seed.footer,...saved.footer}});const rc=await apiFetch(`/api/stores/${p.id}/products`);const cd=await readJson(rc);if(rc.ok)setProducts(cd.products||[])}catch(e){setMessage(e instanceof Error?e.message:"خطا در بارگذاری")}finally{setBusy(false)}}
 const activeProducts=useMemo(()=>products.filter(p=>p.status==="ACTIVE"),[products]);
 const width=viewport==="desktop"?"1180px":viewport==="tablet"?"780px":"390px";
 function applyPreview(target:MediaTarget,url:string){if(target==="logo")setTheme(t=>({...t,header:{...t.header,logoUrl:url}}));if(target==="hero")setTheme(t=>({...t,hero:{...t.hero,imageUrl:url}}));if(target==="banner")setTheme(t=>({...t,banner:{...t.banner,imageUrl:url}}))}
 async function upload(target:MediaTarget,file:File){if(!project)return;if(!file.type.startsWith("image/")){setMessage("فقط فایل تصویری قابل قبول است");return}if(file.size>3*1024*1024){setMessage("حداکثر حجم تصویر ۳ مگابایت است");return}const dataUrl=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error("خواندن تصویر ناموفق بود"));r.readAsDataURL(file)});applyPreview(target,dataUrl);setMessage("پیش‌نمایش فوری اعمال شد؛ در حال ذخیره تصویر…");try{setBusy(true);const kind=target==="logo"?"logo":target==="hero"?"hero":"banner";const r=await apiFetch(`/api/site-projects/${project.id}/assets`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,name:file.name,url:dataUrl,altText:file.name,metadata:{placement:target}})});const d=await readJson(r);if(!r.ok)throw new Error(d.message||"آپلود ناموفق بود");applyPreview(target,d.asset?.url||dataUrl);setMessage("تصویر ذخیره شد و روی همان بخش ماند") }catch(e){setMessage(e instanceof Error?e.message:"خطا در آپلود")}finally{setBusy(false);setDragTarget(null)}}
 function pick(target:MediaTarget){pendingTarget.current=target;fileRef.current?.click()}
 function onDrop(e:DragEvent,target:MediaTarget){e.preventDefault();e.stopPropagation();setDragTarget(null);const f=e.dataTransfer.files?.[0];if(f)void upload(target,f)}
 async function save(){if(!project)return;setBusy(true);try{const r=await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:{...project.content,commerceStudioV5:theme}})});const d=await readJson(r);if(!r.ok)throw new Error(d.message||"ذخیره نشد");setProject(d.project);setMessage("طراحی ذخیره شد")}catch(e){setMessage(e instanceof Error?e.message:"خطا در ذخیره")}finally{setBusy(false)}}
 async function ensureCart(){if(cart)return cart;if(!project)throw new Error("پروژه آماده نیست");const r=await apiFetch(`/api/stores/${project.id}/carts`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currency:activeProducts[0]?.currency||"USD"})});const d=await readJson(r);if(!r.ok)throw new Error(d.message||"سبد ساخته نشد");setCart(d.cart);return d.cart as Cart}
 async function addToCart(p:Product){const v=p.variants?.find(x=>x.active);if(!v)return setMessage("Variant فعال ندارد");try{const c=await ensureCart();const r=await apiFetch(`/api/commerce/carts/${c.id}/items`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({variantId:v.id,quantity:1})});const d=await readJson(r);if(!r.ok)throw new Error(d.message||"به سبد اضافه نشد");setCart(d.cart)}catch(e){setMessage(e instanceof Error?e.message:"خطا")}}
 const dropProps=(target:MediaTarget)=>({onDragOver:(e:DragEvent)=>{e.preventDefault();setDragTarget(target)},onDragLeave:()=>setDragTarget(null),onDrop:(e:DragEvent)=>onDrop(e,target)});
 return <main dir="rtl" className="h-screen overflow-hidden bg-[#0a0f17] text-white"><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(pendingTarget.current,f);e.target.value=""}}/>
 <header className="flex h-16 items-center justify-between border-b border-white/10 bg-[#0d131d] px-4"><div className="flex gap-2"><Link to="/dashboard" className="rounded-xl border border-white/10 p-2"><ArrowRight/></Link><button disabled={busy} onClick={()=>void save()} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-bold"><FloppyDisk/>ذخیره</button><Link to="/dashboard/websites/commerce" className="rounded-xl border border-white/10 px-4 py-2 text-sm">مدیریت محصولات</Link></div><div className="flex rounded-xl bg-white/5 p-1"><button onClick={()=>setViewport("desktop")} className="p-2"><Desktop/></button><button onClick={()=>setViewport("tablet")} className="p-2"><DeviceTablet/></button><button onClick={()=>setViewport("mobile")} className="p-2"><DeviceMobile/></button></div><div><div className="text-[10px] text-white/40">Store Studio V5 · Direct Canvas Upload</div><b>{project?.name||"Store Builder"}</b></div></header>
 <div className="grid h-[calc(100vh-64px)] grid-cols-[250px_minmax(0,1fr)_330px]"><aside className="overflow-y-auto border-l border-white/10 bg-[#101722] p-4"><b className="text-sm">بخش‌های سایت</b><p className="mt-1 text-[11px] leading-5 text-white/40">برای لوگو، Hero و Banner لازم نیست از پنل بیرون بروی؛ فایل را مستقیم روی خود بخش بکش یا روی «آپلود مستقیم» بزن.</p><div className="mt-4 space-y-2">{(["header","hero","banner","products","trust","footer"] as Section[]).map(s=><button key={s} onClick={()=>setSelected(s)} className={`w-full rounded-xl border p-3 text-right text-xs ${selected===s?"border-violet-500 bg-violet-500/10":"border-white/10"}`}>{sectionNames[s]}</button>)}</div><div className="mt-5 rounded-xl border border-white/10 p-3 text-xs"><Package className="mb-2"/> {activeProducts.length} محصول فعال</div>{message&&<div className="mt-4 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-6">{message}</div>}</aside>
 <section className="overflow-auto bg-[#252c38] p-7"><div className="mx-auto min-h-full overflow-hidden bg-white text-slate-900 shadow-2xl" style={{width,maxWidth:"100%"}}>
 {theme.header.visible&&<div {...dropProps("logo")} onClick={()=>setSelected("header")} className={`relative flex items-center gap-5 border-b px-7 py-4 ${selected==="header"?"ring-2 ring-inset ring-violet-500":""} ${dragTarget==="logo"?"bg-violet-50":""}`}>{theme.header.logoUrl?<img src={theme.header.logoUrl} className="h-12 w-12 rounded-xl object-contain"/>:<DirectButton label="لوگو" onClick={()=>pick("logo")}/>}<b className="text-xl">{theme.header.storeName}</b>{theme.header.showSearch&&<div className="flex-1 rounded-xl border px-4 py-3 text-xs text-slate-400">جستجو در محصولات…</div>}{theme.header.showAccount&&<button className="rounded-xl border px-4 py-2 text-xs">حساب کاربری</button>}{theme.header.showCart&&<button className="flex items-center gap-2 rounded-xl border px-4 py-2 text-xs"><ShoppingCart/>سبد {cart?.items?.reduce((s,i)=>s+i.quantity,0)||0}</button>}<DropBadge target="logo" active={dragTarget==="logo"} onClick={()=>pick("logo")} label="آپلود مستقیم لوگو"/></div>}
 {theme.hero.visible&&<section {...dropProps("hero")} onClick={()=>setSelected("hero")} className={`relative grid place-items-center overflow-hidden px-10 ${selected==="hero"?"ring-2 ring-inset ring-violet-500":""}`} style={{height:theme.hero.height,background:theme.hero.imageUrl?`linear-gradient(90deg,rgba(10,15,25,.72),rgba(10,15,25,.22)),url(${theme.hero.imageUrl}) center/cover`:`linear-gradient(135deg,${theme.accent}22,#fff)`}}><div className="w-full max-w-3xl text-right text-white"><h1 className="text-5xl font-black leading-tight">{theme.hero.title}</h1><p className="mt-5 text-lg opacity-85">{theme.hero.subtitle}</p><button className="mt-7 rounded-2xl px-7 py-3 font-black text-white" style={{background:theme.accent}}>{theme.hero.buttonText}</button></div><DropOverlay active={dragTarget==="hero"} label={theme.hero.imageUrl?"تصویر جدید Hero را اینجا رها کن":"تصویر Hero را اینجا بکش یا کلیک کن"} onClick={()=>pick("hero")}/></section>}
 {theme.trust.visible&&<section onClick={()=>setSelected("trust")} className={`grid grid-cols-4 gap-3 px-8 py-6 ${selected==="trust"?"ring-2 ring-inset ring-violet-500":""}`}>{["پرداخت امن","ارسال سریع","موجودی لحظه‌ای","ضمانت بازگشت"].map(x=><div key={x} className="rounded-2xl border p-5 text-center text-xs font-bold">✦<div className="mt-2">{x}</div></div>)}</section>}
 {theme.products.visible&&<section onClick={()=>setSelected("products")} className={`px-8 py-10 ${selected==="products"?"ring-2 ring-inset ring-violet-500":""}`} style={{background:theme.surface}}><h2 className="mb-6 text-3xl font-black">{theme.products.title}</h2><div className="grid gap-4" style={{gridTemplateColumns:`repeat(${Math.max(2,Math.min(5,theme.productColumns))},minmax(0,1fr))`}}>{activeProducts.map(p=>{const v=p.variants?.[0],stock=v?.inventoryQuantity||0,price=v?.priceMinor??p.basePriceMinor;return <article key={p.id} className="overflow-hidden bg-white shadow-sm ring-1 ring-black/5" style={{borderRadius:theme.cardRadius}}><div className="aspect-square bg-slate-100">{v?.imageUrl?<img src={v.imageUrl} className="h-full w-full object-contain p-3"/>:<div className="grid h-full place-items-center text-4xl">📦</div>}</div><div className="p-4">{theme.products.showBrand&&p.brand&&<div className="text-[10px] font-bold text-violet-500">{p.brand}</div>}<b className="mt-1 block text-sm">{p.name}</b>{theme.products.showSku&&v?.sku&&<div className="mt-1 text-[10px] text-slate-400">SKU {v.sku}</div>}<div className="mt-4 flex items-end justify-between"><div><div className="font-black">{money(price,p.currency)}</div>{theme.products.showStock&&<div className={`mt-1 text-[10px] ${stock>0?"text-emerald-600":"text-red-500"}`}>{stock>0?`${stock} موجود`:"ناموجود"}</div>}</div><button disabled={stock<=0} onClick={e=>{e.stopPropagation();void addToCart(p)}} className="rounded-xl px-3 py-2 text-xs font-bold text-white disabled:opacity-40" style={{background:theme.accent}}>افزودن</button></div></div></article>})}</div></section>}
 {theme.banner.visible&&<section {...dropProps("banner")} onClick={()=>setSelected("banner")} className={`relative m-8 overflow-hidden rounded-3xl ${selected==="banner"?"ring-2 ring-violet-500":""}`} style={{height:theme.banner.height,background:theme.banner.imageUrl?`linear-gradient(90deg,rgba(10,15,25,.76),rgba(10,15,25,.25)),url(${theme.banner.imageUrl}) center/cover`:theme.accent}}><div className="flex h-full items-center p-10 text-white"><div><h2 className="text-3xl font-black">{theme.banner.title}</h2><p className="mt-3 opacity-85">{theme.banner.subtitle}</p><button className="mt-5 rounded-xl bg-white px-5 py-2 text-sm font-black text-slate-900">{theme.banner.buttonText}</button></div></div><DropOverlay active={dragTarget==="banner"} label={theme.banner.imageUrl?"بنر جدید را اینجا رها کن":"بنر را مستقیم اینجا بکش یا کلیک کن"} onClick={()=>pick("banner")}/></section>}
 {theme.footer.visible&&<footer onClick={()=>setSelected("footer")} className={`bg-slate-950 px-8 py-10 text-white ${selected==="footer"?"ring-2 ring-inset ring-violet-500":""}`}><b>{theme.footer.title}</b><p className="mt-2 text-xs text-white/50">{theme.footer.subtitle}</p></footer>}
 </div></section><aside className="overflow-y-auto border-r border-white/10 bg-[#101722] p-5"><div className="text-[10px] text-white/40">در حال ویرایش</div><h3 className="mt-1 text-lg font-black">{sectionNames[selected]}</h3><Editor selected={selected} theme={theme} setTheme={setTheme} pick={pick}/></aside></div></main>}

function DirectButton({label,onClick}:{label:string;onClick:()=>void}){return <button onClick={e=>{e.stopPropagation();onClick()}} className="grid h-12 w-12 place-items-center rounded-xl border-2 border-dashed border-violet-300 text-violet-500" title={`آپلود ${label}`}><UploadSimple/></button>}
function DropBadge({active,onClick,label}:{target:MediaTarget;active:boolean;onClick:()=>void;label:string}){return <button onClick={e=>{e.stopPropagation();onClick()}} className={`absolute bottom-2 left-2 z-30 flex items-center gap-1 rounded-lg px-3 py-2 text-[11px] font-bold ${active?"bg-violet-600 text-white":"bg-slate-950/80 text-white"}`}><UploadSimple/>{active?"رها کن":label}</button>}
function DropOverlay({active,label,onClick}:{active:boolean;label:string;onClick:()=>void}){return <button onClick={e=>{e.stopPropagation();onClick()}} className={`absolute inset-0 z-20 grid place-items-center transition ${active?"bg-violet-600/45 opacity-100":"bg-black/0 opacity-0 hover:bg-black/35 hover:opacity-100"}`}><span className="flex items-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-black text-slate-900 shadow-2xl"><Image/><UploadSimple/>{active?"همین‌جا رها کن":label}</span></button>}
function Editor({selected,theme,setTheme,pick}:{selected:Section;theme:Theme;setTheme:React.Dispatch<React.SetStateAction<Theme>>;pick:(t:MediaTarget)=>void}){const input="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-white";if(selected==="header")return <div className="mt-5"><label className="text-xs text-white/50">نام فروشگاه<input className={input} value={theme.header.storeName} onChange={e=>setTheme(t=>({...t,header:{...t.header,storeName:e.target.value}}))}/></label><button onClick={()=>pick("logo")} className="mt-3 w-full rounded-xl border border-white/10 p-3 text-xs">آپلود لوگو</button></div>;if(selected==="hero")return <div className="mt-5"><label className="text-xs text-white/50">عنوان Hero<input className={input} value={theme.hero.title} onChange={e=>setTheme(t=>({...t,hero:{...t.hero,title:e.target.value}}))}/></label><label className="mt-4 block text-xs text-white/50">توضیح<textarea className={input} value={theme.hero.subtitle} onChange={e=>setTheme(t=>({...t,hero:{...t.hero,subtitle:e.target.value}}))}/></label><button onClick={()=>pick("hero")} className="mt-3 w-full rounded-xl border border-white/10 p-3 text-xs">آپلود تصویر Hero</button><label className="mt-4 block text-xs text-white/50">ارتفاع {theme.hero.height}px<input type="range" min="280" max="700" value={theme.hero.height} onChange={e=>setTheme(t=>({...t,hero:{...t.hero,height:Number(e.target.value)}}))} className="mt-2 w-full"/></label></div>;if(selected==="banner")return <div className="mt-5"><label className="text-xs text-white/50">عنوان بنر<input className={input} value={theme.banner.title} onChange={e=>setTheme(t=>({...t,banner:{...t.banner,title:e.target.value}}))}/></label><button onClick={()=>pick("banner")} className="mt-3 w-full rounded-xl border border-white/10 p-3 text-xs">آپلود تصویر بنر</button><label className="mt-4 block text-xs text-white/50">ارتفاع {theme.banner.height}px<input type="range" min="140" max="420" value={theme.banner.height} onChange={e=>setTheme(t=>({...t,banner:{...t.banner,height:Number(e.target.value)}}))} className="mt-2 w-full"/></label></div>;if(selected==="products")return <div className="mt-5"><label className="text-xs text-white/50">عنوان محصولات<input className={input} value={theme.products.title} onChange={e=>setTheme(t=>({...t,products:{...t.products,title:e.target.value}}))}/></label><label className="mt-4 block text-xs text-white/50">ستون‌ها {theme.productColumns}<input type="range" min="2" max="5" value={theme.productColumns} onChange={e=>setTheme(t=>({...t,productColumns:Number(e.target.value)}))} className="mt-2 w-full"/></label></div>;return <div className="mt-5 text-xs text-white/50">این بخش تنظیمات محتوایی خودش را دارد و با Hero/Banner قاطی نیست.</div>}
