import {useEffect,useState} from "react";
import {Desktop,DeviceMobile,GearSix,X} from "@phosphor-icons/react";
import StoreWebsiteStudioPageV11 from "./StoreWebsiteStudioPageV11";
import {apiFetch} from "../lib/api";

type Project={id:string;content:Record<string,any>};
type Design={font:string;primary:string;surface:string;text:string;radius:number;productColumns:number;textScale:number;sectionGap:number};
const seed:Design={font:"Vazirmatn",primary:"#6d5dfc",surface:"#ffffff",text:"#111827",radius:18,productColumns:4,textScale:100,sectionGap:32};
const fonts=["Vazirmatn","IRANSansX","Peyda","Dana","Shabnam","Sahel","Tahoma","Arial"];
async function read(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"خطا");return d}
export default function StoreWebsiteStudioPageV12(){const[mode,setMode]=useState<"desktop"|"mobile">("desktop"),[project,setProject]=useState<Project|null>(null),[design,setDesign]=useState<Design>(seed),[open,setOpen]=useState(false),[msg,setMsg]=useState("");useEffect(()=>{void boot()},[]);useEffect(()=>{applyMode()},[mode]);useEffect(()=>{applyDesign()},[design,mode]);async function boot(){try{const d=await read(await apiFetch("/api/site-projects"));const p=(d.projects||[]).find((x:any)=>String(x.siteType).toUpperCase()==="STORE")||d.projects?.[0];if(!p)return;const detail=await read(await apiFetch(`/api/site-projects/${p.id}`));setProject(detail.project);const old=detail.project?.content?.storeBuilderV11?.design||{};setDesign({...seed,...old,textScale:old.textScale||100,sectionGap:old.sectionGap||32})}catch(e){setMsg(e instanceof Error?e.message:"خطا")}}
 function canvas(){const shell=[...document.querySelectorAll("section")].find(el=>String(el.className).includes("bg-[#252c38]"));return shell?.querySelector(":scope > div") as HTMLElement|null}
 function applyMode(){setTimeout(()=>{const el=canvas();if(!el)return;el.classList.toggle("loadder-mobile-frame",mode==="mobile");el.classList.toggle("loadder-desktop-frame",mode==="desktop");el.style.width=mode==="mobile"?"390px":"100%";el.style.minWidth=mode==="mobile"?"390px":"0";el.style.maxWidth=mode==="mobile"?"390px":"1180px";el.style.margin="0 auto";el.style.borderRadius=mode==="mobile"?"30px":"0";el.style.boxShadow=mode==="mobile"?"0 24px 70px rgba(0,0,0,.4)":"none";el.style.overflow="hidden"},30)}
 function applyDesign(){setTimeout(()=>{const el=canvas();if(!el)return;el.style.fontFamily=`${design.font}, Tahoma, sans-serif`;el.style.color=design.text;el.style.setProperty("--loadder-primary",design.primary);el.style.setProperty("--loadder-radius",`${design.radius}px`);el.style.setProperty("--loadder-text-scale",String(design.textScale/100));el.style.setProperty("--loadder-section-gap",`${design.sectionGap}px`)},30)}
 async function save(){if(!project)return;try{const current=project.content||{},builder=current.storeBuilderV11||{},v7=current.commerceStudioV7||{};const content={...current,storeBuilderV11:{...builder,design:{...(builder.design||{}),...design}},commerceStudioV7:{...v7,fontFamily:`${design.font}, Tahoma, sans-serif`,baseTextColor:design.text,accent:design.primary,surface:design.surface,cardRadius:design.radius}};const r=await read(await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})}));setProject(r.project);setMsg("طراحی ذخیره شد") }catch(e){setMsg(e instanceof Error?e.message:"ذخیره نشد")}}
 return <div className="studio-v12"><StoreWebsiteStudioPageV11/><div dir="rtl" className="fixed left-1/2 top-[118px] z-[260] flex -translate-x-1/2 items-center gap-1 rounded-2xl border border-white/15 bg-[#0b111a]/95 p-1.5 text-white shadow-2xl backdrop-blur"><button onClick={()=>setMode("desktop")} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-black ${mode==="desktop"?"bg-violet-600":"hover:bg-white/10"}`}><Desktop/>دسکتاپ</button><button onClick={()=>setMode("mobile")} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-black ${mode==="mobile"?"bg-violet-600":"hover:bg-white/10"}`}><DeviceMobile/>موبایل واقعی</button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-black hover:bg-white/10"><GearSix/>طراحی</button></div>{open&&<aside dir="rtl" className="fixed left-5 top-20 z-[300] w-[340px] max-w-[calc(100vw-40px)] rounded-3xl border border-white/10 bg-[#0d131d] p-5 text-white shadow-2xl"><div className="flex items-center justify-between"><div><b>Design System</b><p className="mt-1 text-[11px] text-white/45">فونت، رنگ، ابعاد و فاصله‌ها</p></div><button onClick={()=>setOpen(false)} className="rounded-lg bg-white/5 p-2"><X/></button></div><div className="mt-5 space-y-4"><label className="block text-xs text-white/60">فونت سایت<select value={design.font} onChange={e=>setDesign({...design,font:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 p-3 text-white">{fonts.map(f=><option key={f} value={f}>{f}</option>)}</select></label><Color label="رنگ اصلی برند" value={design.primary} onChange={v=>setDesign({...design,primary:v})}/><Color label="رنگ متن" value={design.text} onChange={v=>setDesign({...design,text:v})}/><Color label="پس‌زمینه" value={design.surface} onChange={v=>setDesign({...design,surface:v})}/><Range label={`مقیاس متن ${design.textScale}%`} min={80} max={130} value={design.textScale} onChange={v=>setDesign({...design,textScale:v})}/><Range label={`گردی کارت ${design.radius}px`} min={0} max={40} value={design.radius} onChange={v=>setDesign({...design,radius:v})}/><Range label={`فاصله سکشن‌ها ${design.sectionGap}px`} min={12} max={64} value={design.sectionGap} onChange={v=>setDesign({...design,sectionGap:v})}/></div><button onClick={()=>void save()} className="mt-5 w-full rounded-xl bg-violet-600 p-3 text-sm font-black">ذخیره Design System</button>{msg&&<p className="mt-3 text-[11px] text-white/55">{msg}</p>}</aside>}<style>{`
.studio-v12 .loadder-mobile-frame{background:#fff!important;position:relative!important}
.studio-v12 .loadder-mobile-frame [class*="grid-cols-4"],.studio-v12 .loadder-mobile-frame [style*="grid-template-columns"]{grid-template-columns:repeat(2,minmax(0,1fr))!important}
.studio-v12 .loadder-mobile-frame [class*="grid-cols-2"]{grid-template-columns:1fr!important}
.studio-v12 .loadder-mobile-frame [class*="gap-5"][class*="border-b"]{gap:8px!important;padding-left:12px!important;padding-right:12px!important;height:64px!important}
.studio-v12 .loadder-mobile-frame [class*="gap-5"][class*="border-b"]>[class*="flex-1"]{display:none!important}
.studio-v12 .loadder-mobile-frame [class*="gap-5"][class*="border-b"] button{padding:8px!important;font-size:10px!important}
.studio-v12 .loadder-mobile-frame section.relative.grid.place-items-center{height:520px!important;padding-left:24px!important;padding-right:24px!important;background-position:center center!important;background-size:cover!important}
.studio-v12 .loadder-mobile-frame section.relative.grid.place-items-center h1{font-size:34px!important;line-height:1.25!important;max-width:330px!important}
.studio-v12 .loadder-mobile-frame section.relative.grid.place-items-center p{font-size:15px!important;line-height:1.8!important}
.studio-v12 .loadder-mobile-frame section[class*="p-8"]{padding:16px!important}
.studio-v12 .loadder-mobile-frame section[class*="px-8"]{padding-left:16px!important;padding-right:16px!important}
.studio-v12 .loadder-mobile-frame section h2{font-size:22px!important}
.studio-v12 .loadder-mobile-frame article{border-radius:var(--loadder-radius)!important}
.studio-v12 .loadder-mobile-frame *{text-size-adjust:100%}
.studio-v12 .loadder-mobile-frame{font-size:calc(16px * var(--loadder-text-scale,1))}
.studio-v12 .loadder-desktop-frame{font-size:calc(16px * var(--loadder-text-scale,1))}
`}</style></div>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="flex items-center justify-between text-xs text-white/60"><span>{label}</span><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-16 rounded-lg bg-transparent"/></label>}
function Range({label,min,max,value,onChange}:{label:string;min:number;max:number;value:number;onChange:(v:number)=>void}){return <label className="block text-xs text-white/60">{label}<input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-2 w-full"/></label>}