import {useEffect,useMemo,useState} from "react";
import {ArrowRight,ArrowsDownUp,CheckCircle,Desktop,DeviceMobile,DeviceTablet,FloppyDisk,GearSix,Package,ShoppingCart} from "@phosphor-icons/react";
import {Link} from "react-router-dom";
import {apiFetch} from "../lib/api";
import {productMainImage} from "../lib/productMedia";

type DeviceMode="desktop"|"tablet"|"mobile";
type CommercePreviewMode="storefront"|"cart"|"checkout"|"success";
type Panel="commerce"|"design"|"sections";
type Product={id:string;name:string;currency:string;basePriceMinor:number;compareAtPriceMinor?:number|null;metadata?:{gallery?:string[]};variants?:Array<{inventoryQuantity:number;imageUrl?:string|null}>};
type ProductOverride={title:string;regularPriceMinor:number;compareAtPriceMinor:number|null;promotionBadge:boolean;promotionBadgeText:string};
type CommerceConfig={currency:string;lowStockThreshold:number;allowBackorder:boolean;showCoupon:boolean;freeShippingThresholdMinor:number;shippingLabel:string;collectEmail:boolean;collectPostalCode:boolean;paymentMode:"MANUAL"|"ONLINE";orderSuccessTitle:string;cartButtonLabel:string;checkoutButtonLabel:string;productOverrides:Record<string,ProductOverride>};
type DesignSettings={fontFamily:string;primaryColor:string;textColor:string;backgroundColor:string;typographyScale:number;borderRadius:number;sectionSpacing:number;heroOverlayIntensity:number;headingSize:number;bodyTextSize:number;buttonRadius:number;cardShadowStrength:number};
type Section={id:string;type:"products"|"banner"|"trust"|"text";title:string;enabled:boolean};
type Project={id:string;name?:string;content:Record<string,any>};

const commerceSeed:CommerceConfig={currency:"IRT",lowStockThreshold:3,allowBackorder:false,showCoupon:true,freeShippingThresholdMinor:0,shippingLabel:"ارسال استاندارد",collectEmail:false,collectPostalCode:true,paymentMode:"MANUAL",orderSuccessTitle:"سفارش شما با موفقیت ثبت شد",cartButtonLabel:"افزودن به سبد خرید",checkoutButtonLabel:"ادامه و ثبت سفارش",productOverrides:{}};
const designSeed:DesignSettings={fontFamily:"Vazirmatn",primaryColor:"#6d5dfc",textColor:"#111827",backgroundColor:"#ffffff",typographyScale:100,borderRadius:18,sectionSpacing:32,heroOverlayIntensity:38,headingSize:38,bodyTextSize:16,buttonRadius:12,cardShadowStrength:12};
const sectionSeed:Section[]=[{id:"products",type:"products",title:"محصولات منتخب",enabled:true},{id:"banner",type:"banner",title:"پیشنهاد ویژه",enabled:true},{id:"trust",type:"trust",title:"خرید مطمئن",enabled:true}];
const fonts=["Vazirmatn","IRANSansX","Peyda","Dana","Shabnam","Sahel","Tahoma","Arial"];

async function read(response:Response){const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"خطا در ارتباط با سرور");return data}
function restoreDesign(content:Record<string,any>):DesignSettings{const legacy=content.storeBuilderV11?.design||{},v13=content.storeBuilderV13?.design||{};return{...designSeed,fontFamily:legacy.font||designSeed.fontFamily,primaryColor:legacy.primary||designSeed.primaryColor,textColor:legacy.text||designSeed.textColor,backgroundColor:legacy.surface||designSeed.backgroundColor,borderRadius:legacy.radius??designSeed.borderRadius,typographyScale:legacy.textScale??designSeed.typographyScale,sectionSpacing:legacy.sectionGap??designSeed.sectionSpacing,...v13,...content.storeBuilderV15?.design}}
function toSection(value:any,index:number):Section{return{id:String(value?.id||`section-${index}`),type:value?.type==="product-slider"?"products":value?.type==="banner-grid"?"banner":value?.type==="trust"?"trust":"text",title:String(value?.title||"بخش فروشگاه"),enabled:value?.enabled!==false}}
function formatMoney(value:number,currency:string){return `${new Intl.NumberFormat("fa-IR").format(Math.max(0,value)/100)} ${currency==="IRT"?"تومان":currency}`}

export default function StoreWebsiteStudioPageV15(){
  const[project,setProject]=useState<Project|null>(null),[products,setProducts]=useState<Product[]>([]),[commerce,setCommerce]=useState<CommerceConfig>(commerceSeed),[design,setDesign]=useState<DesignSettings>(designSeed),[sections,setSections]=useState<Section[]>(sectionSeed),[device,setDevice]=useState<DeviceMode>("desktop"),[previewMode,setPreviewMode]=useState<CommercePreviewMode>("storefront"),[panel,setPanel]=useState<Panel>("commerce"),[selectedProductId,setSelectedProductId]=useState(""),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
  useEffect(()=>{const controller=new AbortController();void(async()=>{try{const listing=await read(await apiFetch("/api/site-projects",{signal:controller.signal})),selected=(listing.projects||[]).find((item:any)=>String(item.siteType).toUpperCase()==="STORE")||listing.projects?.[0];if(!selected)throw new Error("پروژه فروشگاهی پیدا نشد");const detail=await read(await apiFetch(`/api/site-projects/${selected.id}`,{signal:controller.signal})),loaded=detail.project as Project,content=loaded.content||{},v15=content.storeBuilderV15||{},v14=content.storeBuilderV14?.commerce||{};setProject(loaded);setCommerce({...commerceSeed,...v14,...v15.commerce,productOverrides:{...commerceSeed.productOverrides,...v15.commerce?.productOverrides}});setDesign(restoreDesign(content));const savedSections=Array.isArray(v15.sections)?v15.sections:Array.isArray(content.storeBuilderV11?.sections)?content.storeBuilderV11.sections.map(toSection):sectionSeed;setSections(savedSections);if(["storefront","cart","checkout","success"].includes(v15.previewMode))setPreviewMode(v15.previewMode);const catalog=await read(await apiFetch(`/api/stores/${selected.id}/products`,{signal:controller.signal}));setProducts(catalog.products||[]);setSelectedProductId(catalog.products?.[0]?.id||"")}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;setMessage(error instanceof Error?error.message:"خطا در بارگذاری Studio")}finally{if(!controller.signal.aborted)setBusy(false)}})();return()=>controller.abort()},[]);
  const selectedProduct=products.find(product=>product.id===selectedProductId)||products[0]||null;
  const visibleSections=useMemo(()=>sections.filter(section=>section.enabled),[sections]);
  function productView(product:Product){const saved=commerce.productOverrides[product.id];return{title:saved?.title||product.name,regularPriceMinor:saved?.regularPriceMinor??product.basePriceMinor,compareAtPriceMinor:saved?.compareAtPriceMinor??product.compareAtPriceMinor??null,promotionBadge:saved?.promotionBadge??false,promotionBadgeText:saved?.promotionBadgeText||"فروش ویژه"}}
  function updateProduct(change:Partial<ProductOverride>){if(!selectedProduct)return;const current=productView(selectedProduct);setCommerce(value=>({...value,productOverrides:{...value.productOverrides,[selectedProduct.id]:{...current,...change}}}))}
  async function save(){if(!project)return;setBusy(true);setMessage("");try{const content={...project.content,storeBuilderV15:{version:15,commerce,design,sections,previewMode}};const output=await read(await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})}));setProject(output.project);setMessage("تنظیمات Commerce Studio V15 ذخیره شد")}catch(error){setMessage(error instanceof Error?error.message:"ذخیره انجام نشد")}finally{setBusy(false)}}
  return <main dir="rtl" className="h-screen overflow-hidden bg-[#070b12] text-white" data-studio-version="15">
    <style>{`[data-studio-version="15"] .control{width:100%;min-height:44px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:#0f172a;padding:0 12px;color:white;outline:none}[data-studio-version="15"] .control:focus{border-color:#34d399}[data-studio-version="15"] .eyebrow{font-size:10px;font-weight:900;letter-spacing:.16em;color:#6ee7b7}[data-studio-version="15"] .panel-card{margin-top:16px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:rgba(255,255,255,.05);padding:16px;display:grid;gap:16px}`}</style>
    <header className="flex min-h-20 flex-wrap items-center justify-between gap-3 border-b border-emerald-400/15 bg-[#0b121c] px-4 py-3"><div className="flex items-center gap-3"><Link to="/dashboard" aria-label="بازگشت به داشبورد" className="grid min-h-11 min-w-11 place-items-center rounded-xl border border-white/10 bg-white/5"><ArrowRight/></Link><div><div className="text-[10px] font-black tracking-[.18em] text-emerald-300">LOADDER COMMERCE PLATFORM</div><h1 className="text-base font-black sm:text-lg">Loadder Commerce Studio V15</h1><p className="text-[10px] text-white/40">{project?.name||"ویرایش تجربه فروشگاه"}</p></div></div><Toolbar device={device} setDevice={setDevice} previewMode={previewMode} setPreviewMode={setPreviewMode}/><button type="button" disabled={busy||!project} onClick={()=>void save()} className="flex min-h-11 items-center gap-2 rounded-xl bg-emerald-400 px-4 text-sm font-black text-slate-950 disabled:opacity-40"><FloppyDisk/>ذخیره V15</button></header>
    <div className="grid h-[calc(100vh-80px)] grid-cols-1 lg:grid-cols-[minmax(0,1fr)_380px]"><section className="order-2 overflow-auto bg-[#202936] p-4 sm:p-7 lg:order-1">{busy&&!project?<div className="grid min-h-96 place-items-center text-white/50">در حال آماده‌سازی Commerce Studio…</div>:<PreviewFrame device={device} design={design}><CommercePreview mode={previewMode} device={device} design={design} commerce={commerce} products={products} productView={productView} sections={visibleSections}/></PreviewFrame>}</section><aside className="order-1 max-h-[46vh] overflow-y-auto border-b border-white/10 bg-[#0e1622] p-5 lg:order-2 lg:max-h-none lg:border-b-0 lg:border-r"><div className="grid grid-cols-3 gap-1 rounded-2xl bg-black/20 p-1"><PanelButton active={panel==="commerce"} onClick={()=>setPanel("commerce")} icon={<ShoppingCart/>}>تجارت</PanelButton><PanelButton active={panel==="design"} onClick={()=>setPanel("design")} icon={<GearSix/>}>طراحی</PanelButton><PanelButton active={panel==="sections"} onClick={()=>setPanel("sections")} icon={<ArrowsDownUp/>}>بخش‌ها</PanelButton></div>{panel==="commerce"&&<CommercePanel products={products} selectedProductId={selectedProductId} setSelectedProductId={setSelectedProductId} selectedProduct={selectedProduct} view={selectedProduct?productView(selectedProduct):null} updateProduct={updateProduct} commerce={commerce} setCommerce={setCommerce}/>} {panel==="design"&&<DesignPanel design={design} setDesign={setDesign}/>} {panel==="sections"&&<SectionsPanel sections={sections} setSections={setSections}/>} {message&&<p role="status" className="mt-5 rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/65">{message}</p>}<p className="mt-5 text-[10px] leading-5 text-white/35">V15 فقط configuration و preview را ذخیره می‌کند. Runtime عمومی Cart/Checkout/Order بدون تغییر باقی می‌ماند.</p></aside></div>
  </main>
}

function Toolbar({device,setDevice,previewMode,setPreviewMode}:{device:DeviceMode;setDevice:(value:DeviceMode)=>void;previewMode:CommercePreviewMode;setPreviewMode:(value:CommercePreviewMode)=>void}){return <div className="flex flex-wrap items-center justify-center gap-2"><nav aria-label="اندازه پیش‌نمایش" className="flex rounded-2xl border border-white/10 bg-white/5 p-1">{([['desktop','دسکتاپ',Desktop],['tablet','تبلت',DeviceTablet],['mobile','موبایل',DeviceMobile]] as const).map(([value,label,Icon])=><button key={value} type="button" aria-pressed={device===value} onClick={()=>setDevice(value)} className={`flex min-h-10 items-center gap-1 rounded-xl px-3 text-xs font-bold ${device===value?'bg-emerald-400 text-slate-950':'text-white/60'}`}><Icon/>{label}</button>)}</nav><nav aria-label="صفحه تجارت" className="flex max-w-full overflow-x-auto rounded-2xl border border-white/10 bg-white/5 p-1">{([['storefront','فروشگاه'],['cart','سبد'],['checkout','تسویه'],['success','موفقیت']] as const).map(([value,label])=><button key={value} type="button" aria-pressed={previewMode===value} onClick={()=>setPreviewMode(value)} className={`min-h-10 whitespace-nowrap rounded-xl px-3 text-xs font-bold ${previewMode===value?'bg-violet-600':'text-white/60'}`}>{label}</button>)}</nav></div>}
function PreviewFrame({device,design,children}:{device:DeviceMode;design:DesignSettings;children:React.ReactNode}){const width=device==="desktop"?"100%":device==="tablet"?"768px":"390px";return <div className="mx-auto min-h-full" data-preview-device={device} style={{width,maxWidth:device==="desktop"?"1180px":undefined}}><div className="min-h-[680px] overflow-hidden bg-white transition-[width,border-radius]" style={{borderRadius:device==="desktop"?4:24,fontFamily:`${design.fontFamily},Tahoma,sans-serif`,color:design.textColor,boxShadow:"0 24px 80px rgba(0,0,0,.3)"}}>{children}</div></div>}

function CommercePreview({mode,device,design,commerce,products,productView,sections}:{mode:CommercePreviewMode;device:DeviceMode;design:DesignSettings;commerce:CommerceConfig;products:Product[];productView:(product:Product)=>ReturnType<typeof normalizeView>;sections:Section[]}){const mobile=device==="mobile",sample=products.slice(0,mobile?4:8);if(mode==="cart")return <CartPreview design={design} commerce={commerce} products={sample} productView={productView} mobile={mobile}/>;if(mode==="checkout")return <CheckoutPreview design={design} commerce={commerce} mobile={mobile}/>;if(mode==="success")return <SuccessPreview design={design} commerce={commerce}/>;return <div style={{background:design.backgroundColor,fontSize:`${design.bodyTextSize}px`}}><StoreHeader mobile={mobile} design={design}/><section className="px-5 py-10 text-white" style={{background:`linear-gradient(135deg,${design.primaryColor},#111827)`}}><span className="rounded-full bg-white/15 px-3 py-1 text-xs">فروشگاه شما</span><h2 className="mt-4 font-black" style={{fontSize:mobile?Math.max(27,design.headingSize*.72):design.headingSize}}>فروش آنلاین، ساده و قابل مدیریت</h2><p className="mt-3 max-w-xl opacity-80">پیش‌نمایش زنده کارت محصول، قیمت‌گذاری و تجربه خرید.</p></section>{sections.map(section=>section.type==="products"?<section key={section.id} style={{padding:mobile?16:design.sectionSpacing}}><h3 className="mb-5 text-xl font-black">{section.title}</h3><div className="grid gap-3" style={{gridTemplateColumns:`repeat(${mobile?2:device==='tablet'?3:4},minmax(0,1fr))`}}>{sample.map(product=><ProductCard key={product.id} product={product} view={productView(product)} design={design} commerce={commerce}/>)}</div></section>:section.type==="banner"?<section key={section.id} className="grid gap-3 p-5" style={{gridTemplateColumns:mobile?'1fr':'repeat(2,minmax(0,1fr))'}}><div className="min-h-32 rounded-3xl p-5 text-white" style={{background:design.primaryColor}}><b>{section.title}</b><p className="mt-2 text-xs opacity-75">{commerce.shippingLabel}</p></div><div className="min-h-32 rounded-3xl bg-slate-900 p-5 text-white"><b>ارسال رایگان</b><p className="mt-2 text-xs opacity-75">از {formatMoney(commerce.freeShippingThresholdMinor,commerce.currency)}</p></div></section>:<section key={section.id} className="p-5"><div className="rounded-3xl bg-slate-50 p-5 text-center text-sm">{section.title} · پرداخت امن · پشتیبانی فروشگاه</div></section>)}</div>}
function normalizeView(){return{title:"",regularPriceMinor:0,compareAtPriceMinor:null as number|null,promotionBadge:false,promotionBadgeText:""}}
function StoreHeader({mobile,design}:{mobile:boolean;design:DesignSettings}){return <header className="flex min-h-16 items-center gap-3 border-b px-4"><b className="flex-1">فروشگاه شما</b>{!mobile&&<div className="min-w-64 rounded-xl bg-slate-100 px-4 py-3 text-xs text-slate-400">جستجو در محصولات</div>}<button className="grid min-h-11 min-w-11 place-items-center rounded-xl border" style={{borderRadius:design.buttonRadius}}><ShoppingCart/></button></header>}
function ProductCard({product,view,design,commerce}:{product:Product;view:ReturnType<typeof normalizeView>;design:DesignSettings;commerce:CommerceConfig}){const image=productMainImage(product);return <article className="relative overflow-hidden border bg-white" style={{borderRadius:design.borderRadius,boxShadow:`0 8px 24px rgba(15,23,42,${design.cardShadowStrength/200})`}}>{view.promotionBadge&&<span className="absolute right-2 top-2 z-10 rounded-full px-2 py-1 text-[10px] font-black text-white" style={{background:design.primaryColor}}>{view.promotionBadgeText}</span>}<div className="aspect-square bg-slate-100">{image?<img src={image} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-slate-300"><Package size={36}/></div>}</div><div className="p-3"><b className="line-clamp-2 text-sm">{view.title}</b>{view.compareAtPriceMinor&&view.compareAtPriceMinor>view.regularPriceMinor?<small className="mt-2 block text-slate-400 line-through">{formatMoney(view.compareAtPriceMinor,product.currency)}</small>:null}<div className="mt-1 font-black" style={{color:design.primaryColor}}>{formatMoney(view.regularPriceMinor,product.currency)}</div><button className="mt-3 min-h-11 w-full px-2 text-xs font-black text-white" style={{background:design.primaryColor,borderRadius:design.buttonRadius}}>{commerce.cartButtonLabel}</button></div></article>}
function CartPreview({design,commerce,products,productView,mobile}:{design:DesignSettings;commerce:CommerceConfig;products:Product[];productView:(product:Product)=>ReturnType<typeof normalizeView>;mobile:boolean}){const shown=products.slice(0,2),total=shown.reduce((sum,p)=>sum+productView(p).regularPriceMinor,0);return <div className="min-h-[680px] bg-slate-50 p-5"><h2 className="text-xl font-black">سبد خرید</h2><div className={`mt-5 grid gap-5 ${mobile?'':'grid-cols-[1fr_300px]'}`}><div className="space-y-3">{shown.map(product=><div key={product.id} className="flex items-center gap-3 rounded-2xl border bg-white p-3"><div className="h-16 w-16 rounded-xl bg-slate-100"/><div className="flex-1"><b>{productView(product).title}</b><p className="text-xs text-slate-400">تعداد: ۱</p></div><b>{formatMoney(productView(product).regularPriceMinor,product.currency)}</b></div>)}</div><aside className="rounded-3xl border bg-white p-5"><b>خلاصه سفارش</b><p className="mt-4 flex justify-between"><span>{commerce.shippingLabel}</span><span>{total>=commerce.freeShippingThresholdMinor&&commerce.freeShippingThresholdMinor>0?'رایگان':'محاسبه در مرحله بعد'}</span></p><button className="mt-5 min-h-12 w-full text-white" style={{background:design.primaryColor,borderRadius:design.buttonRadius}}>{commerce.checkoutButtonLabel}</button></aside></div></div>}
function CheckoutPreview({design,commerce,mobile}:{design:DesignSettings;commerce:CommerceConfig;mobile:boolean}){return <div className="min-h-[680px] bg-slate-50 p-5"><h2 className="text-xl font-black">تکمیل سفارش</h2><div className={`mt-5 grid gap-5 ${mobile?'':'grid-cols-[1fr_300px]'}`}><div className="space-y-4"><PreviewBox title="اطلاعات گیرنده"><div className="grid grid-cols-2 gap-2"><FakeInput label="نام و نام خانوادگی"/><FakeInput label="موبایل"/><FakeInput label="استان"/><FakeInput label="شهر"/></div></PreviewBox><PreviewBox title="روش ارسال"><div className="flex min-h-14 items-center justify-between rounded-xl border p-3"><span>{commerce.shippingLabel}</span><CheckCircle color={design.primaryColor}/></div></PreviewBox><PreviewBox title="روش پرداخت"><p className="text-sm text-slate-500">اتصال Payment Adapter در Runtime فعلی مدیریت می‌شود.</p></PreviewBox></div><aside className="rounded-3xl border bg-white p-5"><b>خلاصه پرداخت</b><button className="mt-5 min-h-12 w-full text-white" style={{background:design.primaryColor,borderRadius:design.buttonRadius}}>{commerce.checkoutButtonLabel}</button></aside></div></div>}
function SuccessPreview({design,commerce}:{design:DesignSettings;commerce:CommerceConfig}){return <div className="grid min-h-[680px] place-items-center bg-slate-50 p-6 text-center"><div className="max-w-md rounded-[32px] border bg-white p-8 shadow-sm"><CheckCircle size={64} weight="fill" className="mx-auto" color={design.primaryColor}/><h2 className="mt-5 text-2xl font-black">{commerce.orderSuccessTitle}</h2><p className="mt-3 text-sm leading-7 text-slate-500">سفارش ثبت شده و جزئیات آن از Runtime فعلی Commerce دریافت می‌شود.</p><button className="mt-6 min-h-12 px-6 text-white" style={{background:design.primaryColor,borderRadius:design.buttonRadius}}>بازگشت به فروشگاه</button></div></div>}
function PreviewBox({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl border bg-white p-5"><h3 className="mb-4 font-black">{title}</h3>{children}</section>}
function FakeInput({label}:{label:string}){return <div className="min-h-12 rounded-xl border px-3 py-2 text-xs text-slate-400">{label}</div>}

function CommercePanel({products,selectedProductId,setSelectedProductId,selectedProduct,view,updateProduct,commerce,setCommerce}:{products:Product[];selectedProductId:string;setSelectedProductId:(value:string)=>void;selectedProduct:Product|null;view:ReturnType<typeof normalizeView>|null;updateProduct:(change:Partial<ProductOverride>)=>void;commerce:CommerceConfig;setCommerce:React.Dispatch<React.SetStateAction<CommerceConfig>>}){const patch=<K extends keyof CommerceConfig>(key:K,value:CommerceConfig[K])=>setCommerce(current=>({...current,[key]:value}));return <div className="mt-6 space-y-5"><div><p className="text-[10px] font-black tracking-[.16em] text-emerald-300">PRODUCT CARD</p><h2 className="mt-1 font-black">ویرایش کارت محصول</h2><select value={selectedProductId} onChange={event=>setSelectedProductId(event.target.value)} className="mt-3 min-h-11 w-full rounded-xl border border-white/10 bg-slate-900 px-3 text-sm text-white">{products.map(product=><option key={product.id} value={product.id}>{product.name}</option>)}</select></div>{selectedProduct&&view?<section className="space-y-4 rounded-2xl border border-white/10 bg-white/5 p-4"><TextField label="عنوان محصول" value={view.title} onChange={value=>updateProduct({title:value})}/><NumberField label="قیمت اصلی (واحد کوچک پول)" value={view.regularPriceMinor} onChange={value=>updateProduct({regularPriceMinor:value})}/><NumberField label="Compare-at / قیمت قبل" value={view.compareAtPriceMinor||0} onChange={value=>updateProduct({compareAtPriceMinor:value||null})}/><Toggle label="نمایش نشان فروش ویژه" checked={view.promotionBadge} onChange={value=>updateProduct({promotionBadge:value})}/><TextField label="متن نشان فروش ویژه" value={view.promotionBadgeText} onChange={value=>updateProduct({promotionBadgeText:value})}/></section>:<p className="rounded-2xl border border-white/10 bg-white/5 p-4 text-xs text-white/45">محصولی برای پیش‌نمایش موجود نیست.</p>}<section className="space-y-4 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-[10px] font-black tracking-[.16em] text-emerald-300">CART & CHECKOUT COPY</p><TextField label="متن دکمه سبد" value={commerce.cartButtonLabel} onChange={value=>patch("cartButtonLabel",value)}/><TextField label="عنوان ارسال" value={commerce.shippingLabel} onChange={value=>patch("shippingLabel",value)}/><NumberField label="آستانه ارسال رایگان" value={commerce.freeShippingThresholdMinor} onChange={value=>patch("freeShippingThresholdMinor",value)}/><TextField label="متن دکمه Checkout" value={commerce.checkoutButtonLabel} onChange={value=>patch("checkoutButtonLabel",value)}/><TextField label="عنوان موفقیت سفارش" value={commerce.orderSuccessTitle} onChange={value=>patch("orderSuccessTitle",value)}/></section></div>}
function DesignPanel({design,setDesign}:{design:DesignSettings;setDesign:React.Dispatch<React.SetStateAction<DesignSettings>>}){const patch=<K extends keyof DesignSettings>(key:K,value:DesignSettings[K])=>setDesign(current=>({...current,[key]:value}));return <div className="mt-6 space-y-4"><p className="eyebrow">DESIGN SYSTEM</p><select value={design.fontFamily} onChange={event=>patch("fontFamily",event.target.value)} className="control">{fonts.map(font=><option key={font}>{font}</option>)}</select><div className="grid grid-cols-3 gap-2"><Color label="اصلی" value={design.primaryColor} onChange={value=>patch("primaryColor",value)}/><Color label="متن" value={design.textColor} onChange={value=>patch("textColor",value)}/><Color label="زمینه" value={design.backgroundColor} onChange={value=>patch("backgroundColor",value)}/></div>{([['typographyScale','مقیاس تایپوگرافی',80,130],['borderRadius','گردی کارت',0,36],['sectionSpacing','فاصله بخش‌ها',12,72],['heroOverlayIntensity','شدت پوشش Hero',0,90],['headingSize','اندازه تیتر',24,64],['bodyTextSize','اندازه متن',13,22],['buttonRadius','گردی دکمه',0,32],['cardShadowStrength','شدت سایه کارت',0,40]] as const).map(([key,label,min,max])=><Range key={key} label={label} min={min} max={max} value={design[key]} onChange={value=>patch(key,value)}/>)}</div>}
function SectionsPanel({sections,setSections}:{sections:Section[];setSections:React.Dispatch<React.SetStateAction<Section[]>>}){function move(index:number,delta:number){const target=index+delta;if(target<0||target>=sections.length)return;setSections(current=>{const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next})}return <div className="mt-6"><p className="eyebrow">SECTIONS</p><h2 className="mt-1 font-black">مدیریت بخش‌های فروشگاه</h2><div className="mt-4 space-y-3">{sections.map((section,index)=><article key={section.id} className="panel-card"><div className="flex items-center gap-2"><input type="checkbox" checked={section.enabled} onChange={event=>setSections(current=>current.map(item=>item.id===section.id?{...item,enabled:event.target.checked}:item))}/><input value={section.title} onChange={event=>setSections(current=>current.map(item=>item.id===section.id?{...item,title:event.target.value}:item))} className="control min-w-0 flex-1"/><button onClick={()=>move(index,-1)} className="min-h-10 min-w-8">↑</button><button onClick={()=>move(index,1)} className="min-h-10 min-w-8">↓</button></div></article>)}</div></div>}
function PanelButton({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:React.ReactNode;children:React.ReactNode}){return <button type="button" onClick={onClick} className={`flex min-h-11 items-center justify-center gap-1 rounded-xl text-xs font-black ${active?'bg-emerald-400 text-slate-950':'text-white/55'}`}>{icon}{children}</button>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="block text-xs text-white/60">{label}<input value={value} onChange={event=>onChange(event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-slate-900 px-3 text-sm text-white outline-none focus:border-emerald-400"/></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className="block text-xs text-white/60">{label}<input type="number" min={0} value={value} onChange={event=>onChange(Math.max(0,Number(event.target.value)||0))} className="mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-slate-900 px-3 text-sm text-white outline-none focus:border-emerald-400"/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex min-h-11 items-center justify-between rounded-xl bg-black/20 px-3 text-xs text-white/65"><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="h-5 w-5 accent-emerald-400"/></label>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="rounded-xl border border-white/10 p-2 text-center text-[10px] text-white/55"><input aria-label={`رنگ ${label}`} type="color" value={value} onChange={event=>onChange(event.target.value)} className="mb-1 h-9 w-full bg-transparent"/>{label}</label>}
function Range({label,min,max,value,onChange}:{label:string;min:number;max:number;value:number;onChange:(value:number)=>void}){return <label className="block text-xs text-white/60"><span className="flex justify-between"><span>{label}</span><b>{value}</b></span><input type="range" min={min} max={max} value={value} onChange={event=>onChange(Number(event.target.value))} className="mt-2 w-full"/></label>}
