import { useEffect,useMemo,useState } from "react";
import { ArrowRight,ChartLineUp,Checks,Cube,Globe,MagicWand,Megaphone,Package,PaintBrush,Receipt,ShoppingCartSimple,Storefront,Truck,UsersThree,Wallet } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string;content:Record<string,unknown>};
type Product={id:string;status:string;variants:Array<{inventoryQuantity:number}>};
type Order={id:string;status:string;paymentStatus:string;fulfillmentStatus:string;totalMinor:number;currency:string};
type Setup={industry?:string;channels?:string[];storeName?:string;currency?:string;country?:string;completed?:boolean};
async function json(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"خطا در دریافت اطلاعات فروشگاه");return d}
const money=(minor:number,currency="IRT")=>new Intl.NumberFormat("fa-IR",{maximumFractionDigits:0}).format(currency==="IRT"?minor/100:minor/100)+` ${currency}`;
export default function StoreAdminDashboardPage(){
 const[project,setProject]=useState<Project|null>(null),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{void boot()},[]);
 async function boot(){try{const p=await json(await apiFetch("/api/site-projects"));const store=(p.projects||[]).find((x:Project)=>String(x.siteType).toUpperCase()==="STORE")||p.projects?.[0];if(!store)throw new Error("پروژه فروشگاهی پیدا نشد.");const [detail,pc,oc]=await Promise.all([json(await apiFetch(`/api/site-projects/${store.id}`)),json(await apiFetch(`/api/stores/${store.id}/products`)),json(await apiFetch(`/api/stores/${store.id}/orders`))]);setProject(detail.project);setProducts(pc.products||[]);setOrders(oc.orders||[])}catch(e){setMessage(e instanceof Error?e.message:"خطا")}}
 const setup=(project?.content?.storeSetupV10||{}) as Setup;
 const stock=useMemo(()=>products.reduce((sum,p)=>sum+p.variants.reduce((x,v)=>x+Number(v.inventoryQuantity||0),0),0),[products]);
 const revenue=useMemo(()=>orders.filter(o=>!['CANCELLED','REFUNDED'].includes(o.status)).reduce((s,o)=>s+Number(o.totalMinor||0),0),[orders]);
 const completed=orders.filter(o=>o.status==="COMPLETED").length;
 const checklist=[
  {title:"تنظیمات عمومی",done:!!setup.completed,href:"/dashboard/websites/setup",icon:<Checks/>},
  {title:"افزودن محصول",done:products.length>0,href:"/dashboard/websites/commerce",icon:<Cube/>},
  {title:"طراحی فروشگاه",done:true,href:"/dashboard/websites",icon:<PaintBrush/>},
  {title:"اتصال دامنه",done:false,href:"/dashboard/site-operations",icon:<Globe/>},
  {title:"روش‌های ارسال",done:false,href:"/dashboard/websites/commerce",icon:<Truck/>},
  {title:"روش‌های پرداخت",done:false,href:"/dashboard/websites/commerce",icon:<Wallet/>},
 ];
 const grow=[{title:"اتصال Google Ads و Conversion",href:"/dashboard/ads",icon:<Megaphone/>},{title:"CRM و مشتریان",href:"/dashboard/crm",icon:<UsersThree/>},{title:"اتوماسیون بازیابی سبد رهاشده",href:"/dashboard/automation",icon:<MagicWand/>},{title:"گزارش و تحلیل فروش",href:"/dashboard/analytics",icon:<ChartLineUp/>}];
 return <main dir="rtl" className="min-h-screen bg-[#f4f6fa] text-slate-900"><header className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-4"><div className="flex items-center gap-3"><Link to="/dashboard" className="rounded-xl border p-2"><ArrowRight/></Link><div><div className="text-xs text-slate-400">Loadder Commerce</div><h1 className="font-black">{setup.storeName||project?.name||"فروشگاه"}</h1></div></div><div className="flex gap-2"><Link to="/dashboard/websites" className="rounded-xl border px-4 py-2 text-sm font-bold">طراحی سایت</Link><Link to="/dashboard/websites/commerce" className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-black text-white">مدیریت محصولات</Link></div></div></header><div className="mx-auto max-w-7xl px-5 py-7">{message&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</div>}
 <section className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Cube/>} title="تعداد محصولات" value={String(products.length)}/><Stat icon={<Package/>} title="موجودی کل" value={String(stock)}/><Stat icon={<ShoppingCartSimple/>} title="سفارش‌ها" value={String(orders.length)}/><Stat icon={<Receipt/>} title="فروش ثبت‌شده" value={money(revenue,orders[0]?.currency||setup.currency||"IRT")}/></section>
 <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-black">مراحل فعال‌سازی فروشگاه</h2><p className="mt-1 text-sm text-slate-400">از راه‌اندازی تا اولین فروش، مرحله‌ها را همینجا ببند.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{checklist.filter(x=>x.done).length}/{checklist.length} تکمیل</span></div><div className="divide-y">{checklist.map((x,i)=><Link key={x.title} to={x.href} className="flex items-center gap-4 py-4 hover:bg-slate-50"><span className={`grid h-10 w-10 place-items-center rounded-full font-black ${x.done?"bg-emerald-100 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{x.done?<Checks/>:i+1}</span><span className="text-xl text-slate-400">{x.icon}</span><div className="flex-1"><b>{x.title}</b><div className="text-xs text-slate-400">{x.done?"انجام شده":"نیاز به تکمیل"}</div></div><ArrowRight className="rotate-180 text-slate-300"/></Link>)}</div></section>
 <section className="rounded-3xl bg-[#101827] p-6 text-white shadow-sm"><div className="flex items-center gap-3"><Storefront size={28} className="text-violet-300"/><div><h2 className="text-xl font-black">وضعیت فروشگاه</h2><p className="text-xs text-white/45">مرکز کنترل Commerce</p></div></div><div className="mt-6 space-y-3 text-sm"><Row k="حوزه" v={setup.industry||"تعیین نشده"}/><Row k="کشور" v={setup.country||"—"}/><Row k="ارز" v={setup.currency||"—"}/><Row k="کانال‌های فروش" v={String(setup.channels?.length||0)}/><Row k="سفارش تکمیل‌شده" v={String(completed)}/></div><Link to="/dashboard/websites/setup" className="mt-6 block rounded-xl bg-white px-4 py-3 text-center text-sm font-black text-slate-900">ویرایش تنظیمات فروشگاه</Link></section></div>
 <section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-5"><h2 className="text-xl font-black">افزایش فروش</h2><p className="mt-1 text-sm text-slate-400">اینجا جایی است که Loadder از یک فروشگاه‌ساز ساده جدا می‌شود.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{grow.map(x=><Link key={x.title} to={x.href} className="rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-50 text-2xl text-violet-700">{x.icon}</span><b className="mt-4 block">{x.title}</b><span className="mt-2 block text-xs leading-6 text-slate-400">ورود به ابزار و اتصال به داده‌های فروشگاه</span></Link>)}</div></section>
 <section className="mt-6 grid gap-4 md:grid-cols-3"><Quick title="محصولات و موجودی" sub="کاتالوگ، SKU و کنترل موجودی" href="/dashboard/websites/commerce" icon={<Cube/>}/><Quick title="سفارش و تست خرید" sub="مسیر Cart → Checkout → Order" href="/dashboard/websites/storefront-test" icon={<ShoppingCartSimple/>}/><Quick title="Visual Website Studio" sub="طراحی Hero، Banner و Product Blocks" href="/dashboard/websites" icon={<PaintBrush/>}/></section></div></main>}
function Stat({icon,title,value}:{icon:React.ReactNode;title:string;value:string}){return <div className="flex items-center gap-4 rounded-2xl border bg-white p-5 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-xl bg-violet-50 text-2xl text-violet-700">{icon}</span><div><div className="text-xs text-slate-400">{title}</div><b className="text-xl">{value}</b></div></div>}
function Row({k,v}:{k:string;v:string}){return <div className="flex items-center justify-between rounded-xl bg-white/5 px-4 py-3"><span className="text-white/50">{k}</span><b>{v}</b></div>}
function Quick({title,sub,href,icon}:{title:string;sub:string;href:string;icon:React.ReactNode}){return <Link to={href} className="flex items-center gap-4 rounded-2xl border bg-white p-5 shadow-sm hover:border-violet-300"><span className="text-3xl text-violet-700">{icon}</span><div><b>{title}</b><p className="mt-1 text-xs text-slate-400">{sub}</p></div></Link>}
