import { useEffect,useMemo,useState } from "react";
import { createPortal } from "react-dom";
import { ArrowsDownUp, Eye, EyeSlash, GearSix, Plus, Trash } from "@phosphor-icons/react";
import StoreWebsiteStudioPageV10 from "./StoreWebsiteStudioPageV10";
import { apiFetch } from "../lib/api";

type Project={id:string;content:Record<string,unknown>};
type Product={id:string;name:string;currency:string;basePriceMinor:number;brand?:string|null;category?:string|null;variants?:Array<{inventoryQuantity:number}>};
type SectionType="product-slider"|"banner-grid"|"trust"|"text";
type Section={id:string;type:SectionType;title:string;enabled:boolean;mode?:"all"|"newest"|"in-stock";subtitle?:string;items?:string[]};
type Design={font:string;primary:string;surface:string;text:string;radius:number;productColumns:number};
const seedSections:Section[]=[
 {id:"s1",type:"product-slider",title:"پیشنهاد ویژه",enabled:true,mode:"in-stock"},
 {id:"s2",type:"banner-grid",title:"بنرهای کمپین",enabled:true,items:["ارسال رایگان برای خریدهای ویژه","تخفیف محدود آخر هفته"]},
 {id:"s3",type:"product-slider",title:"جدیدترین محصولات",enabled:true,mode:"newest"},
 {id:"s4",type:"trust",title:"چرا از ما خرید کنید؟",enabled:true,items:["ارسال سریع","ضمانت بازگشت","پرداخت امن","پشتیبانی"]},
];
const seedDesign:Design={font:"Vazirmatn",primary:"#6d5dfc",surface:"#ffffff",text:"#111827",radius:18,productColumns:4};
async function read(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"خطا");return d}
const money=(minor:number,currency:string)=>new Intl.NumberFormat("fa-IR",{style:"currency",currency:currency||"IRR",maximumFractionDigits:0}).format((minor||0)/100);
const fonts=["Vazirmatn","IRANSansX","Shabnam","Sahel","Dana","Peyda"];
export default function StoreWebsiteStudioPageV11(){
 const[project,setProject]=useState<Project|null>(null),[products,setProducts]=useState<Product[]>([]),[sections,setSections]=useState<Section[]>(seedSections),[design,setDesign]=useState<Design>(seedDesign),[panel,setPanel]=useState<"sections"|"appearance"|null>(null),[target,setTarget]=useState<HTMLElement|null>(null),[message,setMessage]=useState("");
 useEffect(()=>{void boot()},[]);
 useEffect(()=>{const locate=()=>{const canvas=[...document.querySelectorAll("section")].find(el=>String(el.className).includes("bg-[#252c38]"));const inner=canvas?.querySelector(":scope > div") as HTMLElement|null;if(inner&&inner!==target)setTarget(inner)};locate();const o=new MutationObserver(locate);o.observe(document.body,{subtree:true,childList:true});return()=>o.disconnect()},[target]);
 async function boot(){try{const d=await read(await apiFetch("/api/site-projects"));const p=(d.projects||[]).find((x:any)=>String(x.siteType).toUpperCase()==="STORE")||d.projects?.[0];if(!p)return;const detail=await read(await apiFetch(`/api/site-projects/${p.id}`));setProject(detail.project);const saved=detail.project?.content?.storeBuilderV11 as {sections?:Section[];design?:Design}|undefined;if(saved?.sections)setSections(saved.sections);if(saved?.design)setDesign({...seedDesign,...saved.design});const pd=await read(await apiFetch(`/api/stores/${p.id}/products`));setProducts(pd.products||[])}catch(e){setMessage(e instanceof Error?e.message:"خطا در بارگذاری")}}
 async function save(){if(!project)return;try{const r=await read(await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:{...project.content,storeBuilderV11:{sections,design}}})}));setProject(r.project);setMessage("تنظیمات سکشن‌ها و ظاهر ذخیره شد")}catch(e){setMessage(e instanceof Error?e.message:"ذخیره نشد")}}
 function move(i:number,d:number){const j=i+d;if(j<0||j>=sections.length)return;const n=[...sections];[n[i],n[j]]=[n[j],n[i]];setSections(n)}
 function add(type:SectionType){setSections(s=>[...s,{id:`sec-${Date.now()}`,type,title:type==="product-slider"?"محصولات منتخب":type==="banner-grid"?"مجموعه بنر":"سکشن جدید",enabled:true,mode:"all",items:type==="trust"?["ارسال سریع","پرداخت امن"]:type==="banner-grid"?["بنر جدید"]:[""]}])}
 const rendered=sections.filter(s=>s.enabled).map((s,i)=><SectionPreview key={s.id} section={s} products={products} design={design} index={i}/>);
 return <div className="studio-v11" style={{fontFamily:design.font,color:design.text}}><StoreWebsiteStudioPageV10/>{target&&createPortal(<div dir="rtl" style={{background:design.surface}}>{rendered}</div>,target)}
 <div dir="rtl" className="fixed right-5 top-20 z-[230] flex gap-2"><button onClick={()=>setPanel(panel==="sections"?null:"sections")} className="flex items-center gap-2 rounded-xl bg-[#101722]/95 px-4 py-3 text-xs font-black text-white shadow-xl"><ArrowsDownUp/> تنظیمات بخش‌ها</button><button onClick={()=>setPanel(panel==="appearance"?null:"appearance")} className="flex items-center gap-2 rounded-xl bg-[#101722]/95 px-4 py-3 text-xs font-black text-white shadow-xl"><GearSix/> ظاهر</button></div>
 {panel&&<aside dir="rtl" className="fixed right-5 top-36 z-[240] w-[360px] max-w-[calc(100vw-40px)] max-h-[calc(100vh-165px)] overflow-y-auto rounded-2xl border border-white/10 bg-[#101722] p-4 text-white shadow-2xl">
 {panel==="sections"?<><div className="mb-4"><b>مدیریت بخش‌های صفحه</b><p className="mt-1 text-[11px] leading-5 text-white/45">ترتیب، نمایش و نوع سکشن‌ها را مثل یک صفحه‌ساز فروشگاهی مدیریت کن.</p></div><div className="space-y-2">{sections.map((s,i)=><div key={s.id} className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="flex items-center gap-2"><button onClick={()=>setSections(x=>x.map(a=>a.id===s.id?{...a,enabled:!a.enabled}:a))} className="text-lg">{s.enabled?<Eye/>:<EyeSlash/>}</button><input value={s.title} onChange={e=>setSections(x=>x.map(a=>a.id===s.id?{...a,title:e.target.value}:a))} className="min-w-0 flex-1 rounded-lg bg-black/20 p-2 text-xs"/><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button onClick={()=>setSections(x=>x.filter(a=>a.id!==s.id))} className="text-red-400"><Trash/></button></div>{s.type==="product-slider"&&<select value={s.mode||"all"} onChange={e=>setSections(x=>x.map(a=>a.id===s.id?{...a,mode:e.target.value as any}:a))} className="mt-2 w-full rounded-lg bg-black/20 p-2 text-xs"><option value="all">همه محصولات</option><option value="newest">جدیدترین</option><option value="in-stock">فقط موجود</option></select>}</div>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><Add onClick={()=>add("product-slider")}>اسلایدر محصول</Add><Add onClick={()=>add("banner-grid")}>مجموعه بنر</Add><Add onClick={()=>add("trust")}>اعتمادسازی</Add><Add onClick={()=>add("text")}>متن آزاد</Add></div></>:<><b>تنظیمات ظاهر</b><div className="mt-4 space-y-4"><label className="block text-xs text-white/60">فونت<select value={design.font} onChange={e=>setDesign({...design,font:e.target.value})} className="mt-2 w-full rounded-lg bg-black/20 p-3">{fonts.map(f=><option key={f}>{f}</option>)}</select></label><Color label="رنگ اصلی" value={design.primary} onChange={v=>setDesign({...design,primary:v})}/><Color label="پس‌زمینه" value={design.surface} onChange={v=>setDesign({...design,surface:v})}/><Color label="رنگ متن" value={design.text} onChange={v=>setDesign({...design,text:v})}/><label className="block text-xs text-white/60">گردی کارت‌ها: {design.radius}px<input type="range" min="0" max="36" value={design.radius} onChange={e=>setDesign({...design,radius:Number(e.target.value)})} className="mt-2 w-full"/></label><label className="block text-xs text-white/60">ستون محصولات<select value={design.productColumns} onChange={e=>setDesign({...design,productColumns:Number(e.target.value)})} className="mt-2 w-full rounded-lg bg-black/20 p-3"><option value="2">۲</option><option value="3">۳</option><option value="4">۴</option><option value="5">۵</option></select></label></div></>}
 <button onClick={()=>void save()} className="mt-5 w-full rounded-xl bg-violet-600 p-3 text-xs font-black">ذخیره تغییرات</button>{message&&<div className="mt-3 text-[11px] text-white/55">{message}</div>}</aside>}</div>;
}
function Add({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <button onClick={onClick} className="flex items-center justify-center gap-2 rounded-xl border border-dashed border-white/15 p-3 text-xs"><Plus/>{children}</button>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="flex items-center justify-between text-xs text-white/60"><span>{label}</span><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-9 w-14 rounded border-0 bg-transparent"/></label>}
function SectionPreview({section,products,design,index}:{section:Section;products:Product[];design:Design;index:number}){if(section.type==="product-slider"){let list=[...products];if(section.mode==="in-stock")list=list.filter(p=>(p.variants||[]).some(v=>v.inventoryQuantity>0));if(section.mode==="newest")list=list.reverse();list=list.slice(0,Math.max(4,design.productColumns));return <section className="px-6 py-9 sm:px-8" style={{background:index%2?"#f8fafc":design.surface}}><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">{section.title}</h2><button className="text-sm font-bold" style={{color:design.primary}}>مشاهده همه</button></div><div className="grid gap-4" style={{gridTemplateColumns:`repeat(${Math.min(design.productColumns,4)},minmax(0,1fr))`}}>{list.map(p=><article key={p.id} className="overflow-hidden border border-slate-200 bg-white p-3" style={{borderRadius:design.radius}}><div className="aspect-square rounded-xl bg-slate-100"/><div className="mt-3 truncate font-bold">{p.name}</div><div className="mt-1 text-xs text-slate-400">{p.brand||p.category||"محصول فروشگاه"}</div><div className="mt-3 font-black" style={{color:design.primary}}>{money(p.basePriceMinor,p.currency)}</div></article>)}</div></section>}
 if(section.type==="banner-grid")return <section className="px-6 py-8 sm:px-8"><h2 className="mb-4 text-xl font-black">{section.title}</h2><div className="grid gap-3 sm:grid-cols-2">{(section.items||["بنر"]).map((x,i)=><div key={i} className="flex min-h-32 items-end bg-slate-900 p-5 text-white" style={{borderRadius:design.radius,background:i%2?`linear-gradient(135deg,${design.primary},#111827)`:`linear-gradient(135deg,#111827,${design.primary})`}}><b>{x}</b></div>)}</div></section>;
 if(section.type==="trust")return <section className="px-6 py-9 sm:px-8"><h2 className="mb-6 text-center text-xl font-black">{section.title}</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(section.items||[]).map((x,i)=><div key={i} className="rounded-2xl border border-slate-200 bg-white p-5 text-center"><div className="mx-auto mb-3 h-10 w-10 rounded-full" style={{background:`${design.primary}22`}}/><b className="text-sm">{x}</b></div>)}</div></section>;
 return <section className="px-6 py-10 text-center sm:px-8"><h2 className="text-2xl font-black">{section.title}</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-slate-500">متن این بخش را می‌توانی برای معرفی برند، داستان فروشگاه یا کمپین بنویسی.</p></section>}
