import { useEffect, useRef, useState, type DragEvent } from "react";
import { ArrowRight, ArrowsClockwise, Desktop, DeviceMobile, DeviceTablet, Eye, FloppyDisk, Image, ShoppingBag, UploadSimple } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string;content:Record<string,unknown>};
type Asset={id:string;name:string;kind:string;url:string;altText?:string|null};
type Product={id:string;name:string;price:string;imageUrl:string;visible:boolean};
type Kind="hero"|"trust"|"categories"|"products"|"banners"|"footer";
type Section={id:string;kind:Kind;title:string;subtitle:string;bg:string;fg:string;padding:number;radius:number;visible:boolean;imageUrl?:string;secondaryImageUrl?:string;buttonText?:string;columns?:number};
type Studio={accent:string;sections:Section[];products:Product[]};
type Target={kind:"hero"|"banner"|"product";slot?:"primary"|"secondary"};

const seed:Studio={accent:"#ef4444",products:[],sections:[
{id:"hero",kind:"hero",title:"جدیدترین پیشنهادهای فروشگاه",subtitle:"محصولات منتخب، ارسال سریع و خرید مطمئن",bg:"#f8fafc",fg:"#111827",padding:28,radius:22,visible:true,buttonText:"مشاهده محصولات"},
{id:"trust",kind:"trust",title:"خرید مطمئن و سریع",subtitle:"ضمانت بازگشت کالا · ارسال سریع · پرداخت امن · پشتیبانی آنلاین · ضمانت اصالت",bg:"#fff",fg:"#111827",padding:22,radius:16,visible:true,columns:5},
{id:"categories",kind:"categories",title:"دسته‌بندی‌های محبوب",subtitle:"دسترسی سریع به دسته‌های اصلی فروشگاه",bg:"#f5f5f5",fg:"#111827",padding:34,radius:0,visible:true,columns:6},
{id:"products",kind:"products",title:"محصولات پرفروش",subtitle:"محصولات محبوب فروشگاه شما",bg:"#f5f5f5",fg:"#111827",padding:32,radius:0,visible:true,columns:5},
{id:"banners",kind:"banners",title:"پیشنهادهای ویژه",subtitle:"کمپین‌ها و بنرهای تبلیغاتی",bg:"#f5f5f5",fg:"#111827",padding:24,radius:18,visible:true,columns:3},
{id:"footer",kind:"footer",title:"فروشگاه شما",subtitle:"لینک‌ها، خدمات مشتریان، شبکه‌های اجتماعی و اطلاعات تماس",bg:"#111827",fg:"#fff",padding:42,radius:0,visible:true,columns:4}
]};
const clone=<T,>(x:T):T=>structuredClone(x);
const normalize=(s:Section):Section=>({...s,visible:s.visible!==false,imageUrl:s.imageUrl||"",secondaryImageUrl:s.secondaryImageUrl||"",columns:Number(s.columns||3)});
const fromProject=(p:Project,assets:Asset[]):Studio=>{const saved=p.content?.storeStudio as Studio|undefined;const base=saved?.sections?.length?{accent:saved.accent||seed.accent,sections:saved.sections.map(normalize),products:Array.isArray(saved.products)?saved.products:[]}:clone(seed);if(!base.products.length)base.products=assets.filter(a=>a.kind==="product").slice(0,20).map(a=>({id:a.id,name:a.altText||a.name,price:"قیمت را تنظیم کن",imageUrl:a.url,visible:true}));const hero=assets.find(a=>a.kind==="hero");const banners=assets.filter(a=>a.kind==="banner");if(hero&&!base.sections.find(s=>s.kind==="hero")?.imageUrl)base.sections=base.sections.map(s=>s.kind==="hero"?{...s,imageUrl:hero.url}:s);if(banners[0]&&!base.sections.find(s=>s.kind==="banners")?.imageUrl)base.sections=base.sections.map(s=>s.kind==="banners"?{...s,imageUrl:banners[0].url,secondaryImageUrl:banners[1]?.url||""}:s);return base};
async function responseJson(r:Response){const text=await r.text();try{return text?JSON.parse(text):{}}catch{throw new Error(r.status===413?"حجم تصویر برای مسیر فعلی زیاد است؛ تصویر بهینه نشد. دوباره تلاش کن.":`پاسخ نامعتبر از سرور (${r.status})`)}}
async function optimizeImage(file:File){if(file.size>3*1024*1024)throw new Error("حداکثر حجم فایل ورودی ۳ مگابایت است");if(!file.type.startsWith("image/"))throw new Error("فقط فایل تصویری قابل قبول است");const objectUrl=URL.createObjectURL(file);try{const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const x=new window.Image();x.onload=()=>resolve(x);x.onerror=()=>reject(new Error("تصویر خوانده نشد"));x.src=objectUrl});const max=2200,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext("2d");if(!ctx)throw new Error("پردازش تصویر ممکن نیست");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let quality=.86,data=canvas.toDataURL("image/jpeg",quality);while(data.length>1_550_000&&quality>.48){quality-=.08;data=canvas.toDataURL("image/jpeg",quality)}if(data.length>1_850_000)throw new Error("تصویر پس از بهینه‌سازی هنوز بزرگ است؛ ابعاد تصویر را کمتر کن");return data}finally{URL.revokeObjectURL(objectUrl)}}

export default function StoreWebsiteStudioPageV2(){
 const[project,setProject]=useState<Project|null>(null),[studio,setStudio]=useState<Studio>(clone(seed)),[selected,setSelected]=useState("hero"),[viewport,setViewport]=useState<"desktop"|"tablet"|"mobile">("desktop"),[past,setPast]=useState<Studio[]>([]),[future,setFuture]=useState<Studio[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),target=useRef<Target>({kind:"hero"});
 useEffect(()=>{void(async()=>{try{const r=await apiFetch("/api/site-projects");const d=await responseJson(r);if(!r.ok)throw new Error(d.message||"پروژه‌ها بارگذاری نشدند");const p=(d.projects||[]).find((x:Project)=>String(x.siteType).toUpperCase()==="STORE")||d.projects?.[0];if(!p)return;const rr=await apiFetch(`/api/site-projects/${p.id}`);const dd=await responseJson(rr);if(!rr.ok)throw new Error(dd.message||"پروژه باز نشد");const s=fromProject(dd.project,dd.assets||[]);setProject(dd.project);setStudio(s);setSelected(s.sections[0]?.id||"hero")}catch(e){setMessage(e instanceof Error?e.message:"خطا در بارگذاری")}})()},[]);
 const active=studio.sections.find(s=>s.id===selected)||studio.sections[0],width=viewport==="desktop"?"1220px":viewport==="tablet"?"780px":"390px";
 const commit=(next:Studio)=>{setPast(x=>[...x.slice(-39),clone(studio)]);setStudio(next);setFuture([])};
 const patch=(changes:Partial<Section>)=>commit({...studio,sections:studio.sections.map(s=>s.id===active.id?{...s,...changes}:s)});
 const choose=(t:Target)=>{target.current=t;fileInput.current?.click()};
 async function upload(file:File,t:Target){if(!project)return setMessage("پروژه هنوز بارگذاری نشده");setBusy(true);setMessage("در حال بهینه‌سازی و آپلود تصویر…");try{const dataUrl=await optimizeImage(file);const kind=t.kind==="product"?"product":t.kind==="hero"?"hero":"banner";const r=await apiFetch(`/api/site-projects/${project.id}/assets`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,name:file.name.replace(/\.[^.]+$/,".jpg"),url:dataUrl,altText:file.name.replace(/\.[^.]+$/," ").trim()})});const d=await responseJson(r);if(!r.ok)throw new Error(d.message||"آپلود ناموفق بود");const a=d.asset as Asset;if(t.kind==="product"){const next=clone(studio),name=window.prompt("نام محصول",a.altText||"محصول")||a.altText||"محصول",price=window.prompt("قیمت محصول","")||"قیمت را تنظیم کن";next.products.push({id:a.id,name,price,imageUrl:a.url,visible:true});commit(next);setSelected("products")}else{const sectionKind=t.kind==="hero"?"hero":"banners";const next=clone(studio);next.sections=next.sections.map(s=>s.kind===sectionKind?{...s,...(t.slot==="secondary"?{secondaryImageUrl:a.url}:{imageUrl:a.url})}:s);commit(next);setSelected(sectionKind)}setMessage("تصویر روی Canvas اعمال شد")}catch(e){setMessage(e instanceof Error?e.message:"آپلود ناموفق بود")}finally{setBusy(false)}}
 async function save(){if(!project)return;setBusy(true);try{const r=await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:{...project.content,storeStudio:studio,visualStudio:studio}})});const d=await responseJson(r);if(!r.ok)throw new Error(d.message||"ذخیره ناموفق بود");setProject(d.project);setMessage("ذخیره شد")}catch(e){setMessage(e instanceof Error?e.message:"خطا در ذخیره")}finally{setBusy(false)}}
 async function publish(){await save();if(!project)return;setBusy(true);try{const r=await apiFetch(`/api/site-projects/${project.id}/publish`,{method:"POST"});const d=await responseJson(r);if(!r.ok)throw new Error(d.message||"انتشار ناموفق بود");setMessage("فروشگاه منتشر شد")}catch(e){setMessage(e instanceof Error?e.message:"خطا در انتشار")}finally{setBusy(false)}}
 const undo=()=>{const p=past.at(-1);if(!p)return;setFuture(x=>[clone(studio),...x]);setStudio(p);setPast(x=>x.slice(0,-1))},redo=()=>{const n=future[0];if(!n)return;setPast(x=>[...x,clone(studio)]);setStudio(n);setFuture(x=>x.slice(1))};
 const drop=(e:DragEvent,t:Target)=>{e.preventDefault();const f=e.dataTransfer.files?.[0];if(f)void upload(f,t)};
 return <main dir="rtl" className="h-screen overflow-hidden bg-[#0b1019] text-white">
 <input ref={fileInput} hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,target.current);e.target.value=""}}/>
 <header className="flex h-[62px] items-center justify-between border-b border-white/10 bg-[#0d131d] px-4"><div className="flex gap-2"><Link to="/dashboard" className="rounded-lg border border-white/10 p-2"><ArrowRight/></Link><button disabled={busy} onClick={()=>void publish()} className="rounded-lg bg-violet-600 px-5 py-2 text-sm font-bold">انتشار</button><button disabled={busy} onClick={()=>void save()} className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm"><FloppyDisk/> ذخیره</button><button className="flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm"><Eye/> پیش‌نمایش</button></div><div className="flex items-center gap-1 rounded-xl bg-white/5 p-1"><button onClick={()=>setViewport("desktop")} className="p-2"><Desktop/></button><button onClick={()=>setViewport("tablet")} className="p-2"><DeviceTablet/></button><button onClick={()=>setViewport("mobile")} className="p-2"><DeviceMobile/></button><button onClick={undo} className="p-2"><ArrowsClockwise/></button><button onClick={redo} className="rotate-180 p-2"><ArrowsClockwise/></button></div><div><div className="text-[10px] text-white/40">Store Builder</div><b>{project?.name||"…"}</b></div></header>
 <div className="grid h-[calc(100vh-62px)] grid-cols-[255px_minmax(0,1fr)_320px]">
 <aside className="overflow-y-auto border-l border-white/10 bg-[#101722] p-4"><b className="text-sm">بخش‌های فروشگاه</b><div className="mt-4 grid grid-cols-2 gap-3">{studio.sections.map(s=><button key={s.id} onClick={()=>setSelected(s.id)} className={`min-h-20 rounded-xl border p-3 text-xs ${selected===s.id?"border-violet-500 bg-violet-500/10":"border-white/10"}`}>{s.kind}</button>)}</div><div className="mt-5 rounded-xl border border-white/10 p-3"><div className="flex items-center gap-2"><ShoppingBag/> محصولات</div><button onClick={()=>choose({kind:"product"})} className="mt-3 w-full rounded-lg bg-violet-600 py-2 text-xs">افزودن محصول</button></div>{message&&<div className="mt-4 rounded-lg border border-white/10 bg-white/5 p-3 text-xs leading-6">{message}</div>}</aside>
 <section className="overflow-auto bg-[#252c38] p-7"><div className="mx-auto bg-white text-slate-900 shadow-2xl transition-all" style={{width,maxWidth:"100%"}}><StoreHeader name={project?.name||"فروشگاه شما"}/>{studio.sections.filter(s=>s.visible).map(s=><section key={s.id} onClick={()=>setSelected(s.id)} className={`relative ${selected===s.id?"ring-2 ring-inset ring-violet-500":""}`} style={{background:s.bg,color:s.fg,padding:s.padding,borderRadius:s.radius}}>{s.kind==="hero"?<Hero s={s} choose={choose} drop={drop}/>:s.kind==="trust"?<Trust title={s.title}/>:s.kind==="categories"?<Categories title={s.title}/>:s.kind==="products"?<Products title={s.title} products={studio.products} choose={choose} drop={drop}/>:s.kind==="banners"?<Banners s={s} choose={choose} drop={drop}/>:<Footer s={s}/>}</section>)}</div></section>
 <aside className="overflow-y-auto border-r border-white/10 bg-[#101722] p-5"><b className="text-sm">تنظیمات بخش</b><label className="mt-5 block text-xs text-white/50">عنوان<input value={active.title} onChange={e=>patch({title:e.target.value})} className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-white"/></label><label className="mt-4 block text-xs text-white/50">توضیح<textarea value={active.subtitle} onChange={e=>patch({subtitle:e.target.value})} className="mt-2 min-h-24 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-white"/></label><label className="mt-4 flex items-center justify-between rounded-lg border border-white/10 p-3 text-xs"><span>نمایش در صفحه</span><input type="checkbox" checked={active.visible} onChange={e=>patch({visible:e.target.checked})}/></label>{active.kind==="hero"&&<button onClick={()=>choose({kind:"hero"})} className="mt-4 w-full rounded-lg border border-white/10 p-3 text-xs">آپلود / تغییر Hero</button>}{active.kind==="banners"&&<><button onClick={()=>choose({kind:"banner",slot:"primary"})} className="mt-4 w-full rounded-lg border border-white/10 p-3 text-xs">بنر اول</button><button onClick={()=>choose({kind:"banner",slot:"secondary"})} className="mt-2 w-full rounded-lg border border-white/10 p-3 text-xs">بنر دوم</button></>}</aside>
 </div></main>}
function StoreHeader({name}:{name:string}){return <><div className="flex items-center gap-5 border-b border-slate-100 px-7 py-4"><b className="text-xl">{name}</b><div className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-xs text-slate-400">جستجو در محصولات…</div><button className="rounded-xl border px-4 py-2 text-xs">ورود / حساب</button><button className="rounded-xl border px-4 py-2 text-xs">سبد خرید</button></div><div className="flex gap-8 border-b px-7 py-3 text-xs text-slate-600"><span>دسته‌بندی کالا</span><span>برندها</span><span>فروشگاه</span><span>وبلاگ</span><span>تماس</span></div></>}
function UploadOverlay({label,onClick}:{label:string;onClick:()=>void}){return <button onClick={e=>{e.stopPropagation();onClick()}} className="absolute inset-0 z-10 grid place-items-center bg-black/0 opacity-0 transition hover:bg-black/35 hover:opacity-100"><span className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-bold text-slate-900 shadow-xl"><UploadSimple/> {label}</span></button>}
function Hero({s,choose,drop}:{s:Section;choose:(t:Target)=>void;drop:(e:DragEvent,t:Target)=>void}){return <div className="grid min-h-[390px] grid-cols-[1fr_280px] gap-4"><div onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,{kind:"hero"})} className="relative overflow-hidden rounded-[28px] bg-slate-200" style={s.imageUrl?{backgroundImage:`linear-gradient(90deg,rgba(10,15,25,.72),rgba(10,15,25,.15)),url(${s.imageUrl})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined}><div className="relative z-[1] max-w-xl p-14 text-white"><div className="text-sm">پیشنهاد ویژه</div><h1 className="mt-3 text-4xl font-black leading-tight">{s.title}</h1><p className="mt-4 opacity-80">{s.subtitle}</p><button className="mt-6 rounded-xl bg-red-500 px-6 py-3 font-bold">{s.buttonText||"مشاهده محصولات"}</button></div><UploadOverlay label={s.imageUrl?"تغییر تصویر Hero":"آپلود تصویر Hero"} onClick={()=>choose({kind:"hero"})}/></div><div className="grid gap-4"><Promo label="Promo Banner 1" onClick={()=>choose({kind:"banner",slot:"primary"})}/><Promo label="Promo Banner 2" onClick={()=>choose({kind:"banner",slot:"secondary"})}/></div></div>}
function Promo({label,onClick}:{label:string;onClick:()=>void}){return <div className="relative grid min-h-44 place-items-center overflow-hidden rounded-2xl bg-white text-xs text-slate-400 ring-1 ring-slate-100"><span>{label}</span><UploadOverlay label="آپلود بنر" onClick={onClick}/></div>}
function Trust({title}:{title:string}){return <><h2 className="mb-5 text-2xl font-black">{title}</h2><div className="grid grid-cols-5 gap-3">{["ضمانت بازگشت","ارسال سریع","پرداخت امن","ضمانت اصالت","پشتیبانی آنلاین"].map(x=><div className="rounded-2xl bg-white p-5 text-center text-xs shadow-sm" key={x}>✦<div className="mt-3 font-bold">{x}</div></div>)}</div></>}
function Categories({title}:{title:string}){return <><h2 className="mb-5 text-2xl font-black">{title}</h2><div className="grid grid-cols-6 gap-3">{[1,2,3,4,5,6].map(x=><div key={x} className="rounded-2xl bg-white p-5 text-center text-sm shadow-sm">دسته {x}</div>)}</div></>}
function Products({title,products,choose,drop}:{title:string;products:Product[];choose:(t:Target)=>void;drop:(e:DragEvent,t:Target)=>void}){return <><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={e=>{e.stopPropagation();choose({kind:"product"})}} className="rounded-xl border border-slate-200 px-4 py-2 text-xs">+ محصول</button></div><div onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,{kind:"product"})} className="grid grid-cols-5 gap-4">{products.length?products.filter(p=>p.visible).map(p=><div key={p.id} className="group relative rounded-2xl bg-white p-3 shadow-sm"><div className="relative aspect-square overflow-hidden rounded-xl bg-slate-50"><img src={p.imageUrl} className="h-full w-full object-contain p-2"/><UploadOverlay label="جایگزینی تصویر" onClick={()=>choose({kind:"product"})}/></div><div className="mt-3 line-clamp-2 min-h-10 text-xs font-bold">{p.name}</div><div className="mt-3 text-sm font-black">{p.price}</div></div>):<button onClick={()=>choose({kind:"product"})} className="col-span-5 rounded-2xl border-2 border-dashed border-slate-200 p-16 text-slate-400"><UploadSimple className="mx-auto mb-3 text-3xl"/>محصول را اینجا بکش یا کلیک کن</button>}</div></>}
function Banners({s,choose,drop}:{s:Section;choose:(t:Target)=>void;drop:(e:DragEvent,t:Target)=>void}){return <><h2 className="mb-5 text-2xl font-black">{s.title}</h2><div className="grid grid-cols-2 gap-4"><Banner src={s.imageUrl} label="بنر اول" onClick={()=>choose({kind:"banner",slot:"primary"})} onDrop={e=>drop(e,{kind:"banner",slot:"primary"})}/><Banner src={s.secondaryImageUrl} label="بنر دوم" onClick={()=>choose({kind:"banner",slot:"secondary"})} onDrop={e=>drop(e,{kind:"banner",slot:"secondary"})}/></div></>}
function Banner({src,label,onClick,onDrop}:{src?:string;label:string;onClick:()=>void;onDrop:(e:DragEvent)=>void}){return <div onDragOver={e=>e.preventDefault()} onDrop={onDrop} className="relative min-h-52 overflow-hidden rounded-2xl bg-slate-200">{src?<img src={src} className="h-52 w-full object-cover"/>:<div className="grid h-52 place-items-center text-slate-400">{label}</div>}<UploadOverlay label={src?"تغییر بنر":"آپلود بنر"} onClick={onClick}/></div>}
function Footer({s}:{s:Section}){return <div className="grid grid-cols-4 gap-8"><div><b className="text-xl">{s.title}</b><p className="mt-3 text-xs opacity-60">{s.subtitle}</p></div><div><b>لینک‌ها</b><p className="mt-3 text-xs opacity-60">خانه · تماس · بلاگ</p></div><div><b>خدمات مشتریان</b><p className="mt-3 text-xs opacity-60">قوانین · ارسال · بازگشت</p></div><div><b>عضویت در خبرنامه</b><div className="mt-3 rounded-xl border border-white/20 p-3 text-xs opacity-60">ایمیل شما…</div></div></div>}
