import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CursorClick, ImageSquare, Plus, Tag, UploadSimple, X } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import InspectorPanel from "../components/store-studio-v16/InspectorPanel";
import StudioCanvas from "../components/store-studio-v16/StudioCanvas";
import StudioToolbar from "../components/store-studio-v16/StudioToolbar";
import { defaultProductSettings, designDefaults, productsForSection, restoreConfig } from "../components/store-studio-v16/config";
import type { DeviceMode, MediaAsset, Product, ProductSettings, SectionConfig, StudioActions, StudioConfig } from "../components/store-studio-v16/types";
import { apiFetch } from "../lib/api";

type Project = { id: string; name?: string; content: Record<string, any> };
type MediaTarget = { kind: "hero" } | { kind: "banner"; sectionId: string } | { kind: "logo" };
async function read(response: Response) { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "عملیات Studio ناموفق بود"); return data; }
function newSection(type: SectionConfig["type"]): SectionConfig { const labels={products:"محصولات جدید",banner:"بنر جدید",trust:"مزیت‌های خرید",text:"متن جدید",spacer:"فاصله"}; return { id:`${type}-${crypto.randomUUID()}`, type, enabled:true, title:labels[type], subtitle:type==="spacer"?"":"برای ویرایش این بخش روی آن کلیک کنید.", backgroundColor:type==="banner"?designDefaults.primaryColor:designDefaults.surfaceColor, textColor:type==="banner"?"#fff":designDefaults.textColor, spacingTop:type==="spacer"?32:designDefaults.sectionSpacing, spacingBottom:type==="spacer"?32:designDefaults.sectionSpacing, ...(type==="products"?{productSettings:{...defaultProductSettings}}:{}) }; }
function normalizeManual(settings: ProductSettings, products: Product[]) { if(settings.source==="manual") return {...settings,productIds:[...settings.productIds]}; return {...settings,source:"manual" as const,productIds:productsForSection(products,settings).slice(0,12).map(p=>p.id)}; }

export default function StoreWebsiteStudioPageV16(){
 const [project,setProject]=useState<Project|null>(null); const [products,setProducts]=useState<Product[]>([]); const [assets,setAssets]=useState<MediaAsset[]>([]); const [config,setConfig]=useState<StudioConfig>(()=>restoreConfig({})); const [device,setDevice]=useState<DeviceMode>("desktop"); const [tab,setTab]=useState<"context"|"sections"|"design">("context"); const [busy,setBusy]=useState(true); const [message,setMessage]=useState(""); const [previewOpen,setPreviewOpen]=useState(false); const [pickerSectionId,setPickerSectionId]=useState<string|null>(null); const [mediaTarget,setMediaTarget]=useState<MediaTarget|null>(null); const [mediaBusy,setMediaBusy]=useState(false);
 useEffect(()=>{const c=new AbortController(); void(async()=>{try{const listing=await read(await apiFetch("/api/site-projects",{signal:c.signal})); const selected=(listing.projects||[]).find((i:any)=>String(i.siteType).toUpperCase()==="STORE")||listing.projects?.[0]; if(!selected)throw new Error("پروژه فروشگاهی پیدا نشد"); const detail=await read(await apiFetch(`/api/site-projects/${selected.id}`,{signal:c.signal})); const loaded=detail.project as Project; setProject(loaded); setConfig(restoreConfig(loaded.content||{})); setAssets((detail.assets||[]).filter((a:MediaAsset)=>typeof a.url==="string")); const catalog=await read(await apiFetch(`/api/stores/${selected.id}/products`,{signal:c.signal})); setProducts(catalog.products||[]);}catch(e){if(e instanceof DOMException&&e.name==="AbortError")return;setMessage(e instanceof Error?e.message:"بارگذاری Studio ناموفق بود");}finally{if(!c.signal.aborted)setBusy(false)}})();return()=>c.abort()},[]);
 const actions=useMemo<StudioActions>(()=>({select:(selectedElement)=>{setConfig(cur=>({...cur,selectedElement}));setTab("context"); if(selectedElement.type==="hero")setMediaTarget({kind:"hero"}); if(selectedElement.type==="banner"&&selectedElement.id)setMediaTarget({kind:"banner",sectionId:selectedElement.id});},patchDesign:(p)=>setConfig(c=>({...c,design:{...c.design,...p}})),patchHeader:(p)=>setConfig(c=>({...c,header:{...c.header,...p}})),patchHero:(p)=>setConfig(c=>({...c,hero:{...c.hero,...p}})),patchSection:(id,p)=>setConfig(c=>({...c,sections:c.sections.map(s=>s.id===id?{...s,...p}:s)})),patchProduct:(id,p)=>setConfig(c=>({...c,commerce:{...c.commerce,productOverrides:{...c.commerce.productOverrides,[id]:{...(c.commerce.productOverrides[id]||{}),...p}}}})),patchCommerce:(p)=>setConfig(c=>({...c,commerce:{...c.commerce,...p}}))}),[]);
 function patchProductSection(sectionId:string,updater:(s:ProductSettings)=>ProductSettings){setConfig(c=>({...c,sections:c.sections.map(s=>s.id===sectionId&&s.type==="products"&&s.productSettings?{...s,productSettings:updater(s.productSettings)}:s)}));}
 function addProduct(sectionId:string,productId:string){patchProductSection(sectionId,raw=>{const s=normalizeManual(raw,products);return s.productIds.includes(productId)?s:{...s,productIds:[...s.productIds,productId].slice(0,12)}});setPickerSectionId(null);actions.select({type:"product-card",id:productId});setMessage("محصول به بخش اضافه شد.");}
 function reorderProduct(sectionId:string,fromId:string,toId:string){if(fromId===toId)return;patchProductSection(sectionId,raw=>{const s=normalizeManual(raw,products),ids=[...s.productIds],from=ids.indexOf(fromId),to=ids.indexOf(toId);if(from<0||to<0)return s;ids.splice(from,1);ids.splice(to,0,fromId);return{...s,productIds:ids}})}
 function moveSection(id:string,delta:number){setConfig(c=>{const i=c.sections.findIndex(s=>s.id===id),t=i+delta;if(i<0||t<0||t>=c.sections.length)return c;const sections=[...c.sections];[sections[i],sections[t]]=[sections[t],sections[i]];return{...c,sections}})}
 function reorderSection(fromId:string,toId:string){if(fromId===toId)return;setConfig(c=>{const sections=[...c.sections],from=sections.findIndex(s=>s.id===fromId),to=sections.findIndex(s=>s.id===toId);if(from<0||to<0)return c;const [moved]=sections.splice(from,1);sections.splice(to,0,moved);return{...c,sections,selectedElement:{type:moved.type==="banner"?"banner":moved.type==="trust"?"trust":"section",id:moved.id}}})}
 function insertSection(index:number,type:SectionConfig["type"]){const section=newSection(type);setConfig(c=>{const sections=[...c.sections];sections.splice(Math.min(index,sections.length),0,section);return{...c,sections,selectedElement:{type:type==="banner"?"banner":type==="trust"?"trust":"section",id:section.id}}});setTab("context");if(type==="banner")setMediaTarget({kind:"banner",sectionId:section.id});if(type==="products")setMessage("بخش محصولات اضافه شد؛ از + داخل آن محصول انتخاب کنید.");}
 function addSection(type:SectionConfig["type"]){insertSection(config.sections.length,type)}
 function duplicateSection(id:string){setConfig(c=>{const i=c.sections.findIndex(s=>s.id===id);if(i<0)return c;const src=c.sections[i];const copy={...src,id:`${src.type}-${crypto.randomUUID()}`,title:`${src.title} (کپی)`,productSettings:src.productSettings?{...src.productSettings,productIds:[...src.productSettings.productIds]}:undefined};const sections=[...c.sections];sections.splice(i+1,0,copy);return{...c,sections}})}
 function deleteSection(id:string){setConfig(c=>({...c,sections:c.sections.filter(s=>s.id!==id),selectedElement:{type:"hero",id:"hero"}}))}
 function addDiscountSection(){const section=newSection("products");section.title="تخفیف‌های ویژه";section.productSettings={...defaultProductSettings,source:"discounted",showPromotionBadge:true,showCompareAt:true};setConfig(c=>({...c,sections:[...c.sections,section],selectedElement:{type:"section",id:section.id}}));}
 function applyMedia(url:string){if(!mediaTarget)return;if(mediaTarget.kind==="hero")actions.patchHero({imageUrl:url});if(mediaTarget.kind==="logo")actions.patchHeader({logoUrl:url});if(mediaTarget.kind==="banner")actions.patchSection(mediaTarget.sectionId,{imageUrl:url});setMediaTarget(null);setMessage("تصویر اعمال شد.");}
 async function uploadMedia(file:File){if(!project||!mediaTarget)return;const mimeType=file.type||"image/jpeg",assetType=mediaTarget.kind==="logo"?"logo":mediaTarget.kind==="hero"?"hero":"banner";setMediaBusy(true);try{const created=await read(await apiFetch(`/api/site-projects/${project.id}/media/upload-url`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetType,fileName:file.name,mimeType,sizeBytes:file.size})}));const upload=created.upload;const uploaded=await fetch(upload.signedUrl,{method:"PUT",headers:{"Content-Type":mimeType},body:file});if(!uploaded.ok)throw new Error("آپلود فایل ناموفق بود");const completed=await read(await apiFetch(`/api/site-projects/${project.id}/media/complete`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetType,mimeType,sizeBytes:file.size,storageKey:upload.path,metadata:{name:file.name}})}));const asset={...completed.media,name:completed.media?.name||file.name} as MediaAsset;setAssets(c=>[asset,...c.filter(a=>a.id!==asset.id)]);applyMedia(asset.url);}catch(e){setMessage(e instanceof Error?e.message:"آپلود ناموفق بود");}finally{setMediaBusy(false)}}
 async function save(){if(!project)return;setBusy(true);try{const storeBuilderV16:StudioConfig={...config,version:16};const content={...project.content,storeBuilderV16};const out=await read(await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})}));setProject(out.project);setMessage("طراحی ذخیره شد.");}catch(e){setMessage(e instanceof Error?e.message:"ذخیره ناموفق بود");}finally{setBusy(false)}}
 const inspectorProps={config,products,assets,actions,moveSection,duplicateSection,deleteSection,addSection}; const pickerSection=pickerSectionId?config.sections.find(s=>s.id===pickerSectionId):null; const pickerSettings=pickerSection?.type==="products"&&pickerSection.productSettings?normalizeManual(pickerSection.productSettings,products):null;
 return <main dir="rtl" className="h-screen overflow-hidden bg-[#070b12] text-white" data-studio-version="16"><header className="flex min-h-20 items-center gap-3 border-b border-white/10 bg-[#0a111b] px-4 py-3"><Link to="/dashboard" className="grid h-11 w-11 place-items-center rounded-xl border border-white/10"><ArrowRight/></Link><div className="min-w-56"><div className="text-[10px] font-black tracking-[.18em] text-emerald-300">LOADDER VISUAL STUDIO</div><h1 className="font-black">فروشگاه شما</h1><p className="mt-1 flex items-center gap-1 text-[10px] text-white/35"><CursorClick/> روی خود سایت کلیک کنید</p></div><StudioToolbar device={device} page={config.activePage} busy={busy||!project} onDevice={setDevice} onPage={(activePage)=>setConfig(c=>({...c,activePage,selectedElement:{type:activePage==="storefront"?"hero":activePage,id:activePage==="storefront"?"hero":activePage}}))} onPreview={()=>setPreviewOpen(true)} onSave={()=>void save()}/></header>
 <div className="grid h-[calc(100vh-80px)] grid-cols-1 lg:grid-cols-[minmax(0,1fr)_340px]"><section className="order-2 min-h-0 overflow-auto bg-[#dfe5ec] p-4 lg:order-1 lg:p-7"><div className="sticky top-0 z-40 mx-auto mb-4 flex max-w-[1240px] gap-2 rounded-2xl border border-white/15 bg-[#111827]/95 p-2 shadow-xl backdrop-blur"><button onClick={()=>setMediaTarget({kind:"hero"})} className="rounded-xl bg-white/5 px-3 py-2 text-xs font-bold"><ImageSquare/> تصویر Hero</button><button onClick={()=>insertSection(0,"banner")} className="rounded-xl bg-white/5 px-3 py-2 text-xs font-bold"><Plus/> بنر</button><button onClick={addDiscountSection} className="rounded-xl bg-rose-500/10 px-3 py-2 text-xs font-bold text-rose-200"><Tag/> تخفیف‌ها</button><button onClick={()=>setMediaTarget({kind:"logo"})} className="mr-auto rounded-xl bg-emerald-400/10 px-3 py-2 text-xs font-bold text-emerald-200"><UploadSimple/> لوگو</button></div>{busy&&!project?<div className="grid min-h-96 place-items-center text-slate-500">در حال آماده‌سازی…</div>:<StudioCanvas config={config} products={products} device={device} selected={config.selectedElement} select={actions.select} onAddProduct={setPickerSectionId} onReorderProduct={reorderProduct} onInsertSection={insertSection} onReorderSection={reorderSection}/>}</section><div className="order-1 min-h-0 lg:order-2"><InspectorPanel {...inspectorProps} tab={tab} onTab={setTab}/></div></div>
 {previewOpen&&<div className="fixed inset-0 z-[100] overflow-auto bg-slate-950/95 p-5"><div className="mx-auto mb-3 flex max-w-[1240px] items-center justify-between"><b>پیش‌نمایش Draft</b><button onClick={()=>setPreviewOpen(false)} className="grid h-11 w-11 place-items-center rounded-xl bg-white/10"><X/></button></div><StudioCanvas config={{...config,activePage:"storefront"}} products={products} device={device} selected={config.selectedElement} select={()=>undefined} interactive={false}/></div>}
 {pickerSectionId&&<div className="fixed inset-0 z-[110] grid place-items-center bg-slate-950/75 p-4"><div className="max-h-[80vh] w-full max-w-3xl overflow-hidden rounded-3xl bg-[#0d1622]"><div className="flex items-center justify-between border-b border-white/10 p-4"><div><h2 className="font-black">افزودن محصول</h2><p className="text-xs text-white/40">روی کالا بزنید؛ همان لحظه وارد این بخش می‌شود.</p></div><button onClick={()=>setPickerSectionId(null)}><X/></button></div><div className="grid max-h-[65vh] gap-3 overflow-auto p-4 sm:grid-cols-2">{products.map(p=>{const added=pickerSettings?.productIds.includes(p.id)??false;return <button key={p.id} onClick={()=>addProduct(pickerSectionId,p.id)} className={`flex items-center gap-3 rounded-2xl border p-3 text-right ${added?"border-emerald-400/40 bg-emerald-400/10":"border-white/10 bg-white/[.03]"}`}><div className="h-14 w-14 rounded-xl bg-white/5"/><div className="flex-1"><b>{p.name}</b><span className="block text-[10px] text-white/35">{p.brand||p.category||"محصول"}</span></div><span className="text-[10px]">{added?"اضافه شده":"انتخاب"}</span></button>})}</div></div></div>}
 {mediaTarget&&<div className="fixed inset-0 z-[120] grid place-items-center bg-slate-950/80 p-4"><div className="max-h-[86vh] w-full max-w-4xl overflow-hidden rounded-3xl bg-[#0d1622]"><div className="flex items-center justify-between border-b border-white/10 p-4"><h2 className="font-black">انتخاب تصویر</h2><button onClick={()=>setMediaTarget(null)}><X/></button></div><div className="p-4"><label className="flex min-h-16 cursor-pointer items-center justify-center gap-3 rounded-2xl border-2 border-dashed border-emerald-400/30 bg-emerald-400/5 text-sm font-black text-emerald-200"><UploadSimple/>{mediaBusy?"در حال آپلود…":"آپلود تصویر جدید"}<input type="file" accept="image/*" className="hidden" disabled={mediaBusy} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadMedia(f);e.currentTarget.value=""}}/></label></div><div className="grid max-h-[58vh] grid-cols-2 gap-3 overflow-auto p-4 sm:grid-cols-4">{assets.map(a=><button key={a.id} onClick={()=>applyMedia(a.url)} className="overflow-hidden rounded-2xl border border-white/10"><img src={a.url} alt={a.name} className="aspect-[4/3] w-full object-cover"/><div className="truncate p-2 text-xs">{a.name}</div></button>)}</div></div></div>}
 {message&&<div className="fixed bottom-5 left-5 z-[140] rounded-xl bg-slate-950 px-4 py-3 text-xs shadow-2xl">{message}</div>}</main>;
}
