import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ArrowsClockwise, CaretDown, CaretUp, Desktop, DeviceMobile, DeviceTablet, Eye, FloppyDisk, Image, Layout, PaintBrush, Plus, Sparkle, TextT, Trash, Undo, Redo } from "@phosphor-icons/react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

type Project={id:string;name:string;siteType:string;content:Record<string,unknown>};
type SectionKind="hero"|"features"|"products"|"cta"|"footer";
type Section={id:string;kind:SectionKind,title:string,subtitle:string,bg:string,fg:string,padding:number,radius:number,align:"right"|"center"|"left"};
type Studio={sections:Section[];accent:string};
const makeId=()=>Math.random().toString(36).slice(2,10);
const defaults:Studio={accent:"#6C5DD3",sections:[
{id:"hero",kind:"hero",title:"جدیدترین محصولات با بهترین کیفیت",subtitle:"یک تجربه خرید سریع، ساده و حرفه‌ای با فروشگاه شما",bg:"#f7f5ff",fg:"#111827",padding:72,radius:0,align:"right"},
{id:"features",kind:"features",title:"چرا از ما خرید کنید؟",subtitle:"ارسال سریع · پرداخت امن · پشتیبانی واقعی",bg:"#ffffff",fg:"#111827",padding:44,radius:0,align:"center"},
{id:"products",kind:"products",title:"محصولات پرفروش",subtitle:"محصولات محبوب مشتریان را اینجا نمایش بده",bg:"#fafafa",fg:"#111827",padding:64,radius:0,align:"right"},
{id:"cta",kind:"cta",title:"آماده‌ای فروش را شروع کنی؟",subtitle:"همین حالا محصولاتت را به مشتریان نشان بده",bg:"#111827",fg:"#ffffff",padding:56,radius:28,align:"center"},
{id:"footer",kind:"footer",title:"فروشگاه شما",subtitle:"تمام حقوق محفوظ است.",bg:"#05070d",fg:"#cbd5e1",padding:40,radius:0,align:"right"},
]};
function normalize(project:Project|null):Studio{const raw=project?.content?.visualStudio as Studio|undefined;return raw?.sections?.length?raw:defaults;}
export default function VisualWebsiteStudioPage(){
 const[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[studio,setStudio]=useState<Studio>(defaults),[selected,setSelected]=useState("hero"),[viewport,setViewport]=useState<"desktop"|"tablet"|"mobile">("desktop"),[history,setHistory]=useState<Studio[]>([]),[future,setFuture]=useState<Studio[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{void apiFetch("/api/site-projects").then(async r=>{if(!r.ok)return;const d=await r.json();setProjects(d.projects||[]);if(d.projects?.[0])void choose(d.projects[0].id);});},[]);
 async function choose(id:string){const r=await apiFetch(`/api/site-projects/${id}`);if(!r.ok)return;const d=await r.json();setProject(d.project);const next=normalize(d.project);setStudio(next);setSelected(next.sections[0]?.id||"");setHistory([]);setFuture([]);}
 const active=studio.sections.find(s=>s.id===selected)||studio.sections[0];
 const width=viewport==="desktop"?"100%":viewport==="tablet"?"768px":"390px";
 function commit(next:Studio){setHistory(h=>[...h.slice(-39),studio]);setStudio(next);setFuture([]);}
 function patch(p:Partial<Section>){if(!active)return;commit({...studio,sections:studio.sections.map(s=>s.id===active.id?{...s,...p}:s)});}
 function move(id:string,delta:number){const i=studio.sections.findIndex(s=>s.id===id),j=i+delta;if(i<0||j<0||j>=studio.sections.length)return;const a=[...studio.sections];[a[i],a[j]]=[a[j],a[i]];commit({...studio,sections:a});}
 function add(kind:SectionKind){const labels:Record<SectionKind,string>={hero:"بخش قهرمان",features:"مزیت‌های ما",products:"محصولات",cta:"دعوت به اقدام",footer:"فوتر"};const s:Section={id:makeId(),kind,title:labels[kind],subtitle:"برای ویرایش این متن، بخش را انتخاب کن.",bg:"#ffffff",fg:"#111827",padding:56,radius:0,align:"right"};commit({...studio,sections:[...studio.sections,s]});setSelected(s.id);}
 function remove(){if(!active||studio.sections.length<=1)return;const arr=studio.sections.filter(s=>s.id!==active.id);commit({...studio,sections:arr});setSelected(arr[0].id);}
 function undo(){const prev=history.at(-1);if(!prev)return;setFuture(f=>[studio,...f]);setStudio(prev);setHistory(h=>h.slice(0,-1));}
 function redo(){const next=future[0];if(!next)return;setHistory(h=>[...h,studio]);setStudio(next);setFuture(f=>f.slice(1));}
 async function save(){if(!project)return;setBusy(true);setMsg("");try{const r=await apiFetch(`/api/site-projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:{...project.content,visualStudio:studio}})});const d=await r.json();if(!r.ok)throw new Error(d.message||"ذخیره انجام نشد");setProject(d.project);setMsg("طراحی Visual Studio ذخیره شد.");}catch(e){setMsg(e instanceof Error?e.message:"خطا در ذخیره");}finally{setBusy(false)}}
 const stats=useMemo(()=>({sections:studio.sections.length,undo:history.length}),[studio.sections.length,history.length]);
 return <main dir="rtl" className="min-h-screen bg-[#090d17] text-white">
  <header className="sticky top-0 z-50 flex h-16 items-center justify-between border-b border-white/10 bg-[#0c111d]/95 px-4 backdrop-blur-xl">
   <div className="flex items-center gap-3"><Link to="/dashboard/websites" className="rounded-xl border border-white/10 p-2 text-white/60"><ArrowRight/></Link><div><div className="text-sm font-bold">Loadder Visual Studio</div><div className="text-[11px] text-white/35">{project?.name||"یک پروژه انتخاب کن"}</div></div></div>
   <div className="flex items-center gap-2"><button onClick={undo} disabled={!history.length} className="rounded-xl border border-white/10 p-2 disabled:opacity-25"><Undo/></button><button onClick={redo} disabled={!future.length} className="rounded-xl border border-white/10 p-2 disabled:opacity-25"><Redo/></button><div className="mx-1 h-7 w-px bg-white/10"/><button onClick={()=>setViewport("desktop")} className={`rounded-xl p-2 ${viewport==="desktop"?"bg-violet-600":"bg-white/5"}`}><Desktop/></button><button onClick={()=>setViewport("tablet")} className={`rounded-xl p-2 ${viewport==="tablet"?"bg-violet-600":"bg-white/5"}`}><DeviceTablet/></button><button onClick={()=>setViewport("mobile")} className={`rounded-xl p-2 ${viewport==="mobile"?"bg-violet-600":"bg-white/5"}`}><DeviceMobile/></button></div>
   <div className="flex items-center gap-2"><button className="hidden items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-500/10 px-4 py-2 text-sm text-violet-200 md:flex"><Sparkle/> AI Design</button><button onClick={()=>window.open(project?`/api/auth/sites/${project.id}`:"#","_blank")} className="rounded-xl border border-white/10 p-2"><Eye/></button><button onClick={()=>void save()} disabled={!project||busy} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-sm font-bold disabled:opacity-40"><FloppyDisk/> ذخیره</button></div>
  </header>
  <div className="grid min-h-[calc(100vh-64px)] grid-cols-1 xl:grid-cols-[280px_minmax(0,1fr)_310px]">
   <aside className="order-2 border-l border-white/10 bg-[#0d1320] p-4 xl:order-1">
    <select value={project?.id||""} onChange={e=>void choose(e.target.value)} className="input mb-5"><option value="">انتخاب پروژه</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
    <div className="flex items-center justify-between"><h2 className="text-sm font-bold">لایه‌ها و بخش‌ها</h2><span className="text-xs text-white/30">{stats.sections}</span></div>
    <div className="mt-3 space-y-2">{studio.sections.map((s,i)=><div key={s.id} onClick={()=>setSelected(s.id)} className={`group flex cursor-pointer items-center gap-2 rounded-xl border p-3 ${selected===s.id?"border-violet-400/30 bg-violet-500/10":"border-white/8 bg-white/[0.025]"}`}><Layout className="shrink-0 text-white/45"/><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{s.title}</div><div className="text-[10px] uppercase text-white/25">{s.kind}</div></div><div className="flex opacity-0 group-hover:opacity-100"><button onClick={e=>{e.stopPropagation();move(s.id,-1)}} disabled={i===0}><CaretUp/></button><button onClick={e=>{e.stopPropagation();move(s.id,1)}} disabled={i===studio.sections.length-1}><CaretDown/></button></div></div>)}</div>
    <h3 className="mt-6 text-xs font-bold text-white/45">افزودن بخش</h3><div className="mt-3 grid grid-cols-2 gap-2">{(["hero","features","products","cta"] as SectionKind[]).map(k=><button key={k} onClick={()=>add(k)} className="flex items-center gap-2 rounded-xl border border-white/8 bg-white/[0.03] p-3 text-xs hover:bg-white/[0.07]"><Plus/> {k}</button>)}</div>
   </aside>
   <section className="order-1 overflow-auto bg-[#111827] p-4 md:p-8 xl:order-2">
    <div className="mx-auto transition-all duration-300" style={{width,maxWidth:"100%"}}><div className="overflow-hidden rounded-md bg-white shadow-2xl shadow-black/40">
     <nav className="flex items-center justify-between border-b border-slate-100 px-6 py-4 text-slate-900"><strong>{project?.name||"فروشگاه شما"}</strong><div className="hidden gap-5 text-xs text-slate-500 md:flex"><span>خانه</span><span>محصولات</span><span>درباره ما</span><span>تماس</span></div></nav>
     {studio.sections.map(s=><CanvasSection key={s.id} section={s} selected={selected===s.id} accent={studio.accent} onSelect={()=>setSelected(s.id)}/>) }
    </div></div>
    {msg&&<div className="mx-auto mt-4 max-w-xl rounded-xl border border-white/10 bg-black/30 p-3 text-center text-xs text-white/60">{msg}</div>}
   </section>
   <aside className="order-3 border-r border-white/10 bg-[#0d1320] p-5">
    <div className="flex items-center gap-2"><PaintBrush className="text-violet-300"/><h2 className="font-bold">تنظیمات بخش</h2></div>{active?<div className="mt-5 space-y-5">
     <Field label="عنوان"><input className="input" value={active.title} onChange={e=>patch({title:e.target.value})}/></Field>
     <Field label="توضیح"><textarea className="input min-h-24" value={active.subtitle} onChange={e=>patch({subtitle:e.target.value})}/></Field>
     <div className="grid grid-cols-2 gap-3"><Field label="پس‌زمینه"><input type="color" className="h-11 w-full rounded-xl bg-transparent" value={active.bg} onChange={e=>patch({bg:e.target.value})}/></Field><Field label="رنگ متن"><input type="color" className="h-11 w-full rounded-xl bg-transparent" value={active.fg} onChange={e=>patch({fg:e.target.value})}/></Field></div>
     <Field label={`فاصله داخلی: ${active.padding}px`}><input type="range" min="16" max="120" value={active.padding} onChange={e=>patch({padding:Number(e.target.value)})} className="w-full"/></Field>
     <Field label={`گردی گوشه: ${active.radius}px`}><input type="range" min="0" max="48" value={active.radius} onChange={e=>patch({radius:Number(e.target.value)})} className="w-full"/></Field>
     <Field label="تراز"><div className="grid grid-cols-3 gap-2">{(["right","center","left"] as const).map(a=><button key={a} onClick={()=>patch({align:a})} className={`rounded-xl border p-2 text-xs ${active.align===a?"border-violet-400/40 bg-violet-500/15":"border-white/10"}`}>{a}</button>)}</div></Field>
     <Field label="رنگ برند"><input type="color" value={studio.accent} onChange={e=>commit({...studio,accent:e.target.value})} className="h-11 w-full rounded-xl bg-transparent"/></Field>
     <button onClick={remove} className="flex w-full items-center justify-center gap-2 rounded-xl border border-rose-400/20 bg-rose-500/10 p-3 text-sm text-rose-300"><Trash/> حذف این بخش</button>
    </div>:<div className="mt-6 text-sm text-white/35">یک بخش را از Canvas یا Layers انتخاب کن.</div>}
    <div className="mt-7 rounded-2xl border border-violet-400/15 bg-violet-500/[0.07] p-4"><div className="flex items-center gap-2 text-sm font-bold text-violet-200"><Sparkle/> AI Copilot</div><p className="mt-2 text-xs leading-6 text-white/40">نسخه بعدی: «این Hero را لوکس‌تر کن»، «رنگ‌ها را با برند من هماهنگ کن» و تغییرات قابل Accept/Undo.</p></div>
   </aside>
  </div>
 </main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs text-white/40">{label}</span>{children}</label>}
function CanvasSection({section:s,selected,accent,onSelect}:{section:Section;selected:boolean;accent:string;onSelect:()=>void}){const style={background:s.bg,color:s.fg,padding:`${s.padding}px 28px`,borderRadius:s.radius,textAlign:s.align as "right"|"center"|"left"};return <section onClick={onSelect} className={`relative cursor-pointer transition ${selected?"outline outline-2 outline-violet-500 outline-offset-[-2px]":"hover:outline hover:outline-1 hover:outline-violet-300/60"}`} style={style}>{selected&&<div className="absolute right-3 top-3 rounded-full bg-violet-600 px-3 py-1 text-[10px] text-white">{s.kind}</div>}{s.kind==="hero"?<div className="mx-auto grid max-w-6xl items-center gap-10 md:grid-cols-2"><div><span className="text-xs font-bold" style={{color:accent}}>فروشگاه آنلاین</span><h1 className="mt-4 text-4xl font-black leading-tight md:text-6xl">{s.title}</h1><p className="mt-5 leading-8 opacity-60">{s.subtitle}</p><button className="mt-7 rounded-xl px-6 py-3 text-sm font-bold text-white" style={{background:accent}}>مشاهده محصولات</button></div><div className="flex aspect-square items-center justify-center rounded-[40px] bg-gradient-to-br from-slate-100 to-violet-100"><Image size={86} className="text-violet-300"/></div></div>:s.kind==="products"?<div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-2 opacity-50">{s.subtitle}</p><div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-4">{[1,2,3,4].map(n=><div key={n} className="rounded-2xl border border-black/5 bg-white p-3 text-slate-900 shadow-sm"><div className="aspect-square rounded-xl bg-slate-100"/><div className="mt-3 font-bold">محصول نمونه {n}</div><div className="mt-1 text-xs text-slate-400">۱,۲۵۰,۰۰۰ تومان</div></div>)}</div></div>:<div className="mx-auto max-w-5xl"><h2 className="text-3xl font-black">{s.title}</h2><p className="mt-3 leading-8 opacity-55">{s.subtitle}</p>{s.kind==="features"&&<div className="mt-7 grid gap-3 md:grid-cols-3">{["ارسال سریع","پرداخت امن","پشتیبانی حرفه‌ای"].map(x=><div key={x} className="rounded-2xl border border-black/5 bg-white/60 p-5 font-bold text-slate-800">{x}</div>)}</div>}{s.kind==="cta"&&<button className="mt-6 rounded-xl px-6 py-3 font-bold text-white" style={{background:accent}}>شروع خرید</button>}</div>}</section>}
