import test from "node:test";
import assert from "node:assert/strict";
import {copyFileSync,mkdtempSync,rmSync,readFileSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import Database from "better-sqlite3";
import express from "express";
import {runMigrations} from "../db/migrate.mjs";
import {migrations} from "../db/migrations/index.mjs";
import {runWithWorkspace} from "../app/tenant-context.mjs";
import {createActionProposalContractRegistry,actionProposalContractRegistry} from "../app/action-proposals/action-proposal-contract-registry.mjs";
import {createActionProposalRepository} from "../app/repositories/action-proposal-repository.mjs";
import {createIntelligenceRecommendationRepository} from "../app/repositories/intelligence-recommendation-repository.mjs";
import {createHumanGovernanceRepository} from "../app/repositories/human-governance-repository.mjs";
import {createActionProposalService} from "../app/services/action-proposal-service.mjs";
import {createActionProposalRouter} from "../app/routes/action-proposals.mjs";
import {createOperationMetrics} from "../app/observability/operation-metrics.mjs";
import {encodeCursor} from "../app/query/cursor-pagination.mjs";

function copyPhaseBaseline(source,target){copyFileSync(source,target);const db=new Database(target);db.exec("DELETE FROM schema_migrations WHERE version=46;DROP TABLE IF EXISTS content_generations;DELETE FROM schema_migrations WHERE version=45;DROP TABLE IF EXISTS execution_action_inputs;DELETE FROM schema_migrations WHERE version=44;DROP TABLE IF EXISTS execution_dispatch_jobs;DELETE FROM schema_migrations WHERE version=43;DROP TABLE IF EXISTS execution_results;DROP TABLE IF EXISTS provider_invocation_events;DROP TABLE IF EXISTS execution_attempts;DELETE FROM schema_migrations WHERE version=42;DROP TABLE IF EXISTS provider_account_identities;DELETE FROM schema_migrations WHERE version=41;DROP TRIGGER IF EXISTS trg_execution_requests_update;DROP TRIGGER IF EXISTS trg_execution_requests_delete;DROP TRIGGER IF EXISTS trg_execution_requests_insert_guard;DROP INDEX IF EXISTS idx_execution_requests_page;DROP TABLE IF EXISTS execution_requests;DELETE FROM schema_migrations WHERE version=40;");db.close();}
const AT="2026-08-21T12:00:00.000Z",sha="a".repeat(64);
const contract=(type="test_review_followup")=>({actionType:type,actionVersion:1,schemaVersion:1,supportedRecommendationTypes:["attention_evidence_review"],supportedDecisionTypes:["ADOPT"],supportedTargetTypes:["recommendation_subject"],riskClass:"NON_EXECUTING",executionEligible:false,executable:false,requiresAuthorization:true,producer:"test_human_action_proposal",producerVersion:"1.0",policyVersion:"1.0"});

test("Phase 4I v1 Controlled Action Proposal foundation",async t=>{
 const dir=mkdtempSync(join(tmpdir(),"loadder-action-proposal-")),path=join(dir,"proposal.sqlite");copyPhaseBaseline(new URL("../db/loadder.sqlite",import.meta.url),path);const db=new Database(path);db.pragma("foreign_keys=ON");
 db.exec(`
   DROP TRIGGER IF EXISTS trg_execution_authorizations_update;
   DROP TRIGGER IF EXISTS trg_execution_authorizations_delete;
   DROP TRIGGER IF EXISTS trg_execution_authorizations_insert_guard;
   DROP INDEX IF EXISTS idx_execution_authorizations_page;
   DROP TABLE IF EXISTS execution_authorizations;
   DELETE FROM schema_migrations WHERE version=39;
   DROP TRIGGER IF EXISTS trg_action_proposals_update;
   DROP TRIGGER IF EXISTS trg_action_proposals_delete;
   DROP TRIGGER IF EXISTS trg_action_proposals_insert_guard;
   DROP INDEX IF EXISTS idx_action_proposals_page;
   DROP TABLE IF EXISTS action_proposals;
   DELETE FROM schema_migrations WHERE version=38;
 `);
 assert.deepEqual(db.prepare("SELECT COUNT(*) c,MAX(version) m FROM schema_migrations").get(),{c:37,m:37});
 const beforeTables=db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();
 runMigrations(db,migrations.filter(x=>x.version<=38));runMigrations(db,migrations.filter(x=>x.version<=38));
 const setup=(wid)=>{db.prepare("INSERT INTO workspaces(id,name,slug,created_at,updated_at)VALUES(?,?,?,?,?)").run(wid,wid,wid,AT,AT);db.prepare("INSERT INTO business_profiles(id,workspace_id,name,status,created_at,updated_at)VALUES(?,?,?,?,?,?)").run(`p-${wid}`,wid,wid,"active",AT,AT);db.prepare("INSERT INTO business_dna_versions(id,workspace_id,business_profile_id,version_number,status,created_at,updated_at)VALUES(?,?,?,?,?,?,?)").run(`dna-${wid}`,wid,`p-${wid}`,1,"active",AT,AT);db.prepare("INSERT INTO brand_book_versions(id,workspace_id,business_profile_id,version_number,status,created_at,updated_at)VALUES(?,?,?,?,?,?,?)").run(`book-${wid}`,wid,`p-${wid}`,1,"active",AT,AT);db.prepare("INSERT INTO business_context_versions(id,workspace_id,business_profile_id,business_dna_version_id,brand_book_version_id,version_number,status,context_schema_version,snapshot_json,source_manifest_json,created_at,activated_at)VALUES(?,?,?,?,?,1,'active','1.0','{}','{}',?,?)").run(`ctx-${wid}`,wid,`p-${wid}`,`dna-${wid}`,`book-${wid}`,AT,AT);};setup("pa");setup("pb");
 let actorNumber=0;const actor=(id,role,wid="pa")=>{actorNumber++;db.prepare("INSERT INTO users(id,mobile,name,status,created_at,updated_at)VALUES(?,?,?,?,?,?)").run(id,`0912000000${actorNumber}`,id,"active",AT,AT);const membershipId=`m-${id}`;db.prepare("INSERT INTO workspace_memberships(id,workspace_id,user_id,role,status,created_at,updated_at)VALUES(?,?,?,?,?,?,?)").run(membershipId,wid,id,role,"active",AT,AT);return{userId:id,membershipId,role};};const owner=actor("proposal-owner","owner"),member=actor("proposal-member","member"),foreign=actor("proposal-foreign","owner","pb");
 const rec=(id,wid="pa")=>db.prepare("INSERT INTO intelligence_recommendations(id,workspace_id,recommendation_type,recommendation_version,schema_version,subject_type,subject_id,subject_key,consideration_code,rationale_code,review_priority,semantic_manifest_json,semantic_manifest_hash,semantic_finding_count,context_version_id,point_in_time_cutoff,producer,producer_version,producer_key,confidence,confidence_reason,provenance_json,calculated_at,created_at)VALUES(?,?,'attention_evidence_review',1,1,'listening_scope',NULL,'scope','REVIEW_ATTENTION_INCREASE','ATTENTION_RISING','MEDIUM','[]',?,0,?,?,'test','1',?,NULL,'DETERMINISTIC','{}',?,?)").run(id,wid,sha,`ctx-${wid}`,AT,id,AT,AT);rec("r-pa");rec("r-pa-2");rec("r-pb","pb");
 const decision=(id,recommendationId,wid,type="ADOPT",supersedes=null,who=owner)=>db.prepare("INSERT INTO decision_records(id,workspace_id,recommendation_id,recommendation_version,context_version_id,decider_user_id,decider_membership_id,decider_role,decision_type,authority_class,execution_authorizing,observed_freshness,supersedes_decision_id,operation_kind,idempotency_key,request_hash,decided_at,created_at)VALUES(?,?,?,?,?,?,?,?,?,'BUSINESS_INTENT',0,'CURRENT',?,'decision.create',?,?,?,?)").run(id,wid,recommendationId,1,`ctx-${wid}`,who.userId,who.membershipId,who.role,type,supersedes,`key-${id}`,sha,AT,AT);decision("d-adopt","r-pa","pa");decision("d-decline","r-pa","pa","DECLINE","d-adopt");decision("d-current-2","r-pa-2","pa");decision("d-foreign","r-pb","pb","ADOPT",null,foreign);
 const registry=createActionProposalContractRegistry([contract(),contract("test_review_followup_alt")]),repository=createActionProposalRepository(db),recommendations=createIntelligenceRecommendationRepository(db),governance=createHumanGovernanceRepository(db),metrics=createOperationMetrics({limit:100}),service=createActionProposalService({repository,registry,decisionQuery:governance,recommendationRepository:recommendations,now:()=>new Date(AT),operationMetrics:metrics}),within=(wid,fn)=>runWithWorkspace(wid,fn);

 await t.test("migration 038 is idempotent, adds exactly one table, and preserves prior schemas",()=>{assert.deepEqual(db.prepare("SELECT COUNT(*) c,MAX(version) m FROM schema_migrations").get(),{c:38,m:38});const after=db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name!='action_proposals' ORDER BY name").all();assert.deepEqual(after,beforeTables);assert.equal(db.prepare("SELECT COUNT(*) c FROM sqlite_master WHERE type='table' AND name='action_proposals'").get().c,1);});
 await t.test("production registry is intentionally empty and rejects invented actions",()=>{assert.deepEqual(actionProposalContractRegistry.list(),[]);const production=createActionProposalService({repository,registry:actionProposalContractRegistry,decisionQuery:governance,recommendationRepository:recommendations});assert.throws(()=>within("pa",()=>production.create("d-decline",{actionType:"SEND_SMS"},owner,"unsupported")),e=>e.code==="ACTION_PROPOSAL_UNSUPPORTED");});
 await t.test("registry rejects parameters and executable contracts",()=>{assert.throws(()=>createActionProposalContractRegistry([{...contract("bad"),parameterSchema:{}}]));assert.throws(()=>createActionProposalContractRegistry([{...contract("bad2"),executable:true}]));});
 await t.test("request is strict and member is denied",()=>{assert.throws(()=>within("pa",()=>service.create("d-decline",{actionType:"test_review_followup",parameters:{}},owner,"x")));assert.throws(()=>within("pa",()=>service.create("d-decline",{actionType:"test_review_followup"},member,"x")),e=>e.code==="ACTION_PROPOSAL_PERMISSION_DENIED");});
 await t.test("non-ADOPT and superseded decisions are rejected",()=>{assert.throws(()=>within("pa",()=>service.create("d-decline",{actionType:"test_review_followup"},owner,"decline")),e=>e.code==="DECISION_NOT_ADOPTED");assert.throws(()=>within("pa",()=>service.create("d-adopt",{actionType:"test_review_followup"},owner,"old")),e=>e.code==="DECISION_SUPERSEDED");});
 await t.test("cross-workspace decisions are indistinguishable from missing",()=>assert.throws(()=>within("pa",()=>service.create("d-foreign",{actionType:"test_review_followup"},owner,"foreign")),e=>e.code==="DECISION_NOT_FOUND"&&e.status===404));
 decision("d-current","r-pa","pa","ADOPT","d-decline");
 let first;
 await t.test("creates a fixed non-executing immutable proposal",()=>within("pa",()=>{first=service.create("d-current",{actionType:"test_review_followup"},owner,"create-1").proposal;assert.equal(first.executionEligible,false);assert.equal(first.executable,false);assert.equal(first.requiresAuthorization,true);assert.equal(first.riskClass,"NON_EXECUTING");assert.match(first.proposalHash,/^[a-f0-9]{64}$/);assert.equal(Object.hasOwn(first,"parameters"),false);}));
 await t.test("exact retry, concurrent convergence, and deterministic identity reuse",async()=>within("pa",async()=>{const [retry,concurrent]=await Promise.all([Promise.resolve().then(()=>service.create("d-current",{actionType:"test_review_followup"},owner,"create-1")),Promise.resolve().then(()=>service.create("d-current",{actionType:"test_review_followup"},owner,"create-1"))]);assert.equal(retry.proposal.id,first.id);assert.equal(concurrent.proposal.id,first.id);assert.equal(retry.reusedResult,true);assert.equal(concurrent.reusedResult,true);const reuse=service.create("d-current",{actionType:"test_review_followup"},owner,"create-2");assert.equal(reuse.proposal.id,first.id);assert.equal(reuse.proposal.proposalHash,first.proposalHash);}));
 await t.test("same idempotency key with a changed registered request is rejected",()=>within("pa",()=>assert.throws(()=>service.create("d-current",{actionType:"test_review_followup_alt"},owner,"create-1"),e=>e.code==="IDEMPOTENCY_KEY_REUSED")));
 await t.test("database rejects update, delete, identity mismatches, and fixed-flag changes",()=>{assert.throws(()=>db.prepare("UPDATE action_proposals SET target_key='changed' WHERE id=?").run(first.id),/immutable/);assert.throws(()=>db.prepare("DELETE FROM action_proposals WHERE id=?").run(first.id),/immutable/);const row=db.prepare("SELECT * FROM action_proposals WHERE id=?").get(first.id);for(const [column,value] of [["execution_eligible",1],["executable",1],["requires_authorization",0]])assert.throws(()=>{const copy={...row,id:`bad-${column}`,idempotency_key:`bad-${column}`,producer_key:`bad-${column}`,proposal_hash:"b".repeat(64),[column]:value};db.prepare(`INSERT INTO action_proposals(${Object.keys(copy).join(",")})VALUES(${Object.keys(copy).map(()=>"?").join(",")})`).run(...Object.values(copy));});assert.throws(()=>{const copy={...row,id:"bad-tenant",workspace_id:"pb",idempotency_key:"bad-tenant",producer_key:"bad-tenant",proposal_hash:"c".repeat(64)};db.prepare(`INSERT INTO action_proposals(${Object.keys(copy).join(",")})VALUES(${Object.keys(copy).map(()=>"?").join(",")})`).run(...Object.values(copy));});assert.throws(()=>{const copy={...row,id:"bad-recommendation",recommendation_id:"r-pa-2",idempotency_key:"bad-recommendation",producer_key:"bad-recommendation",proposal_hash:"d".repeat(64)};db.prepare(`INSERT INTO action_proposals(${Object.keys(copy).join(",")})VALUES(${Object.keys(copy).map(()=>"?").join(",")})`).run(...Object.values(copy));});});
 await t.test("tenant detail is hidden and lists are bounded",()=>{assert.throws(()=>within("pb",()=>service.get(first.id)),e=>e.code==="ACTION_PROPOSAL_NOT_FOUND");assert.equal(within("pa",()=>service.list({limit:1})).items.length,1);assert.throws(()=>within("pa",()=>service.list({limit:101})));assert.throws(()=>within("pa",()=>service.list({state:"open"})));});
 await t.test("keyset pages have no overlap or loss and reject invalid cursors",()=>within("pa",()=>{const second=service.create("d-current-2",{actionType:"test_review_followup_alt"},owner,"create-second").proposal;const page1=service.list({limit:1}),page2=service.list({limit:1,cursor:page1.nextCursor});assert.equal(page1.items.length,1);assert.equal(page2.items.length,1);assert.equal(new Set([...page1.items,...page2.items].map(item=>item.id)).size,2);assert.deepEqual(new Set([...page1.items,...page2.items].map(item=>item.id)),new Set([first.id,second.id]));assert.equal(page2.nextCursor,null);assert.throws(()=>service.list({cursor:"bad!"}),e=>e.code==="INVALID_CURSOR");assert.throws(()=>service.list({cursor:encodeCursor("decision_records",{createdAt:AT,id:"x"})}),e=>e.code==="INVALID_CURSOR");}));
 await t.test("HTTP exposes only proposal create/list/detail and no execution shortcuts",async()=>{const app=express();app.use(express.json());app.use((req,res,next)=>{req.user={id:owner.userId};req.membership={id:owner.membershipId,role:owner.role};runWithWorkspace("pa",next);});app.use("/api",createActionProposalRouter({service}));const server=await new Promise(resolve=>{const candidate=app.listen(0,"127.0.0.1",()=>resolve(candidate));});const base=`http://127.0.0.1:${server.address().port}/api`;assert.equal((await fetch(`${base}/execution/action-proposals`)).status,200);assert.equal((await fetch(`${base}/execution/action-proposals/${first.id}`)).status,200);for(const path of ["execute","authorize","request","run","send","publish","launch","retry"])assert.equal((await fetch(`${base}/${path}`,{method:"POST"})).status,404);await new Promise(resolve=>server.close(resolve));});
 await t.test("metrics are bounded and content-safe",()=>{const data=JSON.stringify(metrics.recent());for(const value of ["test_review_followup","scope","d-current",first.proposalHash])assert.equal(data.includes(value),false);assert.ok(metrics.recent().some(x=>x.operation==="action_proposal.create"&&Object.hasOwn(x,"proposalCount")));});
 await t.test("query plan uses tenant-leading pagination index",()=>within("pa",()=>{const plan=db.prepare("EXPLAIN QUERY PLAN SELECT * FROM action_proposals WHERE workspace_id=? ORDER BY created_at DESC,id DESC LIMIT ?").all("pa",51).map(x=>x.detail).join(" ");assert.match(plan,/idx_action_proposals_page/);}));
 await t.test("dependencies exclude prohibited domains and database stays valid",()=>{const sources=["../app/action-proposals/action-proposal-contract-registry.mjs","../app/repositories/action-proposal-repository.mjs","../app/services/action-proposal-service.mjs","../app/routes/action-proposals.mjs"].map(x=>readFileSync(new URL(x,import.meta.url),"utf8")).join("\n");for(const forbidden of ["semantic_findings","canonical_listening_records","customers","marketing_campaigns","automations","executions","messaging","openai","embedding","connector_connections"])assert.equal(sources.includes(forbidden),false);assert.equal(db.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(db.pragma("foreign_key_check"),[]);});
 db.close();rmSync(dir,{recursive:true,force:true});
});
