import assert from "node:assert/strict";
import test from "node:test";
import {readFileSync} from "node:fs";
import Database from "better-sqlite3";
import {runMigrations} from "../db/migrate.mjs";
import {migration045ContentGenerations} from "../db/migrations/045_content_generations.mjs";
import {migration047ContentItems} from "../db/migrations/047_content_items.mjs";
import {migration048ContentItemSourceIdentity} from "../db/migrations/048_content_item_source_identity.mjs";
import {migration049ContentAssets} from "../db/migrations/049_content_assets.mjs";
import {migration050RealAssetUpload} from "../db/migrations/050_real_asset_upload.mjs";
import {migration051UploadedCreativeLinkage} from "../db/migrations/051_uploaded_creative_linkage.mjs";
import {migration052CreativePlacements} from "../db/migrations/052_creative_placements.mjs";
import {migration053CreativeIntents} from "../db/migrations/053_creative_intents.mjs";
import {migration054DistributionContexts} from "../db/migrations/054_distribution_contexts.mjs";
import {migration055AttributionTouches} from "../db/migrations/055_attribution_touches.mjs";
import {runWithWorkspace} from "../app/tenant-context.mjs";
import {createDistributionContextRepository} from "../app/repositories/distribution-context-repository.mjs";
import {createAttributionTouchRepository} from "../app/repositories/attribution-touch-repository.mjs";
import {createAttributionTouchService} from "../app/services/attribution-touch-service.mjs";
import {createOperationMetrics} from "../app/observability/operation-metrics.mjs";

const AT="2026-08-23T12:00:00.000Z",W="workspace",U="user",D="distribution",SHA="a".repeat(64),actor={userId:U,role:"member"};
const prior=[migration045ContentGenerations,migration047ContentItems,migration048ContentItemSourceIdentity,migration049ContentAssets,migration050RealAssetUpload,migration051UploadedCreativeLinkage,migration052CreativePlacements,migration053CreativeIntents,migration054DistributionContexts];
function base(){const db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);");runMigrations(db,prior);db.exec("INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('workspace','active');INSERT INTO workspaces VALUES('other','active');INSERT INTO workspace_memberships VALUES('membership','workspace','user','member','active');");db.prepare("INSERT INTO content_items(id,workspace_id,created_by_user_id,source_type,source_generation_id,source_variant_index,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,primary_asset_id,title,content_json,revision,operation_kind,idempotency_key,request_hash,created_at,updated_at,intent_id)VALUES('item',?,?,'MANUAL_TEXT',NULL,NULL,'TEXT','social_post',1,'instagram.feed.text',1,NULL,NULL,'Creative','{}',1,'content_item.manual','item-key',?,?,?,NULL)").run(W,U,SHA,AT,AT);db.prepare("INSERT INTO creative_placements(id,workspace_id,content_item_id,placement_kind,channel,status,external_reference_id,created_by_user_id,operation_kind,idempotency_key,request_hash,created_at,updated_at)VALUES('placement',?,'item','SOCIAL','instagram','ACTIVE',NULL,?,'creative_placement.create','placement-key',?,?,?)").run(W,U,SHA,AT,AT);db.prepare("INSERT INTO distribution_contexts(id,workspace_id,creative_placement_id,channel_id,channel_version,provider,acquisition_mode,destination_reference,tracking_contract_version,created_by_user_id,operation_kind,idempotency_key,request_hash,created_at)VALUES(?,?,'placement','social',1,'instagram','ORGANIC','https://example.com/landing',1,?,'distribution_context.create','distribution-key',?,?)").run(D,W,U,SHA,AT);return db;}
function fixture(){const db=base();runMigrations(db,[migration055AttributionTouches]);let tick=Date.parse(AT);return{db,service:createAttributionTouchService({repository:createAttributionTouchRepository(db),distributionContextRepository:createDistributionContextRepository(db),operationMetrics:createOperationMetrics(),now:()=>new Date(tick+=1000)})};}
const within=(fn,workspace=W)=>runWithWorkspace(workspace,fn),input=(overrides={})=>({distributionContextId:D,touchType:"LANDING_VISIT",sensorType:"website",sensorVersion:1,occurredAt:AT,anonymousSessionKey:"session-correlation",visitorCorrelationKey:"visitor-correlation",landingReference:"https://example.com/landing?utm_source=instagram",sourceSnapshot:"instagram/raw",mediumSnapshot:"social/raw",utmSnapshot:{utm_source:"Instagram",utm_medium:"Social"},externalReference:"event-1",payloadFingerprint:SHA,...overrides}),create=(f,key="touch-key",value=input(),who=actor)=>within(()=>f.service.create(value,who,key));

test("Attribution Touch Foundation v1",async t=>{
 await t.test("migration 055 adds exactly one append-only table and is idempotent",()=>{const db=base(),before=db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();runMigrations(db,[migration055AttributionTouches]);runMigrations(db,[migration055AttributionTouches]);assert.deepEqual(db.prepare("SELECT count(*) count,max(version) max FROM schema_migrations WHERE version=55").get(),{count:1,max:55});assert.deepEqual(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT IN("+before.map(()=>"?").join(",")+")").all(...before.map(x=>x.name)),[{name:"attribution_touches"}]);for(const row of before)assert.equal(db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(row.name).sql,row.sql);});
 await t.test("preserves bounded raw provenance without normalization loss",()=>{const f=fixture(),x=create(f,"raw",input({sourceSnapshot:" Instagram / Raw ",mediumSnapshot:" Social / Raw ",externalReference:" Provider Event 1 "})).touch;assert.equal(x.touchType,"LANDING_VISIT");assert.equal(x.sourceSnapshot," Instagram / Raw ");assert.equal(x.mediumSnapshot," Social / Raw ");assert.deepEqual(x.utmSnapshot,{utm_source:"Instagram",utm_medium:"Social"});assert.equal(x.externalReference," Provider Event 1 ");assert.equal(x.payloadFingerprint,SHA);});
 await t.test("touch is not a session and correlations are optional",()=>{const f=fixture(),a=create(f),b=create(f,"touch-2",input({externalReference:"event-2",anonymousSessionKey:null,visitorCorrelationKey:null}));assert.notEqual(a.touch.id,b.touch.id);assert.equal(b.touch.anonymousSessionKey,null);assert.equal(b.touch.visitorCorrelationKey,null);});
 await t.test("all bounded touch types are accepted and excessive taxonomy is rejected",()=>{for(const touchType of ["LANDING_VISIT","CLICK","MESSAGE_INTERACTION","FORM_START","FORM_SUBMIT","CALL_ACTION","OTHER"]){const f=fixture();assert.equal(create(f,touchType,input({touchType})).touch.touchType,touchType);}const f=fixture();assert.throws(()=>create(f,"bad",input({touchType:"INSTAGRAM_PROFILE_CLICK"})),e=>e.code==="ATTRIBUTION_TOUCH_INVALID");});
 await t.test("same observed event reuses and changed event conflicts",()=>{const f=fixture(),a=create(f),b=create(f);assert.equal(a.touch.id,b.touch.id);assert.equal(b.reusedResult,true);assert.throws(()=>create(f,"touch-key",input({mediumSnapshot:"changed"})),e=>e.code==="ATTRIBUTION_TOUCH_IDEMPOTENCY_CONFLICT");});
 await t.test("multiple touches per distribution context remain separate facts",()=>{const f=fixture();for(let i=0;i<3;i++)create(f,`key-${i}`,input({externalReference:`event-${i}`,touchType:i?"CLICK":"LANDING_VISIT"}));const page=within(()=>f.service.list(D,{limit:10},actor));assert.equal(page.touches.length,3);assert.equal(new Set(page.touches.map(x=>x.id)).size,3);});
 await t.test("tenant isolation hides foreign and missing contexts",()=>{const f=fixture();assert.throws(()=>within(()=>f.service.list(D,{},actor),"other"),e=>e.code==="DISTRIBUTION_CONTEXT_NOT_FOUND");assert.throws(()=>create(f,"missing",input({distributionContextId:"missing"})),e=>e.code==="DISTRIBUTION_CONTEXT_NOT_FOUND");});
 await t.test("strict ownership and unrelated fields are rejected",()=>{for(const field of ["workspaceId","userId","customerId","leadId","campaignId","conversion","fraudScore","attributionCredit","metrics"]){const f=fixture();assert.throws(()=>create(f,field,{...input(),[field]:"x"}),e=>e.code==="ATTRIBUTION_TOUCH_INVALID");}});
 await t.test("database linkage guards and immutability are enforced",()=>{const f=fixture(),id=create(f).touch.id;assert.throws(()=>f.db.prepare("UPDATE attribution_touches SET touch_type='CLICK' WHERE id=?").run(id));assert.throws(()=>f.db.prepare("DELETE FROM attribution_touches WHERE id=?").run(id));assert.throws(()=>f.db.prepare("INSERT INTO attribution_touches(id,workspace_id,distribution_context_id,touch_type,sensor_type,sensor_version,occurred_at,ingested_at,idempotency_key,request_hash,created_at)VALUES('bad','other',?,'CLICK','website',1,?,?,?, ?,?)").run(D,AT,AT,"bad",SHA,AT));});
 await t.test("history is bounded and cursor pagination has no overlap",()=>{const f=fixture();for(let i=0;i<3;i++)create(f,`key-${i}`,input({externalReference:`event-${i}`,occurredAt:new Date(Date.parse(AT)+i*1000).toISOString()}));const a=within(()=>f.service.list(D,{limit:2},actor)),b=within(()=>f.service.list(D,{limit:2,cursor:a.nextCursor},actor));assert.equal(a.touches.length,2);assert.equal(b.touches.length,1);assert.equal(new Set([...a.touches,...b.touches].map(x=>x.id)).size,3);});
 await t.test("schema and sources have no customer performance fraud connector or runtime coupling",()=>{const f=fixture(),columns=f.db.prepare("SELECT name FROM pragma_table_info('attribution_touches')").all().map(x=>x.name);for(const forbidden of ["customer_id","lead_id","campaign_id","conversion","fraud_score","attribution_credit","metrics_json","performance_score"])assert.equal(columns.includes(forbidden),false);const source=["../app/repositories/attribution-touch-repository.mjs","../app/services/attribution-touch-service.mjs","../app/routes/attribution-touches.mjs"].map(p=>readFileSync(new URL(p,import.meta.url),"utf8").toLowerCase()).join("\n");for(const forbidden of ["google-analytics","ga4","instagram-connector","sms-connector","crm-sync","performance_observations","fraud_score","attribution_credit","fetch(","worker","queue","redis"])assert.equal(source.includes(forbidden),false);assert.equal(f.db.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(f.db.pragma("foreign_key_check"),[]);});
});
