import test from"node:test";import assert from"node:assert/strict";import{BUSINESS_BLUEPRINTS}from"../app/business-builder/business-blueprints.mjs";import{loadderBusinessCompiler}from"../app/business-builder/business-compiler.mjs";import{getLoadderAppStore}from"../app/business-builder/app-store.mjs";import{LOADDER_COMMERCE_CORE,validateCommerceBinding}from"../app/business-builder/commerce-core-contract.mjs";

test("app store exposes commerce and accounting as deterministic owned blueprints",()=>{const store=getLoadderAppStore(),ids=new Set(store.map(x=>x.id));assert.ok(ids.has("commerce"));assert.ok(ids.has("accounting"));assert.equal(store.find(x=>x.id==="commerce")?.tokenCost,0);assert.equal(store.find(x=>x.id==="accounting")?.portable,true);assert.equal(Object.keys(BUSINESS_BLUEPRINTS).length,10);});

test("commerce compiles exact shared order domain",()=>{const d=loadderBusinessCompiler.compile({intent:"فروشگاه اینترنتی بساز",blueprintId:"commerce",locale:"fa-IR"}),entities=new Set(d.entities.map(x=>x.id));for(const id of["customer","product","order","orderItem","payment","fulfillment"])assert.ok(entities.has(id));assert.equal(d.vertical,"commerce");});

test("accounting compiles operational finance without claiming jurisdictional tax compliance",()=>{const d=loadderBusinessCompiler.compile({intent:"اپ حسابداری و مالی بساز",blueprintId:"accounting",locale:"fa-IR"}),entities=new Set(d.entities.map(x=>x.id));for(const id of["account","contact","invoice","expense","financialPayment","ledgerEntry"])assert.ok(entities.has(id));assert.equal(d.vertical,"accounting");});

test("website builder and app builder must bind to the same commerce core",()=>{assert.equal(validateCommerceBinding({websiteDomain:LOADDER_COMMERCE_CORE.contract,appDomain:LOADDER_COMMERCE_CORE.contract}).ready,true);const bad=validateCommerceBinding({websiteDomain:"website.shadow-store.v1",appDomain:LOADDER_COMMERCE_CORE.contract});assert.equal(bad.ready,false);assert.ok(bad.blockers.includes("website-commerce-core-binding-required"));assert.ok(LOADDER_COMMERCE_CORE.rules.includes("website-builder-must-not-create-a-shadow-order-database"));});
