import test from"node:test";import assert from"node:assert/strict";import{createPostgresRuntimeProvider}from"../app/business-builder/postgres-runtime-provider.mjs";import{createChainedSecretResolver,createEnvSecretBackend,createExternalSecretBackend,createProductionSecretResolver}from"../app/business-builder/secret-backends.mjs";import{createDistributedRateLimitStore}from"../app/business-builder/distributed-rate-limit-store.mjs";import{createProductionDeployAdapter,sha256Artifact}from"../app/business-builder/production-deploy-adapter.mjs";import{executeCanaryRelease}from"../app/business-builder/canary-release-controller.mjs";

test("postgres health recovers from transient connection failure",async()=>{let calls=0;const pool={async query(){calls++;if(calls===1){const e=new Error("restart");e.code="57P01";throw e;}return{rows:[{ok:1}]}}};const p=createPostgresRuntimeProvider({pool,retry:{attempts:2,baseDelayMs:0,maxDelayMs:0,shouldRetry:e=>e.code==="57P01"}});const h=await p.recover();assert.equal(h.ok,true);assert.equal(calls,2)});
test("secret chain supports development fallback but production is external-only",async()=>{const external=createExternalSecretBackend({kind:"vault",fetchSecret:async n=>n==="DATABASE_URL"?"postgres://external":null}),r=createChainedSecretResolver({required:["DATABASE_URL","API_KEY"],backends:[external,createEnvSecretBackend({API_KEY:"env-key"})]});assert.equal(await r.get("DATABASE_URL"),"postgres://external");assert.equal(await r.get("API_KEY"),"env-key");assert.deepEqual(await r.assertRequired(),{ok:true,count:2});const prod=createProductionSecretResolver({backend:external,required:["DATABASE_URL"]});assert.equal(await prod.get("DATABASE_URL"),"postgres://external");assert.equal((await prod.health()).ok,true);assert.throws(()=>createProductionSecretResolver({backend:createEnvSecretBackend({DATABASE_URL:"postgres://env"}),required:["DATABASE_URL"]}),/external secret backend/);const missing=createProductionSecretResolver({backend:external,required:["API_KEY"]});assert.equal((await missing.health()).ok,false);});
test("distributed rate limit store preserves shared atomic count",async()=>{const counts=new Map();const s=createDistributedRateLimitStore({increment:async key=>{const count=(counts.get(key)||0)+1;counts.set(key,count);return{count,resetAt:Date.now()+60000}}});assert.equal((await s.increment("u:w:write")).totalHits,1);assert.equal((await s.increment("u:w:write")).totalHits,2)});
test("deploy adapter rejects artifact tampering and checksum is canonical",async()=>{const artifact={appId:"a1",version:1,nested:{b:2,a:1}},same={nested:{a:1,b:2},version:1,appId:"a1"};assert.equal(sha256Artifact(artifact),sha256Artifact(same));const adapter=createProductionDeployAdapter({deploy:async()=>({id:"d1"}),health:async()=>({ok:true}),rollback:async()=>({ok:true})});await assert.rejects(()=>adapter.deploy({artifact,expectedChecksum:"bad"}),/checksum mismatch/);assert.equal((await adapter.deploy({artifact,expectedChecksum:sha256Artifact(artifact)})).id,"d1")});
test("canary release returns healthy only after health succeeds",async()=>{let health=0,rolled=false;const adapter=createProductionDeployAdapter({deploy:async()=>({id:"d1"}),health:async()=>({ok:++health>=2}),rollback:async()=>{rolled=true;return{ok:true}}});const r=await executeCanaryRelease({adapter,artifact:{x:1},healthAttempts:3});assert.equal(r.ok,true);assert.equal(health,2);assert.equal(rolled,false)});
test("failed canary automatically rolls back",async()=>{let rolled=false;const adapter=createProductionDeployAdapter({deploy:async()=>({id:"d2"}),health:async()=>({ok:false}),rollback:async(d,reason)=>{rolled=true;return{ok:true,deploymentId:d.id,reason}}});const r=await executeCanaryRelease({adapter,artifact:{x:2},healthAttempts:2});assert.equal(r.status,"rolled_back");assert.equal(rolled,true);assert.equal(r.rollback.deploymentId,"d2")});
test("thrown health checks also rollback instead of escaping release control",async()=>{let rolled=false,calls=0;const adapter=createProductionDeployAdapter({deploy:async()=>({id:"d3"}),health:async()=>{calls++;const e=new Error("health transport down");e.code="ECONNRESET";throw e;},rollback:async(d,reason)=>{rolled=true;return{ok:true,deploymentId:d.id,reason}}});const r=await executeCanaryRelease({adapter,artifact:{x:3},healthAttempts:2});assert.equal(r.status,"rolled_back");assert.equal(rolled,true);assert.equal(calls,2);assert.equal(r.rollback.reason.code,"CANARY_HEALTH_ERROR")});
