import test from"node:test";import assert from"node:assert/strict";import{createPostgresRuntimeProvider,createPostgresRuntimeFromFactory}from"../app/business-builder/postgres-runtime-provider.mjs";import{createEnvSecretResolver}from"../app/business-builder/secret-resolver.mjs";import{withLoadderRetry,defaultTransientRetry}from"../app/business-builder/retry-policy.mjs";import{evaluateProductionSmoke}from"../app/business-builder/production-smoke.mjs";import{LOADDER_BUILDER_RATE_LIMITS,createBusinessBuilderRateLimiter}from"../app/business-builder/business-builder-rate-limit.mjs";

test("postgres runtime provider health and factory are provider-neutral",async()=>{let ended=false,config=null;const pool={query:async text=>({rows:[{ok:text.includes("SELECT 1")?1:0}]}),end:async()=>{ended=true}};const provider=createPostgresRuntimeProvider({pool});assert.equal((await provider.health()).ok,true);const built=await createPostgresRuntimeFromFactory({connectionString:"postgres://example",poolFactory:async c=>(config=c,pool),max:7});assert.equal(config.max,7);assert.equal((await built.health()).ok,true);await built.dispose();assert.equal(ended,true)});

test("required secrets fail closed",async()=>{const ok=createEnvSecretResolver({env:{DATABASE_URL:"postgres://x"},required:["DATABASE_URL"]});assert.deepEqual(await ok.assertRequired(),{ok:true,count:1});const bad=createEnvSecretResolver({env:{},required:["DATABASE_URL"]});await assert.rejects(()=>bad.assertRequired(),/Required secret missing/)});

test("retry is bounded and only repeats transient failures",async()=>{let attempts=0;const value=await withLoadderRetry(async()=>{attempts++;if(attempts<3){const e=new Error("temporary");e.transient=true;throw e}return"ok"},{...defaultTransientRetry,baseDelayMs:0,maxDelayMs:0});assert.equal(value,"ok");assert.equal(attempts,3);attempts=0;await assert.rejects(()=>withLoadderRetry(async()=>{attempts++;throw new Error("permanent")},{...defaultTransientRetry,baseDelayMs:0}),/permanent/);assert.equal(attempts,1)});

test("production smoke fails closed and passes only when every gate is healthy",async()=>{const blocked=await evaluateProductionSmoke({databaseHealth:async()=>({ok:true,latencyMs:10}),secretHealth:async()=>({ok:true}),readiness:{ready:false,blockers:[{id:"approval"}]},backupHealth:async()=>({ok:true})});assert.equal(blocked.ok,false);assert.equal(blocked.status,"blocked");const healthy=await evaluateProductionSmoke({databaseHealth:async()=>({ok:true,latencyMs:10}),secretHealth:async()=>({ok:true}),readiness:{ready:true,blockers:[]},backupHealth:async()=>({ok:true})});assert.equal(healthy.ok,true)});

test("builder rate-limit policies are bounded and middleware can be created",()=>{assert.ok(LOADDER_BUILDER_RATE_LIMITS.operator.limit<LOADDER_BUILDER_RATE_LIMITS.write.limit);assert.ok(LOADDER_BUILDER_RATE_LIMITS.write.limit<LOADDER_BUILDER_RATE_LIMITS.read.limit);assert.equal(typeof createBusinessBuilderRateLimiter("operator"),"function")});
