import test from"node:test";import assert from"node:assert/strict";import{AgentCommerceSafetyError,authorizeAgentCommerceAction,createAgentCommerceCommand,getAgentCommerceActionCatalog}from"../app/commerce/v2/agent-commerce-safety.mjs";
const principal=(caps)=>({type:"AGENT",actorId:"agent-1",workspaceId:"w1",storeId:"s1",capabilities:caps});
const expectCode=(fn,code)=>assert.throws(fn,e=>e instanceof AgentCommerceSafetyError&&e.code===code);

test("catalog exposes only explicit agent-safe actions",()=>{const c=getAgentCommerceActionCatalog();assert.deepEqual(Object.keys(c).sort(),["apply_promotion","check_inventory","checkout","create_cart","discover_products","get_order","return_item","track_order"]);assert.equal(Object.isFrozen(c),true)});
test("read action requires explicit capability and exact tenant scope",()=>{const p=principal(["commerce:catalog:read"]);const d=authorizeAgentCommerceAction({action:"discover_products",input:{workspaceId:"w1",storeId:"s1"},principal:p});assert.equal(d.mode,"READ");expectCode(()=>authorizeAgentCommerceAction({action:"discover_products",input:{workspaceId:"w2"},principal:p}),"AGENT_COMMERCE_WORKSPACE_MISMATCH");expectCode(()=>authorizeAgentCommerceAction({action:"discover_products",input:{storeId:"s2"},principal:p}),"AGENT_COMMERCE_STORE_MISMATCH")});
test("unknown actions and missing capabilities fail closed",()=>{expectCode(()=>authorizeAgentCommerceAction({action:"delete_order",principal:principal(["*"])}),"AGENT_COMMERCE_UNKNOWN_ACTION");expectCode(()=>authorizeAgentCommerceAction({action:"get_order",principal:principal([])}),"AGENT_COMMERCE_CAPABILITY_REQUIRED")});
test("mutating cart actions require server idempotency boundary",()=>{const p=principal(["commerce:cart:write"]);expectCode(()=>authorizeAgentCommerceAction({action:"create_cart",input:{lines:[{quantity:1}]},principal:p}),"AGENT_COMMERCE_IDEMPOTENCY_REQUIRED");const d=authorizeAgentCommerceAction({action:"create_cart",input:{lines:[{quantity:1}]},principal:p,authorization:{idempotencyKey:"cart:req:123"}});assert.equal(d.idempotencyKey,"cart:req:123")});
test("checkout requires trusted human confirmation bound to action and scope",()=>{const p=principal(["commerce:checkout:write"]),auth={idempotencyKey:"checkout:req:1"};expectCode(()=>authorizeAgentCommerceAction({action:"checkout",input:{proposedTotalMinor:1000},principal:p,authorization:auth}),"AGENT_COMMERCE_HUMAN_CONFIRMATION_REQUIRED");const confirmation={verifiedBy:"HUMAN_CONTROL_PLANE",action:"checkout",workspaceId:"w1",storeId:"s1",expiresAt:new Date(Date.now()+60_000).toISOString()};const d=authorizeAgentCommerceAction({action:"checkout",input:{proposedTotalMinor:1000},principal:p,authorization:{...auth,confirmation}});assert.equal(d.mode,"HIGH_IMPACT")});
test("expired or cross-scope confirmation cannot authorize high impact action",()=>{const p=principal(["commerce:returns:write"]);const base={verifiedBy:"HUMAN_CONTROL_PLANE",action:"return_item",workspaceId:"w1",storeId:"s1"};expectCode(()=>authorizeAgentCommerceAction({action:"return_item",input:{quantity:1},principal:p,authorization:{idempotencyKey:"return:req:1",confirmation:{...base,expiresAt:new Date(Date.now()-1).toISOString()}}}),"AGENT_COMMERCE_CONFIRMATION_EXPIRED");expectCode(()=>authorizeAgentCommerceAction({action:"return_item",input:{quantity:1},principal:p,authorization:{idempotencyKey:"return:req:1",confirmation:{...base,storeId:"s2",expiresAt:new Date(Date.now()+60_000).toISOString()}}}),"AGENT_COMMERCE_HUMAN_CONFIRMATION_REQUIRED")});
test("quantity and money ceilings fail closed before execution",()=>{const cart=principal(["commerce:cart:write"]);expectCode(()=>authorizeAgentCommerceAction({action:"create_cart",input:{lines:[{quantity:6},{quantity:5}]},principal:cart,authorization:{idempotencyKey:"cart:req:limit"},limits:{maxQuantity:10}}),"AGENT_COMMERCE_QUANTITY_LIMIT_EXCEEDED");const checkout=principal(["commerce:checkout:write"]),confirmation={verifiedBy:"HUMAN_CONTROL_PLANE",action:"checkout",workspaceId:"w1",storeId:"s1",expiresAt:new Date(Date.now()+60_000).toISOString()};expectCode(()=>authorizeAgentCommerceAction({action:"checkout",input:{proposedTotalMinor:1001},principal:checkout,authorization:{idempotencyKey:"checkout:limit",confirmation},limits:{maxAmountMinor:1000}}),"AGENT_COMMERCE_AMOUNT_LIMIT_EXCEEDED")});
test("command envelope is frozen scoped and does not mutate input",()=>{const input={lines:[{quantity:2}],note:"x"};const d=authorizeAgentCommerceAction({action:"create_cart",input,principal:principal(["commerce:cart:write"]),authorization:{idempotencyKey:"cart:req:freeze"}});const cmd=createAgentCommerceCommand({decision:d,input,requestId:"req-1"});assert.equal(Object.isFrozen(cmd),true);assert.equal(Object.isFrozen(cmd.input),true);assert.notEqual(cmd.input,input);assert.deepEqual(input,{lines:[{quantity:2}],note:"x"});expectCode(()=>createAgentCommerceCommand({decision:d,input:{workspaceId:"evil"},requestId:"req-2"}),"AGENT_COMMERCE_WORKSPACE_MISMATCH")});
