import test from"node:test";import assert from"node:assert/strict";import{authorizeAgentCommerceAction,createAgentCommerceCommand,AgentCommerceSafetyError}from"../app/commerce/v2/agent-commerce-safety.mjs";import{createAgentCommerceExecutionAdapter,AgentCommerceExecutionError}from"../app/commerce/v2/agent-commerce-execution-adapter.mjs";
const principal=(caps)=>({type:"AGENT",actorId:"a1",workspaceId:"w1",storeId:"s1",capabilities:caps});

test("authorized read command executes with trusted scoped context",async()=>{let seen;const adapter=createAgentCommerceExecutionAdapter({handlers:{get_order:async x=>(seen=x,{id:x.input.orderId})}});const decision=authorizeAgentCommerceAction({action:"get_order",input:{orderId:"o1"},principal:principal(["commerce:orders:read"])}),command=createAgentCommerceCommand({decision,input:{orderId:"o1"},requestId:"r1"}),out=await adapter.execute({decision,command});assert.deepEqual(out.result,{id:"o1"});assert.equal(seen.context.workspaceId,"w1");assert.equal(seen.context.storeId,"s1");assert.equal(seen.context.actorId,"a1");assert.equal(Object.isFrozen(seen.context),true);assert.equal(Object.isFrozen(seen.input),true)});
test("forged decision cannot reach execution",async()=>{const adapter=createAgentCommerceExecutionAdapter({handlers:{get_order:async()=>({})}});await assert.rejects(()=>adapter.execute({decision:{allowed:true,action:"get_order",workspaceId:"w1",storeId:"s1",actorId:"a1"},command:{requestId:"r1",action:"get_order",workspaceId:"w1",storeId:"s1",actorId:"a1",input:{}}}),e=>e instanceof AgentCommerceSafetyError&&e.code==="AGENT_COMMERCE_AUTHORIZATION_REQUIRED")});
test("authorized decision cannot be paired with a different command scope or action",async()=>{const adapter=createAgentCommerceExecutionAdapter({handlers:{get_order:async()=>({})}}),decision=authorizeAgentCommerceAction({action:"get_order",input:{orderId:"o1"},principal:principal(["commerce:orders:read"])}),command=createAgentCommerceCommand({decision,input:{orderId:"o1"},requestId:"r1"});await assert.rejects(()=>adapter.execute({decision,command:{...command,storeId:"s2"}}),e=>e instanceof AgentCommerceExecutionError&&e.code==="AGENT_COMMERCE_COMMAND_AUTH_MISMATCH");await assert.rejects(()=>adapter.execute({decision,command:{...command,action:"checkout"}}),e=>e instanceof AgentCommerceExecutionError&&e.code==="AGENT_COMMERCE_COMMAND_AUTH_MISMATCH")});
test("missing handler fails closed",async()=>{const decision=authorizeAgentCommerceAction({action:"check_inventory",input:{variantId:"v1"},principal:principal(["commerce:inventory:read"])}),command=createAgentCommerceCommand({decision,input:{variantId:"v1"},requestId:"r2"});await assert.rejects(()=>createAgentCommerceExecutionAdapter().execute({decision,command}),e=>e instanceof AgentCommerceExecutionError&&e.code==="AGENT_COMMERCE_HANDLER_UNAVAILABLE")});
test("mutating handler receives exact idempotency authority from safety decision",async()=>{let key;const adapter=createAgentCommerceExecutionAdapter({handlers:{create_cart:async({context})=>(key=context.idempotencyKey,{cartId:"c1"})}}),decision=authorizeAgentCommerceAction({action:"create_cart",input:{lines:[{quantity:1}]},principal:principal(["commerce:cart:write"]),authorization:{idempotencyKey:"cart:req:123"}}),command=createAgentCommerceCommand({decision,input:{lines:[{quantity:1}]},requestId:"r3"});const out=await adapter.execute({decision,command});assert.equal(key,"cart:req:123");assert.equal(out.result.cartId,"c1")});
test("handler input is cloned and frozen",async()=>{const source={orderId:"o1",nested:{x:1}};let received;const adapter=createAgentCommerceExecutionAdapter({handlers:{get_order:async({input})=>(received=input,{ok:true})}}),decision=authorizeAgentCommerceAction({action:"get_order",input:source,principal:principal(["commerce:orders:read"])}),command=createAgentCommerceCommand({decision,input:source,requestId:"r4"});await adapter.execute({decision,command});assert.notEqual(received,source);assert.equal(Object.isFrozen(received),true);assert.equal(Object.isFrozen(received.nested),true);assert.deepEqual(source,{orderId:"o1",nested:{x:1}})});
