import test from "node:test";
import assert from "node:assert/strict";
import { copyFileSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import Database from "better-sqlite3";

import { migration049ContentAssets } from "../db/migrations/049_content_assets.mjs";
import { runMigrations } from "../db/migrate.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createContentAssetRepository } from "../app/repositories/content-asset-repository.mjs";
import { createContentAssetService } from "../app/services/content-asset-service.mjs";
import { createOperationMetrics } from "../app/observability/operation-metrics.mjs";
import { createTestOnlyInsecureMemoryContentAssetStore, createUnavailableContentAssetStore } from "../app/content-assets/content-asset-store.mjs";
import { calculateContentAssetQuotaUsage, contentAssetRetentionDecision, sanitizeOriginalFilename, validateDeclaredAsset } from "../app/content-assets/content-asset-policy.mjs";
import { CONTENT_ASSET_ERROR_CODES } from "../app/content-assets/content-asset-errors.mjs";

const AT = "2026-08-22T10:00:00.000Z", SHA = "a".repeat(64);
const IMAGE = { mediaType: "IMAGE", declaredMimeType: "image/png", declaredByteSize: 1024, declaredSha256: SHA, originalFilename: "بنر تابستان.png" };
const VIDEO = { mediaType: "VIDEO", declaredMimeType: "video/mp4", declaredByteSize: 4096, declaredSha256: "b".repeat(64), originalFilename: "ویدیو.mp4" };
const ACTORS = Object.freeze({ owner: { userId: "owner", role: "owner" }, admin: { userId: "admin", role: "admin" }, member: { userId: "member", role: "member" } });

function createFixture() {
  const db = new Database(":memory:"); db.pragma("foreign_keys=ON");
  db.exec(`CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);CREATE TABLE workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE users(id TEXT PRIMARY KEY,mobile TEXT NOT NULL,name TEXT NOT NULL,email TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);`);
  runMigrations(db, [migration049ContentAssets]);
  for (const workspace of ["wa", "wb"]) db.prepare("INSERT INTO workspaces VALUES(?,?,?,'active',?,?)").run(workspace, workspace, workspace, AT, AT);
  for (const [user, role] of Object.entries({ owner: "owner", admin: "admin", member: "member", outsider: "member" })) {
    db.prepare("INSERT INTO users VALUES(?,?,?,NULL,'active',?,?)").run(user, `09${user}`, user, AT, AT);
    const workspace = user === "outsider" ? "wb" : "wa";
    db.prepare("INSERT INTO workspace_memberships VALUES(?,?,?,?,'active',?,?)").run(`m-${user}`, workspace, user, role, AT, AT);
  }
  const repository = createContentAssetRepository(db), store = createTestOnlyInsecureMemoryContentAssetStore(), metrics = createOperationMetrics();
  let tick = Date.parse(AT), sequence = 0;
  const service = createContentAssetService({ repository, store, operationMetrics: metrics, now: () => new Date(tick += 1000), id: () => `asset-${++sequence}` });
  return { db, repository, store, metrics, service, close: () => db.close() };
}
const within = (workspace, operation) => runWithWorkspace(workspace, operation);
let keySequence = 0;
const create = (fixture, input = IMAGE, actor = ACTORS.owner, key = `key-${++keySequence}`) => within("wa", () => fixture.service.createFoundationIntent(input, actor, key));

test("Storage Interface + Content Assets Foundation v1", async (t) => {
  await t.test("migration 049 adds exactly one table, preserves existing schemas/rows, and is idempotent", () => {
    const dir = mkdtempSync(join(tmpdir(), "loadder-assets-migration-")), path = join(dir, "scope.sqlite"); copyFileSync(new URL("../db/loadder.sqlite", import.meta.url), path);
    const db = new Database(path); db.pragma("foreign_keys=ON"); db.exec("DROP TRIGGER IF EXISTS trg_content_generations_intent_guard;DROP TRIGGER IF EXISTS trg_content_items_intent_guard;DROP TRIGGER IF EXISTS trg_content_items_intent_immutable;ALTER TABLE content_generations DROP COLUMN intent_id;ALTER TABLE content_items DROP COLUMN intent_id;DROP TABLE IF EXISTS creative_intents;DROP TABLE IF EXISTS attribution_touches;DELETE FROM schema_migrations WHERE version=55;DROP TABLE IF EXISTS distribution_contexts;DELETE FROM schema_migrations WHERE version=54;DELETE FROM schema_migrations WHERE version=53;DELETE FROM schema_migrations WHERE version=52;DROP TABLE IF EXISTS creative_placements;DELETE FROM schema_migrations WHERE version=51;DELETE FROM schema_migrations WHERE version=50;DELETE FROM schema_migrations WHERE version=49;DROP TABLE IF EXISTS content_assets;");
    const before = db.prepare("SELECT name,sql FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();
    const counts = new Map(before.map(({ name }) => [name, db.prepare(`SELECT COUNT(*) count FROM "${name}"`).get().count]));
    runMigrations(db, [migration049ContentAssets]); runMigrations(db, [migration049ContentAssets]);
    assert.deepEqual(db.prepare("SELECT COUNT(*) count,MAX(version) max FROM schema_migrations WHERE version=49").get(), { count: 1, max: 49 });
    assert.deepEqual(db.prepare("SELECT name,sql FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name!='content_assets' ORDER BY name").all(), before);
    for (const [name, count] of counts) assert.equal(db.prepare(`SELECT COUNT(*) count FROM "${name}"`).get().count, name === "schema_migrations" ? count + 1 : count);
    assert.equal(db.pragma("integrity_check", { simple: true }), "ok"); assert.deepEqual(db.pragma("foreign_key_check"), []); db.close(); rmSync(dir, { recursive: true, force: true });
  });
  await t.test("schema has exactly four explicit indexes and four triggers", () => { const f = createFixture(); const objects = f.db.prepare("SELECT type,name FROM sqlite_schema WHERE tbl_name='content_assets' AND type IN('index','trigger') AND sql IS NOT NULL ORDER BY type,name").all(); assert.equal(objects.filter((x) => x.type === "index").length, 4); assert.equal(objects.filter((x) => x.type === "trigger").length, 4); f.close(); });
  await t.test("IMAGE and VIDEO identities are accepted while TEXT is rejected", () => { assert.equal(validateDeclaredAsset(IMAGE).mediaType, "IMAGE"); assert.equal(validateDeclaredAsset(VIDEO).mediaType, "VIDEO"); assert.throws(() => validateDeclaredAsset({ ...IMAGE, mediaType: "TEXT", declaredMimeType: "text/plain" }), (e) => e.code === "CONTENT_ASSET_MEDIA_UNSUPPORTED"); });
  await t.test("MIME allowlist and declared size policies are exact", () => { for (const mime of ["image/jpeg", "image/png", "image/webp"]) assert.equal(validateDeclaredAsset({ ...IMAGE, declaredMimeType: mime }).declaredMimeType, mime); assert.throws(() => validateDeclaredAsset({ ...IMAGE, declaredMimeType: "image/svg+xml" })); assert.throws(() => validateDeclaredAsset({ ...IMAGE, declaredByteSize: 20 * 1024 * 1024 + 1 }), (e) => e.code === "CONTENT_ASSET_TOO_LARGE"); assert.throws(() => validateDeclaredAsset({ ...VIDEO, declaredByteSize: 200 * 1024 * 1024 + 1 }), (e) => e.code === "CONTENT_ASSET_TOO_LARGE"); });
  await t.test("hash format is strict lowercase SHA-256", () => { for (const value of ["A".repeat(64), "a".repeat(63), `g${"a".repeat(63)}`]) assert.throws(() => validateDeclaredAsset({ ...IMAGE, declaredSha256: value })); });
  await t.test("foundation error taxonomy is exact and bounded", () => { assert.deepEqual(CONTENT_ASSET_ERROR_CODES, ["CONTENT_ASSET_STORAGE_UNAVAILABLE", "CONTENT_ASSET_INVALID", "CONTENT_ASSET_TOO_LARGE", "CONTENT_ASSET_MEDIA_UNSUPPORTED", "CONTENT_ASSET_NOT_FOUND", "CONTENT_ASSET_NOT_READY", "CONTENT_ASSET_QUOTA_EXCEEDED", "CONTENT_ASSET_IDEMPOTENCY_CONFLICT", "CONTENT_ASSET_STATE_CONFLICT", "CONTENT_ASSET_INTEGRITY_FAILED", "CONTENT_ASSET_MEDIA_INVALID", "CONTENT_ASSET_BUSY", "CONTENT_ASSET_IN_USE"]); });
  await t.test("filename sanitizer preserves Persian and removes paths, controls, bidi abuse, trailing danger, and overlength", () => { assert.equal(sanitizeOriginalFilename("بنر تابستان.png"), "بنر تابستان.png"); assert.equal(sanitizeOriginalFilename("../../folder\\تصویر.png"), "تصویر.png"); assert.equal(sanitizeOriginalFilename("\u0000نام\u202e.png... "), "نام.png"); assert.ok([...sanitizeOriginalFilename(`${"الف".repeat(300)}.png`)].length <= 180); });
  await t.test("owner admin and member can create internal test identities", () => { const f = createFixture(); for (const [role, actor] of Object.entries(ACTORS)) assert.equal(create(f, role === "admin" ? VIDEO : IMAGE, actor, role).asset.status, "UPLOADING"); f.close(); });
  await t.test("foreign workspace IDs are hidden and DB ownership guards reject invalid creators", () => { const f = createFixture(), asset = create(f).asset; assert.throws(() => within("wb", () => f.service.get(asset.id)), (e) => e.code === "CONTENT_ASSET_NOT_FOUND"); assert.throws(() => within("wa", () => f.repository.create({ id: "forged", createdByUserId: "outsider", ...IMAGE, originalFilename: null, storageProvider: "TEST_MEMORY", storageObjectKey: "workspaces/wa/content-assets/forged/original", operationKind: "content_asset.intent", idempotencyKey: "forged", requestHash: SHA, uploadExpiresAt: "2026-08-22T11:00:00.000Z", createdAt: AT }))); f.close(); });
  await t.test("intent idempotency reuses exact request and rejects changed request", () => { const f = createFixture(), first = create(f, IMAGE, ACTORS.owner, "same"), replay = create(f, IMAGE, ACTORS.owner, "same"); assert.equal(replay.asset.id, first.asset.id); assert.equal(replay.reusedResult, true); assert.throws(() => create(f, { ...IMAGE, declaredByteSize: 2048 }, ACTORS.owner, "same"), (e) => e.code === "CONTENT_ASSET_IDEMPOTENCY_CONFLICT"); f.close(); });
  await t.test("storage key is server-derived and immutable", () => { const f = createFixture(), asset = create(f).asset, stored = within("wa", () => f.repository.findById(asset.id)); assert.equal(stored.storageObjectKey, `workspaces/wa/content-assets/${asset.id}/original`); assert.equal(stored.storageObjectKey.includes(IMAGE.originalFilename), false); assert.throws(() => f.db.prepare("UPDATE content_assets SET storage_object_key='other',updated_at=? WHERE id=?").run("2026-08-22T11:00:00.000Z", asset.id)); f.close(); });
  await t.test("declared identity is immutable", () => { const f = createFixture(), asset = create(f).asset; for (const statement of ["media_type='VIDEO'", "declared_byte_size=2", `declared_sha256='${"c".repeat(64)}'`, "created_by_user_id='admin'"]) assert.throws(() => f.db.prepare(`UPDATE content_assets SET ${statement},updated_at='2026-08-22T11:00:00.000Z' WHERE id=?`).run(asset.id)); f.close(); });
  await t.test("UPLOADING VERIFYING READY image lifecycle is legal", () => { const f = createFixture(), asset = create(f).asset; assert.equal(within("wa", () => f.service.claimVerification(asset.id)).status, "VERIFYING"); const ready = within("wa", () => f.service.recordReady(asset.id, { mimeType: "image/png", byteSize: 1024, contentSha256: SHA, width: 800, height: 600, durationMs: null })); assert.equal(ready.status, "READY"); f.close(); });
  await t.test("VIDEO READY requires duration and IMAGE READY forbids it", () => { const f = createFixture(), image = create(f).asset, video = create(f, VIDEO, ACTORS.owner, "video").asset; within("wa", () => f.service.claimVerification(image.id)); assert.throws(() => within("wa", () => f.service.recordReady(image.id, { mimeType: "image/png", byteSize: 1, contentSha256: SHA, width: 1, height: 1, durationMs: 1 }))); within("wa", () => f.service.claimVerification(video.id)); assert.throws(() => within("wa", () => f.service.recordReady(video.id, { mimeType: "video/mp4", byteSize: 1, contentSha256: "b".repeat(64), width: 1, height: 1, durationMs: null }))); f.close(); });
  await t.test("VERIFYING can become REJECTED", () => { const f = createFixture(), asset = create(f).asset; within("wa", () => f.service.claimVerification(asset.id)); assert.equal(within("wa", () => f.service.recordRejected(asset.id, "MEDIA_INVALID")).status, "REJECTED"); f.close(); });
  await t.test("VERIFYING can become FAILED and FAILED can retry VERIFYING", () => { const f = createFixture(), asset = create(f).asset; within("wa", () => f.service.claimVerification(asset.id)); assert.equal(within("wa", () => f.service.recordFailed(asset.id, "STORE_UNAVAILABLE")).status, "FAILED"); assert.equal(within("wa", () => f.service.claimVerification(asset.id)).status, "VERIFYING"); f.close(); });
  await t.test("READY DELETING DELETED lifecycle is legal and DELETED is terminal", () => { const f = createFixture(), asset = create(f).asset; within("wa", () => f.service.claimVerification(asset.id)); within("wa", () => f.service.recordReady(asset.id, { mimeType: "image/png", byteSize: 1024, contentSha256: SHA, width: 800, height: 600, durationMs: null })); assert.equal(within("wa", () => f.service.requestDeletion(asset.id)).status, "DELETING"); assert.equal(within("wa", () => f.service.recordDeleted(asset.id)).status, "DELETED"); assert.throws(() => within("wa", () => f.service.claimVerification(asset.id)), (e) => e.code === "CONTENT_ASSET_STATE_CONFLICT"); f.close(); });
  await t.test("illegal backward transitions and physical DELETE are rejected", () => { const f = createFixture(), asset = create(f).asset; within("wa", () => f.service.claimVerification(asset.id)); assert.throws(() => f.db.prepare("UPDATE content_assets SET status='UPLOADING',updated_at='2026-08-22T12:00:00.000Z' WHERE id=?").run(asset.id)); assert.throws(() => f.db.prepare("DELETE FROM content_assets WHERE id=?").run(asset.id)); f.close(); });
  await t.test("quota counts all non-deleted reserved or verified bytes", () => { assert.deepEqual(calculateContentAssetQuotaUsage([{ status: "UPLOADING", declaredByteSize: 10 }, { status: "READY", declaredByteSize: 10, byteSize: 12 }, { status: "DELETED", declaredByteSize: 99 }]), { bytes: 22, count: 2 }); });
  await t.test("retention policy is deterministic", () => { assert.equal(contentAssetRetentionDecision({ status: "UPLOADING", createdAt: AT, updatedAt: AT }, new Date("2026-08-23T10:00:00.000Z")).eligible, true); assert.equal(contentAssetRetentionDecision({ status: "FAILED", createdAt: AT, updatedAt: AT }, new Date("2026-08-24T10:00:00.000Z")).eligible, false); assert.deepEqual(contentAssetRetentionDecision({ status: "DELETING", createdAt: AT }), { eligible: true, action: "RETRY_DELETE" }); });
  await t.test("test store authorization stat checksum read and delete are deterministic", () => { const store = createTestOnlyInsecureMemoryContentAssetStore(), locator = { storageProvider: "TEST_MEMORY", storageObjectKey: "workspaces/wa/content-assets/a/original" }; assert.equal(store.createUploadAuthorization({ locator }).authorization, "test-memory-upload-1"); store.testOnlyInjectObject(locator, { byteSize: 3, contentSha256: SHA }); assert.deepEqual(store.statObject(locator), { byteSize: 3, contentSha256: SHA }); assert.equal(store.verifyChecksum(locator, SHA), true); assert.equal(store.createReadAuthorization(locator).authorization, "test-memory-read-2"); assert.equal(store.deleteObject(locator), true); assert.throws(() => store.statObject(locator), (e) => e.code === "CONTENT_ASSET_NOT_FOUND"); });
  await t.test("test store supports bounded failure injection without network or disk", () => { const store = createTestOnlyInsecureMemoryContentAssetStore(), locator = { storageProvider: "TEST_MEMORY", storageObjectKey: "workspaces/wa/content-assets/a/original" }; store.testOnlyInjectFailure("statObject"); assert.throws(() => store.statObject(locator), (e) => e.code === "CONTENT_ASSET_STORAGE_UNAVAILABLE"); store.testOnlyClearFailure("statObject"); assert.throws(() => store.statObject(locator), (e) => e.code === "CONTENT_ASSET_NOT_FOUND"); });
  await t.test("production store and production service fail closed", () => { const f = createFixture(), store = createUnavailableContentAssetStore(), service = createContentAssetService({ repository: f.repository, store, operationMetrics: f.metrics }); assert.equal(store.configured, false); assert.equal(store.uploadEnabled, false); assert.throws(() => within("wa", () => service.createFoundationIntent(IMAGE, ACTORS.owner, "production")), (e) => e.code === "CONTENT_ASSET_STORAGE_UNAVAILABLE"); assert.equal(f.db.prepare("SELECT COUNT(*) count FROM content_assets").get().count, 0); f.close(); });
  await t.test("metrics are bounded and contain no filename hash or object key", () => { const f = createFixture(); create(f); const metrics = JSON.stringify(f.metrics.recent()); assert.match(metrics, /asset\.intent\.create/); for (const secret of [IMAGE.originalFilename, IMAGE.declaredSha256, "content-assets/asset-"]) assert.equal(metrics.includes(secret), false); f.close(); });
  await t.test("representative tenant history and lifecycle queries use tenant-leading indexes without OFFSET or object calls", () => { const f = createFixture(); within("wa", () => { for (let index = 0; index < 200; index += 1) f.repository.create({ id: `scale-${index}`, createdByUserId: "owner", ...IMAGE, originalFilename: null, storageProvider: "TEST_MEMORY", storageObjectKey: `workspaces/wa/content-assets/scale-${index}/original`, operationKind: "content_asset.intent", idempotencyKey: `scale-${index}`, requestHash: index.toString(16).padStart(64, "0"), uploadExpiresAt: "2026-08-23T10:00:00.000Z", createdAt: new Date(Date.parse(AT) + index * 1000).toISOString() }); }); const history = f.db.prepare("EXPLAIN QUERY PLAN SELECT * FROM content_assets WHERE workspace_id=? ORDER BY created_at DESC,id DESC LIMIT ?").all("wa", 20); const lifecycle = f.db.prepare("EXPLAIN QUERY PLAN SELECT * FROM content_assets WHERE workspace_id=? AND status=? AND created_at<=? ORDER BY created_at,id LIMIT ?").all("wa", "UPLOADING", "2026-08-23T10:00:00.000Z", 20); assert.match(JSON.stringify(history), /idx_content_assets_workspace_history/); assert.match(JSON.stringify(lifecycle), /idx_content_assets_workspace_lifecycle/); const source = readFileSync(new URL("../app/repositories/content-asset-repository.mjs", import.meta.url), "utf8"); assert.doesNotMatch(source, /\bOFFSET\b|store\.|statObject|createReadAuthorization/); f.close(); });
  await t.test("health is fail-closed and no customer asset route or frontend UI exists", () => { const index = readFileSync(new URL("../index.mjs", import.meta.url), "utf8"), app = readFileSync(new URL("../../src/App.tsx", import.meta.url), "utf8"); assert.match(index, /assetStorageConfigured: contentAssetStore\.configured/); assert.match(index, /assetUploadEnabled: contentAssetStore\.uploadEnabled/); for (const route of ["upload-intents", "content/assets/:id/complete", "content/assets/:id/access", "content/items/from-asset"]) assert.equal(index.includes(route), false); for (const label of ["Upload image", "Upload video", "بارگذاری تصویر", "بارگذاری ویدیو"]) assert.equal(app.includes(label), false); });
  await t.test("asset foundation has no provider media parser execution worker or SDK dependency", () => { const paths = ["../app/content-assets/content-asset-store.mjs", "../app/content-assets/content-asset-policy.mjs", "../app/repositories/content-asset-repository.mjs", "../app/services/content-asset-service.mjs"], source = paths.map((path) => readFileSync(new URL(path, import.meta.url), "utf8")).join("\n").toLowerCase(); for (const forbidden of ["openai", "cloudflare", "provider-binding", "action-proposal", "execution-request", "dispatch-job", "messaging", "automation", "worker_threads", "setinterval", "@aws-sdk", "supabase", "ffmpeg", "ffprobe", "sharp", "fetch("]) assert.equal(source.includes(forbidden), false); });
});
