import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import Database from "better-sqlite3";
import { runMigrations } from "../db/migrate.mjs";
import { migration045ContentGenerations } from "../db/migrations/045_content_generations.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { CONTENT_MEDIA_TYPES, assertContentMediaEnabled } from "../app/content-generation/media-types.mjs";
import { contentChannelRegistry, createContentChannelRegistry } from "../app/content-generation/channel-registry.mjs";
import { contentPlacementRegistry, createContentPlacementRegistry } from "../app/content-generation/placement-registry.mjs";
import { generationContractRegistry, createGenerationContractRegistry } from "../app/content-generation/contract-registry.mjs";
import { validateContentBrief } from "../app/content-generation/content-brief.mjs";
import { projectGenerationContext } from "../app/content-generation/generation-context.mjs";
import { textProviderBindingRegistry } from "../app/content-generation/provider-binding-registry.mjs";
import { TextProviderError } from "../app/content-generation/openai-text-provider.mjs";
import { createContentGenerationRateLimiter } from "../app/content-generation/content-generation-rate-limiter.mjs";
import { createContentGenerationRepository } from "../app/repositories/content-generation-repository.mjs";
import { createContentGenerationService, ContentGenerationError } from "../app/services/content-generation-service.mjs";
import { createOperationMetrics } from "../app/observability/operation-metrics.mjs";
import { classifyApiRequest } from "../app/middleware/product-gating.mjs";

const WORKSPACE = "creative-workspace";
const USER = "creative-user";
const CONTEXT = "creative-context";
const BRIEF = Object.freeze({ goal: "افزایش تعامل", offering: "سرویس Loadder Pro", audienceRefinement: "مدیران SaaS", keyMessage: "رشد پایدار با BrandX", cta: "همین حالا شروع کنید", language: "fa-IR", toneOverride: "حرفه‌ای و صمیمی", constraints: ["وعده قطعی نده"], referenceText: "BrandX.example/path" });
const REQUEST = Object.freeze({ contractId: "social_post", contractVersion: 1, placementId: "instagram.feed.text", placementVersion: 1, brief: BRIEF, variantCount: 1 });
const SNAPSHOT = Object.freeze({ identity: { businessName: "BrandX", industry: "نرم‌افزار", description: "ابزار رشد کسب‌وکار" }, strategy: { differentiators: ["یکپارچگی"] }, audiences: { targetAudiences: ["مدیران کسب‌وکار"] }, offerings: ["Loadder Pro"], brand: { personality: ["مطمئن"], tone: "حرفه‌ای", prohibitedPatterns: ["تضمین صددرصد"], keyPhrases: ["رشد پایدار"] } });

const OUTPUTS = Object.freeze({
  social_post: { variants: [{ hook: "رشد پایدار از یک تصمیم روشن شروع می‌شود.", body: "با BrandX مسیر بازاریابی را منسجم کنید.", cta: "همین حالا شروع کنید", hashtags: ["#رشد_پایدار"] }] },
  ad_copy: { variants: [{ headlines: ["رشد با BrandX"], descriptions: ["بازاریابی منسجم برای کسب‌وکار"], ctaLabel: "شروع کنید" }] },
  marketing_email: { variants: [{ subject: "رشد پایدار با BrandX", previewText: "یک مسیر روشن برای رشد", greeting: "سلام", bodySections: ["با برنامه‌ای منسجم شروع کنید."], cta: "شروع کنید", signoff: "تیم BrandX" }] },
  blog_outline: { variants: [{ title: "راهنمای رشد پایدار", seoTitle: "رشد پایدار کسب‌وکار", metaDescription: "راهنمای عملی رشد پایدار برای کسب‌وکارها", primaryKeyword: "رشد پایدار", slug: "roshd-paydar", sections: [{ heading: "شروع", keyPoints: ["هدف را مشخص کنید"] }] }] },
  landing_page_copy: { variants: [{ hero: { headline: "رشد پایدار", subheadline: "بازاریابی منسجم با BrandX", cta: "شروع کنید" }, benefits: ["دید بهتر"], sections: [{ heading: "چرا BrandX؟", body: "برای تصمیم‌های روشن‌تر." }], proofPoints: ["شفافیت"], faq: [{ question: "چطور شروع کنیم؟", answer: "راه‌اندازی را کامل کنید." }], finalCta: "همین حالا شروع کنید" }] },
});

function database() {
  const db = new Database(":memory:"); db.pragma("foreign_keys=ON");
  db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT NOT NULL); CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT NOT NULL); CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,status TEXT NOT NULL); CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL); CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL);`);
  db.prepare("INSERT INTO users VALUES(?,?)").run(USER, "active"); db.prepare("INSERT INTO workspaces VALUES(?,?)").run(WORKSPACE, "active"); db.prepare("INSERT INTO workspace_memberships VALUES(?,?,?,?)").run("membership", WORKSPACE, USER, "active");
  db.prepare("INSERT INTO business_context_versions VALUES(?,?)").run(CONTEXT, WORKSPACE); runMigrations(db, [migration045ContentGenerations]); return db;
}

function fixture({ state = "READY", provider = null, limiter = null, db = database() } = {}) {
  let calls = 0;
  const selectedProvider = provider || { async generateRegisteredContract({ contract }) { calls += 1; return { output: OUTPUTS[contract.contractId], usage: { inputTokens: 120, outputTokens: 80 } }; } };
  const metrics = createOperationMetrics();
  const service = createContentGenerationService({ repository: createContentGenerationRepository(db), contractRegistry: generationContractRegistry, placementRegistry: contentPlacementRegistry, providerBindingRegistry: textProviderBindingRegistry, contextGateway: { consume: () => state === "READY" ? { state, contextVersionId: CONTEXT, context: SNAPSHOT } : { state, contextVersionId: state === "MISSING_CONTEXT" ? null : CONTEXT } }, provider: selectedProvider, rateLimiter: limiter || createContentGenerationRateLimiter(), operationMetrics: metrics, now: () => new Date("2026-08-22T12:00:00.000Z") });
  return { db, service, metrics, calls: () => calls };
}
const within = (callback) => runWithWorkspace(WORKSPACE, callback);
const rejectsCode = (promise, code) => assert.rejects(promise, (error) => error instanceof ContentGenerationError && error.code === code);

test("Creative Generation Core v1 governed TEXT generation", async (t) => {
  await t.test("media model is exact and IMAGE/VIDEO are disabled", () => { assert.deepEqual(CONTENT_MEDIA_TYPES, ["TEXT", "IMAGE", "VIDEO"]); for (const media of ["IMAGE", "VIDEO"]) assert.throws(() => assertContentMediaEnabled(media), (e) => e.code === "CONTENT_MEDIA_DISABLED"); });
  await t.test("channel registry is strict, bounded, and duplicate-safe", () => { assert.deepEqual(contentChannelRegistry.list().map((x) => x.channel), ["instagram", "google_ads", "email", "blog", "website"]); assert.equal(contentChannelRegistry.get("arbitrary"), null); assert.throws(() => createContentChannelRegistry(["blog", "blog"])); });
  await t.test("placement registry contains exactly five production TEXT placements", () => { assert.equal(contentPlacementRegistry.list().length, 5); assert.ok(contentPlacementRegistry.list().every((x) => x.mediaType === "TEXT" && x.productionEnabled)); assert.throws(() => createContentPlacementRegistry([contentPlacementRegistry.list()[0], contentPlacementRegistry.list()[0]])); });
  await t.test("contract registry contains exactly five immutable versioned contracts", () => { assert.deepEqual(generationContractRegistry.list().map((x) => `${x.contractId}@${x.contractVersion}`), ["social_post@1", "ad_copy@1", "marketing_email@1", "blog_outline@1", "landing_page_copy@1"]); assert.throws(() => createGenerationContractRegistry([generationContractRegistry.list()[0], generationContractRegistry.list()[0]])); });
  await t.test("brief accepts bounded Persian and mixed-script values without destructive normalization", () => { const brief = validateContentBrief(BRIEF); assert.equal(brief.keyMessage, BRIEF.keyMessage); assert.equal(brief.referenceText, "BrandX.example/path"); assert.equal(brief.constraints[0], "وعده قطعی نده"); });
  await t.test("brief rejects missing, oversized, unknown, provider, model, and ownership fields", () => { for (const mutation of [{ ...BRIEF, goal: "" }, { ...BRIEF, goal: "x".repeat(301) }, { ...BRIEF, constraints: Array(11).fill("x") }, { ...BRIEF, provider: "openai" }, { ...BRIEF, model: "x" }, { ...BRIEF, workspaceId: WORKSPACE }]) assert.throws(() => validateContentBrief(mutation)); });
  await t.test("generation projection is bounded and carries brand safety rules", () => { const projected = projectGenerationContext({ contextVersionId: CONTEXT, context: SNAPSHOT }, BRIEF); assert.equal(projected.contextVersionId, CONTEXT); assert.deepEqual(projected.brand.prohibitedClaims, ["تضمین صددرصد"]); assert.deepEqual(projected.brand.requiredPhrases, ["رشد پایدار"]); assert.equal(projected.audience.refinement, "مدیران SaaS"); assert.equal(Object.hasOwn(projected, "visual"), false); });
  await t.test("all five output schemas accept their normalized fixtures", () => { for (const contract of generationContractRegistry.list()) assert.equal(contract.validateOutput(OUTPUTS[contract.contractId], 1).length, 1); });
  await t.test("output validators reject unknown fields and contract bounds", () => { const social = generationContractRegistry.get("social_post", 1); assert.throws(() => social.validateOutput({ variants: [{ ...OUTPUTS.social_post.variants[0], raw: "forbidden" }] }, 1)); assert.throws(() => social.validateOutput({ variants: [{ ...OUTPUTS.social_post.variants[0], hashtags: Array(16).fill("#x") }] }, 1)); const ad = generationContractRegistry.get("ad_copy", 1); assert.throws(() => ad.validateOutput({ variants: [{ ...OUTPUTS.ad_copy.variants[0], headlines: ["x".repeat(31)] }] }, 1)); });
  await t.test("successful generation persists only normalized output and usage", async () => { const f = fixture(); const result = await within(() => f.service.generate(REQUEST, { userId: USER }, "success-1")); assert.equal(result.generation.status, "SUCCEEDED"); assert.equal(result.generation.inputTokens, 120); assert.equal(f.db.prepare("SELECT count(*) count FROM content_generations").get().count, 1); const row = f.db.prepare("SELECT * FROM content_generations").get(); assert.equal(row.normalized_result_json.includes("raw"), false); assert.equal(Object.hasOwn(row, "prompt"), false); });
  await t.test("exact replay reuses result without a provider call", async () => { const f = fixture(); await within(() => f.service.generate(REQUEST, { userId: USER }, "replay")); const again = await within(() => f.service.generate(REQUEST, { userId: USER }, "replay")); assert.equal(again.reusedResult, true); assert.equal(f.calls(), 1); });
  await t.test("changed request with same key conflicts and new key intentionally regenerates", async () => { const f = fixture(); await within(() => f.service.generate(REQUEST, { userId: USER }, "key-a")); await within(() => rejectsCode(f.service.generate({ ...REQUEST, brief: { ...BRIEF, keyMessage: "پیام دیگر" } }, { userId: USER }, "key-a"), "CONTENT_IDEMPOTENCY_CONFLICT")); await within(() => f.service.generate(REQUEST, { userId: USER }, "key-b")); assert.equal(f.calls(), 2); });
  await t.test("unknown contract, disabled media intent, missing placement, and mismatch are explicit", async () => { for (const [input, code] of [[{ ...REQUEST, contractId: "unknown" }, "CONTENT_CONTRACT_NOT_FOUND"], [{ ...REQUEST, contractId: "social_image" }, "CONTENT_MEDIA_DISABLED"], [{ ...REQUEST, placementId: "unknown.text" }, "CONTENT_PLACEMENT_NOT_SUPPORTED"], [{ ...REQUEST, placementId: "email.marketing.text" }, "CONTENT_PLACEMENT_NOT_SUPPORTED"]]) { const f = fixture(); await within(() => rejectsCode(f.service.generate(input, { userId: USER }, crypto.randomUUID()), code)); } });
  await t.test("top-level provider, model, context, user, workspace, and parameter injection is rejected before persistence", async () => { for (const field of ["provider", "model", "contextId", "userId", "workspaceId", "temperature", "maxTokens"]) { const f = fixture(); await within(() => rejectsCode(f.service.generate({ ...REQUEST, [field]: "x" }, { userId: USER }, field), "CONTENT_INPUT_INVALID")); assert.equal(f.db.prepare("SELECT count(*) count FROM content_generations").get().count, 0); } });
  await t.test("missing, stale, and unsupported Context fail without persistence", async () => { for (const [state, code] of [["MISSING_CONTEXT", "CONTENT_CONTEXT_MISSING"], ["STALE_CONTEXT", "CONTENT_CONTEXT_STALE"], ["UNSUPPORTED_SCHEMA", "CONTENT_CONTEXT_UNSUPPORTED"]]) { const f = fixture({ state }); await within(() => rejectsCode(f.service.generate(REQUEST, { userId: USER }, state), code)); assert.equal(f.db.prepare("SELECT count(*) count FROM content_generations").get().count, 0); } });
  await t.test("provider unavailable and timeout become bounded failures and persist attempted rows", async () => { for (const code of ["CONTENT_PROVIDER_UNAVAILABLE", "CONTENT_PROVIDER_TIMEOUT"]) { const f = fixture({ provider: { async generateRegisteredContract() { throw new TextProviderError(code); } } }); await within(() => rejectsCode(f.service.generate(REQUEST, { userId: USER }, code), code)); const row = f.db.prepare("SELECT status,error_code,normalized_result_json FROM content_generations").get(); assert.deepEqual(row, { status: "FAILED", error_code: code, normalized_result_json: null }); } });
  await t.test("malformed provider output fails once without repair and persists no raw data", async () => { let calls = 0; const f = fixture({ provider: { async generateRegisteredContract() { calls += 1; return { output: { raw: "bad" }, usage: { inputTokens: 5, outputTokens: 2 } }; } } }); await within(() => rejectsCode(f.service.generate(REQUEST, { userId: USER }, "invalid-output"), "CONTENT_OUTPUT_INVALID")); assert.equal(calls, 1); const row = f.db.prepare("SELECT * FROM content_generations").get(); assert.equal(row.normalized_result_json, null); assert.equal(row.error_code, "CONTENT_OUTPUT_INVALID"); });
  await t.test("user rate limit applies after one new request but replay is free", async () => { const f = fixture({ limiter: createContentGenerationRateLimiter({ userLimit: 1, workspaceLimit: 20 }) }); await within(() => f.service.generate(REQUEST, { userId: USER }, "rate-1")); const replay = await within(() => f.service.generate(REQUEST, { userId: USER }, "rate-1")); assert.equal(replay.reusedResult, true); await within(() => rejectsCode(f.service.generate(REQUEST, { userId: USER }, "rate-2"), "CONTENT_RATE_LIMITED")); });
  await t.test("workspace rate limit is independent from user limit", async () => { const f = fixture({ limiter: createContentGenerationRateLimiter({ userLimit: 20, workspaceLimit: 1 }) }); await within(() => f.service.generate(REQUEST, { userId: USER }, "workspace-rate-1")); await within(() => rejectsCode(f.service.generate(REQUEST, { userId: USER }, "workspace-rate-2"), "CONTENT_RATE_LIMITED")); });
  await t.test("workspace concurrency is capped at two", async () => { let releases = []; const provider = { generateRegisteredContract: () => new Promise((resolve) => releases.push(() => resolve({ output: OUTPUTS.social_post, usage: { inputTokens: 1, outputTokens: 1 } }))) }; const f = fixture({ provider, limiter: createContentGenerationRateLimiter({ userLimit: 20, workspaceLimit: 20, workspaceConcurrency: 2 }) }); const first = within(() => f.service.generate(REQUEST, { userId: USER }, "concurrent-1")); const second = within(() => f.service.generate(REQUEST, { userId: USER }, "concurrent-2")); await new Promise((resolve) => setImmediate(resolve)); await within(() => rejectsCode(f.service.generate(REQUEST, { userId: USER }, "concurrent-3"), "CONTENT_RATE_LIMITED")); releases.forEach((release) => release()); await Promise.all([first, second]); });
  await t.test("history is tenant-scoped, bounded, and cursor-paginated", async () => { const f = fixture(); for (let index = 0; index < 3; index += 1) await within(() => f.service.generate(REQUEST, { userId: USER }, `history-${index}`)); const first = within(() => f.service.list({ limit: "2" })); assert.equal(first.items.length, 2); assert.ok(first.nextCursor); const second = within(() => f.service.list({ limit: "2", cursor: first.nextCursor })); assert.equal(second.items.length, 1); assert.equal(new Set([...first.items, ...second.items].map((x) => x.generationId)).size, 3); });
  await t.test("database rejects cross-workspace context, update, and delete", async () => { const f = fixture(); await within(() => f.service.generate(REQUEST, { userId: USER }, "db-guard")); assert.throws(() => f.db.prepare("UPDATE content_generations SET status='FAILED'").run()); assert.throws(() => f.db.prepare("DELETE FROM content_generations").run()); });
  await t.test("migration 045 is idempotent and adds exactly one table without changing prior schema", () => { const db = new Database(":memory:"); db.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL); CREATE TABLE prior_table(id TEXT PRIMARY KEY,value TEXT); INSERT INTO schema_migrations VALUES(44,'prior','2026-08-22T00:00:00.000Z'); INSERT INTO prior_table VALUES('a','kept');"); const before = db.prepare("SELECT sql FROM sqlite_master WHERE name='prior_table'").get().sql; runMigrations(db, [migration045ContentGenerations]); runMigrations(db, [migration045ContentGenerations]); assert.deepEqual(db.prepare("SELECT count(*) count,max(version) max FROM schema_migrations").get(), { count: 2, max: 45 }); assert.equal(db.prepare("SELECT sql FROM sqlite_master WHERE name='prior_table'").get().sql, before); assert.equal(db.prepare("SELECT value FROM prior_table").get().value, "kept"); assert.equal(db.prepare("SELECT count(*) count FROM content_generations").get().count, 0); db.close(); });
  await t.test("metrics are bounded and content-free", async () => { const f = fixture(); await within(() => f.service.generate(REQUEST, { userId: USER }, "metrics")); const serialized = JSON.stringify(f.metrics.recent()); for (const secret of [BRIEF.keyMessage, BRIEF.offering, OUTPUTS.social_post.variants[0].body, "untrustedCustomerBrief"]) assert.equal(serialized.includes(secret), false); assert.match(serialized, /social_post/); });
  await t.test("Content Studio maps Instagram handoff and exactly five contracts to governed endpoint", () => { const source = readFileSync(new URL("../../src/pages/ContentStudioPage.tsx", import.meta.url), "utf8"); for (const id of ["social_post", "ad_copy", "marketing_email", "blog_outline", "landing_page_copy"]) assert.match(source, new RegExp(id)); assert.match(source, /template.*instagram/); assert.match(source, /\/api\/content\/generate/); assert.doesNotMatch(source, /\/api\/agent\/run|reel|story|sms|maxTokens|temperature/); });
  await t.test("legacy agent is internal experimental while governed generation is customer-facing", () => { assert.deepEqual(classifyApiRequest("POST", "/api/content/generate"), { feature: "content_studio", internal: false }); assert.deepEqual(classifyApiRequest("POST", "/api/agent/run"), { feature: "experimental_ai", internal: true }); assert.deepEqual(classifyApiRequest("POST", "/api/ai/chat"), { feature: "experimental_ai", internal: false }); });
  await t.test("creative sources have no execution, messaging, automation, campaign, worker, image, or video dependency", () => { const paths = ["../app/content-generation/content-brief.mjs", "../app/content-generation/channel-registry.mjs", "../app/content-generation/placement-registry.mjs", "../app/content-generation/contract-registry.mjs", "../app/content-generation/generation-context.mjs", "../app/content-generation/template-registry.mjs", "../app/content-generation/provider-binding-registry.mjs", "../app/content-generation/openai-text-provider.mjs", "../app/repositories/content-generation-repository.mjs", "../app/services/content-generation-service.mjs", "../app/routes/content-generation.mjs"]; const source = paths.map((path) => readFileSync(new URL(path, import.meta.url), "utf8")).join("\n").toLowerCase(); for (const forbidden of ["action-proposal", "execution-authorization", "execution-request", "execution-ledger", "dispatch-job", "execution-capabilit", "provider-account-identit", "action-input", "messaging.mjs", "automation", "worker_threads", "bullmq", "imagegenerationprovider", "videogenerationprovider"]) assert.equal(source.includes(forbidden), false); });
  await t.test("database integrity, foreign keys, indexes, and triggers are valid", () => { const db = database(); assert.equal(db.pragma("integrity_check", { simple: true }), "ok"); assert.deepEqual(db.pragma("foreign_key_check"), []); assert.equal(db.prepare("SELECT count(*) count FROM sqlite_master WHERE type='index' AND tbl_name='content_generations' AND sql IS NOT NULL").get().count, 2); assert.equal(db.prepare("SELECT count(*) count FROM sqlite_master WHERE type='trigger' AND tbl_name='content_generations'").get().count, 3); db.close(); });
});
