import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import Database from "better-sqlite3";
import { runMigrations } from "../db/migrate.mjs";
import { migration045ContentGenerations } from "../db/migrations/045_content_generations.mjs";
import { migration047ContentItems } from "../db/migrations/047_content_items.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createContentGenerationRepository } from "../app/repositories/content-generation-repository.mjs";
import { createContentItemRepository } from "../app/repositories/content-item-repository.mjs";
import { ContentItemError, createContentItemService } from "../app/services/content-item-service.mjs";
import { generationContractRegistry } from "../app/content-generation/contract-registry.mjs";
import { createOperationMetrics } from "../app/observability/operation-metrics.mjs";

const W = "library-workspace", OTHER = "other-workspace", U = "library-user", C = "library-context", G = "library-generation";
const VARIANT = Object.freeze({ hook: "رشد‌ پایدار با BrandX 🚀", body: "از مسیر example.com شروع کنید.", cta: "شروع کنید", hashtags: ["#رشد_پایدار"] });
const ACTOR = Object.freeze({ userId: U, role: "member" });

function database() {
  const db = new Database(":memory:"); db.pragma("foreign_keys=ON");
  db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT NOT NULL); CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT NOT NULL); CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,status TEXT NOT NULL); CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL); CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL);`);
  db.prepare("INSERT INTO users VALUES(?,?)").run(U, "active"); for (const workspace of [W, OTHER]) db.prepare("INSERT INTO workspaces VALUES(?,?)").run(workspace, "active");
  db.prepare("INSERT INTO workspace_memberships VALUES(?,?,?,?)").run("membership", W, U, "active"); db.prepare("INSERT INTO business_context_versions VALUES(?,?)").run(C, W);
  runMigrations(db, [migration045ContentGenerations, migration047ContentItems]);
  db.prepare(`INSERT INTO content_generations(id,workspace_id,user_id,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,template_version,provider_binding,provider_binding_version,provider_model,brief_hash,request_fingerprint,operation_kind,idempotency_key,request_hash,status,normalized_result_json,input_tokens,output_tokens,estimated_cost_minor,cost_currency,error_code,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,1,'binding',1,'model',?,?,'content.generate','generation-key',?,'SUCCEEDED',?,1,1,NULL,NULL,NULL,?,?)`).run(G, W, U, "TEXT", "social_post", 1, "instagram.feed.text", 1, C, "a".repeat(64), "b".repeat(64), "c".repeat(64), JSON.stringify({ variants: [VARIANT] }), "2026-08-22T10:00:00.000Z", "2026-08-22T10:00:00.000Z");
  return db;
}
function fixture() { const db = database(), metrics = createOperationMetrics(); const service = createContentItemService({ repository: createContentItemRepository(db), generationRepository: createContentGenerationRepository(db), contractRegistry: generationContractRegistry, operationMetrics: metrics, now: () => new Date("2026-08-22T12:00:00.000Z") }); return { db, service, metrics }; }
const within = (callback, workspace = W) => runWithWorkspace(workspace, callback);
const throws = (callback, code) => assert.throws(callback, (error) => error instanceof ContentItemError && error.code === code);
const save = (f, key = "save-key", input = { variantIndex: 0 }, actor = ACTOR) => within(() => f.service.saveGeneration(G, input, actor, key));

test("Content Library v1", async (t) => {
  await t.test("migration adds exactly one table, two indexes, and four triggers idempotently", () => { const db = database(); runMigrations(db, [migration047ContentItems]); assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='table' AND name='content_items'").get().n, 1); assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='index' AND tbl_name='content_items' AND sql IS NOT NULL").get().n, 2); assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='trigger' AND tbl_name='content_items'").get().n, 4); assert.equal(db.prepare("SELECT count(*) n FROM schema_migrations WHERE version=47").get().n, 1); db.close(); });
  await t.test("save copies exact server variant and pins lineage", () => { const f = fixture(), result = save(f); assert.deepEqual(result.item.content, VARIANT); assert.equal(result.item.sourceGenerationId, G); assert.equal(result.item.revision, 1); assert.match(result.item.title, /^پست اینستاگرام/); });
  await t.test("failed generation is not savable", () => { const f = fixture(); f.db.exec("DROP TRIGGER trg_content_generations_update"); f.db.prepare("UPDATE content_generations SET status='FAILED',normalized_result_json=NULL,error_code='FAILED'").run(); throws(() => save(f), "CONTENT_GENERATION_NOT_SAVABLE"); });
  await t.test("variant bounds and foreign generation are explicit", () => { const f = fixture(); throws(() => save(f, "bounds", { variantIndex: 1 }), "CONTENT_VARIANT_NOT_FOUND"); throws(() => within(() => f.service.saveGeneration("missing", { variantIndex: 0 }, ACTOR, "missing")), "CONTENT_ITEM_NOT_FOUND"); });
  await t.test("save replay is idempotent and changed request conflicts", () => { const f = fixture(); const first = save(f); const replay = save(f); assert.equal(replay.reusedResult, true); assert.equal(replay.item.id, first.item.id); throws(() => save(f, "save-key", { variantIndex: 0, title: "عنوان دیگر" }), "CONTENT_ITEM_IDEMPOTENCY_CONFLICT"); });
  await t.test("new key intentionally creates a second item", () => { const f = fixture(); save(f, "one"); save(f, "two"); assert.equal(f.db.prepare("SELECT count(*) n FROM content_items").get().n, 2); });
  await t.test("owner admin and member can save and edit", () => { for (const role of ["owner", "admin", "member"]) { const f = fixture(); const saved = save(f, role, { variantIndex: 0 }, { userId: U, role }); const updated = within(() => f.service.update(saved.item.id, { title: `عنوان ${role}`, expectedRevision: 1 }, { userId: U, role })); assert.equal(updated.revision, 2); } });
  await t.test("unknown role is denied", () => { const f = fixture(); throws(() => save(f, "denied", { variantIndex: 0 }, { userId: U, role: "viewer" }), "CONTENT_ITEM_PERMISSION_DENIED"); });
  await t.test("title and valid content update atomically", () => { const f = fixture(), saved = save(f), next = { ...VARIANT, body: "متن فارسی‌ و Latin URL https://loadder.ai" }; const updated = within(() => f.service.update(saved.item.id, { title: "عنوان تازه", content: next, expectedRevision: 1 }, ACTOR)); assert.equal(updated.title, "عنوان تازه"); assert.deepEqual(updated.content, next); assert.equal(updated.revision, 2); });
  await t.test("stale revision conflicts and invalid contract content is rejected", () => { const f = fixture(), saved = save(f); within(() => f.service.update(saved.item.id, { title: "اول", expectedRevision: 1 }, ACTOR)); throws(() => within(() => f.service.update(saved.item.id, { title: "دوم", expectedRevision: 1 }, ACTOR)), "CONTENT_ITEM_REVISION_CONFLICT"); throws(() => within(() => f.service.update(saved.item.id, { content: { arbitrary: true }, expectedRevision: 2 }, ACTOR)), "CONTENT_ITEM_INVALID"); });
  await t.test("lineage update and delete are database-rejected", () => { const f = fixture(), saved = save(f); assert.throws(() => f.db.prepare("UPDATE content_items SET contract_id='ad_copy',revision=2,updated_at='2026-08-22T13:00:00.000Z' WHERE id=?").run(saved.item.id)); assert.throws(() => f.db.prepare("DELETE FROM content_items WHERE id=?").run(saved.item.id)); });
  await t.test("duplicate copies current state and is independently idempotent", () => { const f = fixture(), saved = save(f); within(() => f.service.update(saved.item.id, { title: "ویرایش", expectedRevision: 1 }, ACTOR)); const first = within(() => f.service.duplicate(saved.item.id, {}, ACTOR, "dup")); const replay = within(() => f.service.duplicate(saved.item.id, {}, ACTOR, "dup")); assert.equal(first.item.revision, 1); assert.equal(first.item.title, "ویرایش — نسخه کپی"); assert.equal(replay.reusedResult, true); const second = within(() => f.service.duplicate(saved.item.id, {}, ACTOR, "dup-2")); assert.notEqual(second.item.id, first.item.id); });
  await t.test("list is tenant-scoped, filtered, and cursor pagination has no overlap", () => { const f = fixture(); for (let index = 0; index < 3; index += 1) save(f, `page-${index}`, { variantIndex: 0, title: `محتوا ${index}` }); const first = within(() => f.service.list({ limit: "2", mediaType: "TEXT", contractId: "social_post", placementId: "instagram.feed.text" }, ACTOR)); const second = within(() => f.service.list({ limit: "2", cursor: first.nextCursor }, ACTOR)); assert.equal(first.items.length, 2); assert.equal(second.items.length, 1); assert.equal(new Set([...first.items, ...second.items].map((item) => item.id)).size, 3); assert.equal(within(() => f.service.list({}, ACTOR), OTHER).items.length, 0); });
  await t.test("detail hides foreign workspace items and customer DTO omits hashes/provider", () => { const f = fixture(), saved = save(f); throws(() => within(() => f.service.get(saved.item.id, ACTOR), OTHER), "CONTENT_ITEM_NOT_FOUND"); const item = within(() => f.service.get(saved.item.id, ACTOR)); for (const forbidden of ["requestHash", "provider", "model", "prompt", "workspaceId"]) assert.equal(Object.hasOwn(item, forbidden), false); });
  await t.test("Persian half-space emoji hashtags Latin URLs and numbers survive", () => { const f = fixture(), saved = save(f); assert.equal(saved.item.content.hook, VARIANT.hook); assert.equal(saved.item.content.body, VARIANT.body); assert.equal(saved.item.content.hashtags[0], "#رشد_پایدار"); });
  await t.test("source generation remains immutable after item edits", () => { const f = fixture(), before = f.db.prepare("SELECT normalized_result_json FROM content_generations WHERE id=?").get(G); const saved = save(f); within(() => f.service.update(saved.item.id, { title: "تغییر", expectedRevision: 1 }, ACTOR)); assert.deepEqual(f.db.prepare("SELECT normalized_result_json FROM content_generations WHERE id=?").get(G), before); });
  await t.test("metrics are bounded and contain no title or content", () => { const f = fixture(); const saved = save(f); within(() => f.service.get(saved.item.id, ACTOR)); const serialized = JSON.stringify(f.metrics.recent()); assert.equal(serialized.includes(VARIANT.body), false); assert.equal(serialized.includes(saved.item.title), false); assert.match(serialized, /content_item\.save/); });
  await t.test("sources contain no provider execution or AI dependencies", () => { const source = ["../app/repositories/content-item-repository.mjs", "../app/services/content-item-service.mjs", "../app/routes/content-items.mjs"].map((path) => readFileSync(new URL(path, import.meta.url), "utf8")).join("\n").toLowerCase(); for (const forbidden of ["openai", "cloudflare", "provider-binding", "action-proposal", "execution-request", "execution-ledger", "dispatch-job", "automation"] ) assert.equal(source.includes(forbidden), false); });
  await t.test("frontend has lazy routes save path exports and unsaved-change guard", () => { const app = readFileSync(new URL("../../src/App.tsx", import.meta.url), "utf8"), studio = readFileSync(new URL("../../src/pages/ContentStudioPage.tsx", import.meta.url), "utf8"), editor = readFileSync(new URL("../../src/pages/ContentItemPage.tsx", import.meta.url), "utf8"), dashboard = readFileSync(new URL("../../src/pages/DashboardPage.tsx", import.meta.url), "utf8"), format = readFileSync(new URL("../../src/lib/contentItemFormatting.ts", import.meta.url), "utf8"); assert.match(app, /lazy.*ContentLibraryPage/); assert.match(app, /dashboard\/library\/:id/); assert.match(studio, /content\/generations\/\$\{generation\.generationId\}\/save/); assert.match(editor, /beforeunload/); assert.match(editor, /expectedRevision/); assert.match(format, /contentItemText/); assert.match(format, /contentItemMarkdown/); assert.match(dashboard, /content\/items\?limit=3/); });
  await t.test("integrity foreign keys and query plan are sound", () => { const f = fixture(); save(f); assert.equal(f.db.pragma("integrity_check", { simple: true }), "ok"); assert.deepEqual(f.db.pragma("foreign_key_check"), []); const plan = f.db.prepare("EXPLAIN QUERY PLAN SELECT * FROM content_items WHERE workspace_id=? ORDER BY updated_at DESC,id DESC LIMIT 20").all(W).map((row) => row.detail).join(" "); assert.match(plan, /idx_content_items_workspace_updated/); assert.equal(f.db.prepare("SELECT count(*) n FROM content_items").get().n, 1); });
});
