import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import Database from "better-sqlite3";
import { runMigrations } from "../db/migrate.mjs";
import { migration045ContentGenerations } from "../db/migrations/045_content_generations.mjs";
import { migration047ContentItems } from "../db/migrations/047_content_items.mjs";
import { migration048ContentItemSourceIdentity } from "../db/migrations/048_content_item_source_identity.mjs";
import { CONTENT_SOURCE_TYPES, assertContentSourceCreationEnabled, assertContentSourceType } from "../app/content-items/source-type-registry.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createContentGenerationRepository } from "../app/repositories/content-generation-repository.mjs";
import { createContentItemRepository } from "../app/repositories/content-item-repository.mjs";
import { ContentItemError, createContentItemService } from "../app/services/content-item-service.mjs";
import { generationContractRegistry } from "../app/content-generation/contract-registry.mjs";
import { contentPlacementRegistry } from "../app/content-generation/placement-registry.mjs";
import { createOperationMetrics } from "../app/observability/operation-metrics.mjs";

const W = "source-workspace", OTHER = "source-other", U = "source-user", C = "source-context", G = "source-generation", AT = "2026-08-22T12:00:00.000Z";
const SOCIAL = Object.freeze({ hook: "رشد‌ پایدار با BrandX 🚀", body: "متن فارسی و Latin 123", cta: "شروع", hashtags: ["#رشد_پایدار"] });
const MANUAL = Object.freeze({ contractId: "social_post", contractVersion: 1, placementId: "instagram.feed.text", placementVersion: 1, title: "متن دستی", content: SOCIAL });
const ACTOR = Object.freeze({ userId: U, role: "member" });

function baseDatabase({ migrate48 = true, historicalItem = false } = {}) {
  const db = new Database(":memory:"); db.pragma("foreign_keys=ON");
  db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,status TEXT NOT NULL);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL);");
  db.prepare("INSERT INTO users VALUES(?,?)").run(U, "active"); for (const workspace of [W, OTHER]) db.prepare("INSERT INTO workspaces VALUES(?,?)").run(workspace, "active"); db.prepare("INSERT INTO workspace_memberships VALUES(?,?,?,?)").run("membership", W, U, "active"); db.prepare("INSERT INTO business_context_versions VALUES(?,?)").run(C, W);
  runMigrations(db, [migration045ContentGenerations, migration047ContentItems]);
  db.prepare(`INSERT INTO content_generations(id,workspace_id,user_id,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,template_version,provider_binding,provider_binding_version,provider_model,brief_hash,request_fingerprint,operation_kind,idempotency_key,request_hash,status,normalized_result_json,input_tokens,output_tokens,estimated_cost_minor,cost_currency,error_code,created_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,1,'binding',1,'model',?,?,'content.generate','generation',?,'SUCCEEDED',?,1,1,NULL,NULL,NULL,?,?)`).run(G, W, U, "TEXT", "social_post", 1, "instagram.feed.text", 1, C, "a".repeat(64), "b".repeat(64), "c".repeat(64), JSON.stringify({ variants: [SOCIAL] }), AT, AT);
  if (historicalItem) db.prepare(`INSERT INTO content_items(id,workspace_id,created_by_user_id,source_generation_id,source_variant_index,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,title,content_json,revision,operation_kind,idempotency_key,request_hash,created_at,updated_at) VALUES('historical',?,?,?,?,?,?,?,?,?,?,?,?,1,'content_item.save','historical-key',?,?,?)`).run(W, U, G, 0, "TEXT", "social_post", 1, "instagram.feed.text", 1, C, "قدیمی", JSON.stringify(SOCIAL), "d".repeat(64), AT, AT);
  if (migrate48) runMigrations(db, [migration048ContentItemSourceIdentity]);
  return db;
}
function fixture(overrides = {}) { const db = baseDatabase(), metrics = createOperationMetrics(); const service = createContentItemService({ repository: createContentItemRepository(db), generationRepository: createContentGenerationRepository(db), contractRegistry: overrides.contractRegistry || generationContractRegistry, placementRegistry: overrides.placementRegistry || contentPlacementRegistry, operationMetrics: metrics, now: () => new Date(AT) }); return { db, service, metrics }; }
const within = (fn, workspace = W) => runWithWorkspace(workspace, fn);
const throws = (fn, code) => assert.throws(fn, (error) => error instanceof ContentItemError && error.code === code);
const manual = (f, key = "manual", input = MANUAL, actor = ACTOR) => within(() => f.service.createManual(input, actor, key));
const generated = (f, key = "generated", actor = ACTOR) => within(() => f.service.saveGeneration(G, { variantIndex: 0 }, actor, key));

test("Creative Source Identity and Manual TEXT v1", async (t) => {
  await t.test("migration 048 preserves a non-empty historical row and backfills AI_GENERATED", () => { const db = baseDatabase({ migrate48: false, historicalItem: true }); const before = db.prepare("SELECT * FROM content_items WHERE id='historical'").get(); runMigrations(db, [migration048ContentItemSourceIdentity]); runMigrations(db, [migration048ContentItemSourceIdentity]); const after = db.prepare("SELECT * FROM content_items WHERE id='historical'").get(); assert.equal(after.source_type, "AI_GENERATED"); for (const field of ["id", "workspace_id", "created_by_user_id", "source_generation_id", "source_variant_index", "media_type", "contract_id", "contract_version", "placement_id", "placement_version", "context_version_id", "title", "content_json", "revision", "operation_kind", "idempotency_key", "request_hash", "created_at", "updated_at"]) assert.equal(after[field], before[field]); assert.deepEqual(db.prepare("SELECT count(*) count,max(version) max FROM schema_migrations").get(), { count: 3, max: 48 }); assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='index' AND tbl_name='content_items' AND sql IS NOT NULL").get().n, 2); assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='trigger' AND tbl_name='content_items'").get().n, 4); db.close(); });
  await t.test("source enum is exact and only current sources are creation-enabled", () => { assert.deepEqual(CONTENT_SOURCE_TYPES, ["AI_GENERATED", "CLIENT_UPLOADED", "MANUAL_TEXT", "EXTERNAL_IMPORTED"]); for (const value of CONTENT_SOURCE_TYPES) assert.equal(assertContentSourceType(value), value); assert.throws(() => assertContentSourceType("ARBITRARY"), (e) => e.code === "CONTENT_SOURCE_INVALID"); for (const value of ["CLIENT_UPLOADED", "EXTERNAL_IMPORTED"]) assert.throws(() => assertContentSourceCreationEnabled(value), (e) => e.code === "CONTENT_SOURCE_INVALID"); });
  await t.test("owner admin and member create manual TEXT with null generation and Context lineage", () => { for (const role of ["owner", "admin", "member"]) { const f = fixture(), result = manual(f, role, MANUAL, { userId: U, role }); const row = f.db.prepare("SELECT * FROM content_items WHERE id=?").get(result.item.id); assert.equal(result.item.sourceType, "MANUAL_TEXT"); assert.equal(row.source_generation_id, null); assert.equal(row.context_version_id, null); assert.equal(row.operation_kind, "content_item.manual"); } });
  await t.test("manual input rejects ownership source media provider generation and asset injection", () => { for (const field of ["workspaceId", "userId", "mediaType", "contextVersionId", "provider", "model", "generationId", "assetId", "width"]) { const f = fixture(); throws(() => manual(f, field, { ...MANUAL, [field]: field }), field === "sourceType" ? "CONTENT_SOURCE_INVALID" : "CONTENT_ITEM_INVALID"); } const f = fixture(); throws(() => manual(f, "source", { ...MANUAL, sourceType: "CLIENT_UPLOADED" }), "CONTENT_SOURCE_INVALID"); });
  await t.test("manual replay reuses, changed request conflicts, and new key repeats intentionally", () => { const f = fixture(), first = manual(f); const replay = manual(f); assert.equal(replay.reusedResult, true); assert.equal(replay.item.id, first.item.id); throws(() => manual(f, "manual", { ...MANUAL, title: "دیگر" }), "CONTENT_ITEM_IDEMPOTENCY_CONFLICT"); assert.notEqual(manual(f, "manual-2").item.id, first.item.id); });
  await t.test("unknown contract and placement are not found", () => { const f = fixture(); throws(() => manual(f, "contract", { ...MANUAL, contractId: "missing" }), "CONTENT_ITEM_NOT_FOUND"); throws(() => manual(f, "placement", { ...MANUAL, placementId: "missing.text" }), "CONTENT_ITEM_NOT_FOUND"); });
  await t.test("placement mismatch and invalid contract-shaped content are rejected", () => { const f = fixture(); throws(() => manual(f, "mismatch", { ...MANUAL, placementId: "email.marketing.text" }), "CONTENT_ITEM_INVALID"); throws(() => manual(f, "invalid", { ...MANUAL, content: { arbitrary: true } }), "CONTENT_ITEM_INVALID"); });
  await t.test("non-TEXT contract is rejected with bounded source error", () => { const image = { mediaType: "IMAGE", contractId: "image", contractVersion: 1, placementId: "image.feed", placementVersion: 1, validateOutput: () => [] }; const f = fixture({ contractRegistry: { get: () => image } }); throws(() => manual(f, "image", { ...MANUAL, contractId: "image" }), "CONTENT_SOURCE_INVALID"); });
  await t.test("manual title is required and bounded", () => { const f = fixture(); throws(() => manual(f, "empty", { ...MANUAL, title: " " }), "CONTENT_ITEM_INVALID"); throws(() => manual(f, "long", { ...MANUAL, title: "x".repeat(201) }), "CONTENT_ITEM_INVALID"); });
  await t.test("Persian Unicode half-space mixed Latin and numbers are preserved", () => { const f = fixture(), item = manual(f).item; assert.equal(item.content.hook, SOCIAL.hook); assert.equal(item.content.body, SOCIAL.body); assert.equal(item.content.hashtags[0], SOCIAL.hashtags[0]); });
  await t.test("list and detail expose truthful sourceType with tenant isolation", () => { const f = fixture(), created = manual(f).item; assert.equal(within(() => f.service.list({}, ACTOR)).items[0].sourceType, "MANUAL_TEXT"); assert.equal(within(() => f.service.get(created.id, ACTOR)).sourceType, "MANUAL_TEXT"); throws(() => within(() => f.service.get(created.id, ACTOR), OTHER), "CONTENT_ITEM_NOT_FOUND"); });
  await t.test("generated save remains AI_GENERATED", () => { const f = fixture(), item = generated(f).item; assert.equal(item.sourceType, "AI_GENERATED"); assert.equal(f.db.prepare("SELECT source_type FROM content_items WHERE id=?").get(item.id).source_type, "AI_GENERATED"); });
  await t.test("duplicates retain generated and manual source types", () => { const f = fixture(), ai = generated(f), hand = manual(f); const aiCopy = within(() => f.service.duplicate(ai.item.id, {}, ACTOR, "ai-copy")); const handCopy = within(() => f.service.duplicate(hand.item.id, {}, ACTOR, "hand-copy")); assert.equal(aiCopy.item.sourceType, "AI_GENERATED"); assert.equal(handCopy.item.sourceType, "MANUAL_TEXT"); });
  await t.test("source identity lineage is immutable while revision edits remain valid", () => { const f = fixture(), item = manual(f).item; assert.throws(() => f.db.prepare("UPDATE content_items SET source_type='AI_GENERATED',revision=2,updated_at='2026-08-22T13:00:00.000Z' WHERE id=?").run(item.id)); const updated = within(() => f.service.update(item.id, { title: "عنوان تازه", expectedRevision: 1 }, ACTOR)); assert.equal(updated.revision, 2); assert.equal(updated.sourceType, "MANUAL_TEXT"); });
  await t.test("database enforces pairwise identity and manual lineage constraints", () => { const f = fixture(); const columns = "id,workspace_id,created_by_user_id,source_type,source_generation_id,source_variant_index,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,title,content_json,revision,operation_kind,idempotency_key,request_hash,created_at,updated_at"; const values = ["bad", W, U, "MANUAL_TEXT", null, null, "TEXT", "social_post", null, "instagram.feed.text", 1, null, "bad", JSON.stringify(SOCIAL), 1, "content_item.manual", "bad", "e".repeat(64), AT, AT]; assert.throws(() => f.db.prepare(`INSERT INTO content_items(${columns}) VALUES(${Array(20).fill("?").join(",")})`).run(...values)); values[8] = 1; values[10] = null; assert.throws(() => f.db.prepare(`INSERT INTO content_items(${columns}) VALUES(${Array(20).fill("?").join(",")})`).run(...values)); });
  await t.test("delete remains rejected and database stays valid", () => { const f = fixture(), item = manual(f).item; assert.throws(() => f.db.prepare("DELETE FROM content_items WHERE id=?").run(item.id)); assert.equal(f.db.pragma("integrity_check", { simple: true }), "ok"); assert.deepEqual(f.db.pragma("foreign_key_check"), []); });
  await t.test("manual metrics are bounded and content-free", () => { const f = fixture(); manual(f); const serialized = JSON.stringify(f.metrics.recent()); assert.match(serialized, /content_item\.manual_create/); assert.match(serialized, /MANUAL_TEXT/); for (const secret of [MANUAL.title, SOCIAL.hook, SOCIAL.body, SOCIAL.hashtags[0]]) assert.equal(serialized.includes(secret), false); });
  await t.test("manual backend has no AI provider asset upload performance or execution dependency", () => { const paths = ["../app/content-items/source-type-registry.mjs", "../app/services/content-item-service.mjs", "../app/repositories/content-item-repository.mjs", "../app/routes/content-items.mjs"]; const source = paths.map((path) => readFileSync(new URL(path, import.meta.url), "utf8")).join("\n").toLowerCase(); for (const forbidden of ["openai", "cloudflare", "provider-binding", "content_assets", "object storage", "signed url", "creative_placements", "performance_observations", "execution-request", "action-proposal", "dispatch-job", "messaging", "automation"] ) assert.equal(source.includes(forbidden), false); });
  await t.test("frontend preserves manual flow and approved standalone asset upload controls", () => { const library = readFileSync(new URL("../../src/pages/ContentLibraryPage.tsx", import.meta.url), "utf8"), manualPage = readFileSync(new URL("../../src/pages/ManualContentPage.tsx", import.meta.url), "utf8"), badge = readFileSync(new URL("../../src/components/content/ContentSourceBadge.tsx", import.meta.url), "utf8"), app = readFileSync(new URL("../../src/App.tsx", import.meta.url), "utf8"); assert.match(library, /ساخت متن دستی/); assert.match(library, /content\/assets\/upload-intents/); assert.match(library, /بارگذاری تصویر/); assert.match(library, /بارگذاری ویدیو/); assert.match(manualPage, /content\/items\/manual/); assert.match(app, /dashboard\/library\/new/); for (const label of ["Generated by Loadder", "Created manually", "Uploaded by you", "Imported"]) assert.match(badge, new RegExp(label)); for (const forbidden of ["from-asset", "content_assets", "openai", "execution-request", "publish", "external import"]) assert.equal(`${library}\n${manualPage}`.toLowerCase().includes(forbidden), false); });
});
