import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import Database from "better-sqlite3";
import { runMigrations } from "../db/migrate.mjs";
import { migration045ContentGenerations } from "../db/migrations/045_content_generations.mjs";
import { migration047ContentItems } from "../db/migrations/047_content_items.mjs";
import { migration048ContentItemSourceIdentity } from "../db/migrations/048_content_item_source_identity.mjs";
import { migration049ContentAssets } from "../db/migrations/049_content_assets.mjs";
import { migration050RealAssetUpload } from "../db/migrations/050_real_asset_upload.mjs";
import { migration051UploadedCreativeLinkage } from "../db/migrations/051_uploaded_creative_linkage.mjs";
import { migration052CreativePlacements } from "../db/migrations/052_creative_placements.mjs";
import { migration053CreativeIntents } from "../db/migrations/053_creative_intents.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createCreativeIntentRepository } from "../app/repositories/creative-intent-repository.mjs";
import { createCreativeIntentService } from "../app/services/creative-intent-service.mjs";
import { createOperationMetrics } from "../app/observability/operation-metrics.mjs";

const AT="2026-08-22T15:00:00.000Z",W="workspace",U="user",SHA="a".repeat(64),actor={userId:U,role:"member"};
const migrations=[migration045ContentGenerations,migration047ContentItems,migration048ContentItemSourceIdentity,migration049ContentAssets,migration050RealAssetUpload,migration051UploadedCreativeLinkage,migration052CreativePlacements];
function base(){const db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);");runMigrations(db,migrations);db.exec("INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('workspace','active');INSERT INTO workspaces VALUES('other','active');INSERT INTO workspace_memberships VALUES('membership','workspace','user','member','active');");return db;}
function fixture(){const db=base();runMigrations(db,[migration053CreativeIntents]);let tick=Date.parse(AT);const metrics=createOperationMetrics(),repository=createCreativeIntentRepository(db),service=createCreativeIntentService({repository,operationMetrics:metrics,now:()=>new Date(tick+=1000)});return{db,repository,service,metrics};}
const within=(fn,workspace=W)=>runWithWorkspace(workspace,fn),input=(overrides={})=>({intentType:"AWARENESS",title:"Increase awareness",description:"Introduce the brand to a qualified audience.",goal:"Increase qualified awareness",...overrides}),create=(f,key="key",value=input(),who=actor)=>within(()=>f.service.create(value,who,key));

test("Creative Intent Foundation v1",async t=>{
 await t.test("migration 053 adds one table, nullable lineage, and preserves history",()=>{const db=base();db.prepare("INSERT INTO content_items(id,workspace_id,created_by_user_id,source_type,source_generation_id,source_variant_index,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,primary_asset_id,title,content_json,revision,operation_kind,idempotency_key,request_hash,created_at,updated_at) VALUES('historical','workspace','user','MANUAL_TEXT',NULL,NULL,'TEXT','social_post',1,'instagram.feed.text',1,NULL,NULL,'Historical','{}',1,'content_item.manual','historical',?,?,?)").run(SHA,AT,AT);runMigrations(db,[migration053CreativeIntents]);runMigrations(db,[migration053CreativeIntents]);assert.deepEqual(db.prepare("SELECT count(*) count,max(version) max FROM schema_migrations WHERE version=53").get(),{count:1,max:53});assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='creative_intents'").get());assert.ok(db.prepare("SELECT 1 FROM pragma_table_info('content_generations') WHERE name='intent_id'").get());assert.ok(db.prepare("SELECT 1 FROM pragma_table_info('content_items') WHERE name='intent_id'").get());assert.deepEqual(db.prepare("SELECT id,intent_id intentId FROM content_items WHERE id='historical'").get(),{id:"historical",intentId:null});});
 await t.test("bounded intent types create tenant-owned immutable purpose",()=>{for(const intentType of ["AWARENESS","TRUST_BUILDING","LEAD_GENERATION","SALES","EDUCATION","ENGAGEMENT"]){const f=fixture(),result=create(f,intentType,input({intentType}));assert.equal(result.intent.intentType,intentType);assert.equal(result.intent.goal,"Increase qualified awareness");}});
 await t.test("strict input rejects ownership and unrelated domains",()=>{for(const field of ["workspaceId","workspace_id","creatorId","creator_id","campaignId","placementId","metrics","performance"]){const f=fixture();assert.throws(()=>create(f,field,{...input(),[field]:"x"}),e=>e.code==="CREATIVE_INTENT_INVALID");}const f=fixture();assert.throws(()=>create(f,"bad-type",input({intentType:"PROMOTION"})),e=>e.code==="CREATIVE_INTENT_INVALID");});
 await t.test("creation is idempotent and changed request conflicts",()=>{const f=fixture(),first=create(f),replay=create(f);assert.equal(first.intent.id,replay.intent.id);assert.equal(replay.reusedResult,true);assert.throws(()=>create(f,"key",input({goal:"Different"})),e=>e.code==="CREATIVE_INTENT_IDEMPOTENCY_CONFLICT");});
 await t.test("tenant isolation hides foreign intent IDs",()=>{const f=fixture(),created=create(f).intent;assert.equal(within(()=>f.repository.findById(created.id),"other"),null);assert.equal(within(()=>f.service.list({},actor),"other").intents.length,0);});
 await t.test("owner admin member are allowed while unknown role is denied",()=>{for(const role of ["owner","admin","member"]){const f=fixture();assert.ok(create(f,role,input(),{userId:U,role}).intent.id);}const f=fixture();assert.throws(()=>create(f,"viewer",input(),{userId:U,role:"viewer"}),e=>e.code==="CREATIVE_INTENT_PERMISSION_DENIED");});
 await t.test("meaning is immutable and hard delete is rejected",()=>{const f=fixture(),created=create(f).intent;assert.throws(()=>f.db.prepare("UPDATE creative_intents SET goal='changed',updated_at=? WHERE id=?").run("2026-08-22T16:00:00.000Z",created.id));assert.throws(()=>f.db.prepare("DELETE FROM creative_intents WHERE id=?").run(created.id));});
 await t.test("successor creation links once without mutating prior meaning",()=>{const f=fixture(),prior=create(f).intent,next=create(f,"successor",input({title:"Increase trust",goal:"Increase trust",intentType:"TRUST_BUILDING",successorOfIntentId:prior.id})).intent;assert.equal(f.db.prepare("SELECT successor_intent_id id,title,goal FROM creative_intents WHERE id=?").get(prior.id).id,next.id);assert.throws(()=>create(f,"branch",input({successorOfIntentId:prior.id})),e=>e.code==="CREATIVE_INTENT_SUCCESSOR_CONFLICT");assert.throws(()=>create(f,"missing",input({successorOfIntentId:"missing"})),e=>e.code==="CREATIVE_INTENT_NOT_FOUND");});
 await t.test("lineage references are nullable, tenant guarded, and generation compatible",()=>{const f=fixture(),intent=create(f).intent;f.db.prepare("INSERT INTO business_context_versions VALUES('context','workspace')").run();f.db.prepare(`INSERT INTO content_generations(id,workspace_id,user_id,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,template_version,provider_binding,provider_binding_version,provider_model,brief_hash,request_fingerprint,operation_kind,idempotency_key,request_hash,status,normalized_result_json,input_tokens,output_tokens,estimated_cost_minor,cost_currency,error_code,created_at,completed_at,intent_id) VALUES('generation',?,?, 'TEXT','social_post',1,'instagram.feed.text',1,'context',1,'binding',1,'model',?,?,'content.generate','generation-key',?,'SUCCEEDED','{"variants":[]}',0,0,NULL,NULL,NULL,?,?,?)`).run(W,U,SHA,SHA,SHA,AT,AT,intent.id);assert.equal(f.db.prepare("SELECT intent_id FROM content_generations WHERE id='generation'").get().intent_id,intent.id);});
 await t.test("list is bounded, tenant scoped, and keyset paginated",()=>{const f=fixture();for(let i=0;i<3;i++)create(f,`key-${i}`,input({title:`Intent ${i}`}));const first=within(()=>f.service.list({limit:2},actor)),second=within(()=>f.service.list({limit:2,cursor:first.nextCursor},actor));assert.equal(first.intents.length,2);assert.equal(second.intents.length,1);assert.equal(new Set([...first.intents,...second.intents].map(x=>x.id)).size,3);});
 await t.test("schema and dependencies have no campaign performance website or runtime coupling",()=>{const f=fixture(),columns=f.db.prepare("SELECT name FROM pragma_table_info('creative_intents')").all().map(x=>x.name);for(const forbidden of ["campaign_id","placement_id","website_id","page_id","section_id","impressions","clicks","conversions","ctr","cpa","roas","score"])assert.equal(columns.includes(forbidden),false);const source=["../app/repositories/creative-intent-repository.mjs","../app/services/creative-intent-service.mjs","../app/routes/creative-intents.mjs"].map(p=>readFileSync(new URL(p,import.meta.url),"utf8").toLowerCase()).join("\n");for(const forbidden of ["openai","performance_observations","campaigns","website_projects","worker","queue","redis","billing","fetch("])assert.equal(source.includes(forbidden),false);assert.equal(f.db.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(f.db.pragma("foreign_key_check"),[]);});
});
