import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import Database from "better-sqlite3";
import { runMigrations } from "../db/migrate.mjs";
import { migration045ContentGenerations } from "../db/migrations/045_content_generations.mjs";
import { migration047ContentItems } from "../db/migrations/047_content_items.mjs";
import { migration048ContentItemSourceIdentity } from "../db/migrations/048_content_item_source_identity.mjs";
import { migration049ContentAssets } from "../db/migrations/049_content_assets.mjs";
import { migration050RealAssetUpload } from "../db/migrations/050_real_asset_upload.mjs";
import { migration051UploadedCreativeLinkage } from "../db/migrations/051_uploaded_creative_linkage.mjs";
import { migration052CreativePlacements } from "../db/migrations/052_creative_placements.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createContentItemRepository } from "../app/repositories/content-item-repository.mjs";
import { createCreativePlacementRepository } from "../app/repositories/creative-placement-repository.mjs";
import { createCreativePlacementService } from "../app/services/creative-placement-service.mjs";
import { createOperationMetrics } from "../app/observability/operation-metrics.mjs";

const AT="2026-08-22T12:00:00.000Z",SHA="a".repeat(64),W="workspace",U="user",ITEM="item",actor={userId:U,role:"member"};
function base(){const db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);");runMigrations(db,[migration045ContentGenerations,migration047ContentItems,migration048ContentItemSourceIdentity,migration049ContentAssets,migration050RealAssetUpload,migration051UploadedCreativeLinkage]);db.exec("INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('workspace','active');INSERT INTO workspaces VALUES('other','active');INSERT INTO workspace_memberships VALUES('membership','workspace','user','member','active');");db.prepare("INSERT INTO content_items(id,workspace_id,created_by_user_id,source_type,source_generation_id,source_variant_index,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,primary_asset_id,title,content_json,revision,operation_kind,idempotency_key,request_hash,created_at,updated_at) VALUES(?,?,?,'MANUAL_TEXT',NULL,NULL,'TEXT','social_post',1,'instagram.feed.text',1,NULL,NULL,'Creative','{}',1,'content_item.manual','item-key',?,?,?)").run(ITEM,W,U,SHA,AT,AT);return db;}
function fixture(){const db=base();runMigrations(db,[migration052CreativePlacements]);let tick=Date.parse(AT);const metrics=createOperationMetrics(),service=createCreativePlacementService({repository:createCreativePlacementRepository(db),contentItemRepository:createContentItemRepository(db),operationMetrics:metrics,now:()=>new Date(tick+=1000)});return{db,service,metrics};}
const within=(fn,workspace=W)=>runWithWorkspace(workspace,fn),create=(f,key="key",input={placementKind:"WEBSITE",channel:"website"},item=ITEM,who=actor)=>within(()=>f.service.create(item,input,who,key));
test("Creative Placement Foundation v1",async t=>{
 await t.test("migration 052 adds exactly one table and is idempotent",()=>{const db=base(),before=db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();runMigrations(db,[migration052CreativePlacements]);runMigrations(db,[migration052CreativePlacements]);assert.deepEqual(db.prepare("SELECT count(*) count,max(version) max FROM schema_migrations WHERE version=52").get(),{count:1,max:52});assert.deepEqual(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT IN("+before.map(()=>"?").join(",")+")").all(...before.map(x=>x.name)),[{name:"creative_placements"}]);for(const row of before)assert.equal(db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(row.name).sql,row.sql);});
 await t.test("bounded kinds create ACTIVE placement linked to Content Item",()=>{for(const placementKind of ["WEBSITE","SOCIAL","ADVERTISEMENT","EMAIL","OTHER"]){const f=fixture(),result=create(f,placementKind,{placementKind,channel:"channel"});assert.equal(result.placement.placementKind,placementKind);assert.equal(result.placement.status,"ACTIVE");assert.equal(result.placement.contentItemId,ITEM);}});
 await t.test("strict request rejects ownership external and platform-specific fields",()=>{for(const field of ["workspaceId","userId","externalReferenceId","contentAssetId","campaignId","websitePageId","metrics"]){const f=fixture();assert.throws(()=>create(f,field,{placementKind:"WEBSITE",channel:"website",[field]:"x"}),e=>e.code==="CREATIVE_PLACEMENT_INVALID");}const f=fixture();assert.throws(()=>create(f,"platform",{placementKind:"instagram_feed",channel:"instagram"}),e=>e.code==="CREATIVE_PLACEMENT_INVALID");});
 await t.test("channel is bounded normalized identity",()=>{const f=fixture();assert.equal(create(f,"channel",{placementKind:"SOCIAL",channel:" Instagram "}).placement.channel,"instagram");for(const channel of ["","نامعتبر","a".repeat(81),"has space"]){assert.throws(()=>create(f,`bad-${channel.length}`,{placementKind:"OTHER",channel}),e=>e.code==="CREATIVE_PLACEMENT_INVALID");}});
 await t.test("idempotent replay reuses and changed request conflicts",()=>{const f=fixture(),a=create(f),b=create(f);assert.equal(a.placement.id,b.placement.id);assert.equal(b.reusedResult,true);assert.throws(()=>create(f,"key",{placementKind:"SOCIAL",channel:"instagram"}),e=>e.code==="CREATIVE_PLACEMENT_IDEMPOTENCY_CONFLICT");});
 await t.test("one Creative supports multiple placements without duplication",()=>{const f=fixture();create(f,"web");create(f,"social",{placementKind:"SOCIAL",channel:"instagram"});assert.equal(f.db.prepare("SELECT count(*) n FROM content_items").get().n,1);assert.equal(f.db.prepare("SELECT count(*) n FROM creative_placements").get().n,2);});
 await t.test("foreign and missing Content Items are 404",()=>{const f=fixture();assert.throws(()=>within(()=>f.service.create("missing",{placementKind:"OTHER",channel:"other"},actor,"missing")),e=>e.code==="CONTENT_ITEM_NOT_FOUND");assert.throws(()=>within(()=>f.service.list(ITEM,{},actor),"other"),e=>e.code==="CONTENT_ITEM_NOT_FOUND");});
 await t.test("owner admin member are allowed and unknown role denied",()=>{for(const role of ["owner","admin","member"]){const f=fixture();assert.equal(create(f,role,undefined,ITEM,{userId:U,role}).placement.status,"ACTIVE");}const f=fixture();assert.throws(()=>create(f,"viewer",undefined,ITEM,{userId:U,role:"viewer"}),e=>e.code==="CREATIVE_PLACEMENT_PERMISSION_DENIED");});
 await t.test("list is tenant scoped bounded and keyset paginated",()=>{const f=fixture();for(let i=0;i<3;i++)create(f,`key-${i}`,{placementKind:"OTHER",channel:`channel-${i}`});const first=within(()=>f.service.list(ITEM,{limit:2},actor)),second=within(()=>f.service.list(ITEM,{limit:2,cursor:first.nextCursor},actor));assert.equal(first.placements.length,2);assert.equal(second.placements.length,1);assert.equal(new Set([...first.placements,...second.placements].map(x=>x.id)).size,3);});
 await t.test("identity is immutable status transitions preserve removed history and hard delete rejects",()=>{const f=fixture(),p=create(f).placement;assert.throws(()=>f.db.prepare("UPDATE creative_placements SET channel='other',updated_at=? WHERE id=?").run("2026-08-22T13:00:00.000Z",p.id));f.db.prepare("UPDATE creative_placements SET status='PAUSED',updated_at=? WHERE id=?").run("2026-08-22T13:00:00.000Z",p.id);f.db.prepare("UPDATE creative_placements SET status='REMOVED',updated_at=? WHERE id=?").run("2026-08-22T14:00:00.000Z",p.id);assert.equal(f.db.prepare("SELECT status FROM creative_placements WHERE id=?").get(p.id).status,"REMOVED");assert.throws(()=>f.db.prepare("DELETE FROM creative_placements WHERE id=?").run(p.id));});
 await t.test("schema has no asset website campaign or performance fields",()=>{const f=fixture(),columns=f.db.prepare("SELECT name FROM pragma_table_info('creative_placements')").all().map(x=>x.name);for(const forbidden of ["content_asset_id","website_project_id","page_id","section_id","campaign_id","ad_id","impressions","clicks","conversions","ctr","cpa","roas","score","ranking"])assert.equal(columns.includes(forbidden),false);});
 await t.test("queries are indexed metrics are safe and dependencies remain lightweight",()=>{const f=fixture();create(f);within(()=>f.service.list(ITEM,{},actor));assert.match(JSON.stringify(f.db.prepare("EXPLAIN QUERY PLAN SELECT * FROM creative_placements WHERE workspace_id=? AND content_item_id=? ORDER BY created_at DESC,id DESC LIMIT ?").all(W,ITEM,20)),/idx_creative_placements_content_history/);const measured=JSON.stringify(f.metrics.recent());assert.match(measured,/creative_placement\.create/);assert.equal(measured.includes(ITEM),false);const source=["../app/repositories/creative-placement-repository.mjs","../app/services/creative-placement-service.mjs","../app/routes/creative-placements.mjs"].map(p=>readFileSync(new URL(p,import.meta.url),"utf8").toLowerCase()).join("\n");for(const forbidden of ["openai","content_assets","performance_observations","campaigns","website_projects","worker","queue","redis","billing","fetch("])assert.equal(source.includes(forbidden),false);assert.equal(f.db.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(f.db.pragma("foreign_key_check"),[]);});
});
