import assert from "node:assert/strict";
import test from "node:test";
import {readFileSync} from "node:fs";
import Database from "better-sqlite3";
import {runMigrations} from "../db/migrate.mjs";
import {migration045ContentGenerations} from "../db/migrations/045_content_generations.mjs";
import {migration047ContentItems} from "../db/migrations/047_content_items.mjs";
import {migration048ContentItemSourceIdentity} from "../db/migrations/048_content_item_source_identity.mjs";
import {migration049ContentAssets} from "../db/migrations/049_content_assets.mjs";
import {migration050RealAssetUpload} from "../db/migrations/050_real_asset_upload.mjs";
import {migration051UploadedCreativeLinkage} from "../db/migrations/051_uploaded_creative_linkage.mjs";
import {migration052CreativePlacements} from "../db/migrations/052_creative_placements.mjs";
import {migration053CreativeIntents} from "../db/migrations/053_creative_intents.mjs";
import {migration054DistributionContexts} from "../db/migrations/054_distribution_contexts.mjs";
import {channelRegistry,createChannelRegistry} from "../app/distribution/channel-registry.mjs";
import {runWithWorkspace} from "../app/tenant-context.mjs";
import {createCreativePlacementRepository} from "../app/repositories/creative-placement-repository.mjs";
import {createDistributionContextRepository} from "../app/repositories/distribution-context-repository.mjs";
import {createDistributionContextService} from "../app/services/distribution-context-service.mjs";
import {createOperationMetrics} from "../app/observability/operation-metrics.mjs";

const AT="2026-08-23T10:00:00.000Z",W="workspace",U="user",P="placement",SHA="a".repeat(64),actor={userId:U,role:"member"};
const prior=[migration045ContentGenerations,migration047ContentItems,migration048ContentItemSourceIdentity,migration049ContentAssets,migration050RealAssetUpload,migration051UploadedCreativeLinkage,migration052CreativePlacements,migration053CreativeIntents];
function base(){const db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);");runMigrations(db,prior);db.exec("INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('workspace','active');INSERT INTO workspaces VALUES('other','active');INSERT INTO workspace_memberships VALUES('membership','workspace','user','member','active');");db.prepare("INSERT INTO content_items(id,workspace_id,created_by_user_id,source_type,source_generation_id,source_variant_index,media_type,contract_id,contract_version,placement_id,placement_version,context_version_id,primary_asset_id,title,content_json,revision,operation_kind,idempotency_key,request_hash,created_at,updated_at,intent_id)VALUES('item',?,?, 'MANUAL_TEXT',NULL,NULL,'TEXT','social_post',1,'instagram.feed.text',1,NULL,NULL,'Creative','{}',1,'content_item.manual','item-key',?,?,?,NULL)").run(W,U,SHA,AT,AT);db.prepare("INSERT INTO creative_placements(id,workspace_id,content_item_id,placement_kind,channel,status,external_reference_id,created_by_user_id,operation_kind,idempotency_key,request_hash,created_at,updated_at)VALUES(?,?, 'item','SOCIAL','instagram','ACTIVE',NULL,?,'creative_placement.create','placement-key',?,?,?)").run(P,W,U,SHA,AT,AT);return db;}
function fixture(){const db=base();runMigrations(db,[migration054DistributionContexts]);let tick=Date.parse(AT);const metrics=createOperationMetrics(),service=createDistributionContextService({repository:createDistributionContextRepository(db),placementRepository:createCreativePlacementRepository(db),registry:channelRegistry,operationMetrics:metrics,now:()=>new Date(tick+=1000)});return{db,service,metrics};}
const within=(fn,workspace=W)=>runWithWorkspace(workspace,fn),input=(overrides={})=>({channelId:"social",channelVersion:1,provider:"instagram",acquisitionMode:"ORGANIC",destinationReference:"https://example.com/landing",trackingContractVersion:1,...overrides}),create=(f,key="key",value=input(),placement=P,who=actor)=>within(()=>f.service.create(placement,value,who,key));

test("Distribution Foundation v1",async t=>{
 await t.test("registry is versioned, bounded, and separates family from provider",()=>{assert.deepEqual(channelRegistry.list().map(x=>x.channelFamily),["SEARCH","SOCIAL","MARKETPLACE","CLASSIFIED","MESSAGING","REFERRAL","DIRECT","OWNED_WEB"]);assert.equal(channelRegistry.get("search",1).allowedAcquisitionModes.includes("ORGANIC"),true);assert.equal(Object.hasOwn(channelRegistry.get("social",1),"provider"),false);assert.throws(()=>createChannelRegistry([{channelId:"x",channelVersion:1,channelFamily:"VIDEO",allowedAcquisitionModes:["PAID"]}]));assert.throws(()=>createChannelRegistry([channelRegistry.get("search",1),channelRegistry.get("search",1)]));});
 await t.test("migration 054 adds exactly one table and preserves existing schemas",()=>{const db=base(),before=db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();runMigrations(db,[migration054DistributionContexts]);runMigrations(db,[migration054DistributionContexts]);assert.deepEqual(db.prepare("SELECT count(*) count,max(version) max FROM schema_migrations WHERE version=54").get(),{count:1,max:54});assert.deepEqual(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT IN("+before.map(()=>"?").join(",")+")").all(...before.map(x=>x.name)),[{name:"distribution_contexts"}]);for(const row of before)assert.equal(db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(row.name).sql,row.sql);});
 await t.test("creates immutable distribution identity linked to placement",()=>{const f=fixture(),result=create(f);assert.equal(result.context.creativePlacementId,P);assert.equal(result.context.channelFamily,"SOCIAL");assert.equal(result.context.provider,"instagram");assert.equal(result.context.acquisitionMode,"ORGANIC");});
 await t.test("registry compatibility and strict request are enforced",()=>{const f=fixture();assert.throws(()=>create(f,"bad-mode",input({channelId:"direct",acquisitionMode:"PAID"})),e=>e.code==="DISTRIBUTION_CONTEXT_INVALID");assert.throws(()=>create(f,"missing-channel",input({channelId:"video"})),e=>e.code==="DISTRIBUTION_CHANNEL_NOT_FOUND");for(const field of ["workspaceId","userId","sessionId","customerId","campaignId","utmSource","metrics"]){assert.throws(()=>create(f,field,{...input(),[field]:"x"}),e=>e.code==="DISTRIBUTION_CONTEXT_INVALID");}assert.throws(()=>create(f,"utm",input({destinationReference:"https://example.com/?utm_source=x"})),e=>e.code==="DISTRIBUTION_CONTEXT_INVALID");});
 await t.test("idempotent replay reuses and changed request conflicts",()=>{const f=fixture(),first=create(f),replay=create(f);assert.equal(first.context.id,replay.context.id);assert.equal(replay.reusedResult,true);assert.throws(()=>create(f,"key",input({provider:"other"})),e=>e.code==="DISTRIBUTION_CONTEXT_IDEMPOTENCY_CONFLICT");});
 await t.test("tenant isolation and foreign placement IDs are hidden",()=>{const f=fixture();assert.throws(()=>within(()=>f.service.list(P,{},actor),"other"),e=>e.code==="CREATIVE_PLACEMENT_NOT_FOUND");assert.throws(()=>create(f,"missing",input(),"missing"),e=>e.code==="CREATIVE_PLACEMENT_NOT_FOUND");});
 await t.test("owner admin member are allowed and unknown role is denied",()=>{for(const role of ["owner","admin","member"]){const f=fixture();assert.ok(create(f,role,input(),P,{userId:U,role}).context.id);}const f=fixture();assert.throws(()=>create(f,"viewer",input(),P,{userId:U,role:"viewer"}),e=>e.code==="DISTRIBUTION_CONTEXT_PERMISSION_DENIED");});
 await t.test("context update and delete are rejected",()=>{const f=fixture(),context=create(f).context;assert.throws(()=>f.db.prepare("UPDATE distribution_contexts SET provider='google' WHERE id=?").run(context.id));assert.throws(()=>f.db.prepare("DELETE FROM distribution_contexts WHERE id=?").run(context.id));});
 await t.test("history is tenant scoped and keyset paginated",()=>{const f=fixture();for(let i=0;i<3;i++)create(f,`key-${i}`,input({provider:`provider-${i}`}));const first=within(()=>f.service.list(P,{limit:2},actor)),second=within(()=>f.service.list(P,{limit:2,cursor:first.nextCursor},actor));assert.equal(first.contexts.length,2);assert.equal(second.contexts.length,1);assert.equal(new Set([...first.contexts,...second.contexts].map(x=>x.id)).size,3);});
 await t.test("schema and sources have no touch analytics performance connector or runtime coupling",()=>{const f=fixture(),columns=f.db.prepare("SELECT name FROM pragma_table_info('distribution_contexts')").all().map(x=>x.name);for(const forbidden of ["session_id","user_id","customer_id","campaign_id","utm_source","metrics_json","performance_score","clicks","conversions"])assert.equal(columns.includes(forbidden),false);const source=["../app/distribution/channel-registry.mjs","../app/repositories/distribution-context-repository.mjs","../app/services/distribution-context-service.mjs","../app/routes/distribution-contexts.mjs"].map(p=>readFileSync(new URL(p,import.meta.url),"utf8").toLowerCase()).join("\n");for(const forbidden of ["google-analytics","ga4","instagram-connector","sms-connector","crm","performance_observations","distribution_touches","fetch(","worker","queue","redis"])assert.equal(source.includes(forbidden),false);assert.equal(f.db.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(f.db.pragma("foreign_key_check"),[]);});
});
