import assert from "node:assert/strict";
import test from "node:test";
import { copyFileSync, mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import Database from "better-sqlite3";
import express from "express";
import { runMigrations } from "../db/migrate.mjs";
import { migration064CustomDomainPublishing } from "../db/migrations/064_custom_domain_publishing.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createDomainPublishingRepository } from "../app/repositories/domain-publishing-repository.mjs";
import { createDomainPublishingService } from "../app/services/domain-publishing-service.mjs";
import { createDeterministicDnsVerifier, createDeterministicTlsProvider, createUnavailableTlsProvider } from "../app/publishing/domain-providers.mjs";
import { createDeterministicPublicMediaProvider, createPublicStaticProvider } from "../app/publishing/public-static-provider.mjs";
import { createDomainPublishingRouter } from "../app/routes/domain-publishing.mjs";

const owner = (workspaceId = "domain-w") => ({ userId: "domain-user", role: "owner", workspaceId }), admin = (workspaceId = "domain-w") => ({ ...owner(workspaceId), role: "admin" });
const within = (workspaceId, operation) => runWithWorkspace(workspaceId, operation);
function fixture({ tls = createDeterministicTlsProvider(), base = "https://pages.loadder.test" } = {}) {
  const directory = mkdtempSync(join(tmpdir(), "loadder-domain-")), path = join(directory, "domain.sqlite"); copyFileSync(new URL("../db/loadder.sqlite", import.meta.url), path);
  const db = new Database(path); db.pragma("foreign_keys=ON"); runMigrations(db, [migration064CustomDomainPublishing]);
  db.exec("INSERT INTO users(id,mobile,name,status,created_at,updated_at)VALUES('domain-user','09000000001','Domain User','active','2026-08-23T20:00:00.000Z','2026-08-23T20:00:00.000Z');INSERT INTO workspaces(id,name,slug,status,created_at,updated_at)VALUES('domain-w','Domain W','domain-w','active','2026-08-23T20:00:00.000Z','2026-08-23T20:00:00.000Z'),('domain-x','Domain X','domain-x','active','2026-08-23T20:00:00.000Z','2026-08-23T20:00:00.000Z');INSERT INTO workspace_memberships(id,workspace_id,user_id,role,status,created_at,updated_at)VALUES('domain-mw','domain-w','domain-user','owner','active','2026-08-23T20:00:00.000Z','2026-08-23T20:00:00.000Z'),('domain-mx','domain-x','domain-user','owner','active','2026-08-23T20:00:00.000Z','2026-08-23T20:00:00.000Z');");
  let randomByte = 7; const records = new Map(), repository = createDomainPublishingRepository(db), staticProvider = createPublicStaticProvider({ nodeEnv: "test", publicBaseUrl: base }), service = createDomainPublishingService({ repository, dnsVerifier: createDeterministicDnsVerifier(records), tlsProvider: tls, staticProvider, mediaProvider: createDeterministicPublicMediaProvider({ publicBaseUrl: base }), now: () => new Date("2026-08-23T20:00:00.000Z"), randomBytes: () => Buffer.alloc(32, randomByte++) });
  return { directory, db, records, repository, staticProvider, service, close() { db.close(); rmSync(directory, { recursive: true, force: true }); } };
}
function catalog(f) { f.db.exec("INSERT INTO commerce_catalogs(id,workspace_id,created_by_user_id,name,slug,archetype,archetype_version,currency,status,revision,idempotency_key,request_hash,created_at,updated_at)VALUES('domain-catalog','domain-w','domain-user','فروشگاه','shop','GENERAL_COMMERCE',1,'IRR','ACTIVE',1,'catalog-key','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','2026-08-23T20:00:00.000Z','2026-08-23T20:00:00.000Z');INSERT INTO commerce_products(id,workspace_id,catalog_id,created_by_user_id,name,slug,short_description,description,status,base_price,currency,availability_status,revision,idempotency_key,request_hash,created_at,updated_at)VALUES('domain-product','domain-w','domain-catalog','domain-user','محصول','old-slug','محصول','محصول','ACTIVE',1000,'IRR','IN_STOCK',1,'product-key','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','2026-08-23T20:00:00.000Z','2026-08-23T20:00:00.000Z');"); }
async function activeDomain(f, hostname = "shop.example.com") { const added = within("domain-w", () => f.service.addDomain({ hostname }, owner(), `add-${hostname}`)).domain; f.records.set(added.verificationRecordName, [added.verificationToken]); const verified = await within("domain-w", () => f.service.verify(added.id, owner())); assert.equal(verified.domain.status, "ACTIVE"); return verified.domain; }

test("Custom Domain and Production Publishing v1", async (t) => {
  await t.test("migration 064 adds four bounded tables and is idempotent", () => { const f = fixture(); try { runMigrations(f.db, [migration064CustomDomainPublishing]); assert.deepEqual(f.db.prepare("SELECT COUNT(*) count,MAX(version) max FROM schema_migrations").get(), { count: 64, max: 64 }); assert.equal(f.db.prepare("SELECT COUNT(*) count FROM sqlite_master WHERE type='table' AND name IN('custom_domains','public_domain_bindings','public_binding_activations','published_asset_derivatives')").get().count, 4); } finally { f.close(); } });
  await t.test("hostname normalization accepts IDNA and rejects URL path IP wildcard local and port", () => { const f = fixture(); try { const valid = within("domain-w", () => f.service.addDomain({ hostname: "WWW.Example.COM." }, owner(), "valid")).domain; assert.equal(valid.hostname, "www.example.com"); for (const hostname of ["https://example.com", "example.com/path", "127.0.0.1", "*.example.com", "localhost", "host.internal", "example.com:443", "user@example.com"]) assert.throws(() => within("domain-w", () => f.service.addDomain({ hostname }, owner(), hostname)), /DOMAIN_HOSTNAME_INVALID/); } finally { f.close(); } });
  await t.test("duplicate cross-workspace claim and cross-tenant reads fail without owner disclosure", () => { const f = fixture(); try { const domain = within("domain-w", () => f.service.addDomain({ hostname: "example.com" }, owner(), "w")).domain; assert.throws(() => within("domain-x", () => f.service.addDomain({ hostname: "example.com" }, owner("domain-x"), "x")), (error) => error.code === "DOMAIN_ALREADY_CLAIMED" && error.status === 409); assert.throws(() => within("domain-x", () => f.service.createBinding(domain.id, { targetType: "STOREFRONT", targetId: "x", basePath: "/", canonical: true }, owner("domain-x"))), (error) => error.code === "DOMAIN_NOT_FOUND" && error.status === 404); } finally { f.close(); } });
  await t.test("DNS verification is exact and TLS activation remains fail closed when unavailable", async () => { const f = fixture({ tls: createUnavailableTlsProvider() }); try { const domain = within("domain-w", () => f.service.addDomain({ hostname: "verify.example.com" }, owner(), "verify")).domain; f.records.set(domain.verificationRecordName, ["wrong"]); assert.equal((await within("domain-w", () => f.service.verify(domain.id, owner()))).verified, false); f.records.set(domain.verificationRecordName, [domain.verificationToken]); const result = await within("domain-w", () => f.service.verify(domain.id, owner())); assert.equal(result.verified, true); assert.equal(result.domain.status, "VERIFIED"); assert.equal(result.domain.tlsStatus, "PENDING"); } finally { f.close(); } });
  await t.test("owner and admin may manage domains while member is rejected", async () => { const f = fixture(); try { const domain = await activeDomain(f); assert.equal(within("domain-w", () => f.service.list(admin())).domains.length, 1); assert.throws(() => within("domain-w", () => f.service.addDomain({ hostname: "member.example.com" }, { ...owner(), role: "member" }, "member")), /DOMAIN_PERMISSION_DENIED/); await within("domain-w", () => f.service.disable(domain.id, admin())); } finally { f.close(); } });
  await t.test("verification token rotation revokes active routing and requires fresh proof", async () => { const f = fixture(); try { catalog(f); const domain = await activeDomain(f), binding = within("domain-w", () => f.service.createBinding(domain.id, { targetType: "STOREFRONT", targetId: "domain-catalog", basePath: "/", canonical: true }, owner())).binding; within("domain-w", () => f.service.publish(binding.id, { sourcePublicationId: "domain-catalog" }, owner())); const rotated = within("domain-w", () => f.service.rotateVerification(domain.id, owner())).domain; assert.notEqual(rotated.verificationToken, domain.verificationToken); assert.equal(rotated.status, "PENDING_VERIFICATION"); assert.equal(f.service.resolve(domain.hostname, "/"), null); assert.equal((await within("domain-w", () => f.service.verify(domain.id, owner()))).verified, false); } finally { f.close(); } });
  await t.test("storefront publish is deterministic SEO-safe stable and host-poisoning resistant", async () => { const f = fixture(); try { catalog(f); const domain = await activeDomain(f), binding = within("domain-w", () => f.service.createBinding(domain.id, { targetType: "STOREFRONT", targetId: "domain-catalog", basePath: "/shop", canonical: true }, owner())).binding, first = within("domain-w", () => f.service.publish(binding.id, { sourcePublicationId: "domain-catalog" }, owner())); assert.equal(first.publicUrl, "https://shop.example.com/shop/"); assert.equal(within("domain-w", () => f.repository.productUrl("domain-catalog", "domain-product")), "https://shop.example.com/shop/products/domain-product"); const product = f.service.resolve("shop.example.com", "/shop/products/domain-product"); assert.ok(product.body.includes("https://shop.example.com/shop/products/domain-product")); assert.equal(product.body.includes("evil.example"), false); assert.match(f.service.resolve("shop.example.com", "/shop/sitemap.xml").body, /domain-product/); assert.match(f.service.resolve("shop.example.com", "/shop/robots.txt").body, /Sitemap: https:\/\/shop\.example\.com/); assert.equal(f.service.resolve("evil.example", "/shop/"), null); assert.equal(f.service.resolve("shop.example.com:443", "/shop/"), null); assert.equal(f.service.resolve("shop.example.com", "/shop/%2e%2e/secret"), null); assert.equal(f.service.resolve("shop.example.com", "/shop/../secret"), null); const second = within("domain-w", () => f.service.publish(binding.id, { sourcePublicationId: "domain-catalog" }, owner())); assert.equal(second.activation.artifactChecksum, first.activation.artifactChecksum); assert.notEqual(second.activation.id, first.activation.id); const rollback = within("domain-w", () => f.service.rollback(binding.id, { activationId: first.activation.id }, owner())); assert.equal(rollback.activation.artifactRoot, first.activation.artifactRoot); assert.equal(within("domain-w", () => f.service.history(binding.id, owner())).activations.length, 3); } finally { f.close(); } });
  await t.test("publish failure before activation preserves the prior pointer", async () => { const f = fixture(); try { catalog(f); const domain = await activeDomain(f), binding = within("domain-w", () => f.service.createBinding(domain.id, { targetType: "STOREFRONT", targetId: "domain-catalog", basePath: "/", canonical: true }, owner())).binding, first = within("domain-w", () => f.service.publish(binding.id, { sourcePublicationId: "domain-catalog" }, owner())); assert.throws(() => within("domain-w", () => f.service.publish(binding.id, { sourcePublicationId: "missing" }, owner())), /DOMAIN_PUBLICATION_NOT_FOUND/); assert.equal(within("domain-w", () => f.repository.binding(binding.id)).currentActivationId, first.activation.id); } finally { f.close(); } });
  await t.test("path conflicts disable and dangling takeover protection are enforced", async () => { const f = fixture(); try { const domain = await activeDomain(f); within("domain-w", () => f.service.createBinding(domain.id, { targetType: "STOREFRONT", targetId: "one", basePath: "/shop", canonical: true }, owner())); assert.throws(() => within("domain-w", () => f.service.createBinding(domain.id, { targetType: "LANDING", targetId: "two", basePath: "/shop/product", canonical: false }, owner())), /DOMAIN_PATH_CONFLICT/); await within("domain-w", () => f.service.disable(domain.id, owner())); assert.equal(f.service.resolve(domain.hostname, "/shop"), null); assert.throws(() => within("domain-x", () => f.service.addDomain({ hostname: domain.hostname }, owner("domain-x"), "takeover")), /DOMAIN_ALREADY_CLAIMED/); } finally { f.close(); } });
  await t.test("READY public derivative is deduplicated and private storage key is never exposed", () => { const f = fixture(); try { const sha = "c".repeat(64); f.db.prepare("INSERT INTO content_assets(id,workspace_id,created_by_user_id,media_type,declared_mime_type,declared_byte_size,declared_sha256,mime_type,byte_size,content_sha256,width,height,duration_ms,original_filename,storage_provider,storage_object_key,status,failure_code,operation_kind,idempotency_key,request_hash,upload_expires_at,ready_at,created_at,updated_at,canonical_storage_object_key,canonical_mime_type,canonical_byte_size,canonical_sha256,optimization_policy_version,optimization_outcome,storage_backend_kind)VALUES('domain-asset','domain-w','domain-user','IMAGE','image/webp',10,?,'image/webp',10,?,10,10,NULL,'image.webp','TEST_MEMORY','workspaces/domain-w/content-assets/domain-asset/original','READY',NULL,'content_asset.intent','asset-key',?,'2026-08-23T20:10:00.000Z','2026-08-23T20:01:00.000Z','2026-08-23T20:00:00.000Z','2026-08-23T20:01:00.000Z',NULL,NULL,NULL,NULL,NULL,'ORIGINAL_KEPT','TEST_MEMORY')").run(sha, sha, "d".repeat(64)); const first = within("domain-w", () => f.service.publishAsset("domain-asset", owner())).derivative, second = within("domain-w", () => f.service.publishAsset("domain-asset", owner())).derivative; assert.equal(first.id, second.id); assert.match(first.publicUrl, /^https:\/\/pages\.loadder\.test\/public\/media\//); assert.equal(JSON.stringify(first).includes("workspaces/domain-w"), false); assert.equal(f.db.prepare("SELECT COUNT(*) count FROM published_asset_derivatives").get().count, 1); } finally { f.close(); } });
  await t.test("database guards immutable history and remains valid", async () => { const f = fixture(); try { catalog(f); const domain = await activeDomain(f), binding = within("domain-w", () => f.service.createBinding(domain.id, { targetType: "STOREFRONT", targetId: "domain-catalog", basePath: "/", canonical: true }, owner())).binding, publication = within("domain-w", () => f.service.publish(binding.id, { sourcePublicationId: "domain-catalog" }, owner())).activation; assert.throws(() => f.db.prepare("UPDATE public_binding_activations SET canonical_url='https://evil.example' WHERE id=?").run(publication.id)); assert.equal(f.db.pragma("integrity_check", { simple: true }), "ok"); assert.deepEqual(f.db.pragma("foreign_key_check"), []); } finally { f.close(); } });
  await t.test("domain mutation endpoint is workspace and IP rate limited with bounded response", async () => { const calls = [], app = express(); app.use(express.json()); app.use((request, _response, next) => { request.user = { id: "u" }; request.membership = { role: "owner" }; request.workspace = { id: "w" }; next(); }); app.use("/api", createDomainPublishingRouter({ service: { readiness: () => ({}), addDomain(input) { calls.push(input); return { domain: input }; } } })); const server = app.listen(0, "127.0.0.1"); await new Promise((resolve) => server.once("listening", resolve)); try { const url = `http://127.0.0.1:${server.address().port}/api/domains`; for (let index = 0; index < 20; index++) assert.equal((await fetch(url, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": String(index) }, body: JSON.stringify({ hostname: `x${index}.example.com` }) })).status, 201); const limited = await fetch(url, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": "last" }, body: JSON.stringify({ hostname: "last.example.com" }) }); assert.equal(limited.status, 429); assert.deepEqual(await limited.json(), { success: false, code: "DOMAIN_RATE_LIMITED", message: "Domain publishing request limit exceeded." }); assert.equal(calls.length, 20); } finally { await new Promise((resolve) => server.close(resolve)); } });
});
