import assert from "node:assert/strict";
import test from "node:test";
import Database from "better-sqlite3";
import { runMigrations } from "../db/migrate.mjs";
import { migration059CommerceCatalogFoundation } from "../db/migrations/059_commerce_catalog_foundation.mjs";
import { migration060CartCheckoutFoundation } from "../db/migrations/060_cart_checkout_foundation.mjs";
import { migration061PaymentOrderLifecycle } from "../db/migrations/061_payment_order_lifecycle.mjs";
import { migration062InventoryFulfillmentFoundation } from "../db/migrations/062_inventory_fulfillment_foundation.mjs";
import { createCartCheckoutRepository } from "../app/repositories/cart-checkout-repository.mjs";
import { createCartCheckoutService } from "../app/services/cart-checkout-service.mjs";
import { commerceShippingRegistry } from "../app/commerce/commerce-shipping-registry.mjs";
import { createPaymentOrderRepository } from "../app/repositories/payment-order-repository.mjs";
import { createPaymentOrderService } from "../app/services/payment-order-service.mjs";
import { createDeterministicTestPaymentProvider } from "../app/payments/payment-providers.mjs";
import { createInventoryFulfillmentRepository } from "../app/repositories/inventory-fulfillment-repository.mjs";
import { createInventoryFulfillmentService } from "../app/services/inventory-fulfillment-service.mjs";
import { createTestShippingProvider, createUnavailableShippingProvider } from "../app/shipping/shipping-providers.mjs";

const owner = { userId: "user", role: "owner", workspaceId: "w" };
function fixture(shipping = createTestShippingProvider()) {
  const db = new Database(":memory:"); db.pragma("foreign_keys=ON");
  db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,role TEXT,status TEXT);CREATE TABLE content_assets(id TEXT PRIMARY KEY,workspace_id TEXT,status TEXT,media_type TEXT);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('w','active'),('x','active');INSERT INTO workspace_memberships VALUES('m','w','user','owner','active');");
  runMigrations(db, [migration059CommerceCatalogFoundation, migration060CartCheckoutFoundation, migration061PaymentOrderLifecycle, migration062InventoryFulfillmentFoundation]);
  db.exec("INSERT INTO commerce_catalogs VALUES('cat','w','user','فروشگاه','store','GENERAL_COMMERCE',1,'IRR','ACTIVE',1,'k',lower(hex(randomblob(32))),'2026-01-01','2026-01-01');INSERT INTO commerce_products(id,workspace_id,catalog_id,created_by_user_id,name,slug,short_description,description,status,base_price,currency,availability_status,revision,idempotency_key,request_hash,created_at,updated_at)VALUES('p','w','cat','user','کالا','item','کالا','کالا','ACTIVE',100,'IRR','IN_STOCK',1,'p',lower(hex(randomblob(32))),'2026-01-01','2026-01-01');");
  const repository = createInventoryFulfillmentRepository(db), fulfillment = createInventoryFulfillmentService({ repository, provider: shipping, now: () => new Date("2026-08-23T12:00:00.000Z") });
  const cart = createCartCheckoutService({ repository: createCartCheckoutRepository(db), shippingRegistry: commerceShippingRegistry, now: () => new Date("2026-08-23T12:00:00.000Z") });
  const payment = createPaymentOrderService({ repository: createPaymentOrderRepository(db), provider: createDeterministicTestPaymentProvider(), callbackBaseUrl: "https://loadder.test", postPaymentProcessor: fulfillment, now: () => new Date("2026-08-23T12:00:00.000Z") });
  return { db, repository, fulfillment, cart, payment };
}
function buy(f, quantity = 1, physical = true) { const c = f.cart.createCart({ catalogId: "cat", customerScopeKey: null }); f.cart.addItem(c.cartToken, { revision: c.cart.revision, productId: "p", variantId: null, quantity }); const session = f.cart.createCheckout(c.cartToken, { fulfillmentMode: physical ? "PHYSICAL_DELIVERY" : "DIGITAL_OR_SERVICE" }, `co-${Math.random()}`).checkout; const ready = f.cart.updateCheckout(c.cartToken, session.id, { revision: session.revision, fulfillmentMode: physical ? "PHYSICAL_DELIVERY" : "DIGITAL_OR_SERVICE", shippingMethod: physical ? "STANDARD" : "NONE", contactName: "خریدار", contactMobile: "09121234567", contactEmail: null, recipientName: physical ? "گیرنده" : null, recipientMobile: physical ? "09121234567" : null, province: physical ? "تهران" : null, city: physical ? "تهران" : null, postalAddress: physical ? "نشانی معتبر" : null, postalCode: physical ? "1234567890" : null }).checkout; const pending = f.cart.confirm(c.cartToken, ready.id, { revision: ready.revision }, `confirm-${Math.random()}`).pendingOrder; const attempt = f.payment.initiate(c.cartToken, { orderReference: pending.publicReference }, `pay-${Math.random()}`).attempt; return f.payment.returnSignal({ attempt: attempt.paymentAttemptId }); }

test("Inventory, Fulfillment and Shipping Foundation v1", async (t) => {
  await t.test("migration 062 adds exactly four tables and is idempotent", () => { const f = fixture(); runMigrations(f.db, [migration062InventoryFulfillmentFoundation]); assert.equal(f.db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE type='table' AND name IN('commerce_inventory_items','commerce_inventory_reservations','commerce_fulfillments','commerce_shipments')").get().n, 4); assert.deepEqual(f.db.prepare("SELECT COUNT(*) c,MAX(version) m FROM schema_migrations").get(), { c: 4, m: 62 }); });
  await t.test("tracked inventory uses integer guarded stock and optimistic revision", () => { const f = fixture(), a = f.fulfillment.setInventory("p", { variantId: null, trackingMode: "TRACKED", stockOnHand: 3, lowStockThreshold: 1, revision: 0 }, owner).inventory; assert.equal(a.available, 3); assert.equal(f.fulfillment.setInventory("p", { variantId: null, trackingMode: "TRACKED", stockOnHand: 2, lowStockThreshold: 1, revision: 1 }, owner).inventory.revision, 2); assert.throws(() => f.fulfillment.setInventory("p", { variantId: null, trackingMode: "TRACKED", stockOnHand: -1, lowStockThreshold: null, revision: 2 }, owner), /INVENTORY_INVALID/); });
  await t.test("cross-tenant inventory and member mutation fail closed", () => { const f = fixture(); assert.throws(() => f.fulfillment.setInventory("p", { variantId: null, trackingMode: "TRACKED", stockOnHand: 1, lowStockThreshold: null, revision: 0 }, { ...owner, workspaceId: "x" }), /INVENTORY_ITEM_NOT_FOUND/); assert.throws(() => f.fulfillment.listInventory({ ...owner, role: "member" }), /SHIPPING_PERMISSION_DENIED/); });
  await t.test("verified payment commits stock and creates one fulfillment exactly once", () => { const f = fixture(); f.fulfillment.setInventory("p", { variantId: null, trackingMode: "TRACKED", stockOnHand: 2, lowStockThreshold: null, revision: 0 }, owner); const paid = buy(f, 1); assert.equal(paid.fulfillment.processingStatus, "INVENTORY_COMMITTED"); assert.equal(f.db.prepare("SELECT stock_on_hand FROM commerce_inventory_items").get().stock_on_hand, 1); f.fulfillment.processOrder(paid.order.id, owner); assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_fulfillments").get().n, 1); assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_inventory_reservations").get().n, 1); });
  await t.test("last unit contention never creates negative stock", () => { const f = fixture(); f.fulfillment.setInventory("p", { variantId: null, trackingMode: "TRACKED", stockOnHand: 1, lowStockThreshold: null, revision: 0 }, owner); const first = buy(f), second = buy(f); assert.equal(first.fulfillment.processingStatus, "INVENTORY_COMMITTED"); assert.equal(second.fulfillment.processingStatus, "INVENTORY_EXCEPTION"); assert.equal(second.fulfillment.status, "BLOCKED"); assert.equal(f.db.prepare("SELECT stock_on_hand FROM commerce_inventory_items").get().stock_on_hand, 0); });
  await t.test("inventory exception preserves verified financial truth", () => { const f = fixture(); f.fulfillment.setInventory("p", { variantId: null, trackingMode: "TRACKED", stockOnHand: 0, lowStockThreshold: null, revision: 0 }, owner); const paid = buy(f); assert.equal(paid.order.status, "CONFIRMED"); assert.equal(paid.fulfillment.processingStatus, "INVENTORY_EXCEPTION"); assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_verified_payments").get().n, 1); });
  await t.test("untracked goods do not block fulfillment", () => { const f = fixture(); f.fulfillment.setInventory("p", { variantId: null, trackingMode: "UNTRACKED", stockOnHand: 0, lowStockThreshold: null, revision: 0 }, owner); assert.equal(buy(f, 2).fulfillment.processingStatus, "INVENTORY_COMMITTED"); });
  await t.test("manual physical shipment progresses shipped to delivered", () => { const f = fixture(); const paid = buy(f), shipment = f.fulfillment.createShipment(paid.fulfillment.id, { provider: "MANUAL", trackingNumber: "TRK-123" }, owner, "ship").shipment; assert.equal(shipment.status, "CREATED"); const shipped = f.fulfillment.transitionShipment(shipment.id, { status: "IN_TRANSIT", revision: 1 }, owner).shipment; assert.equal(shipped.status, "IN_TRANSIT"); assert.equal(f.fulfillment.transitionShipment(shipment.id, { status: "DELIVERED", revision: 2 }, owner).shipment.status, "DELIVERED"); assert.equal(f.repository.fulfillment(paid.fulfillment.id).status, "COMPLETED"); });
  await t.test("test adapter is deterministic and shipment creation idempotent", () => { const f = fixture(), paid = buy(f), a = f.fulfillment.createShipment(paid.fulfillment.id, { provider: "TEST", trackingNumber: null }, owner, "same"), b = f.fulfillment.createShipment(paid.fulfillment.id, { provider: "TEST", trackingNumber: null }, owner, "same"); assert.equal(a.shipment.id, b.shipment.id); assert.equal(b.reusedResult, true); assert.match(a.shipment.trackingNumber, /^TEST-/); });
  await t.test("production provider is unavailable while manual shipping remains enabled", () => { const f = fixture(createUnavailableShippingProvider()), readiness=f.fulfillment.readiness(); assert.equal(readiness.shippingManualEnabled, true); assert.equal(readiness.shippingProviderConfigured, false); assert.equal(readiness.shippingProviderEnabled, false); const paid = buy(f); assert.throws(() => f.fulfillment.createShipment(paid.fulfillment.id, { provider: "TEST", trackingNumber: null }, owner, "ship"), /SHIPPING_NOT_CONFIGURED/); });
  await t.test("malformed provider output fails closed without shipment", () => { const f = fixture(createTestShippingProvider({ mode: "invalid" })), paid = buy(f); assert.throws(() => f.fulfillment.createShipment(paid.fulfillment.id, { provider: "TEST", trackingNumber: null }, owner, "ship"), /SHIPPING_PROVIDER_INVALID_RESPONSE/); assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_shipments").get().n, 0); });
  await t.test("service orders cannot create physical shipment and schema has no refund or provider secrets", () => { const f = fixture(), paid = buy(f, 1, false); assert.throws(() => f.fulfillment.createShipment(paid.fulfillment.id, { provider: "MANUAL", trackingNumber: null }, owner, "ship"), /FULFILLMENT_INVALID_STATE/); const sql = f.db.prepare("SELECT group_concat(sql,' ') sql FROM sqlite_master WHERE name IN('commerce_inventory_items','commerce_inventory_reservations','commerce_fulfillments','commerce_shipments')").get().sql.toLowerCase(); for (const term of ["refund", "return_request", "provider_secret", "customer_id", "ga4"]) assert.equal(sql.includes(term), false); assert.equal(f.db.pragma("integrity_check", { simple: true }), "ok"); assert.deepEqual(f.db.pragma("foreign_key_check"), []); });
});
