import assert from"node:assert/strict";import test from"node:test";import Database from"better-sqlite3";import{runMigrations}from"../db/migrate.mjs";import{migration057LandingBuilderCore}from"../db/migrations/057_landing_builder_core.mjs";import{runWithWorkspace}from"../app/tenant-context.mjs";import{createLandingRepository}from"../app/repositories/landing-repository.mjs";import{createLandingService}from"../app/services/landing-service.mjs";import{landingComponentRegistry,createLandingComponentRegistry}from"../app/landing/landing-component-registry.mjs";import{createLandingPublisher}from"../app/landing/landing-publisher.mjs";import{createOperationMetrics}from"../app/observability/operation-metrics.mjs";
const W="workspace",U="user",AT="2026-08-23T15:00:00.000Z",actor={userId:U,role:"member"};
function base(){const db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,role TEXT,status TEXT);CREATE TABLE creative_intents(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE creative_placements(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE content_assets(id TEXT PRIMARY KEY,workspace_id TEXT,status TEXT);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('workspace','active');INSERT INTO workspaces VALUES('other','active');INSERT INTO workspace_memberships VALUES('m','workspace','user','member','active');INSERT INTO creative_intents VALUES('intent','workspace');INSERT INTO business_context_versions VALUES('context','workspace');INSERT INTO creative_placements VALUES('placement','workspace');INSERT INTO content_assets VALUES('asset','workspace','READY');`);return db;}
function fixture({nodeEnv="test"}={}){const db=base();runMigrations(db,[migration057LandingBuilderCore]);const repository=createLandingRepository(db),service=createLandingService({repository,intentRepository:{findById:id=>id==="intent"?{id}:null},contextRepository:{getVersion:id=>id==="context"?{id}:null},placementRepository:{findById:id=>id==="placement"?{id}:null},assetRepository:{findById:id=>id==="asset"?{id,status:"READY"}:null},componentRegistry:landingComponentRegistry,publisher:createLandingPublisher({nodeEnv}),operationMetrics:createOperationMetrics(),now:()=>new Date(AT)});return{db,repository,service};}const within=fn=>runWithWorkspace(W,fn),project=f=>within(()=>f.service.createProject({name:"Landing",slug:"landing",creativeIntentId:"intent"},actor,"project-key")).project;
const bp=()=>({goal:"Generate qualified action",offer:"A clear bounded offer",audienceSummary:"Primary audience",primaryCta:{label:"Start",type:"EXTERNAL_URL",target:"https://example.com"},secondaryCta:null,seo:{title:"Landing title",description:"Landing description"},socialPreview:{title:"Share title",description:"Share description",imageAssetId:null},sections:[{id:"hero",componentId:"HERO",version:1,variant:"CENTERED",props:{headline:"Trusted headline",body:"Bounded copy",primaryCta:{label:"Start",type:"EXTERNAL_URL",target:"https://example.com"}},contentBindings:[{role:"headline",creativePlacementId:"placement"}],assetBindings:[],trackingBindings:[{action:"CTA_CLICK"}]}],designTokens:{font:"brand",primaryColor:"#6633ff",secondaryColor:"#111122",backgroundColor:"#050510",foregroundColor:"#ffffff",mutedColor:"#aaaabb",radius:"lg",spacingDensity:"comfortable",buttonStyle:"solid",containerWidth:"standard"},tracking:{enabledActions:["LANDING_VISIT","CTA_CLICK"]},accessibility:{mainLabel:"Landing page"}});const createBlueprint=(f,p,key="bp-key",value=bp())=>within(()=>f.service.createBlueprint(p.id,{businessContextVersionId:"context",locale:"fa-IR",direction:"rtl",blueprint:value},actor,key)).blueprint;
test("Landing Builder Core v1",async t=>{
 await t.test("migration 057 adds exactly three tables and is idempotent",()=>{const db=base(),before=db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();runMigrations(db,[migration057LandingBuilderCore]);runMigrations(db,[migration057LandingBuilderCore]);assert.deepEqual(db.prepare("SELECT count(*) count,max(version) max FROM schema_migrations WHERE version=57").get(),{count:1,max:57});assert.deepEqual(db.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'landing_%' ORDER BY name`).all().map(x=>x.name),["landing_blueprint_versions","landing_projects","landing_publications"]);for(const x of before)assert.equal(db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(x.name).sql,x.sql);});
 await t.test("registry exposes twelve bounded trusted components",()=>{assert.equal(landingComponentRegistry.list().length,12);assert.throws(()=>createLandingComponentRegistry([landingComponentRegistry.list()[0],landingComponentRegistry.list()[0]]));});
 await t.test("creates tenant-scoped project idempotently",()=>{const f=fixture(),a=project(f),b=project(f);assert.equal(a.id,b.id);assert.equal(a.status,"DRAFT");assert.throws(()=>within(()=>f.service.createProject({name:"Changed",slug:"landing",creativeIntentId:"intent"},actor,"project-key")),e=>e.code==="LANDING_IDEMPOTENCY_CONFLICT");});
 await t.test("creates immutable monotonic blueprint versions",()=>{const f=fixture(),p=project(f),a=createBlueprint(f,p),b=createBlueprint(f,p,"bp-2");assert.deepEqual([a.version,b.version],[1,2]);assert.equal(b.supersedesBlueprintId,a.id);assert.throws(()=>f.db.prepare("UPDATE landing_blueprint_versions SET locale='en-US' WHERE id=?").run(a.id));assert.throws(()=>f.db.prepare("DELETE FROM landing_blueprint_versions WHERE id=?").run(a.id));});
 await t.test("rejects code HTML unknown components and unsafe CTAs",()=>{for(const mutate of [x=>x.sections[0].props.body="<script>alert(1)</script>",x=>x.sections[0].componentId="CUSTOM",x=>x.primaryCta.target="javascript:alert(1)"]){const f=fixture(),p=project(f),x=bp();mutate(x);assert.throws(()=>createBlueprint(f,p,crypto.randomUUID(),x),e=>e.code==="LANDING_BLUEPRINT_INVALID");}});
 await t.test("enforces Persian RTL and referenced lineage",()=>{const f=fixture(),p=project(f),x=bp();x.sections[0].contentBindings[0].creativePlacementId="foreign";assert.throws(()=>createBlueprint(f,p,"foreign",x),e=>e.code==="CREATIVE_PLACEMENT_NOT_FOUND");assert.throws(()=>within(()=>f.service.createBlueprint(p.id,{businessContextVersionId:"context",locale:"fa-IR",direction:"ltr",blueprint:bp()},actor,"ltr")),e=>e.code==="LANDING_INVALID");});
 await t.test("local publication is deterministic and records lineage",()=>{const f=fixture(),p=project(f),b=createBlueprint(f,p),a=within(()=>f.service.publish(p.id,{blueprintId:b.id},actor,"publish"));assert.equal(a.publication.status,"PUBLISHED");assert.match(a.publication.artifactChecksum,/^[0-9a-f]{64}$/);assert.equal(within(()=>f.repository.findProject(p.id)).currentPublishedBlueprintId,b.id);});
 await t.test("production publication fails closed and records no fake URL",()=>{const f=fixture({nodeEnv:"production"}),p=project(f),b=createBlueprint(f,p);assert.throws(()=>within(()=>f.service.publish(p.id,{blueprintId:b.id},actor,"publish")),e=>e.code==="LANDING_PUBLICATION_UNAVAILABLE");const row=f.db.prepare("SELECT * FROM landing_publications").get();assert.equal(row.status,"FAILED");assert.equal(row.host,null);assert.equal(row.path,null);});
 await t.test("tenant isolation hides foreign project and blueprint identifiers",()=>{const f=fixture(),p=project(f),b=createBlueprint(f,p);assert.throws(()=>runWithWorkspace("other",()=>f.service.getProject(p.id,actor)),e=>e.code==="LANDING_PROJECT_NOT_FOUND");assert.throws(()=>runWithWorkspace("other",()=>f.service.getBlueprint(b.id,actor)),e=>e.code==="LANDING_BLUEPRINT_NOT_FOUND");});
 await t.test("schema excludes campaigns metrics analytics PII and executable payloads",()=>{const f=fixture(),sql=f.db.prepare("SELECT group_concat(sql,' ') sql FROM sqlite_master WHERE name LIKE 'landing_%'").get().sql.toLowerCase();for(const word of ["campaign_id","ctr","cpa","roas","customer_id","lead_id","session_id","script_html","custom_css","ga4_id"])assert.equal(sql.includes(word),false);assert.equal(f.db.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(f.db.pragma("foreign_key_check"),[]);});
});
