import assert from"node:assert/strict";import test from"node:test";import{landingChannelStrategyRegistry,landingPresetRegistry,validateLandingMessageMatch}from"../app/landing/landing-conversion-registry.mjs";import{landingComponentRegistry}from"../app/landing/landing-component-registry.mjs";import{validateLandingBlueprint}from"../app/landing/landing-contracts.mjs";
const strategy=(goal="LEAD_GENERATION",channelStrategy="SEARCH_PAID")=>{const s=landingChannelStrategyRegistry.get(channelStrategy);return{presetId:goal,presetVersion:1,goal,channelStrategy,strategyVersion:1,audienceState:s.audienceState,conversionAction:goal==="APPOINTMENT_BOOKING"?"BOOKING":"CONTACT",messageMatchPriority:s.messageMatchPriority,proofPriority:s.proofPriority,frictionLevel:s.frictionLevel,recommendedSectionSequence:landingPresetRegistry.get(goal).recommendedSectionSequence}};
const cta={label:"دریافت مشاوره",type:"WHATSAPP",target:"https://wa.me/989120000000"},section=(id,componentId,props={heading:"عنوان",body:"متن"})=>({id,componentId,version:1,variant:componentId==="HERO"?"CENTERED":componentId==="TRUST"?"FACTS":"CENTERED",props,contentBindings:[],assetBindings:[],trackingBindings:props.primaryCta?[{action:"CTA_CLICK"}]:[]}),blueprint=()=>({goal:"جذب سرنخ",offer:"پیشنهاد روشن",audienceSummary:"مخاطب اصلی",conversionStrategy:strategy(),primaryCta:cta,secondaryCta:null,seo:{title:"صفحه فرود",description:"توضیح صفحه فرود"},socialPreview:{title:"صفحه فرود",description:"توضیح اشتراک",imageAssetId:null},sections:[section("hero","HERO",{headline:"وعده روشن",body:"متن",primaryCta:cta}),section("trust","TRUST",{heading:"شواهد واقعی",items:["مجوز معتبر"]}),section("cta","CTA",{heading:"اقدام",body:"اکنون",primaryCta:cta})],designTokens:{font:"brand",primaryColor:"#6633ff",secondaryColor:"#111122",backgroundColor:"#050510",foregroundColor:"#ffffff",mutedColor:"#aaaabb",radius:"lg",spacingDensity:"comfortable",buttonStyle:"solid",containerWidth:"standard"},tracking:{enabledActions:["LANDING_VISIT","CTA_CLICK"]},accessibility:{mainLabel:"صفحه فرود"}});
test("Landing Conversion UX v1",async t=>{
 await t.test("provides five versioned presets and eight bounded channel strategies",()=>{assert.deepEqual(landingPresetRegistry.list().map(x=>x.presetId),["LEAD_GENERATION","APPOINTMENT_BOOKING","PRODUCT_OFFER","SERVICE_OFFER","SALES_PAGE"]);assert.equal(landingChannelStrategyRegistry.list().length,8);assert.equal(landingPresetRegistry.get("UNKNOWN"),null);});
 await t.test("accepts governed strategy inside immutable blueprint contract",()=>{const value=blueprint();assert.deepEqual(validateLandingBlueprint(value,landingComponentRegistry).conversionStrategy,value.conversionStrategy);});
 await t.test("rejects invented or client-mutated strategy semantics",()=>{for(const mutate of [x=>x.conversionStrategy.channelStrategy="GA4",x=>x.conversionStrategy.proofPriority="LOW",x=>x.conversionStrategy.presetVersion=2,x=>x.conversionStrategy.goal="SALES_PAGE"]){const value=blueprint();mutate(value);assert.throws(()=>validateLandingBlueprint(value,landingComponentRegistry));}});
 await t.test("message match passes coherent lead experience without fake score",()=>{assert.deepEqual(validateLandingMessageMatch(blueprint()),{status:"PASS",warnings:[]});});
 await t.test("warns deterministically for booking CTA and messaging length mismatch",()=>{const value=blueprint(),external={label:"بیشتر",type:"EXTERNAL_URL",target:"https://example.com"};value.conversionStrategy=strategy("APPOINTMENT_BOOKING","MESSAGING");value.primaryCta=external;value.sections=value.sections.map(x=>({...x,props:{...x.props,...(x.props.primaryCta?{primaryCta:external}:{})}}));value.sections.push(section("faq","FAQ"),section("more","BENEFITS"),section("last","CTA",{heading:"اقدام",primaryCta:external}));const result=validateLandingMessageMatch(value);assert.equal(result.status,"WARNING");assert.deepEqual(result.warnings,["BOOKING_ACTION_MISMATCH","MESSAGING_PATH_TOO_LONG"]);});
 await t.test("registry contains no providers sensors metrics AI or executable templates",()=>{const raw=JSON.stringify({presets:landingPresetRegistry.list(),strategies:landingChannelStrategyRegistry.list()}).toLowerCase();for(const forbidden of ["ga4","openai","provider","ctr","roas","javascript","<script"])assert.equal(raw.includes(forbidden),false);});
});
