import assert from"node:assert/strict";
import test from"node:test";
import Database from"better-sqlite3";
import{runMigrations}from"../db/migrate.mjs";
import{migration059CommerceCatalogFoundation}from"../db/migrations/059_commerce_catalog_foundation.mjs";
import{migration060CartCheckoutFoundation}from"../db/migrations/060_cart_checkout_foundation.mjs";
import{migration061PaymentOrderLifecycle}from"../db/migrations/061_payment_order_lifecycle.mjs";
import{createCartCheckoutRepository}from"../app/repositories/cart-checkout-repository.mjs";
import{createCartCheckoutService}from"../app/services/cart-checkout-service.mjs";
import{commerceShippingRegistry}from"../app/commerce/commerce-shipping-registry.mjs";
import{createPaymentOrderRepository}from"../app/repositories/payment-order-repository.mjs";
import{createPaymentOrderService}from"../app/services/payment-order-service.mjs";
import{createDeterministicTestPaymentProvider,createUnavailablePaymentProvider}from"../app/payments/payment-providers.mjs";
import{paymentProviderRegistry}from"../app/payments/payment-provider-registry.mjs";

function fixture(provider=createDeterministicTestPaymentProvider()){const db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,role TEXT,status TEXT);CREATE TABLE content_assets(id TEXT PRIMARY KEY,workspace_id TEXT,status TEXT,media_type TEXT);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('w','active'),('x','active');INSERT INTO workspace_memberships VALUES('m','w','user','owner','active'),('mx','x','user','owner','active');`);runMigrations(db,[migration059CommerceCatalogFoundation,migration060CartCheckoutFoundation,migration061PaymentOrderLifecycle]);db.exec(`INSERT INTO commerce_catalogs VALUES('cat','w','user','فروشگاه','store','GENERAL_COMMERCE',1,'IRR','ACTIVE',1,'k',lower(hex(randomblob(32))),'2026-01-01','2026-01-01');INSERT INTO commerce_products(id,workspace_id,catalog_id,created_by_user_id,name,slug,short_description,description,status,base_price,currency,availability_status,revision,idempotency_key,request_hash,created_at,updated_at)VALUES('p','w','cat','user','کفش','shoe','کفش','کفش','ACTIVE',1200000,'IRR','IN_STOCK',1,'p',lower(hex(randomblob(32))),'2026-01-01','2026-01-01');`);let now=new Date("2026-08-23T12:00:00Z");const cartRepository=createCartCheckoutRepository(db),cartService=createCartCheckoutService({repository:cartRepository,shippingRegistry:commerceShippingRegistry,now:()=>now}),repository=createPaymentOrderRepository(db),service=createPaymentOrderService({repository,provider,callbackBaseUrl:"https://loadder.test",now:()=>now});return{db,cartService,repository,service};}
function order(f){const c=f.cartService.createCart({catalogId:"cat",customerScopeKey:null});f.cartService.addItem(c.cartToken,{revision:c.cart.revision,productId:"p",variantId:null,quantity:2});const ch=f.cartService.createCheckout(c.cartToken,{fulfillmentMode:"DIGITAL_OR_SERVICE"},"checkout").checkout,ready=f.cartService.updateCheckout(c.cartToken,ch.id,{revision:ch.revision,fulfillmentMode:"DIGITAL_OR_SERVICE",shippingMethod:"NONE",contactName:"علی رضایی",contactMobile:"09121234567",contactEmail:null,recipientName:null,recipientMobile:null,province:null,city:null,postalAddress:null,postalCode:null}).checkout,p=f.cartService.confirm(c.cartToken,ready.id,{revision:ready.revision},"confirm").pendingOrder;return{token:c.cartToken,pending:p};}
const initiate=(f,o,key="payment")=>f.service.initiate(o.token,{orderReference:o.pending.publicReference},key);

test("Payment and Order Lifecycle v1",async t=>{
 await t.test("provider registry is versioned identity and does not imply readiness",()=>{assert.equal(paymentProviderRegistry.version,1);assert.equal(paymentProviderRegistry.get("TEST").production,false);assert.equal(paymentProviderRegistry.get("ZARINPAL").production,true);for(const id of["TOROB_PAY","SNAPP_PAY","DIGIPAY"]){const entry=paymentProviderRegistry.get(id);assert.equal(entry.production,true);assert.equal(entry.availability,"BLOCKED_EXTERNAL_VALIDATION");assert.match(entry.liveValidationStatus,/LIVE_VALIDATION_BLOCKED_EXTERNAL$/);}assert.equal(fixture(createUnavailablePaymentProvider()).service.readiness().paymentEnabled,false);});
 await t.test("migration 061 adds exactly four tables and is idempotent",()=>{const f=fixture();runMigrations(f.db,[migration061PaymentOrderLifecycle]);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE type='table' AND name IN('commerce_payment_attempts','commerce_verified_payments','commerce_orders','commerce_order_items')").get().n,4);assert.deepEqual(f.db.prepare("SELECT COUNT(*) c,MAX(version) m FROM schema_migrations").get(),{c:3,m:61});});
 await t.test("production provider fails closed without creating an attempt",()=>{const f=fixture(createUnavailablePaymentProvider()),o=order(f);assert.deepEqual(f.service.readiness(),{paymentConfigured:false,paymentEnabled:false,provider:null,torobPayConfigured:false,torobPayEnabled:false,torobPayLiveValidationStatus:"TOROB_PAY_LIVE_VALIDATION_BLOCKED_EXTERNAL",snappPayConfigured:false,snappPayEnabled:false,snappPayLiveValidationStatus:"SNAPP_PAY_LIVE_VALIDATION_BLOCKED_EXTERNAL",digiPayConfigured:false,digiPayEnabled:false,digiPayLiveValidationStatus:"DIGIPAY_LIVE_VALIDATION_BLOCKED_EXTERNAL"});assert.throws(()=>initiate(f,o),e=>e.code==="PAYMENT_NOT_CONFIGURED");assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_payment_attempts").get().n,0);});
 await t.test("authorization uses server snapshot and initiation is idempotent",()=>{const f=fixture(),o=order(f),a=initiate(f,o),b=initiate(f,o);assert.equal(a.attempt.status,"REDIRECT_READY");assert.equal(a.attempt.redirectUrl,b.attempt.redirectUrl);assert.equal(f.db.prepare("SELECT requested_amount FROM commerce_payment_attempts").get().requested_amount,2400000);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_payment_attempts").get().n,1);});
 await t.test("client money and provider fields are rejected",()=>{const f=fixture(),o=order(f);for(const extra of [{amount:1},{currency:"USD"},{provider:"TEST"},{callbackUrl:"https://evil.invalid"}])assert.throws(()=>f.service.initiate(o.token,{orderReference:o.pending.publicReference,...extra},"x"),e=>e.code==="PAYMENT_ATTEMPT_INVALID");});
 await t.test("payment initiation revalidates current product availability",()=>{const f=fixture(),o=order(f);f.db.prepare("UPDATE commerce_products SET availability_status='OUT_OF_STOCK' WHERE id='p'").run();assert.throws(()=>initiate(f,o),e=>e.code==="PAYMENT_ATTEMPT_INVALID");assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_payment_attempts").get().n,0);});
 await t.test("provider authorization failure creates no verified truth",()=>{const f=fixture(createDeterministicTestPaymentProvider({authorization:"FAILED"})),o=order(f);assert.throws(()=>initiate(f,o),e=>e.code==="PAYMENT_AUTHORIZATION_FAILED");assert.equal(f.db.prepare("SELECT status FROM commerce_payment_attempts").get().status,"FAILED");assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_verified_payments").get().n,0);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_orders").get().n,0);});
 await t.test("untrusted authorization output cannot create an unsafe redirect",()=>{const provider={provider:"TEST",version:1,configured:true,enabled:true,createPayment(){return{providerAttemptReference:"safe-reference",redirectUrl:"javascript:alert(1)",expiresAt:null};},verifyPayment(){throw Error("unused");}},f=fixture(provider),o=order(f);assert.throws(()=>initiate(f,o),e=>e.code==="PAYMENT_AUTHORIZATION_FAILED");assert.equal(f.db.prepare("SELECT redirect_url FROM commerce_payment_attempts").get().redirect_url,null);});
 await t.test("provider return signal never bypasses server verification",()=>{const f=fixture(createDeterministicTestPaymentProvider({verificationStatus:"FAILED"})),o=order(f),a=initiate(f,o);const r=f.service.returnSignal({attempt:a.attempt.paymentAttemptId,status:"success"});assert.equal(r.attempt.status,"FAILED");assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_verified_payments").get().n,0);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_orders").get().n,0);});
 await t.test("pending verification remains retryable without order creation",()=>{const f=fixture(createDeterministicTestPaymentProvider({verificationStatus:"PENDING"})),o=order(f),a=initiate(f,o);assert.throws(()=>f.service.returnSignal({attempt:a.attempt.paymentAttemptId,status:"paid"}),e=>e.code==="PAYMENT_VERIFICATION_PENDING");assert.equal(f.db.prepare("SELECT status FROM commerce_payment_attempts").get().status,"RETURNED");assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_orders").get().n,0);});
 await t.test("verified payment atomically creates immutable confirmed order",()=>{const f=fixture(),o=order(f),a=initiate(f,o),r=f.service.returnSignal({attempt:a.attempt.paymentAttemptId,status:"anything"});assert.equal(r.attempt.status,"VERIFIED");assert.equal(r.order.status,"CONFIRMED");assert.equal(r.order.grandTotal,2400000);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_order_items").get().n,1);assert.throws(()=>f.db.prepare("UPDATE commerce_verified_payments SET verified_amount=1").run());assert.throws(()=>f.db.prepare("UPDATE commerce_orders SET grand_total=1").run());assert.throws(()=>f.db.prepare("DELETE FROM commerce_order_items").run());});
 await t.test("amount mismatch fails without verified payment or order",()=>{const f=fixture(createDeterministicTestPaymentProvider({amountDelta:1})),o=order(f),a=initiate(f,o);assert.throws(()=>f.service.returnSignal({attempt:a.attempt.paymentAttemptId}),e=>e.code==="PAYMENT_AMOUNT_MISMATCH");assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_verified_payments").get().n,0);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_orders").get().n,0);});
 await t.test("currency mismatch fails without verified payment or order",()=>{const f=fixture(createDeterministicTestPaymentProvider({currencyOverride:"USD"})),o=order(f),a=initiate(f,o);assert.throws(()=>f.service.returnSignal({attempt:a.attempt.paymentAttemptId}),e=>e.code==="PAYMENT_CURRENCY_MISMATCH");assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_orders").get().n,0);});
 await t.test("malformed provider verification evidence fails closed",()=>{const base=createDeterministicTestPaymentProvider(),provider={...base,verifyPayment(){return{status:"VERIFIED",providerTransactionReference:"bad reference with spaces",verifiedAmount:2400000,currency:"IRR",verifiedAt:"not-a-date",boundedProviderCode:"VERIFIED"};}},f=fixture(provider),o=order(f),a=initiate(f,o);assert.throws(()=>f.service.returnSignal({attempt:a.attempt.paymentAttemptId}),e=>e.code==="PAYMENT_VERIFICATION_FAILED");assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_verified_payments").get().n,0);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_orders").get().n,0);});
 await t.test("ten callback replays and retry converge to one payment and order",()=>{const f=fixture(),o=order(f),a=initiate(f,o);for(let i=0;i<10;i++)f.service.returnSignal({attempt:a.attempt.paymentAttemptId,status:"forged-success"});const c=f.service.retry(o.token,a.attempt.paymentAttemptId);assert.equal(c.reusedResult,true);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_verified_payments").get().n,1);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM commerce_orders").get().n,1);});
 await t.test("capability token scopes status and confirmed order",()=>{const f=fixture(),o=order(f),a=initiate(f,o);assert.throws(()=>f.service.status(o.token+"x",a.attempt.paymentAttemptId),e=>e.code==="PAYMENT_ATTEMPT_NOT_FOUND");f.service.returnSignal({attempt:a.attempt.paymentAttemptId});assert.equal(f.service.order(o.token,o.pending.publicReference).paymentStatus,"VERIFIED");assert.throws(()=>f.service.order(o.token+"x",o.pending.publicReference),e=>e.code==="PAYMENT_ATTEMPT_NOT_FOUND");});
 await t.test("catalog price changes cannot alter authoritative pending snapshot",()=>{const f=fixture(),o=order(f);f.db.prepare("UPDATE commerce_products SET base_price=1 WHERE id='p'").run();const a=initiate(f,o);f.service.returnSignal({attempt:a.attempt.paymentAttemptId});assert.equal(f.db.prepare("SELECT verified_amount FROM commerce_verified_payments").get().verified_amount,2400000);assert.equal(f.db.prepare("SELECT grand_total FROM commerce_orders").get().grand_total,2400000);});
 await t.test("schema excludes refunds fulfillment inventory SDK and analytics coupling",()=>{const f=fixture(),sql=f.db.prepare("SELECT group_concat(sql,' ') sql FROM sqlite_master WHERE name IN('commerce_payment_attempts','commerce_verified_payments','commerce_orders','commerce_order_items')").get().sql.toLowerCase();for(const word of["refund","shipment_provider","inventory_reservation","stripe","zarinpal_secret","attribution_touch","performance_observation"])assert.equal(sql.includes(word),false);assert.equal(f.db.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(f.db.pragma("foreign_key_check"),[]);});
});
