import assert from"node:assert/strict";
import test from"node:test";
import{classifyEvidenceOrigin,deriveProductionOutcomeEvidence,productionOutcomeEvidencePolicy}from"../app/user-outcomes/production-outcome-evidence-policy.mjs";
import{createWorkflowOutcomeService}from"../app/services/workflow-outcome-service.mjs";
import{createInternalTqmDogfoodService}from"../app/services/internal-tqm-dogfood-service.mjs";
import{evaluateGrowthOutcomeComparison}from"../app/user-outcomes/growth-strategy-value-contract.mjs";
import{classifyApiRequest}from"../app/middleware/product-gating.mjs";

const NOW=new Date("2026-08-24T12:00:00.000Z"),iso=days=>new Date(NOW.getTime()-days*86400000).toISOString();
const row=(id,days=1,extra={})=>({sourceEntityId:id,startedAt:iso(days),completedAt:iso(days-.01),acceptedAt:null,rejectedAt:null,usedAt:null,usedEvidence:false,failedEvidence:false,terminalPosture:"COMPLETED",recoveryPosture:"COMPLETED",workflowVersion:1,operationVersion:1,outcomeContractVersion:1,timeToCompletionMs:864000,timeToAcceptanceMs:null,timeToUsageMs:null,timeToProductValueSignalMs:null,productValueSignal:false,...extra});
const production=(items,extra={})=>deriveProductionOutcomeEvidence(items,{originContext:{nodeEnv:"production",seedDemoData:false},observedAt:NOW,...extra});
const representative=()=>Array.from({length:30},(_,i)=>row(`p-${i}`,1+i*15/29,i<5?{completedAt:null,failedEvidence:true,terminalPosture:"FAILED"}:i<10?{acceptedAt:iso(1+i*15/29-.02),usedAt:iso(1+i*15/29-.03),usedEvidence:true,productValueSignal:true,timeToAcceptanceMs:1728000,timeToUsageMs:2592000,timeToProductValueSignalMs:2592000}:i<15?{acceptedAt:iso(1+i*15/29-.02),timeToAcceptanceMs:1728000}:{}));

test("Production Outcome Evidence v1",async t=>{
 await t.test("origin policy is versioned deterministic and server-metadata only",()=>{assert.equal(productionOutcomeEvidencePolicy.version,1);assert.equal(classifyEvidenceOrigin({},{}),"UNKNOWN");assert.equal(classifyEvidenceOrigin({},{nodeEnv:"production",seedDemoData:false}),"PRODUCTION");assert.equal(classifyEvidenceOrigin({},{nodeEnv:"test"}),"TEST");assert.equal(classifyEvidenceOrigin({},{nodeEnv:"development"}),"DEVELOPMENT");assert.equal(classifyEvidenceOrigin({},{nodeEnv:"production",seedDemoData:true}),"DEMO");});
 await t.test("canonical per-record origin separates test demo seed and production",()=>{for(const origin of["PRODUCTION","TEST","DEMO","SEED","DEVELOPMENT","UNKNOWN"])assert.equal(classifyEvidenceOrigin({evidenceOriginSource:"CANONICAL",evidenceOrigin:origin},{nodeEnv:"production",seedDemoData:false}),origin);});
 await t.test("zero production instances returns NONE with null rates",()=>{const x=production([]);assert.equal(x.productionEvidence,"NONE");assert.equal(x.representative,false);assert.equal(x.completionRateConfirmed,null);});
 await t.test("one production instance is sparse and suppresses percentages",()=>{const x=production([row("one")]);assert.equal(x.productionEvidence,"SPARSE");assert.equal(x.evidenceQuality,"INSUFFICIENT");assert.equal(x.completionRateConfirmed,null);});
 await t.test("small sample is limited and never representative",()=>{const x=production(Array.from({length:8},(_,i)=>row(`s-${i}`,i+1)));assert.equal(x.productionEvidence,"LIMITED");assert.equal(x.representative,false);assert.equal(x.evidenceQuality,"LIMITED");});
 await t.test("adequate synthetic production-shaped fixture reaches representative capability only",()=>{const x=production(representative());assert.equal(x.productionEvidence,"REPRESENTATIVE");assert.equal(x.representative,true);assert.equal(x.representativeness,"ADEQUATE");assert.equal(x.productImprovement,"PRODUCT_IMPROVEMENT_INCONCLUSIVE");});
 await t.test("test and demo contamination cannot improve production posture",()=>{const records=[...Array.from({length:10},(_,i)=>({...row(`prod-${i}`),evidenceOriginSource:"CANONICAL",evidenceOrigin:"PRODUCTION"})),...Array.from({length:100},(_,i)=>({...row(`noise-${i}`),evidenceOriginSource:"CANONICAL",evidenceOrigin:i%2?"TEST":"DEMO"}))],x=deriveProductionOutcomeEvidence(records,{observedAt:NOW});assert.equal(x.productionInstances,10);assert.equal(x.validStarts,10);assert.equal(x.originCounts.TEST,50);assert.equal(x.originCounts.DEMO,50);assert.equal(x.representative,false);});
 await t.test("unknown origin is reported and excluded from production claims",()=>{const x=deriveProductionOutcomeEvidence([row("unknown")],{observedAt:NOW});assert.equal(x.productionEvidence,"ORIGIN_UNKNOWN");assert.equal(x.productionInstances,0);assert.equal(x.validStarts,0);});
 await t.test("development evidence remains non-production",()=>{const x=deriveProductionOutcomeEvidence([row("dev")],{originContext:{nodeEnv:"development"},observedAt:NOW});assert.equal(x.productionEvidence,"NON_PRODUCTION_ONLY");assert.equal(x.originCounts.DEVELOPMENT,1);});
 await t.test("incompatible versions are not blended",()=>{const x=production([row("v1"),row("v2",1,{workflowVersion:2})]);assert.equal(x.productionEvidence,"INCOMPARABLE");assert.equal(x.versionCompatibility,"INCOMPARABLE");assert.equal(x.completionRateConfirmed,null);});
 await t.test("old evidence is stale and cannot become representative",()=>{const x=production(Array.from({length:30},(_,i)=>row(`old-${i}`,100+i)));assert.equal(x.freshness,"STALE");assert.equal(x.representative,false);});
 await t.test("orphan unknown is excluded from confirmed failure denominator",()=>{const items=[row("done"),row("failed",1,{completedAt:null,failedEvidence:true,terminalPosture:"FAILED"}),row("unknown",1,{completedAt:null,terminalPosture:"STARTED",recoveryPosture:"ORPHANED_UNKNOWN"}),...Array.from({length:3},(_,i)=>row(`extra-${i}`))],x=production(items);assert.equal(x.resolvedStarts,5);assert.equal(x.unknownStarts,1);assert.equal(x.failed,1);assert.equal(x.technicalFailureRateConfirmed,.2);});
 await t.test("rates use explicit conservative denominators",()=>{const x=production(representative());assert.equal(x.completionRateConfirmedDenominator,"RESOLVED_STARTS");assert.equal(x.technicalFailureRateConfirmedDenominator,"RESOLVED_STARTS");assert.equal(x.acceptanceRateDenominator,"COMPLETED");assert.equal(x.usageRateDenominator,"ACCEPTED");assert.equal(x.productValueSignalRateDenominator,"ACCEPTED");});
 await t.test("product-value signal never becomes business value or causality",()=>{const x=production(representative());assert.equal(x.productValuePosture,"PRODUCT_VALUE_SIGNAL_PRESENT");assert.equal(x.businessValuePosture,"BUSINESS_VALUE_NOT_PROVEN");assert.equal(x.causalityPosture,"OBSERVATIONAL_ONLY");assert.equal(x.baselinePosture,"NO_COMPARABLE_BASELINE");});
 await t.test("more starts with flat accepted usage is not improvement",()=>{const x=evaluateGrowthOutcomeComparison({started:10,completed:8,accepted:4,rejected:1,used:2,medianTimeToCompletionMs:100},{started:20,completed:16,accepted:4,rejected:1,used:2,medianTimeToCompletionMs:100});assert.equal(x.posture,"TRADEOFF_DETECTED");assert.ok(x.reasonCodes.includes("MORE_STARTS_NOT_IMPROVEMENT"));});
 await t.test("service rejects client authority and defaults absent provenance to unknown",()=>{const service=createWorkflowOutcomeService({repository:{list:type=>type==="GROWTH_STRATEGY"?[row("x")]:[]},now:()=>NOW});assert.throws(()=>service.summary({origin:"PRODUCTION"}),e=>e.code==="OUTCOME_AUTHORITATIVE_STATE_FORBIDDEN");assert.throws(()=>service.summary({representative:true}),e=>e.code==="OUTCOME_AUTHORITATIVE_STATE_FORBIDDEN");assert.equal(service.summary({workflowType:"GROWTH_STRATEGY"}).productionOutcomeEvidence.productionEvidence,"ORIGIN_UNKNOWN");});
 await t.test("internal API remains internal-only and bounded",()=>{for(const path of["/api/internal/quality/user-outcomes/summary","/api/internal/quality/user-outcomes/GROWTH_STRATEGY"])assert.deepEqual(classifyApiRequest("GET",path),{feature:"development_tools",internal:true});const service=createWorkflowOutcomeService({repository:{list:()=>[]},now:()=>NOW});assert.throws(()=>service.summary({start:iso(100),end:NOW.toISOString()}),e=>e.code==="OUTCOME_WINDOW_INVALID");});
 await t.test("TQM exposes production dimensions without claiming improvement",()=>{const outcome=createWorkflowOutcomeService({repository:{list:type=>type==="GROWTH_STRATEGY"?representative():[]},originContext:{nodeEnv:"production",seedDemoData:false},now:()=>NOW}),dogfood=createInternalTqmDogfoodService({economyService:{summary:()=>({})},benchmarkRegistry:{summary:()=>({caseCount:1})},databaseStatus:()=>({bytes:1,pages:1}),outcomeService:outcome}),baseline=dogfood.baseline();assert.equal(baseline.outcomeMeasurement.productionEvidence,"REPRESENTATIVE");assert.equal(baseline.outcomeMeasurement.productValueEvidence,"PRODUCT_VALUE_SIGNAL_PRESENT");assert.equal(baseline.outcomeMeasurement.businessValueEvidence,"BUSINESS_VALUE_NOT_PROVEN");assert.equal(baseline.outcomeMeasurement.productImprovement,"INSUFFICIENT_EVIDENCE");assert.equal(baseline.topConstraint.category,"BUSINESS_VALUE_GAP");});
 await t.test("summary is aggregate metadata only with zero AI and persistence delta",()=>{const source=JSON.stringify(production(representative()));for(const forbidden of["prompt","objective","strategyJson","email","phone","address","businessContext"])assert.equal(source.includes(forbidden),false);assert.equal(production(representative()).businessValueSignals,0);});
});
