import assert from "node:assert/strict";
import test from "node:test";
import { createProductionConfiguration, validateFrontendApiBase } from "../app/config/production-configuration.mjs";

const valid = () => ({ NODE_ENV: "production", AUTH_HASH_SECRET: "production-secret-with-more-than-24-characters", CLIENT_ORIGINS: "https://app.loadder.example", DATABASE_PATH: "/data/loadder.sqlite", OPENAI_API_KEY: "fixture-key", LANDING_STATIC_DIRECTORY: "/data/landing", LANDING_PUBLIC_BASE_URL: "https://pages.loadder.example", LANDING_PUBLIC_API_BASE_URL: "https://api.loadder.example", LANDING_TRACKING_SECRET: "tracking-secret-with-more-than-24-characters", PUBLIC_STATIC_DIRECTORY: "/data/public", PUBLIC_BASE_URL: "https://sites.loadder.example" });

test("production configuration hardening", async (t) => {
  await t.test("valid production distinguishes boot, launch, persistence, and pending SMS validation", () => { const c = createProductionConfiguration(valid()); assert.equal(c.bootReady, true); assert.equal(c.coreLaunchReady, false); assert.equal(c.database.persistenceValidated, false); assert.equal(c.providers.smsOtp, "NOT_CONFIGURED"); });
  await t.test("development preserves localhost defaults", () => { const c = createProductionConfiguration({ NODE_ENV: "development" }); assert.equal(c.bootReady, true); assert.deepEqual(c.clientOrigins, ["http://localhost:5173"]); assert.equal(validateFrontendApiBase("", { production: false }).valid, true); });
  await t.test("production rejects missing and placeholder auth secrets", () => { assert.ok(createProductionConfiguration({ ...valid(), AUTH_HASH_SECRET: "" }).requiredMissing.includes("CONFIG_AUTH_SECRET_MISSING")); assert.ok(createProductionConfiguration({ ...valid(), AUTH_HASH_SECRET: "change-me-this-is-not-a-secret" }).invalid.includes("CONFIG_AUTH_SECRET_INVALID")); });
  await t.test("production rejects wildcard, HTTP, malformed, credentialed, and local origins", () => { for (const origin of ["*", "http://app.example.com", "bad", "https://u:p@app.example.com", "https://localhost"]) assert.ok(createProductionConfiguration({ ...valid(), CLIENT_ORIGINS: origin }).invalid.includes("CONFIG_CLIENT_ORIGIN_INVALID")); });
  await t.test("production requires explicit database path and rejects dangerous development flags", () => { const c = createProductionConfiguration({ ...valid(), DATABASE_PATH: "", AUTH_EXPOSE_DEV_OTP: "true", LOADDER_SEED_DEMO_DATA: "true" }); assert.ok(c.requiredMissing.includes("CONFIG_DATABASE_PATH_MISSING")); assert.ok(c.invalid.includes("CONFIG_DEVELOPMENT_OTP_ENABLED")); assert.ok(c.invalid.includes("CONFIG_DEMO_DATA_ENABLED")); });
  await t.test("missing OpenAI and publishing degrade core launch without blocking boot", () => { const c = createProductionConfiguration({ ...valid(), OPENAI_API_KEY: "", LANDING_STATIC_DIRECTORY: "", PUBLIC_STATIC_DIRECTORY: "" }); assert.equal(c.bootReady, true); assert.equal(c.coreLaunchReady, false); assert.ok(c.optionalUnavailable.includes("CONFIG_OPENAI_MISSING")); });
  await t.test("SMS configuration remains pending live validation", () => { const c = createProductionConfiguration({ ...valid(), SMS_IR_API_KEY: "fixture", SMS_IR_OTP_TEMPLATE_ID: "123" }); assert.equal(c.providers.smsOtp, "CODE_READY_LIVE_VALIDATION_PENDING"); assert.equal(c.coreLaunchReady, false); });
  await t.test("production frontend API requires safe HTTPS without credentials or localhost", () => { assert.equal(validateFrontendApiBase("https://api.loadder.example", { production: true }).valid, true); for (const url of ["", "http://api.example.com", "https://localhost:3001", "https://u:p@api.example.com"]) assert.equal(validateFrontendApiBase(url, { production: true }).valid, false); });
  await t.test("bounded output contains no supplied secret values", () => { const env = valid(), text = JSON.stringify(createProductionConfiguration(env)); assert.equal(text.includes(env.AUTH_HASH_SECRET), false); assert.equal(text.includes(env.OPENAI_API_KEY), false); });
});
