import assert from "node:assert/strict";
import test from "node:test";
import Database from "better-sqlite3";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createPersistenceContract, assertSafeBackupPaths } from "../app/persistence/persistence-contract.mjs";
import { createSqliteBackup, restoreSqliteBackup, validateSqliteFile } from "../app/persistence/sqlite-backup.mjs";
import { createPublicStaticProvider } from "../app/publishing/public-static-provider.mjs";
import { runMigrations } from "../db/migrate.mjs";

const setup = () => { const root = mkdtempSync(join(tmpdir(), "loadder-persistence-")), dbPath = join(root, "db", "loadder.sqlite"), backupDir = join(root, "backups"), landing = join(root, "sites", "landing"), website = join(root, "sites", "website"); mkdirSync(join(root,"db"),{recursive:true}); const db = new Database(dbPath); db.pragma("foreign_keys=ON"); db.exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT); INSERT INTO schema_migrations VALUES(69,'current','now'); CREATE TABLE marker(id TEXT PRIMARY KEY,value TEXT); INSERT INTO marker VALUES('known','before');"); return { root, dbPath, backupDir, landing, website, db }; };
test("Production persistence and backup closure v1", async (t) => {
  await t.test("production contract is pending deployment validation and single-instance", () => { const c=createPersistenceContract({NODE_ENV:"production",DATABASE_PATH:"/var/lib/loadder/db/loadder.sqlite",LANDING_STATIC_DIRECTORY:"/var/lib/loadder/landing",PUBLIC_STATIC_DIRECTORY:"/var/lib/loadder/websites",LOADDER_BACKUP_DIR:"/var/backups/loadder",LOADDER_INSTANCE_COUNT:"1"}); assert.equal(c.status,"CODE_READY_DEPLOYMENT_VALIDATION_PENDING"); assert.equal(c.multiInstanceSqliteSupported,false); });
  await t.test("multi-instance and unsafe temporary DB fail closed", () => { const f=setup(), c=createPersistenceContract({NODE_ENV:"production",DATABASE_PATH:f.dbPath,LANDING_STATIC_DIRECTORY:f.landing,PUBLIC_STATIC_DIRECTORY:f.website,LOADDER_BACKUP_DIR:f.backupDir,LOADDER_INSTANCE_COUNT:"2"}); assert.ok(c.reasonCodes.includes("PERSISTENCE_MULTI_INSTANCE_UNSUPPORTED")); assert.ok(c.reasonCodes.includes("PERSISTENCE_DATABASE_PATH_UNSAFE")); f.db.close(); });
  await t.test("backup directory cannot overlap public artifacts", () => { const f=setup(); assert.throws(()=>assertSafeBackupPaths({databasePath:f.dbPath,backupDirectory:join(f.website,"backups"),publicDirectories:[f.website]}),e=>e.code==="PERSISTENCE_PUBLIC_BACKUP_OVERLAP"); f.db.close(); });
  await t.test("SQLite-safe backup validates checksum integrity FK and migrations", () => { const f=setup(), start=performance.now(), b=createSqliteBackup({db:f.db,databasePath:f.dbPath,backupDirectory:f.backupDir,now:new Date("2026-08-25T00:00:00.000Z")}); assert.equal(b.integrity,"ok"); assert.deepEqual(b.foreignKeys,[]); assert.equal(b.migrationCount,1); assert.equal(b.maxMigrationVersion,69); assert.equal(b.checksum.length,64); assert.ok(b.bytes>0); assert.ok(performance.now()-start<5000); f.db.close(); });
  await t.test("restore recovers known state to an explicit different target", () => { const f=setup(), b=createSqliteBackup({db:f.db,databasePath:f.dbPath,backupDirectory:f.backupDir}); f.db.prepare("UPDATE marker SET value='after'").run(); f.db.close(); const target=join(f.root,"restore","restored.sqlite"), r=restoreSqliteBackup({source:b.path,target,expectedChecksum:b.checksum}), restored=new Database(target,{readonly:true}); assert.equal(restored.prepare("SELECT value FROM marker WHERE id='known'").get().value,"before"); restored.close(); assert.equal(r.integrity,"ok"); });
  await t.test("corrupt source same-file target and missing target fail closed", () => { const f=setup(), bad=join(f.root,"bad.sqlite"); writeFileSync(bad,"not sqlite"); assert.throws(()=>validateSqliteFile(bad),e=>e.code==="PERSISTENCE_BACKUP_INVALID"); assert.throws(()=>restoreSqliteBackup({source:f.dbPath,target:f.dbPath}),e=>e.code==="PERSISTENCE_RESTORE_TARGET_UNSAFE"); assert.throws(()=>restoreSqliteBackup({source:f.dbPath,target:""}),e=>e.code==="PERSISTENCE_RESTORE_TARGET_UNSAFE"); f.db.close(); });
  await t.test("artifact survives provider reinitialization with unchanged bytes", () => { const f=setup(), one=createPublicStaticProvider({nodeEnv:"production",staticDirectory:f.website,publicBaseUrl:"https://sites.example"}); assert.equal(one.publish({root:"publications/a",files:{"index.html":"stable"}}).available,true); const two=createPublicStaticProvider({nodeEnv:"production",staticDirectory:f.website,publicBaseUrl:"https://sites.example"}); assert.equal(two.resolve("publications/a/index.html").body,"stable"); assert.equal(readFileSync(join(f.website,"publications/a/index.html"),"utf8"),"stable"); f.db.close(); });
  await t.test("failed pre-migration backup prevents migration", () => { const f=setup(), old={NODE_ENV:process.env.NODE_ENV,ALLOW:process.env.LOADDER_ALLOW_PRODUCTION_MIGRATIONS,DB:process.env.DATABASE_PATH,BACKUP:process.env.LOADDER_BACKUP_DIR,PUBLIC:process.env.PUBLIC_STATIC_DIRECTORY}; Object.assign(process.env,{NODE_ENV:"production",LOADDER_ALLOW_PRODUCTION_MIGRATIONS:"true",DATABASE_PATH:f.dbPath,LOADDER_BACKUP_DIR:join(f.website,"backups"),PUBLIC_STATIC_DIRECTORY:f.website}); let ran=false; try { assert.throws(()=>runMigrations(f.db,[{version:70,name:"must_not_run",up(){ran=true;}}])); assert.equal(ran,false); } finally { for(const [key,value] of Object.entries({NODE_ENV:old.NODE_ENV,LOADDER_ALLOW_PRODUCTION_MIGRATIONS:old.ALLOW,DATABASE_PATH:old.DB,LOADDER_BACKUP_DIR:old.BACKUP,PUBLIC_STATIC_DIRECTORY:old.PUBLIC})) { if(value===undefined)delete process.env[key];else process.env[key]=value; } f.db.close(); } });
});
