import test from "node:test";
import assert from "node:assert/strict";
import { copyFileSync, mkdtempSync, rmSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import Database from "better-sqlite3";
import express from "express";
import { runMigrations } from "../db/migrate.mjs";
import { providerAccountIdentitiesMigration } from "../db/migrations/041_provider_account_identities.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createProviderIdentityHasher } from "../app/provider-account-identities/identity-hashing.mjs";
import { createProviderIdentityVerifierRegistry, providerIdentityVerifierRegistry } from "../app/provider-account-identities/verifier-registry.mjs";
import { createProviderAccountIdentityRepository } from "../app/repositories/provider-account-identity-repository.mjs";
import { createProviderAccountIdentityService } from "../app/services/provider-account-identity-service.mjs";
import { createProviderAccountIdentityRouter } from "../app/routes/provider-account-identities.mjs";
import { createOperationMetrics } from "../app/observability/operation-metrics.mjs";
import { encodeCursor } from "../app/query/cursor-pagination.mjs";

const AT="2026-08-21T18:00:00.000Z",HASH_KEY="phase-4m-test-key",within=(workspace,fn)=>runWithWorkspace(workspace,fn);

test("Phase 4M v1 Verified Provider Account Identity foundation", async (t) => {
  const dir=mkdtempSync(join(tmpdir(),"loadder-provider-identity-")),scopePath=join(dir,"scope.sqlite");
  copyFileSync(new URL("../db/loadder.sqlite",import.meta.url),scopePath);
  const scope=new Database(scopePath);scope.pragma("foreign_keys=ON");
  scope.exec("DROP TRIGGER IF EXISTS trg_content_generations_intent_guard;DROP TRIGGER IF EXISTS trg_content_items_intent_guard;DROP TRIGGER IF EXISTS trg_content_items_intent_immutable;ALTER TABLE content_generations DROP COLUMN intent_id;ALTER TABLE content_items DROP COLUMN intent_id;DROP TABLE IF EXISTS creative_intents;DROP TABLE IF EXISTS attribution_touches;DELETE FROM schema_migrations WHERE version=55;DROP TABLE IF EXISTS distribution_contexts;DELETE FROM schema_migrations WHERE version=54;DELETE FROM schema_migrations WHERE version=53;DELETE FROM schema_migrations WHERE version=52;DROP TABLE IF EXISTS creative_placements;DELETE FROM schema_migrations WHERE version=51;DELETE FROM schema_migrations WHERE version=50;DELETE FROM schema_migrations WHERE version=49;DROP TABLE IF EXISTS content_assets;DELETE FROM schema_migrations WHERE version=48;DROP TABLE IF EXISTS content_items;DELETE FROM schema_migrations WHERE version=47;DELETE FROM schema_migrations WHERE version=46;DROP TABLE IF EXISTS content_generations;DELETE FROM schema_migrations WHERE version=45;DROP TABLE IF EXISTS execution_action_inputs;DELETE FROM schema_migrations WHERE version=44;DROP TABLE IF EXISTS execution_dispatch_jobs;DELETE FROM schema_migrations WHERE version=43;DROP TABLE IF EXISTS execution_results;DROP TABLE IF EXISTS provider_invocation_events;DROP TABLE IF EXISTS execution_attempts;DELETE FROM schema_migrations WHERE version=42;DROP TABLE IF EXISTS provider_account_identities;DELETE FROM schema_migrations WHERE version=41;");
  assert.deepEqual(scope.prepare("SELECT COUNT(*) c,MAX(version) m FROM schema_migrations").get(),{c:40,m:40});
  const before=scope.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();
  runMigrations(scope,[providerAccountIdentitiesMigration]);runMigrations(scope,[providerAccountIdentitiesMigration]);

  const db=new Database(join(dir,"fixture.sqlite"));db.pragma("foreign_keys=ON");
  db.exec(`CREATE TABLE workspaces(id TEXT PRIMARY KEY);CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,role TEXT,status TEXT);CREATE TABLE connector_connections(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,connector_id TEXT NOT NULL,connector_version INTEGER NOT NULL,UNIQUE(workspace_id,id));`);
  runMigrations(db,[providerAccountIdentitiesMigration]);
  for(const id of["wa","wb"])db.prepare("INSERT INTO workspaces VALUES(?)").run(id);
  for(const [id,w,role,status] of [["owner","wa","owner","active"],["admin","wa","admin","active"],["member","wa","member","active"],["inactive","wa","admin","inactive"],["foreign","wb","owner","active"]]){db.prepare("INSERT INTO users VALUES(?)").run(id);db.prepare("INSERT INTO workspace_memberships VALUES(?,?,?,?,?)").run(`m-${id}`,w,id,role,status);}
  for(const row of [["conn","wa","fixture",1],["conn-2","wa","fixture",1],["foreign-conn","wb","fixture",1]])db.prepare("INSERT INTO connector_connections VALUES(?,?,?,?)").run(...row);
  let rawAccount="account-1",providerCalls=0;
  const verifier={connectorId:"fixture",connectorVersion:1,verify({workspaceId,connection,credentialAccess}){providerCalls++;assert.equal(workspaceId,"wa");assert.equal(connection.connectorId,"fixture");assert.equal(credentialAccess,null);return{providerKind:"fixture_provider",externalAccountType:"organization",normalizedExternalAccountKey:rawAccount,normalizedExternalParentTenantKey:"tenant-1",normalizedExternalAccountScope:"scope-1",safeDisplayLabel:"Safe Fixture",verificationMethod:"SANDBOX_ACCOUNT_VERIFICATION",verificationVersion:1,observedAt:AT,evidenceDigestInput:"bounded-evidence"};}};
  const registry=createProviderIdentityVerifierRegistry([verifier]),hasher=createProviderIdentityHasher({key:HASH_KEY}),repository=createProviderAccountIdentityRepository(db),metrics=createOperationMetrics({limit:100}),service=createProviderAccountIdentityService({repository,verifierRegistry:registry,hasher,now:()=>new Date(AT),operationMetrics:metrics}),production=createProviderAccountIdentityService({repository,verifierRegistry:providerIdentityVerifierRegistry,now:()=>new Date(AT)}),owner={userId:"owner",membershipId:"m-owner",role:"owner"},admin={userId:"admin",membershipId:"m-admin",role:"admin"};
  let first;

  await t.test("migration 041 is idempotent, exactly one-table scoped, and preserves prior schema",()=>{assert.deepEqual(scope.prepare("SELECT COUNT(*) c,MAX(version) m FROM schema_migrations").get(),{c:41,m:41});assert.equal(scope.prepare("SELECT COUNT(*) c FROM sqlite_master WHERE type='table' AND name='provider_account_identities'").get().c,1);assert.deepEqual(scope.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name!='provider_account_identities' ORDER BY name").all(),before);});
  await t.test("production registry is empty, unknown verifier is unavailable, and writes zero rows",()=>within("wa",()=>{assert.deepEqual(providerIdentityVerifierRegistry.list(),[]);assert.equal(providerIdentityVerifierRegistry.resolve("fixture",1),null);assert.throws(()=>production.verify("conn",{},owner,"unavailable"),e=>e.code==="IDENTITY_VERIFICATION_UNAVAILABLE"&&e.status===409);assert.equal(db.prepare("SELECT COUNT(*) c FROM provider_account_identities").get().c,0);assert.equal(providerCalls,0);}));
  await t.test("owner and admin reach the verification boundary while member and inactive membership are denied",()=>within("wa",()=>{first=service.verify("conn",{},owner,"owner-1").identity;assert.ok(first.id);assert.equal(service.verify("conn",{},admin,"admin-1").identity.verifiedByRole,"admin");for(const actor of [{userId:"member",membershipId:"m-member",role:"member"},{userId:"inactive",membershipId:"m-inactive",role:"admin"}]){if(actor.role==="member")assert.throws(()=>service.verify("conn",{},actor,"denied"),e=>e.code==="IDENTITY_VERIFICATION_FORBIDDEN");else assert.throws(()=>db.prepare(`INSERT INTO provider_account_identities SELECT 'inactive-row',workspace_id,connection_id,connector_id,connector_version,provider_kind,external_account_type,external_account_key_hash,external_parent_tenant_key_hash,external_account_scope_hash,safe_display_label,identity_version,verification_method,verification_version,verification_evidence_hash,'inactive','m-inactive','admin',operation_kind,'inactive-key',request_hash,verified_at,created_at FROM provider_account_identities LIMIT 1`).run(),/membership mismatch/);}}));
  await t.test("foreign connection is 404 and tenant-scoped identifiers do not leak",()=>{assert.throws(()=>within("wa",()=>service.verify("foreign-conn",{},owner,"foreign")),e=>e.code==="CONNECTION_NOT_FOUND");assert.throws(()=>within("wb",()=>service.get(first.id)),e=>e.code==="PROVIDER_IDENTITY_NOT_FOUND");assert.throws(()=>within("wb",()=>service.list("conn",{})),e=>e.code==="CONNECTION_NOT_FOUND");});
  await t.test("all client identity, actor, workspace, raw-key, hash, and credential overrides are rejected",()=>within("wa",()=>{for(const key of ["workspaceId","userId","membershipId","role","providerKind","connectorId","connectorVersion","externalAccountKey","externalAccountKeyHash","verificationMethod","verificationVersion","identityVersion","verifiedAt","safeDisplayLabel","credentialReference"])assert.throws(()=>service.verify("conn",{[key]:"injected"},owner,`inject-${key}`),e=>e.code==="IDENTITY_CLIENT_OVERRIDE_REJECTED");}));
  await t.test("keyed hashing is deterministic and separated by domain, version, provider, type, and account",()=>{const base={providerKind:"p",accountType:"organization",normalizedKey:"account"},a=hasher.hash(base);assert.equal(a,hasher.hash({...base}));assert.match(a,/^[0-9a-f]{64}$/);for(const candidate of [createProviderIdentityHasher({key:HASH_KEY,domain:"other"}).hash(base),createProviderIdentityHasher({key:HASH_KEY,version:2}).hash(base),hasher.hash({...base,providerKind:"q"}),hasher.hash({...base,accountType:"tenant"}),hasher.hash({...base,normalizedKey:"other"})])assert.notEqual(candidate,a);assert.throws(()=>createProviderIdentityHasher());});
  await t.test("raw identity and credentials never reach persistence",()=>{const schema=db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='provider_account_identities'").get().sql.toLowerCase(),stored=JSON.stringify(db.prepare("SELECT * FROM provider_account_identities").all());assert.equal(schema.includes("credential"),false);assert.equal(schema.includes("raw"),false);assert.equal(stored.includes("account-1"),false);assert.equal(stored.includes(HASH_KEY),false);assert.equal(stored.includes("tenant-1"),false);assert.equal(stored.includes("scope-1"),false);});
  await t.test("same-account reverification creates immutable history",()=>within("wa",()=>{const next=service.verify("conn",{},owner,"owner-2").identity;assert.notEqual(next.id,first.id);assert.equal(next.externalAccountKeyHash,first.externalAccountKeyHash);assert.equal(repository.listPage("conn",{limit:100}).items.length,3);}));
  await t.test("account change is detected without mutating prior observations",()=>within("wa",()=>{rawAccount="account-2";const changed=service.verify("conn",{},owner,"owner-3");assert.equal(changed.accountChanged,true);assert.notEqual(changed.identity.externalAccountKeyHash,first.externalAccountKeyHash);assert.equal(repository.getById(first.id).externalAccountKeyHash,first.externalAccountKeyHash);}));
  await t.test("a recreated connection may observe the same external account",()=>within("wa",()=>{rawAccount="account-1";const observed=service.verify("conn-2",{},owner,"recreated").identity;assert.equal(observed.externalAccountKeyHash,first.externalAccountKeyHash);assert.notEqual(observed.connectionId,first.connectionId);}));
  await t.test("exact actor idempotency reuses and a changed canonical request conflicts",()=>within("wa",()=>{const replay=service.verify("conn",{},owner,"owner-1");assert.equal(replay.identity.id,first.id);assert.equal(replay.reusedResult,true);assert.throws(()=>service.verify("conn-2",{},owner,"owner-1"),e=>e.code==="IDEMPOTENCY_CONFLICT");}));
  await t.test("concurrent identical requests converge",async()=>within("wa",async()=>{const [a,b]=await Promise.all([Promise.resolve().then(()=>service.verify("conn",{},owner,"concurrent")),Promise.resolve().then(()=>service.verify("conn",{},owner,"concurrent"))]);assert.equal(a.identity.id,b.identity.id);assert.equal(db.prepare("SELECT COUNT(*) c FROM provider_account_identities WHERE idempotency_key='concurrent'").get().c,1);}));
  await t.test("latest observation ordering is deterministic",()=>within("wa",()=>{const latest=repository.latest("conn"),expected=db.prepare("SELECT id FROM provider_account_identities WHERE workspace_id='wa' AND connection_id='conn' ORDER BY verified_at DESC,id DESC LIMIT 1").get();assert.equal(latest.id,expected.id);}));
  await t.test("cursor pagination is typed, bounded, deterministic, and tenant-leading",()=>within("wa",()=>{const one=service.list("conn",{limit:1}),two=service.list("conn",{limit:1,cursor:one.nextCursor});assert.notEqual(one.items[0].id,two.items[0].id);assert.throws(()=>service.list("conn",{limit:101}));assert.throws(()=>service.list("conn",{cursor:"bad!"}),e=>e.code==="INVALID_CURSOR");assert.throws(()=>service.list("conn",{cursor:encodeCursor("wrong",{verifiedAt:AT,id:"x"})}),e=>e.code==="INVALID_CURSOR");const plan=db.prepare("EXPLAIN QUERY PLAN SELECT * FROM provider_account_identities WHERE workspace_id=? AND connection_id=? ORDER BY verified_at DESC,id DESC LIMIT ?").all("wa","conn",51).map(x=>x.detail).join(" ");assert.match(plan,/idx_provider_account_identities_connection_page/);}));
  await t.test("database guards connector identity, workspace, user, membership, role, hashes, methods, and immutability",()=>within("wa",()=>{assert.throws(()=>db.prepare("UPDATE provider_account_identities SET safe_display_label='changed' WHERE id=?").run(first.id),/immutable/);assert.throws(()=>db.prepare("DELETE FROM provider_account_identities WHERE id=?").run(first.id),/immutable/);const row=db.prepare("SELECT * FROM provider_account_identities WHERE id=?").get(first.id),insert=(copy)=>db.prepare(`INSERT INTO provider_account_identities(${Object.keys(copy).join(",")})VALUES(${Object.keys(copy).map(()=>"?").join(",")})`).run(...Object.values(copy));for(const [id,change] of [["bad-workspace",{workspace_id:"wb"}],["bad-connector",{connector_id:"other"}],["bad-user",{verified_by_user_id:"missing"}],["bad-member",{verified_by_membership_id:"m-member",verified_by_user_id:"member",verified_by_role:"owner"}],["bad-role",{verified_by_role:"member"}],["bad-hash",{external_account_key_hash:"A".repeat(64)}],["bad-method",{verification_method:"MANUAL"}]])assert.throws(()=>insert({...row,id,idempotency_key:id,...change}));}));
  await t.test("HTTP exposes verify/list/detail only and production POST is stably unavailable",async()=>{const app=express();app.use(express.json());app.use((req,res,next)=>{req.user={id:"owner"};req.membership={id:"m-owner",role:"owner"};runWithWorkspace("wa",next);});app.use("/api",createProviderAccountIdentityRouter({service:production}));const listening=await new Promise(resolve=>{const server=app.listen(0,"127.0.0.1",()=>resolve({server,port:server.address().port}));}),base=`http://127.0.0.1:${listening.port}/api`;let response=await fetch(`${base}/integrations/connections/conn/account-identities/verify`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":"http"},body:"{}"});assert.equal(response.status,409);assert.equal((await response.json()).code,"IDENTITY_VERIFICATION_UNAVAILABLE");assert.equal((await fetch(`${base}/integrations/connections/conn/account-identities`)).status,200);assert.equal((await fetch(`${base}/provider-account-identities/missing`)).status,404);for(const method of ["PUT","PATCH","DELETE"])assert.equal((await fetch(`${base}/provider-account-identities/${first.id}`,{method})).status,404);await new Promise(resolve=>listening.server.close(resolve));});
  await t.test("metrics are bounded and exclude account identity, labels, credentials, evidence, and keys",()=>{const data=JSON.stringify(metrics.recent());for(const forbidden of [rawAccount,first.externalAccountKeyHash,"Safe Fixture","bounded-evidence",HASH_KEY,"owner-1"])assert.equal(data.includes(forbidden),false);assert.ok(metrics.recent().some(x=>x.operation==="provider_identity.verify"&&Object.hasOwn(x,"identityCount")&&Object.hasOwn(x,"providerKind")&&Object.hasOwn(x,"verificationMethod")));});
  await t.test("identity sources have no provider calls, secrets, messaging, execution, workers, AI, or environment dependency",()=>{const paths=["../app/provider-account-identities/identity-hashing.mjs","../app/provider-account-identities/verifier-contract.mjs","../app/provider-account-identities/verifier-registry.mjs","../app/repositories/provider-account-identity-repository.mjs","../app/services/provider-account-identity-service.mjs","../app/routes/provider-account-identities.mjs"],source=paths.map(path=>readFileSync(new URL(path,import.meta.url),"utf8")).join("\n").toLowerCase();for(const forbidden of ["process.env","resend","kavenegar","messaging.mjs","provider-adapter","automation","openai","embedding","semantic_findings","job_queue","execution_attempts","execution_results"])assert.equal(source.includes(forbidden),false);});
  await t.test("fixture and migration databases preserve integrity and foreign keys",()=>{assert.equal(db.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(db.pragma("foreign_key_check"),[]);assert.equal(scope.pragma("integrity_check",{simple:true}),"ok");assert.deepEqual(scope.pragma("foreign_key_check"),[]);});

  scope.close();db.close();rmSync(dir,{recursive:true,force:true});
});
