import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import { readFileSync } from "node:fs";
import Database from "better-sqlite3";
import sharp from "sharp";
import { migration049ContentAssets } from "../db/migrations/049_content_assets.mjs";
import { migration050RealAssetUpload } from "../db/migrations/050_real_asset_upload.mjs";
import { runMigrations } from "../db/migrate.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createContentAssetRepository } from "../app/repositories/content-asset-repository.mjs";
import { createContentAssetService } from "../app/services/content-asset-service.mjs";
import { createTestOnlyInsecureMemoryContentAssetStore } from "../app/content-assets/content-asset-store.mjs";
import { acceptOptimization, MEDIA_OPTIMIZATION_POLICY } from "../app/content-assets/media-optimization-policy.mjs";
import { createBoundedSemaphore } from "../app/content-assets/media-concurrency.mjs";
import { maintainContentAssets } from "../scripts/maintain-content-assets.mjs";
import { assertContentAssetStore } from "../app/content-assets/content-asset-store.mjs";
import { createR2ContentAssetStore } from "../app/content-assets/r2-content-asset-store.mjs";

const AT = "2026-08-22T10:00:00.000Z";
function fixture() {
  const db = new Database(":memory:"); db.pragma("foreign_keys=ON");
  db.exec(`CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);CREATE TABLE workspaces(id TEXT PRIMARY KEY,name TEXT,slug TEXT,status TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE users(id TEXT PRIMARY KEY,mobile TEXT,name TEXT,email TEXT,status TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,role TEXT,status TEXT,created_at TEXT,updated_at TEXT);INSERT INTO workspaces VALUES('wa','wa','wa','active','${AT}','${AT}');INSERT INTO users VALUES('owner','09','owner',NULL,'active','${AT}','${AT}');INSERT INTO workspace_memberships VALUES('m','wa','owner','owner','active','${AT}','${AT}');`);
  runMigrations(db, [migration049ContentAssets, migration050RealAssetUpload]); const store = createTestOnlyInsecureMemoryContentAssetStore(); let sequence = 0, tick = Date.parse(AT);
  const repository = createContentAssetRepository(db), service = createContentAssetService({ repository, store, now: () => new Date(tick += 1000), id: () => `asset-${++sequence}` });
  return { db, store, repository, service };
}

test("Real Asset Upload + Storage Optimization v1", async (t) => {
  await t.test("migration 050 is minimal and idempotent", () => { const f = fixture(); runMigrations(f.db, [migration050RealAssetUpload]); assert.deepEqual(f.db.prepare("SELECT COUNT(*) count,MAX(version) max FROM schema_migrations WHERE version=50").get(), { count: 1, max: 50 }); assert.equal(f.db.pragma("integrity_check", { simple: true }), "ok"); f.db.close(); });
  await t.test("optimization decision requires quality compatibility and meaningful savings", () => { assert.equal(acceptOptimization({ originalBytes: 1000, candidateBytes: 800, qualityPassed: true, compatibilityPassed: true, minimumSavingPercent: 15 }).accepted, true); assert.equal(acceptOptimization({ originalBytes: 1000, candidateBytes: 900, qualityPassed: true, compatibilityPassed: true, minimumSavingPercent: 15 }).accepted, false); assert.equal(acceptOptimization({ originalBytes: 1000, candidateBytes: 500, qualityPassed: false, compatibilityPassed: true, minimumSavingPercent: 15 }).accepted, false); });
  await t.test("signed intent binds exact server key and completion verifies and promotes", async () => { const f = fixture(), body = await sharp({ create: { width: 400, height: 400, channels: 4, background: { r: 20, g: 30, b: 40, alpha: 0 } } }).png().toBuffer(), sha = crypto.createHash("sha256").update(body).digest("hex"), actor = { userId: "owner", role: "owner" }; const intent = await runWithWorkspace("wa", () => f.service.createUploadIntent({ mediaType: "IMAGE", declaredMimeType: "image/png", declaredByteSize: body.length, declaredSha256: sha, originalFilename: "لوگو.png" }, actor, "intent")); assert.equal(intent.method, "PUT"); const stored = runWithWorkspace("wa", () => f.repository.findById(intent.assetId)); assert.equal(stored.storageObjectKey, `workspaces/wa/content-assets/${intent.assetId}/original`); f.store.testOnlyInjectObject({ storageProvider: "TEST_MEMORY", storageObjectKey: stored.storageObjectKey }, { body, byteSize: body.length, contentSha256: sha, contentType: "image/png" }); const ready = await runWithWorkspace("wa", () => f.service.complete(intent.assetId, actor)); assert.equal(ready.status, "READY"); assert.equal(ready.canonicalMimeType, "image/webp"); assert.equal(ready.optimizationOutcome, "LOSSLESS_OPTIMIZED"); f.db.close(); });
  await t.test("checksum mismatch rejects without destroying source", async () => { const f = fixture(), body = Buffer.from("not-an-image"), sha = crypto.createHash("sha256").update(body).digest("hex"), actor = { userId: "owner", role: "owner" }; const intent = await runWithWorkspace("wa", () => f.service.createUploadIntent({ mediaType: "IMAGE", declaredMimeType: "image/png", declaredByteSize: body.length, declaredSha256: sha, originalFilename: "x.png" }, actor, "bad")); const asset = runWithWorkspace("wa", () => f.repository.findById(intent.assetId)); f.store.testOnlyInjectObject({ storageProvider: "TEST_MEMORY", storageObjectKey: asset.storageObjectKey }, { body, byteSize: body.length, contentSha256: "f".repeat(64) }); await assert.rejects(runWithWorkspace("wa", () => f.service.complete(asset.id, actor)), (error) => error.code === "CONTENT_ASSET_INTEGRITY_FAILED"); assert.equal(runWithWorkspace("wa", () => f.repository.findById(asset.id)).status, "REJECTED"); f.db.close(); });
  await t.test("policy keeps 7-day recovery and 100 MiB MVP video ingress", () => { assert.equal(MEDIA_OPTIMIZATION_POLICY.sourceRecoveryMs, 7 * 86400000); assert.equal(MEDIA_OPTIMIZATION_POLICY.video.maxUploadBytes, 100 * 1024 * 1024); });
  await t.test("verification semaphore rejects excess capacity without an in-memory queue", () => { const semaphore = createBoundedSemaphore(1), release = semaphore.tryAcquire(); assert.equal(typeof release, "function"); assert.equal(semaphore.tryAcquire(), null); release(); assert.equal(typeof semaphore.tryAcquire(), "function"); });
  await t.test("durable backend identity is provider-neutral", () => { const f = fixture(); const columns = f.db.prepare("SELECT name FROM pragma_table_info('content_assets')").all().map(({ name }) => name); assert.ok(columns.includes("storage_backend_kind")); assert.equal(columns.includes("active_storage_provider"), false); const sql = f.db.prepare("SELECT sql FROM sqlite_schema WHERE type='table' AND name='content_assets'").get().sql; assert.match(sql, /OBJECT_STORAGE/); assert.doesNotMatch(sql, /\bR2\b|website_project_id|page_id|section_id|campaign_id|ad_id/); f.db.close(); });
  await t.test("maintenance is bounded, one-shot, tenant-leading, and index-backed", async () => { const f = fixture(), actor = { userId: "owner", role: "owner" }, input = { mediaType: "IMAGE", declaredMimeType: "image/png", declaredByteSize: 10, declaredSha256: "a".repeat(64), originalFilename: "x.png" }; runWithWorkspace("wa", () => f.service.createFoundationIntent(input, actor, "stale")); const result = await maintainContentAssets({ database: f.db, store: f.store, now: new Date("2026-08-24T10:00:00.000Z"), limit: 1 }); assert.deepEqual(result, { examined: 1, deleted: 1, failed: 0, storageUnavailable: false }); const plan = f.db.prepare("EXPLAIN QUERY PLAN SELECT * FROM content_assets WHERE workspace_id=? AND status=? AND updated_at<=? ORDER BY updated_at,id LIMIT ?").all("wa", "UPLOADING", "2026-08-24T10:00:00.000Z", 1); assert.match(JSON.stringify(plan), /idx_content_assets_workspace_maintenance/); f.db.close(); });
  await t.test("R2 adapter satisfies the replaceable neutral store contract without import-time network access", () => { const store = createR2ContentAssetStore({ accountId: "test", bucket: "private", accessKeyId: "test", secretAccessKey: "test", mediaRuntimeAvailable: true }); assert.equal(assertContentAssetStore(store), store); assert.equal(store.configured, true); assert.equal(store.uploadEnabled, true); assert.equal(store.backendKind, "OBJECT_STORAGE"); const serviceSource = readFileSync(new URL("../app/services/content-asset-service.mjs", import.meta.url), "utf8"); assert.doesNotMatch(serviceSource, /\bR2\b|@aws-sdk/); });
});
