import assert from "node:assert/strict";
import test from "node:test";
import { gzipSync } from "node:zlib";
import Database from "better-sqlite3";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runMigrations } from "../db/migrate.mjs";
import { migration058WebsiteBuilderFoundation } from "../db/migrations/058_website_builder_foundation.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createWebsiteRepository } from "../app/repositories/website-repository.mjs";
import { createWebsiteService } from "../app/services/website-service.mjs";
import { landingComponentRegistry } from "../app/landing/landing-component-registry.mjs";
import { createLandingPublisher } from "../app/landing/landing-publisher.mjs";
import { createWebsitePublisher } from "../app/website/website-publisher.mjs";
import { websitePresetRegistry } from "../app/website/website-preset-registry.mjs";
import { evaluateVisualManifest } from "../app/visual-components/visual-component-policy.mjs";
import { geometricPatternManifest, glowBandsManifest, gradientFieldManifest, visualComponentRegistry } from "../app/visual-components/visual-component-registry.mjs";
import { createVisualPublicationDescriptor, renderStaticVisualPublication, validatePinnedVisualDescriptor, validateVisualPublicationPage, visualPublishingCompatibility } from "../app/visual-publishing/visual-publisher-contract.mjs";
import { createWebsiteVisualBindings, renderWebsiteVisualBindings } from "../app/website/website-visual-revision.mjs";

const PACK = Object.freeze([gradientFieldManifest, glowBandsManifest, geometricPatternManifest]);
const IDS = Object.freeze(PACK.map(manifest => manifest.componentId));
const W = "workspace", actor = { userId: "user", role: "member" };
const theme = Object.freeze({ font: "brand", primaryColor: "#6633ff", secondaryColor: "#116677", backgroundColor: "#f8fafc", foregroundColor: "#111827", mutedColor: "#64748b", radius: "lg", spacingDensity: "comfortable", buttonStyle: "solid", containerWidth: "standard" });
const section = (id, title = id) => ({ id, componentId: "HERO", version: 1, variant: "CENTERED", props: { headline: title, body: "محتوای معنایی مستقل", primaryCta: { label: "رزرو", type: "BOOKING", target: "https://example.com/book" } }, contentBindings: [], assetBindings: [], trackingBindings: [{ action: "CTA_CLICK" }] });
const blueprint = (ids = ["hero"], title = "صفحه") => ({ goal: "حضور پایدار", offer: "معرفی خدمات", audienceSummary: "مخاطب کسب‌وکار", primaryCta: { label: "رزرو", type: "BOOKING", target: "https://example.com/book" }, secondaryCta: null, seo: { title, description: "توضیح معتبر" }, socialPreview: { title, description: "معرفی", imageAssetId: null }, sections: ids.map(id => section(id)), designTokens: theme, tracking: { enabledActions: ["LANDING_VISIT", "CTA_CLICK"] }, accessibility: { mainLabel: title } });
const visualRequest = (componentId, sectionId = "hero", props = {}) => ({ sectionId, componentId, componentVersion: 1, props, assetRefs: [] });
const descriptor = (componentId, props = {}) => createVisualPublicationDescriptor({ componentId, componentVersion: 1, props, assetRefs: [] });
const within = fn => runWithWorkspace(W, fn);

function base() { const db = new Database(":memory:"); db.pragma("foreign_keys=ON"); db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,role TEXT,status TEXT);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE creative_placements(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE content_assets(id TEXT PRIMARY KEY,workspace_id TEXT,status TEXT);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('workspace','active');INSERT INTO workspace_memberships VALUES('m','workspace','user','member','active');INSERT INTO business_context_versions VALUES('context','workspace');"); runMigrations(db, [migration058WebsiteBuilderFoundation]); return db; }
function fixture(directory) { const db = base(), repository = createWebsiteRepository(db), landingPublisher = createLandingPublisher({ nodeEnv: "production", staticDirectory: directory, publicBaseUrl: "https://site.example", publicApiBaseUrl: "https://api.example" }), publisher = createWebsitePublisher({ landingPublisher, visualRegistry: visualComponentRegistry }), service = createWebsiteService({ repository, contextRepository: { getVersion: id => id === "context" ? { id } : null }, placementRepository: { findById: () => null }, assetRepository: { findById: () => null }, componentRegistry: landingComponentRegistry, presetRegistry: websitePresetRegistry, visualRegistry: visualComponentRegistry, publisher, now: () => new Date("2026-08-24T18:00:00.000Z") }); const project = within(() => service.createProject({ name: "سایت", slug: "primitive-pack", websiteType: "MEDICAL", presetId: "CLINIC", businessContextVersionId: "context", locale: "fa-IR", direction: "rtl", theme }, actor, "site")).website; return { db, repository, publisher, service, project }; }
function createPage(f, index, componentId) { const page = within(() => f.service.createPage(f.project.id, { pageType: index ? "CUSTOM_PAGE" : "HOME", name: `صفحه ${index}`, path: index ? `/page-${index}` : "/", navigationVisible: true, navigationOrder: index }, actor, `page-${index}`)).page, revision = within(() => f.service.createVisualBlueprint(page.id, { blueprint: blueprint(["hero"], page.name), visualRequests: [visualRequest(componentId)] }, actor, `revision-${index}`)).blueprint; return { page, revision }; }

test("Loadder Static Visual Primitive Pack v1", async t => {
  await t.test("selects exactly three distinct Loadder-native production primitives", () => { assert.deepEqual(IDS, ["LOADDER_GRADIENT_FIELD", "LOADDER_GLOW_BANDS", "LOADDER_GEOMETRIC_PATTERN"]); assert.equal(new Set(IDS).size, 3); assert.equal(visualComponentRegistry.list().length, 5); });
  await t.test("all manifests pass unchanged admission with static no-asset restrictions", () => { for (const manifest of PACK) { const result = evaluateVisualManifest(manifest); assert.equal(result.state, "ADMITTED_WITH_RESTRICTIONS"); assert.equal(manifest.runtimeTier, "STATIC"); assert.equal(manifest.assetPolicy, "NO_ASSETS"); assert.equal(manifest.provider, "LOADDER_NATIVE"); assert.ok(result.restrictions.includes("DECORATIVE_ONLY")); assert.ok(result.restrictions.includes("NO_PRIMARY_CONTENT")); assert.ok(result.restrictions.includes("MAX_ONE_PER_PAGE")); assert.match(visualComponentRegistry.get(manifest.componentId, 1).fingerprint, /^[0-9a-f]{64}$/); } });
  await t.test("publisher compatibility and defaults are conservative", () => { for (const id of IDS) { const compatibility = visualPublishingCompatibility(id, 1); assert.equal(compatibility.state, "PUBLISHABLE_WITH_RESTRICTIONS"); const output = renderStaticVisualPublication([descriptor(id)], { designTokens: theme }); assert.match(output.markup, /aria-hidden="true"/); assert.match(output.css, /pointer-events:none/); assert.doesNotMatch(output.markup + output.css, /<script|iframe|onerror|onclick|@import|url\(|animation|javascript:/i); } });
  await t.test("bounded variants and approved theme tokens produce distinct deterministic output", () => { const cases = [["LOADDER_GRADIENT_FIELD", { variant: "HALO", intensity: "BALANCED", accentToken: "PRIMARY" }], ["LOADDER_GLOW_BANDS", { orientation: "HORIZONTAL", intensity: "STRONG", accentToken: "SECONDARY" }], ["LOADDER_GEOMETRIC_PATTERN", { pattern: "CHEVRON", density: "DENSE", intensity: "BALANCED", accentToken: "MUTED" }]]; for (const [id, props] of cases) { const a = renderStaticVisualPublication([descriptor(id, props)], { designTokens: theme }), b = renderStaticVisualPublication([descriptor(id, props)], { designTokens: theme }); assert.deepEqual(a, b); assert.match(a.css, new RegExp(theme[props.accentToken === "PRIMARY" ? "primaryColor" : props.accentToken === "SECONDARY" ? "secondaryColor" : "mutedColor"], "i")); } });
  await t.test("every primitive rejects unknown enum token CSS URL HTML and executable payloads", () => { const attacks = [{ unknown: "x" }, { intensity: "MAXIMUM" }, { accentToken: "UNKNOWN" }, { css: "body{display:none}" }, { background: "url(https://evil.test/x)" }, { style: "position:fixed" }, { payload: "<script>alert(1)</script>" }, { className: "onerror=alert(1)" }]; for (const id of IDS) for (const props of attacks) assert.throws(() => descriptor(id, props), error => error.code === "VISUAL_PROPS_INVALID"); });
  await t.test("unknown versions and all asset references fail closed", () => { for (const id of IDS) { assert.throws(() => createVisualPublicationDescriptor({ componentId: id, componentVersion: 999, props: {}, assetRefs: [] })); assert.throws(() => createVisualPublicationDescriptor({ componentId: id, componentVersion: 1, props: {}, assetRefs: ["foreign"] })); } });
  await t.test("mixed pack coexists with exact section binding and isolated CSS", () => { const page = blueprint(["atmosphere", "emphasis", "structure"]), bindings = createWebsiteVisualBindings(page, IDS.map((id, index) => visualRequest(id, page.sections[index].id))), rendered = renderWebsiteVisualBindings(page, bindings); assert.equal(rendered.length, 3); assert.equal(new Set(rendered.map(item => item.sectionId)).size, 3); assert.equal(new Set(rendered.map(item => item.checksum)).size, 3); for (const item of rendered) { assert.match(item.css, /ld-visual-scope-[0-9a-f]{16}/); assert.doesNotMatch(item.css, /(?:^|[},])(?:body|html|\*|h1|p|button)(?:[{,])/); } });
  await t.test("global four-visual budget passes and five fails", () => { const ids = [...IDS, "LOADDER_STATIC_DOT_FIELD"], page = blueprint(ids.map((_, index) => `s${index}`)), four = createWebsiteVisualBindings(page, ids.map((id, index) => visualRequest(id, `s${index}`))); assert.equal(four.length, 4); assert.throws(() => createWebsiteVisualBindings(blueprint(["a", "b", "c", "d", "e"]), [...ids.map((id, index) => visualRequest(id, String.fromCharCode(97 + index))), visualRequest(IDS[0], "e") ])); });
  await t.test("MAX_ONE_PER_PAGE rejects duplicate primitive instances", () => { const page = blueprint(["a", "b"]); for (const id of IDS) assert.throws(() => createWebsiteVisualBindings(page, [visualRequest(id, "a"), visualRequest(id, "b")])); });
  await t.test("section reorder preserves identity and deletion fails closed", () => { const original = blueprint(["a", "b"]), bindings = createWebsiteVisualBindings(original, [visualRequest(IDS[0], "b")]), reordered = { ...original, sections: [...original.sections].reverse() }; assert.equal(renderWebsiteVisualBindings(reordered, bindings)[0].sectionId, "b"); assert.throws(() => renderWebsiteVisualBindings(blueprint(["a"]), bindings)); });
  await t.test("three-page canonical Website publication is reproducible and immutable", () => { const directory = mkdtempSync(join(tmpdir(), "loadder-static-pack-")); try { const f = fixture(directory), pages = IDS.map((id, index) => createPage(f, index, id)), first = within(() => f.service.publish(f.project.id, {}, actor, "publish")), second = f.publisher.publish({ project: f.project, pages: pages.map(item => ({ page: item.page, blueprint: item.revision })) }); assert.equal(first.publication.manifest.pages.length, 3); assert.equal(second.manifestHash, first.publication.manifestHash); for (const page of first.publication.manifest.pages) { const html = readFileSync(join(directory, page.artifactPath), "utf8"); assert.match(html, /ld-(gradient-field|glow-bands|geometric-pattern)/); assert.match(html, /dir="rtl"/); assert.match(html, /<h1>/); } const clone = within(() => f.service.cloneBlueprint(pages[0].page.id, pages[0].revision.id, actor, "clone")).blueprint; assert.deepEqual(clone.blueprint.websiteVisualDescriptors, pages[0].revision.blueprint.websiteVisualDescriptors); assert.throws(() => f.db.prepare("UPDATE website_page_blueprint_versions SET blueprint_json='{}' WHERE id=?").run(pages[0].revision.id)); } finally { rmSync(directory, { recursive: true, force: true }); } });
  await t.test("configuration changes checksum without changing historical revision", () => { const page = blueprint(), old = createWebsiteVisualBindings(page, [visualRequest(IDS[0], "hero", { variant: "AURORA" })]), newer = createWebsiteVisualBindings(page, [visualRequest(IDS[0], "hero", { variant: "HALO" })]); const oldOutput = renderWebsiteVisualBindings(page, old), newOutput = renderWebsiteVisualBindings(page, newer); assert.notEqual(oldOutput[0].checksum, newOutput[0].checksum); assert.equal(old[0].descriptor.props.variant, "AURORA"); });
  await t.test("manifest drift blocks historical descriptor while identity remains preserved", () => { for (const id of IDS) { const pinned = descriptor(id), changed = structuredClone(pinned); changed.manifestFingerprint = "0".repeat(64); assert.throws(() => validatePinnedVisualDescriptor(changed), error => error.code === "VISUAL_MANIFEST_FINGERPRINT_MISMATCH"); assert.equal(pinned.componentVersion, 1); } });
  await t.test("raw output footprint remains bounded", () => { const sizes = Object.fromEntries(IDS.map(id => { const output = renderStaticVisualPublication([descriptor(id)], { designTokens: theme }), html = Buffer.byteLength(output.markup), css = Buffer.byteLength(output.css), combined = html + css; assert.ok(combined < 1400); return [id, { html, css, combined, gzip: gzipSync(output.markup + output.css, { mtime: 0 }).length }]; })); t.diagnostic(JSON.stringify({ outputSizes: sizes })); });
  await t.test("10,000 pack admission validation and render cycles are deterministic", () => { const descriptors = IDS.map(id => descriptor(id)), startAdmission = performance.now(); for (let index = 0; index < 10_000; index += 1) evaluateVisualManifest(PACK[index % PACK.length]); const admissionMs = performance.now() - startAdmission, startValidation = performance.now(); for (let index = 0; index < 10_000; index += 1) validatePinnedVisualDescriptor(descriptors[index % descriptors.length]); const validationMs = performance.now() - startValidation, startRender = performance.now(); for (let index = 0; index < 10_000; index += 1) renderStaticVisualPublication([descriptors[index % descriptors.length]], { designTokens: theme }); const renderMs = performance.now() - startRender; assert.ok(admissionMs + validationMs + renderMs < 10_000); t.diagnostic(JSON.stringify({ iterations: 10_000, admission: { totalMs: +admissionMs.toFixed(3), meanMs: +(admissionMs / 10_000).toFixed(6) }, validation: { totalMs: +validationMs.toFixed(3), meanMs: +(validationMs / 10_000).toFixed(6) }, render: { totalMs: +renderMs.toFixed(3), meanMs: +(renderMs / 10_000).toFixed(6) } })); });
  await t.test("native WebGL remains pilot-only and pack does not alter runtime policy", () => { assert.equal(visualComponentRegistry.get("LOADDER_DOT_MATRIX", 1).admission.state, "PILOT_ONLY"); assert.equal(visualPublishingCompatibility("LOADDER_DOT_MATRIX", 1).state, "PUBLISH_BLOCKED"); assert.throws(() => validateVisualPublicationPage([descriptor(IDS[0]), descriptor(IDS[1]), descriptor(IDS[2]), descriptor("LOADDER_STATIC_DOT_FIELD"), descriptor(IDS[0])])); });
});
