import assert from "node:assert/strict";
import test from "node:test";
import Database from "better-sqlite3";
import { runMigrations } from "../db/migrate.mjs";
import { migration045ContentGenerations } from "../db/migrations/045_content_generations.mjs";
import { migration047ContentItems } from "../db/migrations/047_content_items.mjs";
import { migration048ContentItemSourceIdentity } from "../db/migrations/048_content_item_source_identity.mjs";
import { migration049ContentAssets } from "../db/migrations/049_content_assets.mjs";
import { migration050RealAssetUpload } from "../db/migrations/050_real_asset_upload.mjs";
import { migration051UploadedCreativeLinkage } from "../db/migrations/051_uploaded_creative_linkage.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createContentItemRepository } from "../app/repositories/content-item-repository.mjs";
import { createContentAssetRepository } from "../app/repositories/content-asset-repository.mjs";
import { createContentItemService } from "../app/services/content-item-service.mjs";
import { generationContractRegistry } from "../app/content-generation/contract-registry.mjs";
import { contentPlacementRegistry } from "../app/content-generation/placement-registry.mjs";
import { createOperationMetrics } from "../app/observability/operation-metrics.mjs";

const AT="2026-08-22T10:00:00.000Z", SHA="a".repeat(64), actor={userId:"user",role:"member"};
function fixture(){const db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT NOT NULL);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);");runMigrations(db,[migration045ContentGenerations,migration047ContentItems,migration048ContentItemSourceIdentity,migration049ContentAssets,migration050RealAssetUpload,migration051UploadedCreativeLinkage]);db.exec("INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('workspace','active');INSERT INTO workspaces VALUES('other','active');INSERT INTO workspace_memberships VALUES('member','workspace','user','member','active');");const add=(id,status="READY",media="IMAGE",workspace="workspace")=>db.prepare("INSERT INTO content_assets(id,workspace_id,created_by_user_id,media_type,declared_mime_type,declared_byte_size,declared_sha256,mime_type,byte_size,content_sha256,width,height,duration_ms,original_filename,storage_provider,storage_object_key,status,failure_code,operation_kind,idempotency_key,request_hash,upload_expires_at,ready_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL,'content_asset.intent',?,?,?,?,?,?)").run(id,workspace,"user",media,media==="IMAGE"?"image/png":"video/mp4",100,SHA,media==="IMAGE"?"image/png":"video/mp4",100,SHA,800,600,media==="VIDEO"?1000:null,"creative", "TEST_MEMORY",`workspaces/${workspace}/content-assets/${id}/original`,status,`asset-${id}`,SHA,"2026-08-23T10:00:00.000Z",status==="READY"?AT:null,AT,AT);add("ready");add("uploading","UPLOADING");add("video","READY","VIDEO");const assets=createContentAssetRepository(db),items=createContentItemRepository(db),service=createContentItemService({repository:items,generationRepository:{},assetRepository:assets,contractRegistry:generationContractRegistry,placementRegistry:contentPlacementRegistry,operationMetrics:createOperationMetrics(),now:()=>new Date(AT)});return{db,assets,items,service};}
const within=(fn)=>runWithWorkspace("workspace",fn);
test("Uploaded Creative Linkage v1",async t=>{
 await t.test("migration 051 is idempotent and adds the nullable asset FK",()=>{const f=fixture();runMigrations(f.db,[migration051UploadedCreativeLinkage]);assert.equal(f.db.prepare("SELECT count(*) n FROM schema_migrations WHERE version=51").get().n,1);assert.ok(f.db.prepare("SELECT 1 FROM pragma_table_info('content_items') WHERE name='primary_asset_id'").get());assert.deepEqual(f.db.pragma("foreign_key_check"),[]);});
 await t.test("READY asset creates truthful metadata-only library item",()=>{const f=fixture(),result=within(()=>f.service.createFromAsset({assetId:"ready",title:"بنر"},actor,"key"));assert.equal(result.item.sourceType,"CLIENT_UPLOADED");assert.equal(result.item.mediaType,"IMAGE");assert.equal(result.item.primaryAsset.id,"ready");assert.equal(result.item.contractId,null);assert.deepEqual(result.item.content,{});assert.equal(JSON.stringify(result.item).includes("storageObjectKey"),false);});
 await t.test("non-ready asset is rejected",()=>{const f=fixture();assert.throws(()=>within(()=>f.service.createFromAsset({assetId:"uploading",title:"بنر"},actor,"key")),e=>e.code==="CONTENT_ASSET_NOT_READY");});
 await t.test("every non-READY lifecycle state is rejected",()=>{for(const status of ["VERIFYING","REJECTED","FAILED","DELETING","DELETED"]){const f=fixture();f.db.exec("DROP TRIGGER trg_content_assets_transition_guard");f.db.prepare("UPDATE content_assets SET status=?,failure_code=?,deletion_requested_at=?,deleted_at=? WHERE id='uploading'").run(status,["REJECTED","FAILED"].includes(status)?"TEST_FAILURE":null,["DELETING","DELETED"].includes(status)?AT:null,status==="DELETED"?AT:null);assert.throws(()=>within(()=>f.service.createFromAsset({assetId:"uploading",title:"بنر"},actor,`key-${status}`)),e=>e.code==="CONTENT_ASSET_NOT_READY");}});
 await t.test("idempotency and changed-request conflict are enforced",()=>{const f=fixture(),a=within(()=>f.service.createFromAsset({assetId:"ready",title:"بنر"},actor,"key")),b=within(()=>f.service.createFromAsset({assetId:"ready",title:"بنر"},actor,"key"));assert.equal(a.item.id,b.item.id);assert.throws(()=>within(()=>f.service.createFromAsset({assetId:"ready",title:"دیگر"},actor,"key")),e=>e.code==="CONTENT_ITEM_IDEMPOTENCY_CONFLICT");});
 await t.test("duplicate retains the same asset without storage operations",()=>{const f=fixture(),a=within(()=>f.service.createFromAsset({assetId:"video",title:"ویدیو"},actor,"key")),b=within(()=>f.service.duplicate(a.item.id,{},actor,"copy"));assert.equal(b.item.primaryAsset.id,"video");assert.equal(f.db.prepare("SELECT count(*) n FROM content_assets").get().n,3);});
 await t.test("binary PATCH is title-only and asset lineage is immutable",()=>{const f=fixture(),a=within(()=>f.service.createFromAsset({assetId:"ready",title:"بنر"},actor,"key"));assert.throws(()=>within(()=>f.service.update(a.item.id,{content:{x:1},expectedRevision:1},actor)),e=>e.code==="CONTENT_ITEM_INVALID");const b=within(()=>f.service.update(a.item.id,{title:"بنر تازه",expectedRevision:1},actor));assert.equal(b.title,"بنر تازه");assert.throws(()=>f.db.prepare("UPDATE content_items SET primary_asset_id='video',revision=revision+1,updated_at='2026-08-22T11:00:00.000Z' WHERE id=?").run(a.item.id));});
 await t.test("referenced-asset query is indexed",()=>{const f=fixture();const plan=f.db.prepare("EXPLAIN QUERY PLAN SELECT 1 FROM content_items WHERE workspace_id=? AND primary_asset_id=? LIMIT 1").all("workspace","ready");assert.match(JSON.stringify(plan),/idx_content_items_workspace_primary_asset/);});
});
