import assert from "node:assert/strict";
import test from "node:test";
import Database from "better-sqlite3";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runMigrations } from "../db/migrate.mjs";
import { migration058WebsiteBuilderFoundation } from "../db/migrations/058_website_builder_foundation.mjs";
import { runWithWorkspace } from "../app/tenant-context.mjs";
import { createWebsiteRepository } from "../app/repositories/website-repository.mjs";
import { createWebsiteService } from "../app/services/website-service.mjs";
import { landingHash } from "../app/landing/landing-contracts.mjs";
import { landingComponentRegistry } from "../app/landing/landing-component-registry.mjs";
import { createLandingPublisher } from "../app/landing/landing-publisher.mjs";
import { createWebsitePublisher } from "../app/website/website-publisher.mjs";
import { websitePresetRegistry } from "../app/website/website-preset-registry.mjs";
import { createVisualComponentRegistry, safeCssDecorativeManifest, visualComponentRegistry } from "../app/visual-components/visual-component-registry.mjs";
import { createWebsiteVisualBindings, validateWebsiteVisualBindings } from "../app/website/website-visual-revision.mjs";

const W = "workspace", OTHER = "other", actor = { userId: "user", role: "member" };
const theme = { font: "brand", primaryColor: "#6633ff", secondaryColor: "#111122", backgroundColor: "#050510", foregroundColor: "#ffffff", mutedColor: "#aaaabb", radius: "lg", spacingDensity: "comfortable", buttonStyle: "solid", containerWidth: "standard" };
const blueprint = (title = "خانه") => ({ goal: "حضور پایدار", offer: "معرفی خدمات", audienceSummary: "مخاطب کسب‌وکار", primaryCta: { label: "رزرو", type: "BOOKING", target: "https://example.com/book" }, secondaryCta: null, seo: { title, description: "توضیح معتبر" }, socialPreview: { title, description: "معرفی", imageAssetId: null }, sections: [{ id: "hero", componentId: "HERO", version: 1, variant: "CENTERED", props: { headline: title, body: "متن معتبر", primaryCta: { label: "رزرو", type: "BOOKING", target: "https://example.com/book" } }, contentBindings: [], assetBindings: [], trackingBindings: [{ action: "CTA_CLICK" }] }], designTokens: theme, tracking: { enabledActions: ["LANDING_VISIT", "CTA_CLICK"] }, accessibility: { mainLabel: title } });
const request = (overrides = {}) => ({ sectionId: "hero", componentId: "LOADDER_STATIC_DOT_FIELD", componentVersion: 1, props: {}, assetRefs: [], ...overrides });
const within = fn => runWithWorkspace(W, fn);

function base() {
  const db = new Database(":memory:"); db.pragma("foreign_keys=ON");
  db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspaces(id TEXT PRIMARY KEY,status TEXT);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,role TEXT,status TEXT);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE creative_placements(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE content_assets(id TEXT PRIMARY KEY,workspace_id TEXT,status TEXT);CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);INSERT INTO users VALUES('user','active');INSERT INTO workspaces VALUES('workspace','active'),('other','active');INSERT INTO workspace_memberships VALUES('m','workspace','user','member','active');INSERT INTO business_context_versions VALUES('context','workspace');");
  runMigrations(db, [migration058WebsiteBuilderFoundation]); return db;
}

function fixture({ registry = visualComponentRegistry, staticDirectory = "" } = {}) {
  const db = base(), repository = createWebsiteRepository(db), landingPublisher = createLandingPublisher({ nodeEnv: staticDirectory ? "production" : "test", staticDirectory, publicBaseUrl: staticDirectory ? "https://example.test" : "", publicApiBaseUrl: staticDirectory ? "https://api.example.test" : "" }), publisher = createWebsitePublisher({ landingPublisher, visualRegistry: registry });
  const service = createWebsiteService({ repository, contextRepository: { getVersion: id => id === "context" ? { id } : null }, placementRepository: { findById: () => null }, assetRepository: { findById: () => null }, componentRegistry: landingComponentRegistry, presetRegistry: websitePresetRegistry, visualRegistry: registry, publisher, now: () => new Date("2026-08-24T12:00:00.000Z") });
  const project = within(() => service.createProject({ name: "سایت", slug: "visual-site", websiteType: "MEDICAL", presetId: "CLINIC", businessContextVersionId: "context", locale: "fa-IR", direction: "rtl", theme }, actor, "site")).website;
  const page = within(() => service.createPage(project.id, { pageType: "HOME", name: "خانه", path: "/", navigationVisible: true, navigationOrder: 0 }, actor, "page")).page;
  return { db, repository, landingPublisher, publisher, service, project, page };
}

const createVisual = (f, key = "visual", value = blueprint(), visualRequests = [request()]) => within(() => f.service.createVisualBlueprint(f.page.id, { blueprint: value, visualRequests }, actor, key)).blueprint;

test("Website Revision Visual Descriptor Integration v1", async t => {
  await t.test("stores the exact server-derived descriptor in canonical immutable revision state", () => { const f = fixture(), revision = createVisual(f), stored = revision.blueprint.websiteVisualDescriptors[0]; assert.equal(stored.sectionId, "hero"); assert.equal(stored.descriptor.componentId, "LOADDER_STATIC_DOT_FIELD"); assert.equal(revision.contentHash, landingHash(revision.blueprint)); assert.throws(() => f.db.prepare("UPDATE website_page_blueprint_versions SET blueprint_json='{}' WHERE id=?").run(revision.id)); });
  await t.test("publishes deterministic static markup and compact audit manifest", () => { const directory = mkdtempSync(join(tmpdir(), "loadder-website-visual-")); try { const f = fixture({ staticDirectory: directory }), revision = createVisual(f), first = within(() => f.service.publish(f.project.id, {}, actor, "publish-1")), page = first.publication.manifest.pages[0], html = readFileSync(join(directory, page.artifactPath), "utf8"); assert.equal(page.visualDescriptors.length, 1); assert.equal(page.visualDescriptors[0].manifestFingerprint, revision.blueprint.websiteVisualDescriptors[0].descriptor.manifestFingerprint); assert.match(html, /data-loadder-visual-checksum=/); assert.match(html, /ld-static-dot-field/); assert.doesNotMatch(html, /<iframe|onclick=|onload=|webgl|three/i); const second = f.publisher.publish({ project: f.project, pages: [{ page: f.page, blueprint: revision }] }); assert.equal(second.manifest.pages[0].artifactChecksum, page.artifactChecksum); assert.equal(second.manifestHash, first.publication.manifestHash); } finally { rmSync(directory, { recursive: true, force: true }); } });
  await t.test("customer blueprint route cannot submit descriptor authority", () => { const f = fixture(), forged = { ...blueprint(), websiteVisualDescriptors: [{ sectionId: "hero", descriptor: { manifestFingerprint: "forged" } }] }; assert.throws(() => within(() => f.service.createBlueprint(f.page.id, { blueprint: forged }, actor, "forged")), error => error.code === "WEBSITE_BLUEPRINT_INVALID"); });
  await t.test("unknown identity, native pilot, invalid props, remote assets, and arbitrary URLs fail closed", () => { const cases = [request({ componentId: "UNKNOWN_COMPONENT" }), request({ componentId: "LOADDER_DOT_MATRIX" }), request({ props: { unknown: true } }), request({ assetRefs: ["foreign_asset"] }), request({ props: { url: "https://evil.test" } })]; for (const [index, visual] of cases.entries()) { const f = fixture(); assert.throws(() => createVisual(f, `bad-${index}`, blueprint(), [visual])); } });
  await t.test("section identity is exact and arbitrary DOM selectors are rejected", () => { const f = fixture(); assert.throws(() => createVisual(f, "selector", blueprint(), [request({ sectionId: "#hero .child" })])); });
  await t.test("clone copies the immutable descriptor exactly without repinning", () => { const f = fixture(), original = createVisual(f), clone = within(() => f.service.cloneBlueprint(f.page.id, original.id, actor, "clone")).blueprint; assert.equal(clone.supersedesBlueprintId, original.id); assert.deepEqual(clone.blueprint.websiteVisualDescriptors, original.blueprint.websiteVisualDescriptors); assert.equal(clone.contentHash, original.contentHash); });
  await t.test("new visual configuration creates a new checksum while preserving history", () => { const manifest = { ...safeCssDecorativeManifest, propsSchema: Object.freeze({ intensity: Object.freeze({ type: "boundedNumber", minimum: 0, maximum: 1 }) }) }, registry = createVisualComponentRegistry([manifest]), f = fixture({ registry }), old = createVisual(f, "old", blueprint(), [request({ props: { intensity: .25 } })]), newer = createVisual(f, "new", blueprint(), [request({ props: { intensity: .75 } })]); assert.notEqual(old.contentHash, newer.contentHash); assert.equal(old.blueprint.websiteVisualDescriptors[0].descriptor.props.intensity, .25); assert.equal(newer.blueprint.websiteVisualDescriptors[0].descriptor.props.intensity, .75); const a = f.publisher.publish({ project: f.project, pages: [{ page: f.page, blueprint: old }] }), b = f.publisher.publish({ project: f.project, pages: [{ page: f.page, blueprint: newer }] }); assert.notEqual(a.manifest.pages[0].artifactChecksum, b.manifest.pages[0].artifactChecksum); });
  await t.test("registry fingerprint and current-policy drift block republish without rewriting history", () => { const f = fixture(), revision = createVisual(f), pinned = structuredClone(revision.blueprint.websiteVisualDescriptors); const drifted = createVisualComponentRegistry([{ ...safeCssDecorativeManifest, displayName: "Drifted" }]), publisher = createWebsitePublisher({ landingPublisher: f.landingPublisher, visualRegistry: drifted }); assert.throws(() => publisher.publish({ project: f.project, pages: [{ page: f.page, blueprint: revision }] }), error => error.code === "VISUAL_MANIFEST_FINGERPRINT_MISMATCH"); assert.deepEqual(revision.blueprint.websiteVisualDescriptors, pinned); const revoked = createVisualComponentRegistry([{ ...safeCssDecorativeManifest, securityPosture: Object.freeze({ ...safeCssDecorativeManifest.securityPosture, remoteCode: true }) }]); assert.throws(() => createWebsitePublisher({ landingPublisher: f.landingPublisher, visualRegistry: revoked }).publish({ project: f.project, pages: [{ page: f.page, blueprint: revision }] })); });
  await t.test("page budget is bounded and independently evaluated", () => { const manifest = { ...safeCssDecorativeManifest, instanceBudget: Object.freeze({ maxInstancesPerPage: 20 }), accessibilityPolicy: "SEMANTIC_SUPPORTED", seoPolicy: "SEMANTIC_DOM_PRESERVED" }, registry = createVisualComponentRegistry([manifest]), page = blueprint(), one = createWebsiteVisualBindings(page, [request()], { registry }); assert.equal(validateWebsiteVisualBindings(page, one, { registry }).length, 1); const four = Array.from({ length: 4 }, (_, index) => ({ ...request(), sectionId: `section-${index}` })), multi = { ...page, sections: four.map((_, index) => ({ ...page.sections[0], id: `section-${index}` })) }; assert.equal(createWebsiteVisualBindings(multi, four, { registry }).length, 4); assert.throws(() => createWebsiteVisualBindings({ ...multi, sections: [...multi.sections, { ...page.sections[0], id: "section-4" }] }, [...four, { ...request(), sectionId: "section-4" }], { registry })); });
  await t.test("tenant boundaries hide foreign Website identities", () => { const f = fixture(); assert.throws(() => runWithWorkspace(OTHER, () => f.service.createVisualBlueprint(f.page.id, { blueprint: blueprint(), visualRequests: [request()] }, actor, "foreign")), error => error.code === "WEBSITE_PAGE_NOT_FOUND"); });
  await t.test("10,000 pinned revision validations remain deterministic", () => { const page = blueprint(), bindings = createWebsiteVisualBindings(page, [request()]), start = performance.now(); for (let index = 0; index < 10_000; index += 1) validateWebsiteVisualBindings(page, bindings); const totalMs = performance.now() - start; assert.ok(totalMs < 5000); assert.equal(validateWebsiteVisualBindings(page, bindings)[0].descriptor.manifestFingerprint, bindings[0].descriptor.manifestFingerprint); t.diagnostic(JSON.stringify({ validations: 10_000, totalMs: Number(totalMs.toFixed(3)), meanMs: Number((totalMs / 10_000).toFixed(6)) })); });
});
