import assert from"node:assert/strict";
import test from"node:test";
import{classifyWorkflowIntentRecovery,workflowIntentRecoveryPolicy}from"../app/user-outcomes/workflow-intent-recovery-policy.mjs";
import{createWorkflowOutcomeService}from"../app/services/workflow-outcome-service.mjs";
import{deriveDogfoodBaseline}from"../app/internal-quality/tqm-dogfood-engine.mjs";

const START="2026-08-24T10:00:00.000Z",at=minutes=>new Date(Date.parse(START)+minutes*60_000);
const intent=terminalPosture=>({terminalPosture,startedAt:START});
const outcomeRepository=rows=>({list:()=>rows});
const evidence=measurementIntegrityPosture=>({benchmark:{caseCount:1,humanEvaluationAvailable:false},economy:{verifiedPricing:false},reliability:{engineeringTestsPassed:true,productionEvidenceAvailable:true,productionHealthy:true},latency:{benchmarkAvailable:true},security:{evidenceAvailable:true,critical:0,high:0},storage:{bytes:1,pages:1,boundedRetention:true},userOutcome:{available:true,healthy:measurementIntegrityPosture!=="MEASUREMENT_INTEGRITY_GAP",measurementIntegrityPosture}});

test("Workflow Intent recovery and measurement integrity v1",async t=>{
 await t.test("versioned thresholds exceed the provider timeout and classify boundaries deterministically",()=>{assert.equal(workflowIntentRecoveryPolicy.version,1);assert.ok(workflowIntentRecoveryPolicy.activeThroughMs>workflowIntentRecoveryPolicy.providerTimeoutMs);assert.ok(workflowIntentRecoveryPolicy.orphanedAfterMs>workflowIntentRecoveryPolicy.activeThroughMs);assert.equal(classifyWorkflowIntentRecovery(intent("STARTED"),at(1)).posture,"ACTIVE");assert.equal(classifyWorkflowIntentRecovery(intent("STARTED"),at(3)).posture,"AGING");assert.equal(classifyWorkflowIntentRecovery(intent("STARTED"),at(15)).posture,"ORPHANED_UNKNOWN");});
 await t.test("canonical terminal states remain terminal regardless of age",()=>{assert.equal(classifyWorkflowIntentRecovery(intent("COMPLETED"),at(1000)).posture,"COMPLETED");assert.equal(classifyWorkflowIntentRecovery(intent("FAILED"),at(1000)).posture,"FAILED");});
 await t.test("future timestamps fail safe as ACTIVE instead of replayable",()=>{const result=classifyWorkflowIntentRecovery(intent("STARTED"),at(-5));assert.equal(result.posture,"ACTIVE");assert.equal(result.reasonCode,"CLOCK_SKEW_FAIL_SAFE_ACTIVE");});
 await t.test("stale unresolved starts are unknown, never failures or abandonment",()=>{const service=createWorkflowOutcomeService({repository:outcomeRepository([{sourceEntityId:"unknown",startedAt:START,completedAt:null,acceptedAt:null,rejectedAt:null,usedAt:null,failedEvidence:false,terminalPosture:"STARTED"}]),now:()=>at(20)}),item=service.instances("GROWTH_STRATEGY").instances[0],summary=service.summary({workflowType:"GROWTH_STRATEGY"}).summaries[0];assert.equal(item.outcomePosture,"OUTCOME_UNKNOWN");assert.equal(item.recoveryPosture,"ORPHANED_UNKNOWN");assert.equal(summary.validStarts,1);assert.equal(summary.resolvedStarts,0);assert.equal(summary.unknownStarts,1);assert.equal(summary.failed,0);assert.equal(summary.abandoned,0);assert.equal(summary.measurementIntegrityPosture,"MEASUREMENT_INTEGRITY_GAP");});
 await t.test("confirmed rates use resolved starts and coverage uses all valid starts",()=>{const rows=[{sourceEntityId:"done",startedAt:START,completedAt:at(1).toISOString(),failedEvidence:false,terminalPosture:"COMPLETED"},{sourceEntityId:"failed",startedAt:START,completedAt:null,failedEvidence:true,terminalPosture:"FAILED"},{sourceEntityId:"unknown",startedAt:START,completedAt:null,failedEvidence:false,terminalPosture:"STARTED"}],summary=createWorkflowOutcomeService({repository:outcomeRepository(rows),now:()=>at(20)}).summary({workflowType:"GROWTH_STRATEGY"}).summaries[0];assert.equal(summary.validStarts,3);assert.equal(summary.resolvedStarts,2);assert.equal(summary.unknownStarts,1);assert.equal(summary.confirmedCompletionRate,.5);assert.equal(summary.confirmedTechnicalFailureRate,.5);assert.equal(summary.resolutionCoverage,.6667);assert.equal(summary.confirmedCompletionRateDenominator,"RESOLVED_STARTS");});
 await t.test("TQM reports measurement integrity rather than provider failure",()=>{const baseline=deriveDogfoodBaseline(evidence("MEASUREMENT_INTEGRITY_GAP")),constraint=baseline.constraintCandidates.find(x=>x.category==="MEASUREMENT_INTEGRITY_GAP");assert.ok(constraint);assert.ok(constraint.reasonCodes.includes("UNKNOWN_OUTCOMES_NOT_PROVIDER_FAILURES"));assert.equal(baseline.constraintCandidates.some(x=>x.category==="PROVIDER_FAILURE_SPIKE"),false);});
});
