import assert from"node:assert/strict";
import test from"node:test";
import Database from"better-sqlite3";
import{runMigrations}from"../db/migrate.mjs";
import{migration067AiNativeGrowthWorkflow}from"../db/migrations/067_ai_native_growth_workflow.mjs";
import{migration069CanonicalWorkflowIntents}from"../db/migrations/069_canonical_workflow_intents.mjs";
import{runWithWorkspace}from"../app/tenant-context.mjs";
import{createGrowthWorkflowRepository}from"../app/repositories/growth-workflow-repository.mjs";
import{createGrowthWorkflowService}from"../app/services/growth-workflow-service.mjs";
import{createGrowthRateLimiter}from"../app/growth/growth-rate-limiter.mjs";
import{createAiOperationRegistry}from"../app/ai/ai-operation-registry.mjs";
import{createWorkflowOutcomeRepository}from"../app/repositories/workflow-outcome-repository.mjs";
import{createWorkflowOutcomeService}from"../app/services/workflow-outcome-service.mjs";

const AT="2026-08-24T10:00:00.000Z",W="wi-workspace",U="wi-user",actor={userId:U,role:"owner"};
const strategy={strategySummary:"رشد سنجش‌پذیر",strategicObjective:"افزایش درخواست",targetSegments:[{name:"مدیران",need:"اعتماد",opportunity:"راهنما",priority:"HIGH"}],positioning:{current:"عمومی",recommended:"متخصص",differentiation:["شواهد"]},growthPillars:[{title:"اعتماد",rationale:"کاهش ابهام",priority:"HIGH",horizon:"NOW"}],channelPriorities:[{channel:"وب",role:"مرجع",priority:"HIGH"}],funnelPriorities:[{stage:"CONVERSION",objective:"درخواست",priority:"HIGH"}],contentThemes:[{title:"راهنما",purpose:"آموزش",audience:"مدیران"}],conversionOpportunities:[{title:"مشاوره",rationale:"مسیر روشن",recommendedSurface:"LANDING"}],risks:[{title:"داده کم",mitigation:"اندازه‌گیری"}],recommendedNextSteps:["بازبینی"],confidenceScore:80};
function database(){const db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec(`CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,name TEXT,applied_at TEXT);CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE workspaces(id TEXT PRIMARY KEY);CREATE TABLE workspace_memberships(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,role TEXT,status TEXT);CREATE TABLE business_profiles(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE business_dna_versions(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE brand_book_versions(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE business_context_versions(id TEXT PRIMARY KEY,workspace_id TEXT,status TEXT,business_profile_id TEXT,business_dna_version_id TEXT,brand_book_version_id TEXT);INSERT INTO users VALUES('${U}'),('wi-other-user');INSERT INTO workspaces VALUES('${W}'),('wi-other');INSERT INTO workspace_memberships VALUES('wi-membership','${W}','${U}','owner','active'),('wi-other-membership','wi-other','wi-other-user','owner','active');INSERT INTO business_profiles VALUES('wi-profile','${W}'),('wi-other-profile','wi-other');INSERT INTO business_dna_versions VALUES('wi-dna','${W}'),('wi-other-dna','wi-other');INSERT INTO brand_book_versions VALUES('wi-brand','${W}'),('wi-other-brand','wi-other');INSERT INTO business_context_versions VALUES('wi-context','${W}','active','wi-profile','wi-dna','wi-brand'),('wi-other-context','wi-other','active','wi-other-profile','wi-other-dna','wi-other-brand');`);runMigrations(db,[migration067AiNativeGrowthWorkflow,migration069CanonicalWorkflowIntents]);return db;}
function fixture({providerFailure=false,times=[AT,"2026-08-24T10:00:05.000Z"]}={}){const db=database(),repository=createGrowthWorkflowRepository(db),calls=[],clock=[...times];const service=createGrowthWorkflowService({repository,contextRepository:{getActiveVersion:()=>({id:"wi-context",businessProfileId:"wi-profile",businessDnaVersionId:"wi-dna",brandBookVersionId:"wi-brand",snapshot:{profile:{name:"کسب‌وکار"}}}),getCurrentSources:()=>({profile:{},dna:{},brandBook:{}})},provider:{async executeStructured(input){calls.push(input);if(providerFailure){const error=new Error("secret provider detail");error.code="AI_PROVIDER_TIMEOUT";throw error;}return{data:structuredClone(strategy)};}},policyRegistry:createAiOperationRegistry(),rateLimiter:createGrowthRateLimiter({userLimit:100,workspaceLimit:100}),landingService:{},websiteService:{},contentGenerationService:{},now:()=>new Date(clock.shift()||times.at(-1))});return{db,repository,service,calls};}
const within=(fn,workspace=W)=>runWithWorkspace(workspace,fn);

test("Workflow Intent canonical START v1",async t=>{
 await t.test("migration 069 is one-table idempotent scope with compact guards",()=>{const db=database();runMigrations(db,[migration069CanonicalWorkflowIntents]);assert.equal(db.prepare("SELECT count(*) n FROM schema_migrations WHERE version=69").get().n,1);assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='table' AND name='workflow_intents'").get().n,1);assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='index' AND tbl_name='workflow_intents' AND sql IS NOT NULL").get().n,2);assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE type='trigger' AND tbl_name='workflow_intents'").get().n,3);db.close();});
 await t.test("valid authorized intent starts before provider and links exactly to strategy",async()=>{const f=fixture(),result=await within(()=>f.service.generateStrategy({objective:"افزایش درخواست"},actor,"intent-1")),row=f.db.prepare("SELECT * FROM workflow_intents").get();assert.equal(f.calls.length,1);assert.equal(row.started_at,AT);assert.equal(row.terminal_posture,"COMPLETED");assert.equal(row.completed_entity_id,result.strategy.id);assert.equal(result.intentId,row.id);f.db.close();});
 await t.test("invalid, unauthorized, and client-authoritative requests create no START",async()=>{const f=fixture();for(const [input,currentActor,key] of [[{objective:""},actor,"empty"],[{objective:"valid",startedAt:AT},actor,"forged-time"],[{objective:"valid",terminalPosture:"COMPLETED"},actor,"forged-state"],[{objective:"valid",completedEntityId:"x"},actor,"forged-link"],[{objective:"valid"},{userId:U,role:"viewer"},"forbidden"]])await assert.rejects(within(()=>f.service.generateStrategy(input,currentActor,key)));assert.equal(f.db.prepare("SELECT count(*) n FROM workflow_intents").get().n,0);assert.equal(f.calls.length,0);f.db.close();});
 await t.test("provider failure preserves one bounded FAILED intent without raw error",async()=>{const f=fixture({providerFailure:true});await assert.rejects(within(()=>f.service.generateStrategy({objective:"رشد"},actor,"fails")));const row=f.db.prepare("SELECT * FROM workflow_intents").get();assert.equal(row.terminal_posture,"FAILED");assert.equal(row.error_code,"AI_PROVIDER_TIMEOUT");assert.equal(row.completed_entity_id,null);assert.equal(JSON.stringify(row).includes("secret provider detail"),false);f.db.close();});
 await t.test("same retry converges while same payload with a new key is a new intent",async()=>{const f=fixture(),a=await within(()=>f.service.generateStrategy({objective:"رشد"},actor,"same")),b=await within(()=>f.service.generateStrategy({objective:"رشد"},actor,"same")),c=await within(()=>f.service.generateStrategy({objective:"رشد"},actor,"new"));assert.equal(a.strategy.id,b.strategy.id);assert.equal(b.reusedResult,true);assert.notEqual(c.strategy.id,a.strategy.id);assert.equal(f.db.prepare("SELECT count(*) n FROM workflow_intents").get().n,2);assert.equal(f.calls.length,2);f.db.close();});
 await t.test("idempotency payload mismatch fails and user/workspace scopes cannot collide",async()=>{const f=fixture();await within(()=>f.service.generateStrategy({objective:"اول"},actor,"collision"));await assert.rejects(within(()=>f.service.generateStrategy({objective:"دوم"},actor,"collision")),e=>e.code==="GROWTH_IDEMPOTENCY_CONFLICT");assert.equal(f.db.prepare("SELECT count(*) n FROM workflow_intents").get().n,1);assert.throws(()=>within(()=>f.repository.createIntent({id:"foreign",userId:"wi-other-user",requestIdentityHash:"a".repeat(64),requestHash:"b".repeat(64),at:AT})));f.db.close();});
 await t.test("evidence fields and deletion are immutable and foreign linkage fails closed",async()=>{const f=fixture(),result=await within(()=>f.service.generateStrategy({objective:"رشد"},actor,"immutable")),id=result.intentId;for(const sql of["UPDATE workflow_intents SET started_at='2020-01-01T00:00:00.000Z' WHERE id=?","UPDATE workflow_intents SET terminal_posture='FAILED',completed_entity_id=NULL,error_code='X' WHERE id=?","DELETE FROM workflow_intents WHERE id=?"])assert.throws(()=>f.db.prepare(sql).run(id));const pending=within(()=>f.repository.createIntent({id:"pending",userId:U,requestIdentityHash:"a".repeat(64),requestHash:"b".repeat(64),at:AT}));f.db.prepare("INSERT INTO growth_strategies(id,workspace_id,version_number,status,business_context_version_id,business_profile_id,business_dna_version_id,brand_book_version_id,objective,strategy_json,operation_id,created_by_user_id,created_at)VALUES('foreign-strategy','wi-other',1,'PROPOSED','wi-other-context','wi-other-profile','wi-other-dna','wi-other-brand','x','{}','GROWTH_STRATEGY_GENERATION','wi-other-user',?)").run(AT);assert.throws(()=>f.db.prepare("UPDATE workflow_intents SET terminal_posture='COMPLETED',completed_entity_id='foreign-strategy' WHERE id=?").run(pending.id));f.db.close();});
 await t.test("canonical outcome derives exact completion, acceptance, rejection and usage times",async()=>{const f=fixture({times:[AT,"2026-08-24T10:00:05.000Z","2026-08-24T10:00:20.000Z"]}),result=await within(()=>f.service.generateStrategy({objective:"رشد"},actor,"timed"));within(()=>f.service.review("strategy",result.strategy.id,"APPROVED",actor));f.db.prepare("INSERT INTO growth_content_plans(id,workspace_id,growth_strategy_id,version_number,status,plan_json,operation_id,created_by_user_id,created_at)VALUES('wi-plan',?,?,1,'PROPOSED','{}','CONTENT_PLAN_GENERATION',?,'2026-08-24T10:01:00.000Z')").run(W,result.strategy.id,U);const outcome=createWorkflowOutcomeService({repository:createWorkflowOutcomeRepository(f.db),now:()=>new Date("2026-08-24T12:00:00.000Z")}),item=within(()=>outcome.instances("GROWTH_STRATEGY")).instances[0];assert.equal(item.timeToCompletionMs,5000);assert.equal(item.timeToAcceptanceMs,20000);assert.equal(item.timeToUsageMs,60000);assert.equal(item.timeToProductValueSignalMs,60000);assert.equal(item.timeToValidatedValueMs,null);assert.equal(item.validatedValuePosture,"NOT_YET_VALIDATED");f.db.close();});
 await t.test("negative and missing timestamps fail safe to null",()=>{const service=createWorkflowOutcomeService({repository:{list:()=>[{sourceEntityId:"x",startedAt:"2026-08-24T10:00:10.000Z",completedAt:"2026-08-24T10:00:00.000Z",acceptedAt:null,rejectedAt:null,usedAt:null}]},now:()=>new Date("2026-08-24T12:00:00.000Z")}),item=service.instances("GROWTH_STRATEGY").instances[0];assert.equal(item.timeToCompletionMs,null);assert.equal(item.timeToAcceptanceMs,null);});
 await t.test("schema contains metadata only and no content/provider/customer fields",()=>{const db=database(),sql=db.prepare("SELECT sql FROM sqlite_schema WHERE type='table' AND name='workflow_intents'").get().sql.toLowerCase();for(const forbidden of["objective","prompt","business_context","strategy_json","provider","token","email","phone","crm","metadata"])assert.equal(sql.includes(forbidden),false);db.close();});
});
