import { useEffect, useMemo, useState } from "react";
import { apiUrl } from "../lib/api";

type Store = { id: string; name: string; slug: string };
type Address = { id:string;label?:string|null;name:string;phone:string;email?:string|null;country?:string|null;province?:string|null;city:string;address1:string;address2?:string|null;postalCode?:string|null };
type Account = { id:string;revision:number;profile:{displayName?:string|null;phone?:string|null};addresses:Address[];defaultShippingAddressId?:string|null;defaultBillingAddressId?:string|null };
type Order = { id:string;status:string;paymentStatus:string;fulfillmentStatus:string;currency:string;totalMinor:number;createdAt:string };
const emptyAddress={label:"",name:"",phone:"",email:"",country:"IR",province:"",city:"",address1:"",address2:"",postalCode:""};

export default function PublicCustomerAccountPanel({projectId,token,stores}:{projectId:string;token:string;stores:Store[]}){
  const [storeId,setStoreId]=useState(stores[0]?.id||"");
  const [account,setAccount]=useState<Account|null>(null),[orders,setOrders]=useState<Order[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [profile,setProfile]=useState({displayName:"",phone:""});
  const [address,setAddress]=useState<Record<string,string>>(emptyAddress),[editingId,setEditingId]=useState<string|null>(null);
  const base=useMemo(()=>`/api/auth/public/apps/${projectId}/commerce/stores/${storeId}/me`,[projectId,storeId]);
  const headers=(revision?:number)=>({"X-Loadder-App-Token":token,...(revision?{"If-Match":String(revision)}:{})});
  async function api(path:string,init:RequestInit={}){const r=await fetch(apiUrl(path),{...init,credentials:"omit",headers:{...(init.body?{"Content-Type":"application/json"}:{}),...headers(),...(init.headers||{})}});const b=await r.json();if(!r.ok)throw Object.assign(new Error(b.message||b.code||"عملیات ناموفق بود."),{status:r.status,code:b.code});return b;}
  async function load(){if(!storeId)return;setBusy(true);setMessage("");try{let r=await fetch(apiUrl(base),{headers:headers(),credentials:"omit"}),b=await r.json();if(r.status===404){b=await api(base,{method:"POST"});}else if(!r.ok)throw new Error(b.message||b.code);const a=b.account as Account;setAccount(a);setProfile({displayName:a.profile?.displayName||"",phone:a.profile?.phone||""});const o=await api(`${base}/orders`);setOrders(o.orders||[]);}catch(e){setMessage(e instanceof Error?e.message:"خطا در دریافت حساب");}finally{setBusy(false)}}
  useEffect(()=>{load().catch(()=>{})},[storeId]);
  async function mutate(path:string,method:string,body?:unknown){if(!account)return;setBusy(true);setMessage("");try{const b=await api(path,{method,headers:{"If-Match":String(account.revision)},body:body?JSON.stringify(body):undefined});setAccount(b.account);setProfile({displayName:b.account.profile?.displayName||"",phone:b.account.profile?.phone||""});setMessage("ذخیره شد.");return b.account as Account;}catch(e:any){if(e?.status===409){setMessage("اطلاعات در جای دیگری تغییر کرده؛ دوباره بارگذاری شد.");await load();}else setMessage(e instanceof Error?e.message:"عملیات ناموفق بود.");return null;}finally{setBusy(false)}}
  async function saveProfile(){await mutate(base,"PATCH",{profile});}
  async function saveAddress(){const payload={address};const next=editingId?await mutate(`${base}/addresses/${editingId}`,"PATCH",payload):await mutate(`${base}/addresses`,"POST",{...payload,makeDefaultShipping:account?.addresses.length===0});if(next){setAddress(emptyAddress);setEditingId(null);}}
  function edit(a:Address){setEditingId(a.id);setAddress({label:a.label||"",name:a.name||"",phone:a.phone||"",email:a.email||"",country:a.country||"",province:a.province||"",city:a.city||"",address1:a.address1||"",address2:a.address2||"",postalCode:a.postalCode||""});}
  async function defaults(id:string,shipping:boolean,billing:boolean){await mutate(`${base}/addresses/${id}/defaults`,"PUT",{shipping,billing});}
  async function remove(id:string){await mutate(`${base}/addresses/${id}`,"DELETE");}
  if(!stores.length)return <div className="rounded-2xl border border-white/10 p-6 text-sm text-white/50">فروشگاه متصل فعالی برای این حساب پیدا نشد.</div>;
  return <section className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold">حساب من</h2><p className="mt-1 text-xs text-white/40">پروفایل، آدرس‌ها و سفارش‌های متصل به حساب شما</p></div><select value={storeId} onChange={e=>setStoreId(e.target.value)} className="rounded-xl border border-white/10 bg-[#111318] px-3 py-2 text-sm">{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>
    {busy&&!account?<p className="text-sm text-white/45">در حال بارگذاری...</p>:null}
    {account&&<><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 p-5"><h3 className="font-semibold">پروفایل</h3><label className="mt-4 block text-xs text-white/45">نام نمایشی<input value={profile.displayName} onChange={e=>setProfile(x=>({...x,displayName:e.target.value}))} className="mt-1 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/></label><label className="mt-3 block text-xs text-white/45">تلفن<input value={profile.phone} onChange={e=>setProfile(x=>({...x,phone:e.target.value}))} className="mt-1 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/></label><button disabled={busy} onClick={saveProfile} className="mt-4 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">ذخیره پروفایل</button></div>
    <div className="rounded-2xl border border-white/10 p-5"><h3 className="font-semibold">{editingId?"ویرایش آدرس":"آدرس جدید"}</h3><div className="mt-4 grid gap-2 sm:grid-cols-2">{[["label","عنوان"],["name","نام گیرنده"],["phone","تلفن"],["city","شهر"],["province","استان"],["postalCode","کدپستی"],["address1","آدرس"],["address2","ادامه آدرس"]].map(([k,l])=><label key={k} className={`text-xs text-white/45 ${k==="address1"||k==="address2"?"sm:col-span-2":""}`}>{l}<input value={address[k]||""} onChange={e=>setAddress(x=>({...x,[k]:e.target.value}))} className="mt-1 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/></label>)}</div><div className="mt-4 flex gap-2"><button disabled={busy} onClick={saveAddress} className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">{editingId?"ذخیره تغییرات":"افزودن آدرس"}</button>{editingId&&<button onClick={()=>{setEditingId(null);setAddress(emptyAddress)}} className="rounded-xl border border-white/10 px-4 py-2 text-sm">انصراف</button>}</div></div></div>
    <div className="rounded-2xl border border-white/10 p-5"><h3 className="font-semibold">آدرس‌های ذخیره‌شده</h3><div className="mt-4 grid gap-3 lg:grid-cols-2">{account.addresses.map(a=><div key={a.id} className="rounded-xl border border-white/10 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{a.label||a.name}</p><p className="mt-1 text-sm text-white/55">{a.city}، {a.address1}</p><p className="mt-1 text-xs text-white/35">{a.phone}</p></div><div className="text-left text-[10px] text-white/40">{account.defaultShippingAddressId===a.id&&<div>ارسال پیش‌فرض</div>}{account.defaultBillingAddressId===a.id&&<div>صورتحساب پیش‌فرض</div>}</div></div><div className="mt-3 flex flex-wrap gap-2 text-xs"><button onClick={()=>edit(a)} className="rounded-lg border border-white/10 px-2.5 py-1.5">ویرایش</button><button onClick={()=>defaults(a.id,true,false)} className="rounded-lg border border-white/10 px-2.5 py-1.5">پیش‌فرض ارسال</button><button onClick={()=>defaults(a.id,false,true)} className="rounded-lg border border-white/10 px-2.5 py-1.5">پیش‌فرض صورتحساب</button><button onClick={()=>remove(a.id)} className="rounded-lg border border-red-500/20 px-2.5 py-1.5 text-red-300">حذف</button></div></div>)}{!account.addresses.length&&<p className="text-sm text-white/35">هنوز آدرسی ذخیره نشده است.</p>}</div></div>
    <div className="rounded-2xl border border-white/10 p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">سفارش‌های من</h3><button onClick={load} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">به‌روزرسانی</button></div><div className="mt-4 space-y-2">{orders.map(o=><div key={o.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 p-3 text-sm"><div><p className="font-medium">{o.id}</p><p className="text-xs text-white/35">{new Date(o.createdAt).toLocaleString("fa-IR")}</p></div><div className="text-left"><p>{Number(o.totalMinor).toLocaleString("fa-IR")} {o.currency}</p><p className="text-xs text-white/40">{o.paymentStatus} · {o.fulfillmentStatus}</p></div></div>)}{!orders.length&&<p className="text-sm text-white/35">سفارش متصل به این حساب وجود ندارد.</p>}</div></div></>}
    {message&&<p className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/55">{message}</p>}
  </section>;
}
