import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle, MagnifyingGlass, PencilSimple, Plus, Robot, RocketLaunch, Trash } from "@phosphor-icons/react";
import { apiFetch } from "../../lib/api";

type Field={id:string;type:string;required?:boolean;options?:string[];references?:string};
type Entity={id:string;name:string;fields:Field[]};
type Definition={id:string;name:string;entities:Entity[];workflows:Array<{id:string;name:string}>};
type Props={projectId:string;definition:Definition};
type RecordRow={id:string;createdAt?:string;updatedAt?:string;[key:string]:unknown};
type DeployReadiness={approved:boolean;providerConfigured:boolean;canaryPercent:number;healthCheckRequired:boolean;rollbackSupported:boolean;status:string};
const PAGE_SIZE=12;
function inputType(field:Field){if(field.type==="email")return"email";if(field.type==="date")return"date";if(field.type==="datetime")return"datetime-local";if(["integer","decimal","money"].includes(field.type))return"number";return"text";}

export default function GeneratedAppRuntime({projectId,definition}:Props){
  const [entityId,setEntityId]=useState(definition.entities[0]?.id||""),[records,setRecords]=useState<RecordRow[]>([]),[query,setQuery]=useState(""),[form,setForm]=useState<Record<string,unknown>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[editingId,setEditingId]=useState<string|null>(null),[page,setPage]=useState(0),[total,setTotal]=useState(0),[refs,setRefs]=useState<Record<string,RecordRow[]>>({}),[copilotInput,setCopilotInput]=useState(""),[copilotAnswer,setCopilotAnswer]=useState(""),[deploy,setDeploy]=useState<DeployReadiness|null>(null);
  const entity=useMemo(()=>definition.entities.find(x=>x.id===entityId)||definition.entities[0],[definition,entityId]);
  const pageCount=Math.max(1,Math.ceil(total/PAGE_SIZE));

  async function load(){if(!entity)return;const qs=new URLSearchParams({limit:String(PAGE_SIZE),offset:String(page*PAGE_SIZE)});if(query.trim())qs.set("q",query.trim());const r=await apiFetch(`/api/business-builder/projects/${projectId}/data/${entity.id}?${qs}`);const b=await r.json();if(r.ok&&b.success){setRecords(b.records||[]);setTotal(Number(b.total||0));}}
  async function loadReferences(){if(!entity)return;const next:Record<string,RecordRow[]>={};for(const f of entity.fields.filter(x=>x.type==="reference"&&x.references)){const r=await apiFetch(`/api/business-builder/projects/${projectId}/data/${f.references}?limit=100`);const b=await r.json();if(r.ok&&b.success)next[f.id]=b.records||[];}setRefs(next);}
  async function loadDeploy(){const r=await apiFetch(`/api/business-builder/projects/${projectId}/deployment-readiness`);const b=await r.json();if(r.ok&&b.success)setDeploy(b.readiness);}
  useEffect(()=>{setForm({});setEditingId(null);setPage(0);loadReferences().catch(()=>{});loadDeploy().catch(()=>{});},[entity?.id,projectId]);
  useEffect(()=>{const t=setTimeout(()=>load().catch(()=>{}),220);return()=>clearTimeout(t);},[entity?.id,projectId,page,query]);

  async function save(){if(!entity)return;setBusy(true);setMessage("");try{const payload=Object.fromEntries(Object.entries(form).filter(([,v])=>v!==""&&v!==undefined));const url=`/api/business-builder/projects/${projectId}/data/${entity.id}${editingId?`/${editingId}`:""}`;const r=await apiFetch(url,{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok||!b.success)throw new Error(b.message||"ذخیره رکورد ناموفق بود.");setForm({});setEditingId(null);await load();setMessage(editingId?"تغییرات ذخیره شد.":"رکورد ثبت شد.");}catch(e){setMessage(e instanceof Error?e.message:"خطا");}finally{setBusy(false);}}
  async function remove(id:string){if(!entity)return;await apiFetch(`/api/business-builder/projects/${projectId}/data/${entity.id}/${id}`,{method:"DELETE"});await load();}
  function edit(row:RecordRow){if(!entity)return;const next:Record<string,unknown>={};entity.fields.forEach(f=>{next[f.id]=row[f.id]??"";});setForm(next);setEditingId(row.id);}
  async function runWorkflow(workflowId:string){const r=await apiFetch(`/api/business-builder/projects/${projectId}/workflows/${workflowId}/run`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entityId})});const b=await r.json();setMessage(r.ok&&b.success?`Workflow اجرا شد: ${b.result.status}`:(b.message||"اجرای Workflow ناموفق بود."));}
  async function askCopilot(){const r=await apiFetch(`/api/business-builder/projects/${projectId}/copilot`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:copilotInput})});const b=await r.json();if(r.ok&&b.success)setCopilotAnswer(b.result.answer||"");else setCopilotAnswer(b.message||"Copilot در دسترس نیست.");}
  const kpis=[{label:"رکوردهای این بخش",value:total},{label:"Entityها",value:definition.entities.length},{label:"Workflowها",value:definition.workflows.length},{label:"صفحه",value:`${page+1}/${pageCount}`}];
  if(!entity)return <div className="rounded-2xl border border-white/10 p-5 text-white/40">هیچ Entity برای اجرا وجود ندارد.</div>;

  return <div className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(k=><div key={k.label} className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><div className="text-2xl font-semibold">{k.value}</div><div className="mt-1 text-xs text-white/40">{k.label}</div></div>)}</div>
    <div className="grid gap-4 xl:grid-cols-[220px_1fr_330px]">
      <aside className="rounded-2xl border border-white/10 bg-black/20 p-3"><p className="px-2 py-2 text-xs text-white/35">داده‌های اپ</p>{definition.entities.map(x=><button key={x.id} onClick={()=>setEntityId(x.id)} className={`mb-1 w-full rounded-lg px-3 py-2 text-right text-sm ${entity.id===x.id?"bg-white/10 text-white":"text-white/55 hover:bg-white/5"}`}>{x.name}</button>)}<div className="mt-5 border-t border-white/10 pt-3"><p className="px-2 pb-2 text-xs text-white/35">Workflowها</p>{definition.workflows.map(w=><button key={w.id} onClick={()=>runWorkflow(w.id)} className="mb-1 w-full rounded-lg border border-white/8 px-3 py-2 text-right text-xs text-white/55 hover:bg-white/5">{w.name}</button>)}</div></aside>
      <section className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-white/35">Live entity</p><h3 className="text-xl font-medium">{entity.name}</h3></div><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/25 px-3"><MagnifyingGlass size={15} className="text-white/35"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="جست‌وجوی سرور" className="w-44 bg-transparent py-2 text-sm outline-none"/></div></div><div className="overflow-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-white/10 text-white/40">{entity.fields.map(f=><th key={f.id} className="px-3 py-3 text-right font-normal">{f.id}</th>)}<th className="px-3 py-3"></th></tr></thead><tbody>{records.map(row=><tr key={row.id} className="border-b border-white/5">{entity.fields.map(f=><td key={f.id} className="max-w-48 truncate px-3 py-3 text-white/70">{String(row[f.id]??"—")}</td>)}<td className="px-3 py-3"><div className="flex gap-2"><button onClick={()=>edit(row)} className="text-white/35 hover:text-white"><PencilSimple size={16}/></button><button onClick={()=>remove(row.id)} className="text-white/30 hover:text-red-300"><Trash size={16}/></button></div></td></tr>)}</tbody></table>{!records.length&&<div className="py-14 text-center text-sm text-white/30">داده‌ای پیدا نشد.</div>}</div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-white/35">{total} رکورد</span><div className="flex gap-2"><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))} className="rounded-lg border border-white/10 p-2 disabled:opacity-30"><ArrowRight size={15}/></button><button disabled={page>=pageCount-1} onClick={()=>setPage(p=>Math.min(pageCount-1,p+1))} className="rounded-lg border border-white/10 p-2 disabled:opacity-30"><ArrowLeft size={15}/></button></div></div></section>
      <aside className="space-y-4"><div className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="mb-4 flex items-center gap-2"><Plus size={16}/><h3 className="font-medium">{editingId?"ویرایش رکورد":"رکورد جدید"}</h3></div><div className="space-y-3">{entity.fields.map(field=><label key={field.id} className="block"><span className="mb-1 block text-xs text-white/45">{field.id}{field.required?" *":""}</span>{field.type==="reference"?<select value={String(form[field.id]??"")} onChange={e=>setForm(v=>({...v,[field.id]:e.target.value}))} className="w-full rounded-xl border border-white/10 bg-[#0b0c0f] px-3 py-2 text-sm"><option value="">انتخاب</option>{(refs[field.id]||[]).map(r=><option key={r.id} value={r.id}>{String(r.name||r.title||r.sku||r.id)}</option>)}</select>:field.type==="enum"?<select value={String(form[field.id]??"")} onChange={e=>setForm(v=>({...v,[field.id]:e.target.value}))} className="w-full rounded-xl border border-white/10 bg-[#0b0c0f] px-3 py-2 text-sm"><option value="">انتخاب</option>{field.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:field.type==="boolean"?<input type="checkbox" checked={Boolean(form[field.id])} onChange={e=>setForm(v=>({...v,[field.id]:e.target.checked}))}/>:<input type={inputType(field)} value={String(form[field.id]??"")} onChange={e=>setForm(v=>({...v,[field.id]:["integer","decimal","money"].includes(field.type)&&e.target.value!==""?Number(e.target.value):e.target.value}))} className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm outline-none"/>}</label>)}</div><div className="mt-5 flex gap-2"><button disabled={busy} onClick={save} className="flex-1 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-40">{busy?"در حال ذخیره...":editingId?"ذخیره تغییرات":"ثبت رکورد"}</button>{editingId&&<button onClick={()=>{setEditingId(null);setForm({});}} className="rounded-xl border border-white/10 px-3 text-xs">لغو</button>}</div>{message&&<p className="mt-3 text-xs leading-5 text-white/50">{message}</p>}</div>
      <div className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="mb-3 flex items-center gap-2"><Robot size={17}/><h3 className="font-medium">Loadder Copilot</h3></div><textarea value={copilotInput} onChange={e=>setCopilotInput(e.target.value)} placeholder="مثلاً وضعیت این اپ را تحلیل کن" rows={3} className="w-full rounded-xl border border-white/10 bg-black/25 p-3 text-sm outline-none"/><button onClick={askCopilot} className="mt-2 w-full rounded-xl border border-white/15 py-2 text-sm">تحلیل</button>{copilotAnswer&&<p className="mt-3 text-xs leading-6 text-white/60">{copilotAnswer}</p>}</div>
      <div className="rounded-2xl border border-amber-400/20 bg-amber-400/[0.03] p-4"><div className="mb-3 flex items-center gap-2"><RocketLaunch size={17}/><h3 className="font-medium">Deploy Console</h3></div>{deploy?<><div className="space-y-2 text-xs text-white/55"><p className="flex justify-between"><span>Production approval</span><b>{deploy.approved?"✓":"قفل"}</b></p><p className="flex justify-between"><span>Canary</span><b>{deploy.canaryPercent}%</b></p><p className="flex justify-between"><span>Health check</span><b>{deploy.healthCheckRequired?"فعال":"—"}</b></p><p className="flex justify-between"><span>Rollback</span><b>{deploy.rollbackSupported?"آماده":"—"}</b></p></div><div className="mt-3 rounded-xl border border-white/8 p-3 text-xs text-white/40">{deploy.providerConfigured?"آماده استقرار":"Adapter تولید هنوز عمداً متصل نشده؛ استقرار Production قفل است."}</div></>:<p className="text-xs text-white/35">در حال بررسی...</p>}</div></aside>
    </div>
  </div>;
}
