import crypto from "node:crypto";
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, statSync } from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import { assertSafeBackupPaths, PersistenceError } from "./persistence-contract.mjs";
const stamp = (date) => date.toISOString().replace(/[:.]/g, "-");
export function validateSqliteFile(file, expectedMigrationCount = null) { let db; try { db = new Database(file, { readonly: true, fileMustExist: true }); const integrity = db.pragma("integrity_check", { simple: true }), foreignKeys = db.pragma("foreign_key_check"), row = db.prepare("SELECT count(*) count, coalesce(max(version),0) maxVersion FROM schema_migrations").get(); if (integrity !== "ok" || foreignKeys.length || (expectedMigrationCount !== null && row.count !== expectedMigrationCount)) throw new Error(); return Object.freeze({ integrity, foreignKeys: Object.freeze(foreignKeys), migrationCount: row.count, maxMigrationVersion: row.maxVersion }); } catch { throw new PersistenceError("PERSISTENCE_BACKUP_INVALID"); } finally { db?.close(); } }
export function createSqliteBackup({ db, databasePath, backupDirectory, publicDirectories = [], now = new Date() }) { const safe = assertSafeBackupPaths({ databasePath, backupDirectory, publicDirectories }); mkdirSync(safe.backupDirectory, { recursive: true, mode: 0o750 }); const migration = db.prepare("SELECT count(*) count FROM schema_migrations").get(), base = `loadder-${stamp(now)}`, temporary = path.join(safe.backupDirectory, `.${base}.tmp.sqlite`), destination = path.join(safe.backupDirectory, `${base}.sqlite`); rmSync(temporary, { force: true }); try { db.prepare("VACUUM INTO ?").run(temporary); const validation = validateSqliteFile(temporary, migration.count); renameSync(temporary, destination); const bytes = statSync(destination).size, checksum = crypto.createHash("sha256").update(readFileSync(destination)).digest("hex"); return Object.freeze({ path: destination, filename: path.basename(destination), bytes, checksum, ...validation }); } catch (error) { rmSync(temporary, { force: true }); if (error instanceof PersistenceError) throw error; throw new PersistenceError("PERSISTENCE_BACKUP_FAILED"); } }
export function restoreSqliteBackup({ source, target, expectedChecksum = null }) { if (!source || !target || !path.isAbsolute(source) || !path.isAbsolute(target) || path.resolve(source) === path.resolve(target) || existsSync(target)) throw new PersistenceError("PERSISTENCE_RESTORE_TARGET_UNSAFE"); const validation = validateSqliteFile(source), actual = crypto.createHash("sha256").update(readFileSync(source)).digest("hex"); if (expectedChecksum && actual !== expectedChecksum) throw new PersistenceError("PERSISTENCE_BACKUP_INVALID"); mkdirSync(path.dirname(target), { recursive: true, mode: 0o750 }); const temporary = `${target}.restore-${process.pid}.tmp`; rmSync(temporary, { force: true }); try { const sourceDb = new Database(source, { readonly: true, fileMustExist: true }); try { sourceDb.prepare("VACUUM INTO ?").run(temporary); } finally { sourceDb.close(); } validateSqliteFile(temporary, validation.migrationCount); renameSync(temporary, target); return Object.freeze({ target, checksum: actual, ...validation }); } catch (error) { rmSync(temporary, { force: true }); if (error instanceof PersistenceError) throw error; throw new PersistenceError("PERSISTENCE_RESTORE_INVALID_SOURCE"); } }
